### ISSUE TITLE
Assistente de campo - aviso sobre dados não submetidos

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#100]
Incluir algum aviso quando fechamos a janela do Assistente de campo sem submeter as alterações.

**Comment by viniciusandrade** [comment]
Quando o usuário não alterar nenhum dado é possível fechar a janela diretamente, quando algo for alterado será mostrado uma caixa de mensagem informando que os dados serão perdidos.

Implementado em https://github.com/bireme/fi-admin/commit/e8f62824e38f8eea6a4c04292233fa1b7bdd79ee
