### ISSUE TITLE
Alteração da tradução de qualificador

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#1009]
Por gentileza alterar o conteúdo do qualificador "DE - efeito de drogas" para "DE - efeitos dos fármacos" no sistema FI-Admin.

Seguem links para referência:
Conteúdo para ser alterado - ver em DE:
https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&mode=dataentry&tree_id=A03.620

Qualificador atual
http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&search_language=p&interface_language=p&previous_page=homepage&task=show_qualifier&qualifier=DE

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/iahx-opac/commit/5ecc4d25dc64bdd11c35d714c07049f9e413932a
