### ISSUE TITLE
Assistente de campo - visualização das informações

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#101]
- Em todos os campos que precisam do "Assistente de campo" aparece "**Data***".
Alterar tradução para "Dado" ou nome do campo para não causar confusão.

**Comment by viniciusandrade** [comment]
Esta informação foi suprimida da tela pois não é um dado de controle e não precisaria estar visivel.

Implementado em https://github.com/bireme/fi-admin/commit/e8f62824e38f8eea6a4c04292233fa1b7bdd79ee
