### ISSUE TITLE
Apagar definitivamente as traduções erradas com status apagado

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1020]
Fábio, por favor, 
1) apagar a tradução "**Medidas de Desfechoss**" que consta erroneamente como **PEP (pt-br)** no conceito **M0025935**.

2) apagar a tradução "isómero (SP-4-3-(cis)) del oxaliplatinos" que consta erroneamente como **PEP  (es-es)** no conceito **M0318698**.

Agradeço!
Ana Cristina

**Comment by falbrito** [comment]
Realizado.
