### ISSUE TITLE
Criar opção para apagar registros no sistema (Instituições)

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#1025]
Falta opção para apagar registros.

Obrigada
Marilda

**Comment by viniciusandrade** [comment]
@alvesmarilda disponibilizei a opção de apagar (somente para usuários BR1.1).
Favor quando possível validar.

Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 
OK! Validado!

Obrigada

**Comment by viniciusandrade** [comment]
Obrigado pela validação.
