### ISSUE TITLE
Criar opção para correção de registro/nome aba "Unidades" (Instituições)

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#1026]
Falta opção para correção do nome (Unidade).

Obrigada
Marilda

**Comment by viniciusandrade** [comment]
@alvesmarilda o gerenciamento das unidades foi implementado e esta disponível dentro do módulo 
**Admin** do sistema. 

Por favor verifique se com seu usuário consegue acessá-lo para efetuar as correções.

Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade  Validado com a mudança de meu perfil para superusuário.


Obrigada!

**Comment by viniciusandrade** [comment]
Perfeito.
