### ISSUE TITLE
Criar pesquisa combinada e filtros (Instituições)

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#1030]
Pesquisa combinada:
Exemplo: Universidade and Fluminense
Nmail = 20 hits
Fi-admin = 0

Filtros para pesquisa como:
Usuário (User), Categoria, Data de entrada, Cidade ou Estado.

Obrigada!

**Comment by viniciusandrade** [comment]
Marilda,
A busca no FI-ADMIN não permite o uso de operadores, esta limitação deve ser compensada pelo uso dos fitros. 
Dos sugeridos foi implementado os filtros de tipo de instituição e categoria. Data, cidade e estado não campos controlados e portanto não podem ser usados como filtros.

Favor quando possível validar. Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade Validado tipo de instituição e categoria.
Quanto a data de entrada precisamos analisar como fazer para a atribuição dos códigos novos.
Preciso saber qual o último código atribuído para o País para um novo registro.
Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
OK, estou fechando esse e abri o #1031 para verificarmos se é suficiente para esta necessidade.
