### ISSUE TITLE
Criar nova unidade (Instituições)

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#1033]
@viniciusandrade 
Sistema não possibilita criação de nova unidade.

![image](https://user-images.githubusercontent.com/38661168/74064448-72215100-49d1-11ea-97cf-18a4d0ce7dae.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Conforme combinamos será melhor realizar a gestão das unidades pelo módulo de Admin do sitema, por isso estou tirando esta opção da janela de popup.
