### ISSUE TITLE
Autor individual, subcampo de Afiliação - erro de grafia

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#104]
No assistente de campo de Autor individual, aparece "Afilialção - Grau de responsabilidade". Corrigir a palavra "Afiliação'.

**Comment by sarahviola** [comment]
No assistente de campo de Autor individual, aparece "Afilialção - Grau de responsabilidade". Corrigir a palavra "Afiliação'.

**Comment by viniciusandrade** [comment]
Corrigido no arquivo de traduções.
