### ISSUE TITLE
Ajuste em campos no schema Solr para uso na busca do plugin DeCS

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#1052]
Com o objetivo de melhorar o filtro para o novo portal DeCS solicito realizar os seguintes ajustes ao schema do Solr

**Retirar campos:**

ths_preferredterm
ths_termall
ths_termall_en
ths_termall_es
ths_termall_pt
ths_termall_fr
ths_termall_eses

**Incluir campos:**
- MH
ths_mh_en
ths_mh_es
ths_mh_pt
ths_mh_fr
ths_mh_eses

- MH - Sinônimos
ths_mh_et_en
ths_mh_et_es
ths_mh_et_pt
ths_mh_et_fr
ths_mh_et_eses

- PEP
ths_pep_en
ths_pep_es
ths_pep_pt
ths_pep_fr
ths_pep_eses

- PEP - Sinônimos
ths_pep_et_en
ths_pep_et_es
ths_pep_et_pt
ths_pep_et_fr
ths_pep_et_eses

- ETs - PERMUTADOS
ths_permuted_en
ths_permuted_es
ths_permuted_pt
ths_permuted_fr
ths_permuted_eses

**Comment by falbrito** [comment]
Arquivo schema.xml atualizado.

**Comment by falbrito** [comment]
Vinícius por gentileza fazer os seguintes ajustes no schema.xml do FI-admin ( http://db02dx.bireme.br:8984/fi-main/admin/file/?contentType=text/xml;charset=utf-8&file=schema.xml )

1) Pertinente a case insensitive de string.
- Substituir "lowercase" por "string_lowercase"
`<fieldType name="lowercase" class="solr.TextField" positionIncrementGap="100">`

- Substituir "string" por "string_lowercase"
`<field name="ths_exact_term" type="string" indexed="true" stored="false" multiValued="true"/>`

2) Pertinente a poder recuperar radical de hierarquia, substituir "string" por "text"
`<field name="ths_treenumber" type="string" indexed="true" stored="true" multiValued="true"/>`

**Comment by viniciusandrade** [comment]
@falbrito 
Ajustes efetuados e serviço reinicializado. 
Necessário realizar reindexação do XML.

**Comment by falbrito** [comment]
Realizada a indexação.

Verificado que existe problema para a recuperação da pequisa por "Categoria hierárquica"

Ex.: A pequisa traz resultado para 'DO2', mas quando pesquisado 'D02.705' não traz.

**Comment by falbrito** [comment]
Em relação a questão da utilização de "wildcard" diretamente no código.
Não estamos utilizando esse meio no padrão do Portal regional. O usuário coloca no termo de pesquisa se assim o desejar.

**Comment by viniciusandrade** [comment]
@falbrito 

Conforme discutido em reunião foi alterado a definição do campo ths_treenumber novamente para string e revisado a query string que de deve ser enviada para o Solr. 
```
<field name="ths_treenumber" type="string" indexed="true" stored="true" multiValued="true"/>
```
Favor realizar indexação do XML e realizar novo teste.

Obrigado

**Comment by falbrito** [comment]
@viniciusandrade 
Por gentileza fazer alteração novamente no schema.xml para contemplar no ths_treenumber o type string_lowercase

**Comment by viniciusandrade** [comment]
@falbrito 
Ajuste realizado e serviço reiniciado, favor realizar nova indexação e testes.
Obrigado

**Comment by falbrito** [comment]
@viniciusandrade 
Indexado e testes OK
Agora é possível realizar a busca pela categoria e também pelo radical de uma categoria para recuperar a "família".

ex1 - Categoria
D02.455.426.559

ex2 - Família da categoria
D02.455.426.559*

Obrigado!

**Comment by viniciusandrade** [comment]
:+1:
