### ISSUE TITLE
Título abreviado do periódico BEPA, Bol. epidemiol. paul. (Impr.) não está sendo recuperado em outros status

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1055]
Prezados,

Informo que o título abreviado do BEPA, Bol. epidemiol. paul. (Impr.) recupera somente os registros com status publicado dentro da aba "Todos os registros" do FI-Admin.

![image](https://user-images.githubusercontent.com/13105683/75584954-c0b19080-5a4f-11ea-8328-8a2ff9ba1818.png)

Somente registros com status publicado:
![image](https://user-images.githubusercontent.com/13105683/75585023-edfe3e80-5a4f-11ea-9231-fb76076c917f.png)

Sem o título abreviado aparecem outros status como "migrado"
![image](https://user-images.githubusercontent.com/13105683/75585185-49c8c780-5a50-11ea-810b-32429200b4a6.png)

Muito obrigada!
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by AngelicaSAPaula** [comment]
@viniciusandrade 

Refiz a busca e os resultados parecem estar corretos:

![image](https://user-images.githubusercontent.com/47643830/84093377-6cb03380-a9d0-11ea-9862-960ebb10d05d.png)

![image](https://user-images.githubusercontent.com/47643830/84093402-82bdf400-a9d0-11ea-944e-16de7da35320.png)

![image](https://user-images.githubusercontent.com/47643830/84093460-a6813a00-a9d0-11ea-83b5-239fbd5c7c54.png)

![image](https://user-images.githubusercontent.com/47643830/84093333-4f7b6500-a9d0-11ea-8fb7-dcef49388c8c.png)

**Comment by viniciusandrade** [comment]
Obrigado pelo teste @AngelicaSAPaula.
