### ISSUE TITLE
Tornar campo de Título do periódico autocompletável

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1056]
Prezados,

Considerando dificuldade em localizar o título abreviado do periódico a ser indexado, muitos usuários que não o encontram, incluem um "título abreviado" conforme sua conveniência o que tem gerado inconsistência na entrada de dados, mesmo sendo uma tabela controlada.

Recomendamos que o campo seja autocompletável para que o usuário encontre rapidamente o título abreviado adequado.
![image](https://user-images.githubusercontent.com/13105683/76010788-40c57380-5ef2-11ea-96a0-759484afc190.png)

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula,

Implementei o ajuste solicitado pela Sueli mas existem várias condições que precisam ser testadas antes de liberarmos no sistema. Você poderia  me ajudar na validação no ambiente de testes? 

Casos que precisam ser testados:

- usuário é um documentlista/editor e esta adicionando uma fonte LILACS: neste caso ele só pode informar um título de revista indexada na LILACS
- usuário é um documentlista/editor e esta adicionando uma fonte não LILACS: neste caso ele pode informar qualquer título de revista
- usuário em é um editor LLXP: só pode escolher as revistas indexadas por ele, caso seja somente uma revista já deve vir preenchida pelo sistema

Em caso de dúvidas ou tenha algum outro caso que eu não identifiquei nos meus testes favor informar. 

Obrigado

**Comment by AngelicaSAPaula** [comment]
► Acredito que, caso não haja mais a listagem de revistas, o título seja "Título abreviado" ao invés de só "Título"

**1)** usuário é um documentlista/editor e esta adicionando uma fonte LILACS: neste caso ele só pode informar um título de revista indexada na LILACS
► Não aparecem títulos grafados de forma diferente do que está na listagem da LILACS
► Como documentalista, consegui criar fonte em revista que não é do meu CC

**2)** usuário é um documentlista/editor e esta adicionando uma fonte não LILACS: neste caso ele pode informar qualquer título de revista
► O informe só foi dado após eu completar todos os campos e gravar o registro. É possível aparecer antes, no momento em que se está preenchendo o ISSN ou o título?
![image](https://user-images.githubusercontent.com/47643830/84094169-7f2b6c80-a9d2-11ea-8440-1f198beb845b.png)
► Este caso deva ser revisto pela @suelisuga, pois há muitas revistas que são colocadas no Fi-Admin para outras bases que não LILACS, por isso utilizam este campo.

→ SUGESTÃO: caso o usuário preencha um título que não está na listagem, ao colocar o ISSN, se autocomplete o título? Talvez colocar este campo para ser preenchido primeiro? Neste caso, deve ser ligado à Title, mesmo que a revista não seja LILACS.

**3)** usuário em é um editor LLXP: só pode escolher as revistas indexadas por ele, caso seja somente uma revista já deve vir preenchida pelo sistema
► OK!

**Comment by suelisuga** [comment]
@viniciusandrade 

Após nos reunirmos hoje decidimos que o campo Título do periódico como foi implantado pode gerar mais erros do que melhorias, pois haverá casos em que não sabemos o título abreviado, mas saberemos o título completo.

Pensando nisso e pensando que o título abreviado como está e por estar organizado já por títulos indexados pelo Centro Cooperante, resolvemos:

1. Manter o campo como ele está hoje: títulos abreviados que possuem o campo CC indexador independente da base onde esteja indexado:
Título LILACS:
![image](https://user-images.githubusercontent.com/13105683/84517479-c3a25b00-aca5-11ea-9637-d6e453f315e1.png)
Título BDENF:
![image](https://user-images.githubusercontent.com/13105683/84517700-0a905080-aca6-11ea-8149-ea49dcf90cc3.png)
No registro bibliográfico da LILACS:
![image](https://user-images.githubusercontent.com/13105683/84517293-79b97500-aca5-11ea-9d0e-9c60d08475ad.png)
No registro bibliográfico da BDENF:
![image](https://user-images.githubusercontent.com/13105683/84517869-3a3f5880-aca6-11ea-87e2-c83500c1a511.png)

2. Incluir o autocompletar o título do periódico no campo "Outro título de revista (não indexada na Biblioteca Virtual em Saúde)"
![image](https://user-images.githubusercontent.com/13105683/84518043-770b4f80-aca6-11ea-976f-69c0f1f77219.png)

Como o Documentalista/Editor pode não conhecer a abreviatura do título do periódico o ideal seria incluir os **títulos abreviados**, mas também o **título completo do periódico.**

Alguns exemplos de títulos que nos causaram problemas ao testar o autocompletar:

- Títulos que começam com abreviaturas não tão conhecida: Anais =>abreviatura An.
- Títulos que começam com siglas => BIS, Bol. Inst. Saúde (Impr); REMHU (Online); e outros
- Títulos que são os controlados quando eles existem em versão impresso e online => Archiv. med. fam. gen. (En línea); BAG, J. basic appl. genet. (Online); Alcmeón (Impr.); e outros

Gostaria que avaliasse a possibilidade de incluir no autocompletar a lista de todos os periódicos registrados na TITLE, o que deve dar cerca de 18 mil títulos, sendo que seria necessário incluir titulo abreviado e título completo.
Caso não seja possível, que sejam incluidos os títulos correntes.

Muito obrigada!
Sueli, Angélica, Laís, Marilda e Katinha

**Comment by viniciusandrade** [comment]
@suelisuga voltando a este tema implementei o autocomplete no campo de título buscando pelo título completo e abreviado de todas as revistas da TITLE. 

Esta implementação será importante para facilitar a entrada de dados principalmente quando forem adicionadas as revistas do projeto GIM.

![autocomplete](https://user-images.githubusercontent.com/349287/120821979-529a2a00-c52c-11eb-9cc1-a255d317e1d6.png)

Por favor, quando possível, você e a @AngelicaSAPaula poderiam dar uma olhada no ambiente de testes e avaliar se podemos implementar este recurso em produção?

http://fi-admin.teste.bvsalud.org

Obrigado

**Comment by AngelicaSAPaula** [comment]
@viniciusandrade Acredito que teremos problemas porque está recuperando mesmo as revistas já encerradas, e isso vai de encontro ao chamado #1141.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula obrigado pelo retorno. 

Acredito que podemos tratar cada issue de forma independente para podermos avançar.  

Neste caso, o objetivo específico deste issue é substituir a caixa de seleção por algo que simplifique a entrada do nome da revista. Sobre recuperar as revistas já encerradas esta de acordo com o comentário acima da @suelisuga:

_Gostaria que avaliasse a possibilidade de incluir no autocompletar a lista de todos os periódicos registrados na TITLE, o que deve dar cerca de 18 mil títulos, sendo que seria necessário incluir titulo abreviado e título completo.
Caso não seja possível, que sejam incluidos os títulos correntes._

@suelisuga, favor confirmar se o melhor é recuperar somente os títulos correntes ou todos os títulos da TITLE conforme indicado acima.

Obrigado.

**Comment by suelisuga** [comment]
@viniciusandrade testamos a funcionalidade, porém consideramos que há mais contras do que prós.

considerações sobre a nova funcionalidade e detalhes importantes que são:

Prós: facilita acesso tanto a titulo abreviado quanto ao título completo de todos os periódicos indexados na TITLE.

Contras:
Os periódicos tem variações em seu título (idioma, títulos anteriores, print x online) e na LILACS (bases de dados) sempre escolhemos qual a abreviatura que deve ser utilizada.
A possibilidade de escolher qlq título abre a possibilidade de escolherem o título abreviado inapropriado.

Ao escolher qualquer título, automaticamente o ISSN também será preenchido com o ISSN do título inapropriado.

Quando o periódico não existe na TITLE, da mesma maneira foi possível incluir qualquer título, inclusive por extenso, que já é um problema existente.

Entendo que a solução não ficou conforme previamos... @viniciusandrade Há sugestão melhor para essa implantação?

Muito obrigada

**Comment by suelisuga** [comment]
Exemplo de título que está indexado porém não recuperou o título abreviado e nem o título por extenso: 

Título: Revista de APS
Título abreviado: Rev. APS


![image](https://user-images.githubusercontent.com/13105683/124510128-95f4ec00-dda9-11eb-86db-2ee250b052aa.png)
Obrigada

**Comment by viniciusandrade** [comment]
@suelisuga o sistema estava configurado para iniciar o autocomplete a partir da 4 letra por isso não apresentou a lista para APS.

Alterei a configuração para iniciar a busca a partir da 3 letra. Favor atualizar a página e tentar novamente. 

Obrigado.

**Comment by viniciusandrade** [comment]
Implementação disponível em produção.
