### ISSUE TITLE
Não recupera pesquisa no FI-Admin . documento recuperado no IAHX 

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1059]
id:lil-566897
Consenso para o controle do câncer de mama: síntese do documento

**Comment by viniciusandrade** [comment]
O problema esta no sinal de ":"  do título que tanto no IAHX quanto no FI-ADMIN representam um caracter reservado que indica busca por campo e desta forma não é corretamente interpretado na busca.

Pesquisando pelo ID verifiquei que o mesmo aponta para uma tese com o título: 
"Mulheres em risco familiar para o câncer de mama: uma hermenêutica da prevenção secundária", ou seja deve ter sido alterado. 

Para localizar no FI-ADMIN usei as palavras antes do sinal ":" e recuperei o registro.

Estou finalizando por se tratar de comportamento da ferramenta de busca que usa o ":" para busca por campo.
