### ISSUE TITLE
Autor individual, subcampo de "Afiliação - País" - incluir tabela

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#106]
No campo de Autor individual, incluir no assistente de campo uma tabela de país para controlar o preenchimento do subcampo **Afiliação - País**.

**Comment by sarahviola** [comment]
Lista de país funciona, mas em _Latin America & Caribbean_ aparece só Brasil e Colômbia, faltando os outros países, que estão em _Outros_.

Falta também traduzir _Latin America & Caribbean_ para o português.


![image](https://cloud.githubusercontent.com/assets/18355163/14892500/67b5764a-0d41-11e6-874f-1e758f039423.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Realizei o ajuste da tradução do rótulo _Latin America & Caribbean_.

Para a questão da divisão dos paises precisa ser realizado pelo Django Admin na tabela de Paises marcando o campo _Latin America & Caribbean region?_

Vou abrir um ticket em separado para não esquercermos deste ajuste que precisaria ser feito na instância em produção.

Depois por favor dê uma olhada e se estiver de acordo pode fechar este ticket.

**Comment by sarahviola** [comment]
@viniciusandrade 

Marquei Paraguai e Panamá como "Região da América Latina e Caribe?" no django admin em teste, mas eles ainda estão em _Outros_. 

Já deveria ter funcionado, ou tem que fazer algo mais? Desloguei e loguei de novo no sistema e também atualizei a página várias vezes.

**Comment by viniciusandrade** [comment]
@sarahviola 

Deveria ter sido automático ... mas não sei por qual motivo precisei reiniciar o ambiente para os países que você marcou ficarem corretos nas listas. Deve ser um cache interno do Django. 

De qualquer forma adicionei um filtro adicional no Django admin para facilitar o filtro pelos países.

**Comment by sarahviola** [comment]
Certo! 

Depois de finalizarmos os testes, ajustarei na produção como registrado em #124 .
