### ISSUE TITLE
Avaliar solução alternativa para evitar duplicados no FI-Admin

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1062]
Possibilidade de incluir um link, acompanhando todos os campos de título das APP do FI-Admin, que faça uma busca do título na interface do iAHx Regional, filtrado pela FI correspondente. Não é a solução ótima, mas parece que o mecanismo atual de verificação não está sendo acionado. É teoricamente uma solução simples que pode motivar o usuário a buscar. Poderia ser uma busca exata to título, combinado com OR de uma busca exata da metade do título.

Exemplo: 
Título a ser ingressado: "Coronavirus COVID-19 Global Cases by Johns Hopkins CSSE"
A busca no iAHx Regional seria
ti:"Coronavirus COVID-19 Global Cases by Johns Hopkins CSSE" OR ti "Coronavirus COVID-19 Global Cases"

A metade do título é calculada pelo número de tokens.

**Comment by viniciusandrade** [comment]
@suelisuga esta disponível no ambiente de testes do FI-ADMIN no formulário de entrada/edição de Recursos de Internet um link para pesquisar por duplicados na BVS.

Poderia, por gentileza, verificar este recurso e se podemos seguir colocando o mesmo em produção?

Obrigado

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula favor quando possível verificar esta implementação no ambiente de testes.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Realizei alguns testes com registros que já estão publicados, mas um deles não foi recuperado:

► Covid-19 e Amamentação - Recomendação N.0120.170320 (id: lis-LISBR1.1-47075)
→ busca gerada: Covid-19 e Amamentação - Recomendação N0120170320 OR ( Covid-19 e Amamentação)

![image](https://user-images.githubusercontent.com/47643830/77779962-0e5ef000-7032-11ea-9b72-7ed22886eb2b.png)

![image](https://user-images.githubusercontent.com/47643830/77780117-3ea68e80-7032-11ea-9206-edf89d49f175.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula OK, verifiquei que este comportamento é devido a pesquisa pelo número da recomendação que falhou, conforme descrito esta solução não é 100% então estou fechando e qualquer outro caso podemos re-abrir.
