### ISSUE TITLE
Não é possível eliminar dados de campos obrigatórios no Assistente de campo

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#107]
Depois de preencher campos obrigatórios que tem assistente de campo, não é possível deletar o dado. O sistema não aceita gravar campo obrigatório vazio, então não há como apagar.

Problema ocorre nos campos Autor Institucional e Endereço eletrônico.

----

No exemplo, preenchi o campo de Autor Institucional com "teste" e gravei. 
![image](https://cloud.githubusercontent.com/assets/18355163/14535261/5d95f7a6-0243-11e6-8b09-85fe36a8d042.png)

Depois tentei deletar o dado e gravar o campo vazio, mas o sistema não permite.
![image](https://cloud.githubusercontent.com/assets/18355163/14535297/8a2aa14a-0243-11e6-8970-fc0750dbeb88.png)

**Comment by viniciusandrade** [comment]
É  apresentado o ícone de X para permitir apagar a primeira ocorrência do campo, quando for edição de um campo já preenchido.

Implementado em https://github.com/bireme/fi-admin/commit/00710e03697b23692b5d812a446c2d1983b0bebf
