### ISSUE TITLE
Filtros desconfiguram na rolagem de páginas / Instituições

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#1070]
Fiz uma pesquisa e quando vou visualizar os resultados nas páginas seguintes o filtro utilizado desconfigura.
https://fi-admin.bvsalud.org/institution/?page=2&filter_owner=*&s=&filter_status=&filter_type=&filter_category=13&filter_country=30

Exemplo:

![screenshot-fi-admin bvsalud org-2020 04 02-10_39_44a](https://user-images.githubusercontent.com/38661168/78257540-5e293580-74d0-11ea-975c-8bb93967eda7.png)

![screenshot-fi-admin bvsalud org-2020 04 02-10_40_25](https://user-images.githubusercontent.com/38661168/78257614-79944080-74d0-11ea-901c-35f023d54f11.png)
na página 3 já desconfigura:

https://fi-admin.bvsalud.org/institution/?page=3&filter_owner=*&s=&filter_status=&filter_type=&filter_category=13&filter_country=

![screenshot-fi-admin bvsalud org-2020 04 02-10_43_23](https://user-images.githubusercontent.com/38661168/78257659-887af300-74d0-11ea-9e92-c35a44a9a3e1.png)
 

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Correção aplicada, favor quando possível realizar novo teste. 

Obrigado
