### ISSUE TITLE
Mostrar e criar Highlight para os termos DeCS para vários campos

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#1073]

**Comment by arthurtreuherz** [comment]
Além desse campo, favor desenvolver procedimento para mostrar e incluir highlight para os campos abaixo. 

Scope Note (incluir highlight nos descritores mencionados, buscando também em sinônimos)
See Also (mostrar e incluir highlight)
Consider Also (mostrar e incluir highlight nos radicais mencionados com explosão, isto é, incluindo asterisco ao invés do hífen que aparece nesses radicais)
Entry Combination  (mostrar e incluir highlight)
Pharm Action (mostrar e incluir highlight)

Exemplos comparativos:
MeSH
Ibuprofen: https://meshb.nlm.nih.gov/record/ui?ui=D001842
Bone and Bones: https://meshb.nlm.nih.gov/record/ui?ui=D001842

DeCS
Ibuprofen: https://decs.teste.bvs.br/ths/resource/?id=28145&filter=ths_exact_term&q=ibuprofen
Bone and Bones: https://decs.teste.bvs.br/ths/resource/?id=1867&filter=ths_exact_term&q=bone%20and%20bones

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura essa demanda ainda persiste.

**Comment by wilsonmoura** [comment]
Utilizar mesmo mecanismo implementado no BIBLIOREF:
https://github.com/bireme/fi-admin/blob/master/bireme/utils/views.py#L227

**Comment by lucianaPRB** [comment]
@wilsonmoura Acredito que estes desenvolvimentos já foram concluídos em outros issues. Estou encerrando este.
