### ISSUE TITLE
Erro na Pesquisa no FI-Admin por Título de revista com Status "LILACS-Express"

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1075]
Em Registros Bibliográficos na pesquisa  por Título da revista **Saúde Redes** Status **LILACS-Express**
**Recuperou outros títulos de revistas, exemplo:** 
id:1090693 Interface (Botucatu, Online); 24, 2020
id:1059009 Saúde debate 
id:1056280 Hist. ciênc. saúde-Manguinhos
id:1055755 Ciênc. Saúde Colet
id:1055611 Cad. Saúde Pública (Online)

Recuperou registros Fonte e **não foi selecionado Tipo de registro**
id:1087278  Saúde Redes; 5 (1), 2019
id:1087277  Saúde Redes; 5 (2), 2019
id:1087276  Saúde Redes; 2 (supl. 1), 2016 
id:1087275  Saúde Redes; 1 (1), 2015 
id:1087274  Saúde Redes; 1 (2), 2015 
id:1087273  Saúde Redes; 1 (3), 2015 
id:1087272  Saúde Redes; 1 (4), 2015 

![saude redes_pesquisa](https://user-images.githubusercontent.com/37112458/80170086-841c9400-85bd-11ea-82c9-9b378cd08e35.PNG)

![saude redes_pesquisa 2](https://user-images.githubusercontent.com/37112458/80170109-93034680-85bd-11ea-84f0-96b9e965bc51.PNG)

**Comment by suelisuga** [comment]
Verificamos que a busca localizou documentos no qual as palavras saude e rede constavam no título da analítica.

Decidimos fazer as pesquisas por títulos abreviados que tem somente palavras inteiras com oponto e vírgula. Exemplo Saude Redes;
