### ISSUE TITLE
Não é possível filtrar por determinados paises na lista de instituições

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1080]
Erro reportado pela Marilda por email.

**Comment by viniciusandrade** [comment]
@alvesmarilda,

Ajuste realizado no sistema, quando possível favor validar e informar se esta OK.

Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Teste efetuado com sucesso.

Obrigada

**Comment by viniciusandrade** [comment]
Obrigado pela validação.
