### ISSUE TITLE
Permitir recuperar instituição pela raíz do código

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1081]
Reportado pela Marilda por email:

Não consigo mais pesquisar as raízes de um código, exemplo:

MX343 não recupera

Tenho que digitar o código completo: MX343.1 ou MX343.2 ou MX343.9

**Comment by viniciusandrade** [comment]
@alvesmarilda,

Ajuste realizado no sistema, quando possível favor validar e informar se esta OK.

Obrigado

**Comment by alvesmarilda** [comment]
@viniciusandrade 

Teste efetuado com sucesso.

Obrigada

**Comment by viniciusandrade** [comment]
Obrigado pela validação.
