### ISSUE TITLE
Associar usuário que realizou o termo de aceite com o histórico de alterações da instituição

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1082]
@alvesmarilda 

Verifiquei que o sistema ainda não esta registrando o usuário que realizou o termo de aceite ao histórico de mudanças da instituição.

Vou realizar o ajuste e pedir sua validação antes de liberarmos esta função para os centros.

Obrigado.

**Comment by viniciusandrade** [comment]
@alvesmarilda 
O sistema agora esta gravando o usuário que altera o status do termo de adesão. 
Quando possível favor verificar se você alterando o termo de aceite do BR1.1 fica registrado no Histórico de mudanças.

**Comment by renatomurasaki** [comment]
@alvesmarilda Favor confirmar que o FI-Admin está registrando no Histórico de Mudanças, quem e quando está alterando o termo de adesão.

**Comment by alvesmarilda** [comment]
Fiz outro teste neste momento em relação ao termo de adesão e confirmo que está registrando as ações de aceite e não aceite, através de mudança das posições das setas. Sugiro a mudança da frase para o não aceite (no acepted).

![image](https://user-images.githubusercontent.com/38661168/88938975-5c903400-d25c-11ea-9bd1-3c50a7770524.png)

Obrigada!
