### ISSUE TITLE
DeCS 2020 - Carregamento das definições ao espanhol regional (Chile) dos descritores alterados

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1085]
Olá Fábio,

Favor ver arquivo anexo 
[MeSH2020ScopeNote_changes_CHILE 2.0 FINAL.xlsx](https://github.com/bireme/fi-admin/files/4622687/MeSH2020ScopeNote_changes_CHILE.2.0.FINAL.xlsx)
e carregar no DeCS de trabalho a coluna com as definições alteradas em espanhol do Chile. Logo mais enviarei também outro arquivo com as traduções do Chile para as definições dos novos.

Obrigado.

**Comment by arthurtreuherz** [comment]
Desculpe Fábio, tirei do "Sprint Tesauro - Jun2020" por engano.

**Comment by falbrito** [comment]
Atualização/inserção realizado na versão MySQL 2020 congelada, e também no MySQL de trabalho.
