### ISSUE TITLE
Eliminação da categoria SP4.122.006.052.463.639 nos sites de consulta do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1092]
Fábio, por favor, consertar a categoria para o descritor "Pesquisa Ambiental", abaixo de "Desenvolvimento Tecnológico".
Situação que mostrou o erro:
![image](https://user-images.githubusercontent.com/35345406/84036823-25945500-a974-11ea-885c-cfc8c14e15b1.png)

e no novo portal DeCS.teste:
![image](https://user-images.githubusercontent.com/35345406/84036975-55435d00-a974-11ea-85ed-02fab5746c59.png)

Tabela de -> para:
![image](https://user-images.githubusercontent.com/35345406/84037896-9b4cf080-a975-11ea-8c78-891c4c03e784.png)

Muito agradecidos!

**Comment by falbrito** [comment]
Realizado.
