### ISSUE TITLE
Carregar definições em espanhol (latinoamericano e da Espanha) para os descritores novos de 2020

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1095]
Fábio,

Aqui vai o arquivo Excel com as notas de escopo (definições) dos descitores novos de 2020 em duas colunas, uma para cada variante de espanhol após minha revisão. Contém também as colunas para o Descriptor UI e o Concept UI do MeSH. 

[MeSH2020DescriptoresNuevos_CHILE_e_ESPANHA_FINAL_rev_arthur.xlsx](https://github.com/bireme/fi-admin/files/4754826/MeSH2020DescriptoresNuevos_CHILE_e_ESPANHA_FINAL_rev_arthur.xlsx)
Obrigado,
Arthur

**Comment by falbrito** [comment]
Definições carregadas no banco BETA e Fi-Admin de trabalho.
