### ISSUE TITLE
Atualizar "ID de transporte" para os descritores exclusivos mencionados no campo "See Also"

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1100]
Favor atualizar "ID de transporte" para os descritores exclusivos mencionados no campo "See Also" conforme padrão novo e exemplo abaixo.

Exemplo para o campo "See Also" do descritor MeSH/DeCS "Poluição do Ar":

![image](https://user-images.githubusercontent.com/25855735/84933417-3e0b1a80-b0ac-11ea-96a1-ff9004ba234d.png)

No exemplo acima, o primeiro ID de transporte deve mudar para o seguinte, conforme aparece no registro do descritor "Análise do Ar".

![image](https://user-images.githubusercontent.com/25855735/84934274-7a8b4600-b0ad-11ea-9c83-a68858d881b2.png)

Portanto, no padrão novo esse campo para o registro do descritor "Poluição do Ar" deve ficar assim:

![image](https://user-images.githubusercontent.com/25855735/84935561-3ef17b80-b0af-11ea-9b59-a126c9e43544.png)

**Comment by falbrito** [comment]
Necessário listar a tabela thesaurus_seerelatedlistdesc e verificar se todos os term_string e descriptor_ui estão ainda atualizados
* Se encontrar o term_string e o descriptor_ui for o mesmo não fazer nada
* Se encontrar o term_string e o descriptor_ui for outro, atualizar descriptor_ui
* Se não encontrar o term_string mas encontrar o descriptor_ui atualizar term_string
* Se não encontrar o term_string e não encontrar descriptor_ui apagar linha

**Comment by falbrito** [comment]
Realizar consistência dos termos relacionados

- [ ] Verificar se código existe, se não existir apagar
- [ ] Verificar se term_string do registro = term_string de related --> Se igual Apagar
- [ ] Verificar código e trazer term_string related em EN - atualizar term_string related se for diferente - ideal ficar em inglês

**Comment by falbrito** [comment]
Desenvolvido processo para atualizar os códigos armazenados nos TRs vindos do processo legado - que comecavam com UI. Esse tipo de código foi substituido através da verificação do term_string, quando identificado era atualizado pelo descriptor_ui 
real começando com D0* ou DDCS*. Esse script foi necessário a execução apenas uma vez.

`Script: /bases/decs.django/tools/tpl/atualiza_RELACIONADOS_DeCS.py`

Desenvolvido processo para atualizar a condição do TR. Verifica-se primeiro a existência do descriptor_ui do TR, depois verifica-se o term_string desse TR, caso haja diferença de grafia é atualizado.

`script: /bases/decs.django/tools/tpl/consiste_RELACIONADOS.py`

**Comment by falbrito** [comment]
Após a execução dos processos de atualiza_RELACIONADOS_DeCS.py e /consiste_RELACIONADOS.py, foi necessário atualizar o banco de dados congelado da versão 2020 e também o banco de dados do FI-Admin Tesauro de trabalho.
