### ISSUE TITLE
Atualização da instancia de cursos do FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1105]
Prezados,

Solicito atualização da instancia de cursos do FI-Admin.
Capacitação agendada para julho.

Muito obrigada!

Abraços,
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga,
Sistema FI-ADMIN atualizado no ambiente de cursos.

Abraços

**Comment by suelisuga** [comment]
muito obrigada @viniciusandrade!
