### ISSUE TITLE
Ajuste para atualização do procedimento de identificação do tipo de descritor relacionado ("Veja também", "See also", TR)

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1109]
O sistema de edição identifica quando o descritor que aparece no campo "Veja também" é exclusivo do DeCS, acrescentando à sua direita a palavra "DeCS". Só que com a atualização dos códigos do descritor (Descriptor UI) dos descritores exclusivos do DeCS (que antes começavam com UI e agora começam com DDCS), a palavra "DeCS" deixou de aparecer. No sistema de consulta, isso já está ok, portanto agora só é necessário atualizar no sistema FI-ADMIN.

Exemplo:
Caso de descritor que já está com os seus códigos atualizados (DDCS...) e que não estão mais mostrando "DeCS"
Descritor MeSH "Conservação dos Recursos Naturais"

![image](https://user-images.githubusercontent.com/25855735/86376809-f06ee000-bc5d-11ea-90a9-d14b35fac75b.png)

Lista de "Descritores relacionados" deste descritor extraídos do base em homologação: 

>G4 serverw:/home/decs2020/www/bases $ mx decs "pft=if v480:'D0' and v60:'^tDeCS' then (mfn'|'v3[1]'|TR: 'v60/) fi" now | more
> 003266|Conservação dos Recursos Naturais|TR: ^iArid Zone^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iEcology
> 003266|Conservação dos Recursos Naturais|TR: ^iEnvironmental Change^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iEnvironmental Quality^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iErosion^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iNatural Reservations^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iNatural Resources
> 003266|Conservação dos Recursos Naturais|TR: ^iSocioeconomic Planning^tDeCS
> 003266|Conservação dos Recursos Naturais|TR: ^iSoil Treatment^tDeCS

Visão deste registro no FI-ADMIN onde se faz necessário mostrar novamente a palavra "DeCS" à direita de 7 de seus 9 TRs:

![image](https://user-images.githubusercontent.com/25855735/86378192-c1596e00-bc5f-11ea-8ca0-38cf7ac6fc1e.png)

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura uma vez que já está no portal, creio que essa demanda não é necessária. Podemos encerrar esse issue.
