### ISSUE TITLE
Alterar o hyperlink de "Web Services" no footer em inglês da home do novo portal do DeCS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1112]
Oi Márcio,

O link do "Web Services" está indo para o francês. O texto desse link também estava errado: dizia "Services Web". Eu achei onde trocar, mas não consegui trocar o link. Não quis mexer, pois parecia correto. O único lugar onde parecia errado era onde diz "Original". Lá aparece o texto original em francês e o hyperlink indo para o francês. Mas não quis apagar esse original, pois achei que pudesse eliminar o item inteiro do "Web Services", e não apenas esse histórico. Veja a imagem abaixo:

![image](https://user-images.githubusercontent.com/25855735/87313416-36e2fb00-c4f8-11ea-99c2-0218d98a2dd9.png)

**Comment by renatomurasaki** [comment]
@wilsonmoura por favor, poderia ajudar neste issue?
@arthurtreuherz o Márcio está de férias e por isso estou pedindo ajuda para o Wilson.

**Comment by arthurtreuherz** [comment]
obrigado @renato.
________________________________
De: Renato Murasaki <notifications@github.com>
Enviado: segunda-feira, 13 de julho de 2020 11:39
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Treuherz, Arthur (BIR) <treuherz@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Alterar o hyperlink de "Web Services" no footer em inglês da home do novo portal do DeCS (#1112)


@wilsonmoura<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwilsonmoura&data=02%7C01%7Ctreuherz%40paho.org%7C04d08c51ba704408a26e08d8273a80a2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637302479505665763&sdata=bphu9Muuiv%2FibkKBsRsNxm6lg%2B9xIXqNPgfMjqYDCSM%3D&reserved=0> por favor, poderia ajudar neste issue?
@arthurtreuherz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farthurtreuherz&data=02%7C01%7Ctreuherz%40paho.org%7C04d08c51ba704408a26e08d8273a80a2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637302479505675763&sdata=IjpAKdAUv1p2SwW1Y3VTDzhYtw0BMRJziMltxKF7oJo%3D&reserved=0> o Márcio está de férias e por isso estou pedindo ajuda para o Wilson.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1112%23issuecomment-657599809&data=02%7C01%7Ctreuherz%40paho.org%7C04d08c51ba704408a26e08d8273a80a2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637302479505675763&sdata=ErFnfVC73dQ0p08v5YZv8%2BQH8Hdd6MNxyPVfFqCtkXk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFIN54FT6XRSDE5KQJCQK3R3MMAZANCNFSM4OYQNQ4A&data=02%7C01%7Ctreuherz%40paho.org%7C04d08c51ba704408a26e08d8273a80a2%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637302479505685753&sdata=jd90ClwNIevFhxbGJdtifPmNjb5%2F4vhQnjmsBpfx8uQ%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by wilsonmoura** [comment]
@arthurtreuherz esse ajuste já foi realizado? Verifiquei esse menu (cabeçalho e rodapé) e parece que está correto. Poderia confirmar?

**Comment by arthurtreuherz** [comment]
Sim Wilson. Já foi. Obrigado.

Abraço,
Arthur



Arthur Treuherz

Supervisor, Terminologias e Classificações em Saúde

Administração de Fontes de Informação

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel: (55) 11 5576-9817 VOIP 44822

[cid:65156185-68c6-47a3-8dcb-ac46ae63d09b]

________________________________
De: Wilson da Silva Moura <notifications@github.com>
Enviado: segunda-feira, 20 de julho de 2020 17:54
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Treuherz, Arthur (BIR) <treuherz@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Alterar o hyperlink de "Web Services" no footer em inglês da home do novo portal do DeCS (#1112)


@arthurtreuherz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farthurtreuherz&data=02%7C01%7Ctreuherz%40paho.org%7C217211d65dc04a7bf56c08d82cef2879%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637308752988882832&sdata=9ul39m1Wpi7paewewqUaUuaBEq%2B4CS4rRVXnKiB5HtM%3D&reserved=0> esse ajuste já foi realizado? Verifiquei esse menu (cabeçalho e rodapé) e parece que está correto. Poderia confirmar?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1112%23issuecomment-661327953&data=02%7C01%7Ctreuherz%40paho.org%7C217211d65dc04a7bf56c08d82cef2879%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637308752988892830&sdata=l6%2BYaFdIQ8QOzDV2J4Y%2BFiwvhwz6CBqA%2BLHfvsJo3sY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFIN533BYWME2DSJH4WHPDR4SVJ7ANCNFSM4OYQNQ4A&data=02%7C01%7Ctreuherz%40paho.org%7C217211d65dc04a7bf56c08d82cef2879%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637308752988892830&sdata=DjJBkH9i3IjtZfxsFT%2FH9qZKVom6Jxd2nacdtZw8Tww%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by renatomurasaki** [comment]
Link corrigido por meio da edição do menu, trocando a página em francês pela inglês.
