### ISSUE TITLE
Criar campo para o código ISO na API dos países

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#1116]
Lista dos códigos dos países que estão cadastrados no e-BlueInfo:

- Brazil - BRA
- El Salvador - SLV
- Guatemala - GTM
- Peru - PER

**Comment by viniciusandrade** [comment]
@wilsonmoura,
Implementado em https://github.com/bireme/fi-admin/commit/689b20039e9cf0482aeb309e36f63a0b9c6f6eb9, lembrando que o código ISO utilizado no FI-ADMIN é o de 2 letras.
