### ISSUE TITLE
Incorporar ao modelo uma tabela para incluir RelatedRegistryNumberList

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#1120]
Incorporar ao modelo uma tabela para incluir RelatedRegistryNumberList

Exemplo em D000001

```
    <RelatedRegistryNumberList>
     <RelatedRegistryNumber>52665-69-7 (Calcimycin)</RelatedRegistryNumber>
    </RelatedRegistryNumberList>
```

**Comment by falbrito** [comment]
Elementos
https://www.nlm.nih.gov/mesh/xml_data_elements.html
![image](https://user-images.githubusercontent.com/6940371/92397337-08029300-f0fd-11ea-940b-570b51002809.png)

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura essa demanda pode ficar suspensa.

**Comment by acecampos** [comment]
Desculpe-me, @wilsonmoura. Encerremos esse issue.
