### ISSUE TITLE
Criar atributo w para Web of Science ResearcherID no campo autor pessoal [10, 16 e 23]

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1131]
Considerando que o atributo s já é utilizado para estado, solicito a criação do atributo w para Web of Science ResearcherID no campo Autor pessoal para

analítica de série [10] => issue #236 
monográfico [16] =>issue #1126 
coleção [23] => issue #1127 

Muito obrigada!

**Comment by botturam** [comment]
Já está no fluxo regular. Falta haver dado (v10^w) para testar.

**Comment by suelisuga** [comment]
Obrigada @botturam
