### ISSUE TITLE
Diferenciação de palavras acentuadas

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1134]
Prezados,

Parece-me que o sistema de reconhecimento léxico não diferencia a acentuação. Poderiam confirmar?
A sugestão de descritor Canal Anal tem sido frequente em documentos que nada tem a ver com esse conteúdo. Pensamos que o sistema possa estar reconhecendo año como ano, que é um sinônimo de ano no idioma espanhol no vocabulário DeCS.

Ano
Año

Título do documento: Regulación emocional, atención plena y bienestar psicológico en estudiantes universitarios de primer año
Sugestão do DeCS do FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/90823291-0e76c980-e30c-11ea-9700-8d93c1e1eddf.png)

No DeCS:
![image](https://user-images.githubusercontent.com/13105683/91252943-fd2b2400-e734-11ea-86f1-34b82d0fb187.png)

Relacionado a #680 

Obrigada
Sueli

**Comment by heitorbarbieri** [comment]
Confirmo que o comportamento citado se deve ao processo de eliminação de acentos antes da procura por termos. Tal característica busca ampliar as situações onde um termo é encontrado, visto que se um termo fosse acentuado mas não no texto de entrada, ele não seria localizado.
A solução paliativa foi a inclusão da palavra ano ou año na lista de stopwords do sistema.

A versão do DeCSHighlighter contendo tal alteração é a do commit 97d6851
