### ISSUE TITLE
Ajuste na checagem de hierarquias órfãs no DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1139]
Fábio, pode ter passado na nossa checagem manual. O código hierárquico SP4.016.172.968.354 está ausente, mas possui filhos, conforme imagem abaixo.
![image](https://user-images.githubusercontent.com/35345406/92923239-80bf6300-f40d-11ea-9c44-41468b91ea0e.png)

Agradeço!

**Comment by falbrito** [comment]
Necessário revisão no processo de checagem

**Comment by arthurtreuherz** [comment]
Em 6/4/2021, o usuário da UNASUS chamado Onivaldo Rosa Junior, que é um licenciado do XML do DeCS 2020, encaminhou uma mensagem par o Marcelo Bottura, informando que ele havia identificado esse 3 descritores órfãos e outros 6. Nos primeiros 3 casos ele até percebeu que em 2018, o descritor "pai" que existia acima dos primeiros 3 descritores e que era exclusivo do DeCS, foi criado pelo MeSH como um conceito não preferido do descritor Spectral Analysis/Análise Espectral. Mas na época, nós nos esquecemos de alterar o código desses 3 "filhos" para que fossem para baixo do descritor Análise Espectral. Assim, felizmente pudemos corrigir a hierarquia desses 9 descritores.

Sugerimos que o Renato juntamente com o Wilson entrem em contato com o Onivaldo para pedir a ele o procedimento que ele desenvolveu para conseguir identificar esses órfãos e incorporar ao nosso sistema.

**Comment by renatomurasaki** [comment]
Processo revisado e ajustado, utilizando Tableau
