### ISSUE TITLE
Um "Popup" para lembrar usuário de colocar * ou $ ao buscar por permutado

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1140]
Oi, Fábio e Márcio! A maioria dos usuários tem encontrado dificuldade em fazer pesquisa por permutado na nova página do DeCS. 
Ideia de colocar um popup acima da caixa de pesquisa para lembrá-los.

Exemplo:

![image](https://user-images.githubusercontent.com/35345406/93096267-8e2d5500-f67a-11ea-820a-9bb124e980e2.png)

Obrigada!

**Comment by falbrito** [comment]
@acecampos 
Avaliar ambiente https://decs.teste.bvs.br com alteração.
Atentar que a seleção de "Termo exato" não mostra propositalmente a dica.
Avaliar a tradução da dica para os 4 idiomas.

Obrigado

![image](https://user-images.githubusercontent.com/6940371/93137742-5a6f2100-f6b4-11ea-8d61-539aeb561adb.png)

**Comment by acecampos** [comment]
Fábio, ficou ótimo.
Creio que o inglês poderia ficar: Use * or $ for wildcard searching.
Muito obrigada!
Ana Cristina Espindola Campos

Analista de Informação

BIREME<https://www.paho.org/bireme/index.php?lang=pt>

OPAS / OMS | Tel: +55 11 5576-9817 VOIP: 44824


[cid:1c995ae4-1773-4b47-9397-24370222ac8e]

________________________________
De: Fabio Brito <notifications@github.com>
Enviado: segunda-feira, 14 de setembro de 2020 18:03
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Campos, Ana Cristina Espindola (BIR) <camposan@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Um "Popup" para lembrar usuário de colocar * ou $ ao buscar por permutado (#1140)


@acecampos<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facecampos&data=02%7C01%7Ccamposan%40paho.org%7C461035c5df75476b674a08d858f199a1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637357141998460399&sdata=CXuTtfULNLuisUfW872B98YNXuRokApqs%2FIoXogj%2BqE%3D&reserved=0>
Avaliar ambiente https://decs.teste.bvs.br<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdecs.teste.bvs.br%2F&data=02%7C01%7Ccamposan%40paho.org%7C461035c5df75476b674a08d858f199a1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637357141998470396&sdata=73on74BY5De0hOJd1JYsHYcV1XyJsgep1K1GppZ7BJM%3D&reserved=0> com alteração.
Atentar que a seleção de "Termo exato" não mostra propositalmente a dica.
Avaliar a tradução da dica para os 4 idiomas.

Obrigado

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6940371%2F93137742-5a6f2100-f6b4-11ea-8d61-539aeb561adb.png&data=02%7C01%7Ccamposan%40paho.org%7C461035c5df75476b674a08d858f199a1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637357141998480388&sdata=YQV%2FHBqXSB1R%2FkMLgFagLzpO2UjuLSUBWhmn%2ByHIlog%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1140%23issuecomment-692312768&data=02%7C01%7Ccamposan%40paho.org%7C461035c5df75476b674a08d858f199a1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637357141998480388&sdata=CGS3w14atVm5iC%2FhrSKoKJCnfxFKjall3CdlGmcTd7s%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINVH7RKFBJXJ5ACKAJOC7DSF2AJFANCNFSM4RLUWVTQ&data=02%7C01%7Ccamposan%40paho.org%7C461035c5df75476b674a08d858f199a1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637357141998490387&sdata=w7ClDDc7i7%2F6FDslRl44lB%2FCHeIS8g2xyMpIsGPBn4k%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by falbrito** [comment]
Texto configurado nos 4 idiomas:

use * or $ for wildcard search (EN)
utilice * o $ para la búsqueda truncada (ES)
Use * ou $ para pesquisa truncada (PT)
Utilisez * ou $ pour la recherche tronquée (FR)
