### ISSUE TITLE
Desarrollar procedimientos para importar los datos de descripción bibliográfica extraídos y normalizados para la estructura de datos de legislación en salud del FI-Admin

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1155]
Desarrollo de la API JSON para legislación

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Mecanismo para visualizar a estrutura JSON que deve ser utilizada para importação de dados esta disponível no ambiente de testes. Segue abaixo comandos para geração da estrutura que já contempla um exemplo para a tabela de alternate_id:
```
$ cd /home/apps/fi-admin
$ make prod_exec_shell
/app $ python manage.py dumpdata --indent=4 leisref > fixtures/import/leisref_dump.json
/app $ exit
```
O arquivo ficará disponível no diretório **/home/apps/fi-admin/fixtures/import/**.

O processo de importação é o mesmo já em uso para as demais fontes de informação usando o comando **python manage.py loaddata**
