### ISSUE TITLE
Analisar a questão de associação  das imagens no FI-admin dentro do contexto do e-BlueInfo

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#1156]
Essa questão pode estar no protocolo SSL (htpps)

**Comment by viniciusandrade** [comment]
Aberto chamado Ocomon 7550 para avaliação de ativação do SSL no dominio docs.bvsalud.org.

**Comment by viniciusandrade** [comment]
@wilsonmoura foi habilitado SSL no dominio docs.bvsalud.org onde são disponibilizados as imagens e também os documentos do FI-ADMIN, por favor verificar se isso corrigiu o problema de carregamento das imagens de coleções e que não tenha ocorrido algum efeito não previsto na abertura dos documentos.

**Comment by wilsonmoura** [comment]
@viniciusandrade o problema ocorria apenas nas imagens das comunidades. Mas com a implementação do HTTPS, o problema foi solucionado.
