### ISSUE TITLE
Problema nas tabelas de controle com filtro de País/Região.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1157]
Na Leisref administración, as tabelas que tem filtro por País/Região, por exemplo os actType que não tem nenhuma opção de Região selecionada. 
![adm_actType](https://user-images.githubusercontent.com/19270675/97564155-e8803c00-19c2-11eb-8998-b4bef4b8e0db.JPG)
  

aparecem em lista do formulário, acontece com todas as tabelas.
![ar_actType](https://user-images.githubusercontent.com/19270675/97564242-064da100-19c3-11eb-9412-91f4d89c999a.JPG)

**Comment by renatomurasaki** [comment]
@anakatiacamilo o comportamento padrão implementado (@viniciusandrade confirmar, por favor) é de aplicar a todos qdo não há indicação de país. Nesse caso terá que especificar os países, excluindo Argentina.

**Comment by anakatiacamilo** [comment]
@viniciusandrade então eu tenho que selecionar todos os países de todas as opções que não tem nenhum país selecionado para não aparecer somente para a Argentina?

**Comment by renatomurasaki** [comment]
@anakatiacamilo já ajustei para você. Pode checar que estes não aparecem mais para a Argentina

**Comment by anakatiacamilo** [comment]
@renatomurasaki, Obrigada por explicar com funciona, a Tabela Tipo de ato esta OK, vou revisar as outras tabelas.

Coleções
Tipos de ato - OK
Tipos de relacionamento
Órgão Emissor do Ato
Esferas do ato
Fontes do ato
