### ISSUE TITLE
Sugestão para Selecionar País/Região

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1158]
Seria possível mudar o modo de selecionar o País/Região nas tabelas do Leisref 
![adm_1actType](https://user-images.githubusercontent.com/19270675/97573265-3c415400-19c8-11eb-8d8e-d5f815d53acb.JPG)

Deixar igual ao campo de Indexado em 
![Indexadoem](https://user-images.githubusercontent.com/19270675/97573273-3ea3ae00-19c8-11eb-82a0-c94b3939c25d.JPG)

Parece um modo mais seguro de selecionar esta opção sem desmarcar as opções já selecionadas

**Comment by viniciusandrade** [comment]
@anakatiacamilo infelizmente este tipo de alteração não é possível pois se trata de formulário interno do Django Admin.
