### ISSUE TITLE
Revisar a normalização dos dados das listas controladas de legislação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1159]
Exemplo:

- Tipo de ato normativo
  - há duas portarias sendo utilizadas, uma pelo Brasil e outra pelos demais países, pois a tradução da Portaria utilizada pelo Brasil está equivocada (Portería ao invés de Ordenanza)

**Comment by anakatiacamilo** [comment]
Alterei todos os registros do Brasil que estavam com a Portaria cód.95 para o cód. 5.
Incluir o Brasil no tipo de ato Portaria cód. 5 e Apaguei da lista controlada o tipo de ato Portaria cód. 95.
