### ISSUE TITLE
Implementar formulário e validação para tipo "SC" nível de tratamento "as"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#116]
Relacionado ao backlog de produto #77

**Comment by sarahviola** [comment]
Deveriam ser campos obrigatórios para tipo C (Conferência):
- Nome do evento
- Data do evento
- Data normalizada do evento (quando não preenchido **s.d** no campo de data)
- Cidade

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste de campos obrigatórios realizada. Favor quando possível realizar novo teste.

[]s

**Comment by sarahviola** [comment]
Ok.
Considerando "Nome do evento" para gravar C no tipo de documento.
