### ISSUE TITLE
O link Consultar a definição no DeCS não esta funcionando direito nos descritores compostos.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1165]
Quando pesquisamos um Tipo de Publicação e Precodificado com mais de uma palavra ou o descritor não é encontrado ou só mostra a primeira palavra do descritor.

![decs_tipopublicacion_eng](https://user-images.githubusercontent.com/19270675/99338563-2efae500-2863-11eb-94b5-27d0d3db9705.JPG)
 
![decs_tipopublicacion_revision](https://user-images.githubusercontent.com/19270675/99338573-33bf9900-2863-11eb-8ff0-332eee23e298.JPG)

![decs_precod_aged](https://user-images.githubusercontent.com/19270675/99338582-3621f300-2863-11eb-9271-ebf6ec4944b5.JPG)

**Comment by viniciusandrade** [comment]
@falbrito conforme conversamos não consegui identificar uma regra de url no novo portal para recuperar um ou mais termos compostos. 
Exemplo: 
"Relatos de Casos" OR "Revisão Sistemática"

Agradeço se puder verificar se é possível e caso afirmativo informar a regra da url.

**Comment by falbrito** [comment]
@viniciusandrade por favor teste essas URL, criei o filtro **ths_exact_term_bool** no plugin. Veja se te atende, se funcionar vou aplicar em produção.

https://decs.teste.bvs.br/pt/ths?filter=ths_exact_term_bool&q="Relatos de Casos" OR "Revisão Sistemática"

**Comment by viniciusandrade** [comment]
@falbrito fiz os testes e me parece perfeito, obrigado pela implementação.

Favor informar quando estiver disponível em produção para que eu possa ajustar o FI-ADMIN.

**Comment by falbrito** [comment]
@viniciusandrade a alteração no portal DeCS já está em produção.
Abraços

**Comment by viniciusandrade** [comment]
@falbrito obrigado ... código ajustado para utilizar esta nova forma de consulta.
