### ISSUE TITLE
Cria novos índice de busca 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1168]
Campos que já tem no FI-ADMIN:
La búsqueda libre buscará el término en los campos: número del acto, título y denominación.
Para buscar por el identificador único de un registro utilice el prefijo id:
+Estado;
+Tipo del acto;
+País/Región de alcance del acto;
+Indizado en

Campos solicitados pelo usuário

órgano emisor,
tipo de instrumento == Tipo del acto
número == Geral
denominación =Gerel
año
sumario
ciudad
estado
situación == Estado

**Comment by renatomurasaki** [comment]
@viniciusandrade estos indices fueron generados?

**Comment by viniciusandrade** [comment]
@renatomurasaki, ainda não. Estou negociando com eles a redução desta lista devido a impacto na performance do sistema caso sejam implementados todos os solicitados.

**Comment by viniciusandrade** [comment]
En reunión de 15/03 fue solicitado a Oscar que por cuestión de performance de FI-ADMIN sea informado 2 indices principales desta lista para que sea posible su implementacíon. Oscar ira confirmar y enviar los campos.

**Comment by viniciusandrade** [comment]
En la reunión de 29/03 Oscar ha definido que el unico filtro requerido para FI-ADMIN es por el campo **esfera del acto** que sera implementado.

**Comment by viniciusandrade** [comment]
Filtro implementado e disponível em produção.
