### ISSUE TITLE
Implementar formulário e validação para tipo "SP" nível de tratamento "as"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#117]
Relacionado ao backlog de produto #77

**Comment by sarahviola** [comment]
De acordo com a Metodologia LILACS:
_b) É obrigatório o preenchimento do campo de dados 59 ou 60. Não existindo a informação sobre
o nome ou o número do projeto não se indica que o documento faz parte de um projeto. _

Ou seja, deve ser obrigatório preencher "Nome do projeto" [59] ou "Número do projeto" [60].

**Comment by sarahviola** [comment]
O sistema só indica como "SPas" quando preencho o campo "Nome do Projeto".

Quando preencho "Número do projeto" ele continua como Sas, mas também deveria ser "SPas".

**Comment by viniciusandrade** [comment]
@sarahviola,

OK. Ajustei o sistema para registrar o P no tipo de literatura quando for preenchido o campo "Nome do projeto" **E/OU** "Número do projeto".

Quando possível favor validar.
:+1:

**Comment by sarahviola** [comment]
@viniciusandrade, gravei novamente com o perfil de documentalista o registro que já tinha o campo "número de projeto" (id [136](http://fi-admin.teste.bvsalud.org/bibliographic/edit-analytic/136)) e ele continua sem o _P_, só como _Sas_.

Preenchi "número do projeto" também em outro registro (id [156](http://fi-admin.teste.bvsalud.org/bibliographic/edit-analytic/156)) utilizando o perfil editor e esse também continua só _Sas_, sem o _P_.

**Comment by viniciusandrade** [comment]
@sarahviola 

Acho que havia esquecido de atualizar o ambiente de testes. 8-(  Poderia verificar novamente por favor?

**Comment by sarahviola** [comment]
Agora está gravando corretamente como **SPas**.
