### ISSUE TITLE
Avaliar se o campo Órgano Emisor pode ser repetitivo.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1181]
Para poder contemplar o conteúdo migrado do Legisalud Argentina (TC-Legis).

**Comment by viniciusandrade** [comment]
@anakatiacamilo fiz os ajustes necessários no ambiente de cursos para que o campo **orgão emissor** aceite múltiplos valores.

Observações:
* A migração agora vai precisa popular a tabela de relacionamento **leisref_act_issuer_organ** que contém as colunas **act_id** e **actorganissuer_id**
* Após a validação no ambiente de cursos vou precisar parar algumas horas o FI-ADMIN para poder migrar o os conteúdos atuais da base para a nova estrutura.

Por favor, quando possível, ajustar o procedimento de migração deste campo e informar se esta tudo OK.

Obrigado.

**Comment by anakatiacamilo** [comment]
@viniciusandrade, conforme conversamos fiz a alteração no formato 
        "issuer_organ": [
            88,
            84,
            87
        ]
Migrei a base novamente e esta tudo certo.

**Comment by viniciusandrade** [comment]
@anakatiacamilo, ok ... obrigado pela validação. 

Lembrando que vamos precisar coordenar a migração para a base de produção, pois antes eu preciso criar a tabela de relacionamento e migrar os conteúdos do campo antigo para o novo formato.
