### ISSUE TITLE
Campos Legislação - Esfera do Ato x Grupo Geográfico

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1184]
Em Legislação, na instância de Cursos, o campo "Esfera del acto" lista algumas opções como Mercosur, Unisur, Parlatino, mas estas opções não são esfera, mas Grupo Geográfico, que é outro campo existente.

 ![image](https://user-images.githubusercontent.com/47643830/106668825-8a4a9280-6589-11eb-9545-d0628fafd5f6.png)

Manual de descrição bibliográfica:

![image](https://user-images.githubusercontent.com/47643830/106668894-a0f0e980-6589-11eb-97a2-80b969dcf9e2.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, conversamos com o responsável pela base, como o campo Grupo Geográfico não tem lista controla nem como pesquisar por este campo optamos em colocar as opções MERCOSUR, PARLATINO e UNASUR no campo de Coleção.

Foi escolhido o campo de Coleção, porque. já tinha a opção de MERCOSUR só precisamos incluir as outras duas opções: PARLATINO e UNASUR.

Em analise descobri que as opções: Parlamento Latinoamericano e UNASUR estão em outro campo Órgano Emisor del Acto.

- Para manter as três opções juntas tiramos a informação do campo Esfera do Acto, e marcamos a opção Internacional neste campo;
- Incluímos as opções  PARLATINO e UNASUR na lista controlada do campo de Coleção;
- Marcamos os registros no campo Coleção.
