### ISSUE TITLE
Sistema não esta permitindo a edição de leis relacionadas

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1186]
Erro ocorre na versão django2.

**Comment by viniciusandrade** [comment]
@anakatiacamilo favor verificar no processo de importação das leis relacionadas se no JSON esta indo o ID do usuário que criou a lei relaciondada (created_by) porque aparentemente este é o motivo do sistema não conseguir entrar no formulário de edição para estes registros.

**Comment by anakatiacamilo** [comment]
@viniciusandrade, fiz testes e consegui editar o registros que eu criei no FI-ADMIN de curso sem problemas.

**Comment by viniciusandrade** [comment]
OK, obrigado por verificar.
