### ISSUE TITLE
LEGSES - Erro ao abrir registros já publicados

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1188]
A usuária Alessandra.delrei (BR91.2) não consegue editar reistros pois, ao abri-los, aparece uma mensagem de erro.

![image](https://user-images.githubusercontent.com/47643830/108236782-09ad9980-7126-11eb-96dc-48c30d7448dd.png)

Realizei testes com o mesmo perfil, código e mesmo navegador (Chrome), mas não consegui reproduzir o erro.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula também fiz o teste aqui usando trocando o código do meu usuário para BR91.2 e usando mesmo perfil editor e não consegui identificar o problema. 

Eu fiz um ajuste no sistema para na tela que atualmente esta informando Server Error (500) apareça mais informações sobre o erro. Poderia pedir para a usuária tentar novamente editar o mesmo registro e enviar o print screen da tela de erro?

Obrigado

**Comment by AngelicaSAPaula** [comment]
Bom dia! No novo teste, aparece a seguinte tela:

![image](https://user-images.githubusercontent.com/47643830/108350654-424f8080-71c3-11eb-9e92-5a202d5ac471.png)

**Comment by viniciusandrade** [comment]
Bom dia. 

OK, já foi possivel verificar e acredito corrigir o problema. 

O estranho é que, pelo que pude verificar,  essa condição acontece quando a usuária não irá conseguir editar o registro ... por favor peça para ela sair e entrar novamente no FI-ADMIN e fazer um novo teste.

Obrigado.

**Comment by AngelicaSAPaula** [comment]
A usuária realizou a limpeza do cachê, saiu e entrou novamente no sistema e continua visualizando como Documentalista:

![image](https://user-images.githubusercontent.com/47643830/108367316-17bbf280-71d8-11eb-85b1-e1f87edba604.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula precisei reiniciar a senha da usuária para que o sistema atualizasse o perfil para editora.

Estou enviando para você por email a nova senha para que você possa realizar um teste no seu computador e estando OK enviar para ela poder alterar e conseguir editar os registros.
