### ISSUE TITLE
Esconder campo de status para área temática e gravar valores como admitidos

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#119]
Diferente dos outros módulos do FI-ADMIN onde era necessário a revisão deste campo por um editor no caso do módulo de referências bibliográficas este campo pode ser informado diretamente pelo documentalista.

**Comment by sarahviola** [comment]
Ok.

![image](https://cloud.githubusercontent.com/assets/18355163/15077872/df4746ac-1386-11e6-852d-bdaff98b78a1.png)
