### ISSUE TITLE
Implantar ordenação da Coleção na funcionalidade Classificação para eBlueInfo

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1192]
Solicito que seja possível ordenar os nomes de coleção dentro da Subcomunidade para facilitar a marcação no FI-Admin.
![image](https://user-images.githubusercontent.com/13105683/111208494-8eff5f00-85a9-11eb-9754-a135b62dde62.png)
Atualmente o sistema mostra na ordem em que foi criado, o que prejudica o entendimento do bibliotecário que realizará a marcação e também a criação das coleções visto que deve ser feita na ordem e quando temos que incluir outras coleções, elas ficam fora da ordem.
![image](https://user-images.githubusercontent.com/13105683/111208705-dd146280-85a9-11eb-8391-418019e7e49e.png)

![image](https://user-images.githubusercontent.com/13105683/111208830-0634f300-85aa-11eb-9ac1-d029237541c2.png)

Talvez incluir um campo para numeração da ordem como a que existe no bloco de texto...

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga ordenação implementada na tela de classificação.
