### ISSUE TITLE
Como recuperar os registros (bibliográficos, legislacao, multimedia, etc) que foram marcados nas Coleções

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1194]
Para facilitar a curadoria dos conteúdos do e-BlueInfo, o FI-Admin poderia gerar filtros nos registros bibliográficos, legislação, multimidia etc para listar quais registros foram marcados em uma determinada Comunidade, Sub-Comunidade e Coleção.

Atualmente há o filtro "Indexado em". Como poderíamos gerar um ou mais filtros para facilitar o acesso por Comunidade, Sub-Comunidade e Coleção?

Lembrando que hoje temos apenas a Comunidade e-BlueInfo e que pretendemos ampliar para outros projetos que tem utilizado o campo "Base de Dados", da aba "Biblioteca", como por exemplo projetos PIE, BIGG e BRISA.

**Comment by renatomurasaki** [comment]
@viniciusandrade por favor, inclua este issue no próximo sprint.

**Comment by viniciusandrade** [comment]
@renatomurasaki OK, implementado para legislação e multimídia. Retirado da lista as opções de subcomunidade pois  não seria possível filtrar por eles.
