### ISSUE TITLE
API de coleção não esta retornando a tradução do elemento pai (parent) quando disponível

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1195]
Exemplos de coleções onde o elemento parent possui tradução e a API não esta retornando:

https://fi-admin-api.bvsalud.org/api/collection/?community=60&format=json&lang=en

https://fi-admin-api.bvsalud.org/api/collection/?collection=69&format=json&lang=en

**Comment by viniciusandrade** [comment]
@wilsonmoura ajuste aplicado na API, favor verificar se agora esta OK no e-blueinfo.

Obrigado

**Comment by wilsonmoura** [comment]
@viniciusandrade está tudo OK. Obrigado.
