### ISSUE TITLE
Checagem do campo "Veja também" para saber se o(s) descritor(s) contidos no campo ainda existem como descritor

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1199]
A checagem que eu fazia no ISIS checava a presença do subcampo t e do campo ID de transporte (antes chamado de v480 ou UI). Como agora todos os campos "Veja também" possuem o ID de transporte, eu teria teria que editar a shell que eu utilizava. 

Assim, peço por favor que desenvolva um novo procedimento. O procedimento antigo fica no seguinte endereço:
quartzo2:/home/decsweb/www/bases/procs/2020/passos/passo15/passo15a1/chktr.sh

Exemplo de caso que está desatualizado:

Descritor = Cola
Termo alternativo = Kola
Veja também = Kola <--retirar, pois agora é termo alternativo.

O descritor em 2019, Kola, foi incorporado ao descritor Cola em 2020. Provavelmente existirão outros casos semelhantes.

**Comment by arthurtreuherz** [comment]
Wilson,
Assim que possível, há que checar esse issue de prioridade 1, pois a base ainda está com vários "Veja também" desatualizados.
Exemplo, acabo de atualizar um descritor que encontrei "Equidade" que ainda tinha dois "Veja também" errados: "Millenium Development Goals" e "Social Inequity". Estes dois em 2021 agora são conceitos não preferidos respectivamente de "Global Health Strategies" e "Socioeconomic Factors". Se o Fábio já desenvolveu é só executar. Se não, há que criar o procedimento conforme informado acima.

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura Criado o campo de "Veja também" no registro de "Indústria de Cerâmica" https://fi-admin.teste.bvsalud.org/thesaurus/descriptors/view/744591?ths=1 para teste do campo.

**Comment by acecampos** [comment]
@wilsonmoura Talvez seja melhor usar esse exemplo de descritor que mudou em 2023 e é "Veja também" do descritor Homeopsorics: 
DDCS025890 [Pharmacodynamics of Homeopathic Remedy]

https://fi-admin.teste.bvsalud.org/thesaurus/descriptors/view/532480?ths=1

**Comment by acecampos** [comment]
@wilsonmoura Conforme conversado, correção do exemplo utilizado: 
https://fi-admin.teste.bvsalud.org/thesaurus/descriptors/view/532480?ths=1

**Comment by acecampos** [comment]
Exemplo com descritor do MeSH: https://fi-admin.teste.bvsalud.org/thesaurus/descriptors/view/539680?ths=1

**Comment by wilsonmoura** [comment]
@acecampos o processamento para verificar termos relacionados finalizou. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
No ambiente de testes do Fi-Admin, o processamento eliminou dados inválidos no campo "VEJA TAMBÉM". Validado.

**Comment by wilsonmoura** [comment]
## Documentação dos passos para checagem dos descritores relacionados

No servidor de processamento, executar os comandos abaixo para iniciar o processo de checagem dos descritores relacionados:

```
$ cd /bases/dec.000/atualiza_NLM/wrk/
$ # nohup python ../tpl/verifica_relacionados.py &> ../outs/verifica_relacionados.YYYYMMDD.out &
```

**OBS:** Antes de executar o carregamento, certificar que os dados do ambiente de testes do Tesauro FI-ADMIN estão atualizados de acordo com o ambiente de trabalho/produção.
