### ISSUE TITLE
fi-admim title Campos title Online resources (NewURL) retirar

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#12]
Retirar esses campos,  não é mais pertinentes nos dias atuais

ONLINE full text

Unavailable for libraries

Allows buying articles

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
Os campos descritos foram retirados do formulário e ficaram como histórico.
