### ISSUE TITLE
Esconder campo de status para descritores e gravar valores como admitidos

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#120]
Diferente dos outros módulos do FI-ADMIN onde era necessário a revisão deste campo por um editor no caso do módulo de referências bibliográficas este campo pode ser informado diretamente pelo documentalista.

**Comment by sarahviola** [comment]
Ok.

![image](https://cloud.githubusercontent.com/assets/18355163/15077841/b4849bae-1386-11e6-9317-218e55ef6e40.png)
