### ISSUE TITLE
Tesauro FUNASA: erro 500 ao gravar alteração

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1203]
Ao editar o código hierárquico de Radiometria no tesauro FUNASA, apareceu erro 500:

ID de transporte: DFNS000743
ID no tesauro: 743

![image](https://user-images.githubusercontent.com/35345406/114867077-baed4a80-9dca-11eb-8348-48b4ccb01d5e.png)

**Comment by wilsonmoura** [comment]
@acecampos essa problema ainda persiste? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura essa demanda ainda persiste.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura Validado! Agradeço!
