### ISSUE TITLE
Correção de um detalhe no procedimento de carregamento de descritores novos e sinônimos novos do MeSH

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1204]
Existem 9 casos possíveis de duplicação de termos em **inglês** ao se carregar termos do MeSH no DeCS:

1. **PEP do MeSH duplica com MH exclusivo do DeCS**
2. PEP do MeSH duplica com PEP exclusivo do DeCS
3. PEP do MeSH duplica com ET exclusivo do DECS
4. MH do MeSH duplica com MH exclusivo do DeCS
5. MH do MeSH duplica com PEP exclusivo do DeCS
6. MH do MeSH duplica com ET exclusivo do DeCS
7. ET do MeSH duplica com MH exclusivo do DeCS
8. ET do MeSH duplica com PEP exclusivo do DeCS
9. ET do MeSH duplica com ET exclusivo do DeCS

Encontrei um **erro no primeiro caso** mas não sei se há problema nos outros. Seria bom dar uma checada ao menos nesse. Percebi sim que, também quando se carrega PEPs especificamente da Espanha, estes não estão indo para o termo preferido do conceito não preferido, PEP, mas para o termo não preferido do conceito não preferido, ET). Poderia verificar também? Bem, criei esse issue pra a gente (Wilson, Ana, eu e quem mais ler) entender o que aconteceu e analisar o que detalho abaixo e proponho para automatização e correção do problema.

Detalhando o erro encontrado para o primeiro caso acima.

1. PEP do MeSH duplica com MH exclusivo do DeCS

Aparentemente durante o processamento dos campos em inglês do "replaced_marked_POR.xlsx" pelo Fábio, o novo PEP do MeSH Social Cohesion 

**F01 | D003299 | M000679402 | ENG | PEP | Social Cohesion | T001005764 | NEW_ROW** | Solidarity of a group, including the integration of the group for both social and task-related purposes.

foi criado como **ET** dentro do conceito principal e não como um **PEP**. Assim, quando esse termo duplicou com o termo preferido do conceito preferido (MH) do descritor exclusivo do DeCS Social Cohesion, 

No DeCS 2020:

![social_cohesion_DeCS2020](https://user-images.githubusercontent.com/25855735/115430498-cd0c2600-a1da-11eb-8349-28652c140729.jpg)

No FI-ADMIN após processamento - visão Detalhes - Os demais idiomas também ficaram no primeiro conceito mas já movi para um terceiro conceito de nome temporário. Nas 2 imagens mostradas abaixo, o termo Social Cohesion já não aparece pois agora está no terceiro conceito que eu acabo de criar com código de conceito temporário e termo termporário para criação do conceito.

![social_cohesion_visao_detalhes_fi-admin2021](https://user-images.githubusercontent.com/25855735/115431271-80751a80-a1db-11eb-869d-2537d4a5f098.jpg)

No FI-ADMIN após processamento - visão conceitual. Também houve bug na estrutura do conceito principal, pois não deveria aparecer tantos hyperlinks pra "Adicionar termo".

![social_cohesion_visao_conceitual_fi-admin2021](https://user-images.githubusercontent.com/25855735/115431700-fa0d0880-a1db-11eb-83ef-f653668ece0d.jpg)

ele e suas traduções foram movidos para o descritor MeSH. Só que conceito não estava lá no descritor MeSH. Com isso, todos ficaram no primeiro conceito (MH). As traduções vieram com parâmetros **Y** para RecordPreferredTermYN. Não entendi porque o sistema não conseguiu criar o PEP com ConceptUI do MeSH. 

Se, ao executar o **carregamento** dados de um arquivo contendo registros **de descritores novos**, 

**determinado PEP** do MeSH ,
ou seja, com ConceptUI iniciado com M, com o **nome de conceito preferido** (ConceptName com parâmetro PreferredConceptYN=N) e também duplicará com o seu **termo preferido desse conceito NÃO preferido** ((String do campo Term, com parâmetro ConceptPreferredTermYN=Y RecordPreferredTermYN=N)

**duplicar com um MH** não MeSH, 
ou seja, com DescriptorUI iniciado com "DDCS", duplicará então com um **nome em inglês de descritor** (DescriptorName), duplicará também com o **nome em inglês de conceito preferido** (ConceptName com parâmetro PreferredConceptYN=Y) e por fim também duplicará com o seu **termo preferido em inglês desse conceito preferido** ((String do campo Term, com parâmetro ConceptPreferredTermYN=Y RecordPreferredTermYN=Y).

Essa duplicação portanto será em descritores diferentes e entre códigos de descritor, códigos de conceitos diferentes e códigos de termos diferentes e não deve ocorrer nem quando estão em idiomas iguais, diferentes, com caixa alta ou baixa, com acento ou sem acento.

Quando isso ocorrer, precisa ser listado como "duplicação encontrada", conforme já consta formato na última checagem do Fábio desse ano. E informar que a movimentação foi efetuada ou não e que o PEP foi criado ou não. Isso é importante para verificarmos erros e para acertarmos a posição desse novo descritor na estrutura hierárquica exclusiva do DeCS, conforme o(s) código(s) desse descritor exclusivo DeCS. A fusão se possível deverá continuar sendo efetuada de forma automática quando o registro do MH for exclusivamente do DeCS, ou seja, da seguintes maneira:

1. O registro onde está o PEP novo do MeSH permanece como está.
2. No descritor exclusivo do DeCS, 
a) o conceito preferido é transformado em conceito não preferido PEP para que apareça a função do sistema de mover conceito; 
b1) caso o PEP no MeSH ainda não esteja lá, esse PEP inteiro do registro exclusivo deve ser movido para o registro MeSH e os termos preferidos desse conceito deverão ser movidos para o descritor MeSH, continuando como termos preferidos desse conceito não preferido PEP. O código do PEP deve ser atualizado, o código do termo em inglês deve ser atualizado.
b2) caso o PEP no MeSH já esteja lá, os termos preferidos desse conceito deverão ser movidos para o PEP do MeSH, continuando como termos preferidos desse conceito não preferido PEP. -- o termo preferido em inglês do descritor exclusivo DeCS pode ser eliminado não pois ele já está lá com o código correto do MeSH; 
c) no caso de b2 acima, os demais termos não preferidos (ETs) desse conceito e descritor exclusivo do DeCS devem ser movidos para dentro desse conceito do MeSH, continuando com seu status de "não preferidos do conceito não preferido", isto é, ETs. No caso de b1 acima, isso já terá ocorrido pois o conceito inteiro foi movido. 
d) caso ainda não exista definições nos idiomas exceto inglês no PEP do MeSH, as definições em espanhol latinoamericano, português, espanhol da Espanha devem ser movidas para dentro desse conceito PEP do MeSH, -- a definição em inglês não pois o inglês é do MeSH --  Senão, eliminar as definições do descritor exclusivo.
e) os demais conceitos não preferidos e termos preferidos e não preferidos desses conceitos não preferidos desse descritor exclusivo deverão ser movidos para o novo.

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura parece-me que essa demanda foi corrigida pela geração de relatórios
