### ISSUE TITLE
Criar box para mensagem inicial no perfil Editor LILACS-Express

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#121]
Permitir o registro de um texto inicial do sistema para os editores com links para textos de ajuda e links de atalhos (IAH, ajuda, etc).

**Comment by viniciusandrade** [comment]
O texto que será mostrado na tela inicial (Painel de controle) precisa ser adicionada pelo Django Admin na opção "Text blocks".

**Comment by sarahviola** [comment]
Edição da caixa não permite inclusão de links. Só é possível incluir links copiando e colando links mantendo a formatação do texto de origem.

![image](https://cloud.githubusercontent.com/assets/18355163/14898257/414c7178-0d5c-11e6-8a7b-77aafb9cb64b.png)

![image](https://cloud.githubusercontent.com/assets/18355163/14898195/fd7c49f0-0d5b-11e6-98ca-a72f58c1711a.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Adicionado botão para inserir link na caixa de texto. Quando possível favor validar.

**Comment by sarahviola** [comment]
Botão para incluir link funcionando..

![image](https://cloud.githubusercontent.com/assets/18355163/14927756/24b10e74-0e2a-11e6-9ccf-53f76a1ed109.png)

![image](https://cloud.githubusercontent.com/assets/18355163/14927770/32d3b060-0e2a-11e6-9209-756fea504813.png)
