### ISSUE TITLE
Atualizar imagem da estrutura de dados do biblioreference e do models e gerar para as demais aplicações

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1213]
Estruturas a serem atualizadas:
https://github.com/bireme/fi-admin/blob/master/docs/biblioref.png
https://github.com/bireme/fi-admin/blob/master/docs/models.png

Seguir mesmo padrão ou o padrão adotado para o tesauro
https://github.com/bireme/fi-admin/blob/master/docs/thesaurus/thesauro_modelagem.png

Para gerar a estrutura de dados das demais aplicações

**Comment by renatomurasaki** [comment]
@viniciusandrade por favor, gerar as imagens que documentam as estruturas de dados o mais breve possível para auxiliar na construção dos ETL, assim como no compartilhamento de informação técnica com AFRO que quer entender os metadados do FI-Admin, principalmente biblioref e title.

**Comment by viniciusandrade** [comment]
@renatomurasaki atualizei as imagens das estruturas mas como desconheço qual ferramenta utilizada para gerar as do tesauro usei  a mesma utilizada inicialmente.

**Comment by renatomurasaki** [comment]
Está ótimo. Importante mantê-las atualizadas!
