### ISSUE TITLE
Restringir o acesso dos usuários do Tesauro por idioma

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#1218]
Restringir o acesso dos usuários do Tesauro por idioma, ou seja:
- BIREME todos os idiomas
- Chile só `es` da AL
- Espanha só `es-es`
- França somente `fr`

**Comment by renatomurasaki** [comment]
@wilsonmoura por favor, informe para o @arthurtreuherz como ele pode simular o acesso de um usuário do Chile, Espanha e França para perceber o acesso restrito que fora implementado. Quais foram os Centros Cooperantes?

**Comment by wilsonmoura** [comment]
@renatomurasaki a restrição dos CCs foi aplicada de acordo com o prefixo do CC atribuído ao usuário:
- BIREME: BR1.1
- Chile: prefixo CL
- Espanha: prefixo ES
- França: prefixo FR

Com relação aos testes, para que o @arthurtreuherz possa simular os níveis de restrição, teríamos que alterar o CC do seu respectivo usuário no FI-ADMIN.

**Comment by arthurtreuherz** [comment]
Wilson, sugiro que testemos isso assim que encerrarmos os processos de atualização do DeCS definitivo 2021? Para o caso de precisarmos corrigir algum erro nos processos. Aí você alterar o meu CC, ok?

**Comment by arthurtreuherz** [comment]
Wilson, quando puder, podemos testar a restrição de acesso pra mim. Por exemplo, CL.

**Comment by arthurtreuherz** [comment]
Validado. Obrigado.
