### ISSUE TITLE
Ajustar a apresentação das coleções (eblueinfo e BIGG) no filtro coleções segundo o idioma da interface

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1220]
Solicito apresentar os labels no filtro de coleções de acordo com o idioma da interface no FI-Admin:

![image](https://user-images.githubusercontent.com/13105683/120244093-ae6c6680-c23f-11eb-8f3d-bedca5506c78.png)

Muito obrigada!

**Comment by viniciusandrade** [comment]
OK com a limpeza do cache do sistema.
