### ISSUE TITLE
Apresentar coleções no idioma da interface no momento de classificação

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1221]
Solicito que os labels sejam apresentados no idioma da interface quando o bibliotecário for classificar o documento.

![image](https://user-images.githubusercontent.com/13105683/120244229-0f943a00-c240-11eb-9f21-9fa4275c5936.png)

Muito obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga já esta OK com a limpeza do cache.
