### ISSUE TITLE
Geração do MeSH Spanish (MSHSPA) e MeSH Portuguese (MSHPOR) 2021 para o UMLS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1224]
Favor produzir os dois arquivos com o mesmo formato do ano passado. Não há necessidade de modificação de formato para a entrega desses arquivos. A mudança que houve foi apenas para a produção das listas aos centros tradutores.

Dessa vez já podemos incluir as notas de escopo tanto em português quanto em espanhol.

**Comment by arthurtreuherz** [comment]
Wilson, conforme comentado na reunião, a única mudança seria também incluir no arquivo do espanhol as notas de escopo na última coluna, igualando com o formato do português. obrigado.

**Comment by wilsonmoura** [comment]
@arthurtreuherz segue link do arquivo compactado com os relatórios: [RELATORIOS_TERMOS_BIREME.zip](https://github.com/bireme/fi-admin/files/6651999/RELATORIOS_TERMOS_BIREME.zip)

**Comment by arthurtreuherz** [comment]
Excelente Wilson, só um pequenino detalhe: 

Os nomes dos arquivos EM ESPANHOL estão trocados. O que diz ter a definição não tem e o que diz ser só de termos tem a definição (e o conteúdo desse está correto pois a definição está em MH e PEP). 
É só inverter os nomes dos arquivos. Vou aproveitar esse segundo arquivo que você mandou. 

E EM PORTUGUÊS, o arquivo que diz ter só termos tem definições de MH e de PEP (ver, por exemplo, linhas 15 e 337) e o arquivo que diz ter notas de escopo tem notas de escopo só para os MH. Vou aproveitar o primeiro desses dois. 

Portanto, obrigado, está validado. Mas recomendo checar o procedimento pra que os nomes saiam certos da próxima vez.

**Comment by arthurtreuherz** [comment]
Wilson, conforme comentado, solicito assim que possível, a geração de novas listas, devido ao feedback da Stephanie Lipow de ontem, que rodou um controle de qualidade e identificou alguns problemas, já resolvidos na base DeCS e já compartilhados com você.

**Comment by wilsonmoura** [comment]
@arthurtreuherz segue link do arquivo compactado com os relatórios atualizados: [RELATORIOS_TERMOS_BIREME.zip](https://github.com/bireme/fi-admin/files/6751904/RELATORIOS_TERMOS_BIREME.zip)

**Comment by arthurtreuherz** [comment]
Obrigado Wilson, só que os arquivos foram gerados com uma base de antes de ontem ou mais dias, pois ontem de manhã eu entrei pelo fiadmin2 e, por exemplo, já pude alterar o código do conceito Dispositivos Móveis e fiz algumas outras atualizações que já não me lembro mais. Mas, pra não nos atrasarmos mais, vou mandar esses mesmos arquivos e fazer essa correção nos próprios txts que vou enviar.

![image](https://user-images.githubusercontent.com/25855735/124284225-2968bb80-db23-11eb-9b56-82b791eed3de.png)

**Comment by arthurtreuherz** [comment]
Outra coisa, o procedimento gera 4 arquivos. Os que falam ter as notas de escopo tem notas de escopo só para os MH. Os outros dois, que não mencionam ter notas de escopo, têm nota de escopo tanto para MH quanto para PEP. Acho que é melhor melhorar a nomeação dos arquivos, pra não acabarmos enviando arquivos errados da próxima vez.

**Comment by wilsonmoura** [comment]
@arthurtreuherz seguindo sua sugestão, realizei os ajustes nos nomes dos arquivos. Creio que os relatórios estarão com os nomes corretos na próxima vez.
