### ISSUE TITLE
Descritores sem tradução

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1228]
Oi, Wilson!
Ao procurar pelo descritor "Economia da Saúde", recuperou-se um registro em que faltam os descritores (nomes das subcategorias) nos 4 idiomas:
https://decs.bvsalud.org/ths/resource/?id=4540&filter=ths_exact_term&q=Economia%20da%20Sa%C3%BAde#Details
![image](https://user-images.githubusercontent.com/35345406/122814372-78ecf300-d2aa-11eb-87ff-c781f327c2cf.png)
Obrigada!

**Comment by arthurtreuherz** [comment]
Na navegação hierárquica o descritor na posição SP1.016 não está sendo mostrado.

![image](https://user-images.githubusercontent.com/25855735/122818191-45f92e00-d2af-11eb-9440-5e6a86eea28f.png)

**Comment by arthurtreuherz** [comment]
Wilson, é que o sistema está incluindo na estrutura hierárquica da navegação aqueles descritores deletados. Esses não deveriam estar incluídos. veja que o código hierárquico dele é SP1.000. O sistema FI-ADMIN obriga a gente a colocar um código hierárquico lá mesmo que o registro vá depois ficar eliminado.

![image](https://user-images.githubusercontent.com/25855735/122818815-0848d500-d2b0-11eb-85ba-7d0fffd9c233.png)

**Comment by wilsonmoura** [comment]
@arthurtreuherz @acecampos ajustes realizados em https://github.com/bireme/thesaurus-wp-plugin/issues/84. Favor validar no ambiente de testes.

**Comment by arthurtreuherz** [comment]
Ficou ótimo Wilson. Obrigado.
