### ISSUE TITLE
Carregamento das notas de indexação modificadas pelo MeSH para 2021 em inglês e em português

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1231]
Wilson, favor carregar as notas de indexação 

- em inglês do MeSH (pois as que estão na base de trabalho no FI-ADMIN estão desatualizadas) e também as notas de indexação

- em português que acabo de concluir a tradução.

Favor carregar as notas que estão na coluna L para o inglês e coluna M para o português. A coluna B contém o ID do descritor.

O arquivo está nesse endereço do sharepoint:
 https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/Terminologias/DeCS/2021/mesh/notas/annotation/annotation_changes_PORTUGUES_somente_updated.xlsx?d=w4f2b9a837b9942b1b85209ec51b1be12&csf=1&web=1&e=CGuXDw

**Comment by wilsonmoura** [comment]
@arthurtreuherz notas atualizadas no ambiente de testes. Favor validar para que possamos atualizar o ambiente de trabalho.

**Comment by arthurtreuherz** [comment]
Aprovado. Obrigado.

**Comment by arthurtreuherz** [comment]
Wilson, as notas no ambiente de teste não parecem terem sido atualizadas. Será novamente por causa do cache? Veja por exemplo esse termo "Esporos".

As notas tanto no ambiente de testes como no portal público ainda são as versões antigas, tanto no português quanto no inglês. Note que elas ainda possuem abreviaturas e menção ao Manual da NLM.

**Nota antiga:**
GEN: SPORES, BACTERIAL; SPORES, FUNGAL; and SPORES, PROTOZOAN are available; sporulation: coord organism /physiol (IM) + SPORES (NIM); Manual 22.31

**Nota antiga:**
GER: ESPOROS BACTERIANOS, ESPOROS FÚNGICOS e ESPOROS DE PROTOZOÁRIOS estão disponíveis; esporulação: coord organismo /fisiol (como primário) + ESPOROS (como secundário); Manual da NLM 22.31

**Nota nova:**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/treuherz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/treuherz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Esporos | general or unspecified; prefer   specifics; sporulation: coordinate organism /physiol and SPORES | geral ou não especificado;   esporulação: coordene organismo /fisiol + ESPOROS
-- | -- | --




</body>

</html>

**Comment by wilsonmoura** [comment]
@arthurtreuherz eu atualizei a base congelada. Favor validar no ambiente de testes. O ambiente de produção só será atualizado após limpeza de cache. Aguardando OK dos demais envolvidos no lançamento da base definitiva.

**Comment by arthurtreuherz** [comment]
Ótimo Wilson, agora as notas estão lá. Obrigado!!

**Comment by arthurtreuherz** [comment]
As traduções/atualizações às notas de indexação alteradas também já são vistas na versão pública. Obrigado Wilson!
