### ISSUE TITLE
Favor gerar DeCS 2021 em formato ISIS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1237]
Para permitir a geração da planilha de mudanças anuais aos códigos hierárquicos com todas as informações necessários para o usuário, além do arquivo mostrar as colunas dos descritores de 2020, ele mostra nas últimas colunas os descritores de 2021 referentes a esses códigos.

Por isso, e também para que tenhamos a versão definitiva congelada da edição do DeCS 2021 em formato ISIS, solicito novamente a sua criação.

Observação: Esse issue pode ser feito antes do issue #1231 referente ao carregamento das notas de indexação modificadas, já que as notas não constam na planilha mencionada acima.

**Comment by wilsonmoura** [comment]
@arthurtreuherz bases geradas novamente conforme solicitado.

serverofi5:/bases/dec.000/get_thesaurus/wrk_ths_1/

**Comment by arthurtreuherz** [comment]
Obrigado.
