### ISSUE TITLE
Marcar os países da América Latina & Caribe

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#124]
É necessário revisar a tabela de países do FI-ADMIN em produção e marcar no campo _Latin America & Caribbean region?_ os paises da região.

**Comment by sarahviola** [comment]
@viniciusandrade ,
Marquei todos os países da América Latina e Caribe.

Ainda não testei, mas pelo menos quando fizemos isso na instância de teste (#106), depois de marcar os países você teve que reiniciar algo do django.

![image](https://cloud.githubusercontent.com/assets/18355163/15183946/ae209baa-1769-11e6-9975-752523370084.png)

**Comment by sarahviola** [comment]
Lista ok na produção.

![image](https://cloud.githubusercontent.com/assets/18355163/15327076/9ffecb7a-1c26-11e6-8eb0-dc51e65fe976.png)
