### ISSUE TITLE
Registros que foram feitos downloads no sistema FI-Admin., estão dando erro 404 nginx

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1241]
Boa tarde Vinicius!
Escrevo para informar que os  downloads no sistema FI-Admin., estão dando erro 404 nginx

![image](https://user-images.githubusercontent.com/37112458/124309859-bf134380-db41-11eb-8710-e4b4aa6e350e.png)

![image](https://user-images.githubusercontent.com/37112458/124309741-925f2c00-db41-11eb-87e5-59aa0e33a9cc.png)

Se retirar o número dois após o docs no link o registro abre normalmente, isto acontece com todos os registros que foram feitos downloads no sistema FI-Admin

Exemplo: 1254045 
​​https://docs2.bvsalud.org/biblioref/2021/07/1254404/hepatitis-b-chronic-diagnosis-and-management-pdf-35109693447109.pdf

id:1254404 -Hepatitis B (chronic): diagnosis and management
https://docs2.bvsalud.org/biblioref/2021/06/1254045/boletim_2020_1231_tab1-4_graf1_ate_20_rb-ff-co.pdf

O problema acontece no sistema FI-Admin., no plugin da BIGG o registro abre normalmente

![image](https://user-images.githubusercontent.com/37112458/124310174-33e67d80-db42-11eb-8ba0-c8144c072f61.png)

Obrigada

**Comment by viniciusandrade** [comment]
@silvalais obrigado pela verificação.

Este comportamento é normal e será observado durante os testes do ambiente fi-admin2 pois existem dois ambientes onde os uploads estão sendo armazenados (fi-admin e fi-admin2) que depois serão unificados.

De qualquer forma fiz uma condição temporária para que os documentos antigos (antes de 02/07) sejam mostrados usando o docs.bvsalud.org.

Quando possível favor verificar. Obrigado.
