### ISSUE TITLE
Erro ao tentar criar nova instituição (fi-admin2)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1242]
Reportado pela @alvesmarilda no ambiente FI-ADMIN2.

![image](https://user-images.githubusercontent.com/349287/124626961-84691e00-de55-11eb-8757-6a8e089a548e.png)

![image](https://user-images.githubusercontent.com/349287/124626982-87fca500-de55-11eb-9e8c-82bac8c3dfc4.png)

**Erro: AttributeError: 'InstCreateView' object has no attribute 'render'**

**Comment by viniciusandrade** [comment]
@alvesmarilda ajuste realizado no sistema, quando possível favor realizar novo teste.

Obrigado.

**Comment by alvesmarilda** [comment]
@viniciusandrade Teste realizado com sucesso.

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda obrigado pela validação.
