### ISSUE TITLE
Erro 500 ao apagar um arquivo anexo no registro de legislação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1244]
Erro ocorre quando clico no botão Gravar como Publicado.
id:2395

**Comment by renatomurasaki** [comment]
@viniciusandrade é urgente esse issue para retirar o arquivo carregado no Fi-Admin pois o mesmo está violando direitos autorais.

**Comment by renatomurasaki** [comment]
![FireShot Capture 2276 - Editar Legislação - fi-admin2 bvsalud org](https://user-images.githubusercontent.com/1226218/125686682-1f936983-a476-4e40-88c5-5fddc50d0bdb.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki OK, documento apagado usando o ambiente FI-ADMIN normal pois o FI-ADMIN2 não tem acesso aos uploads anteriores e por isso retornou erro ao tentar apagar.

A url https://docs.bvsalud.org/leisref/2018/12/2395/lca_2016_w_specification-for-labelling-of-tobacco-products.pdf

Agora retorna:

Not Found
The requested URL /leisref/2018/12/2395/lca_2016_w_specification-for-labelling-of-tobacco-products.pdf was not found on this server.

**Comment by renatomurasaki** [comment]
@viniciusandrade muito obrigado!
