### ISSUE TITLE
Revisar a regra aplicada ao listar as fontes no momento de criar um registro bibliográfico tipo journals

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1247]
Caso de uso: usuário do CC CG1.1, ao clicar em "New Bibliographic Record" > "Journals (Periodical Series)", esperava-se ver todos os registros fontes de fascículos com os respectivos dados de analíticas para escolher o fascículo que receberá a nova analítica ou criar novo fascículo.

**Comment by viniciusandrade** [comment]
Revisando o código verifiquei que nesta listagem é aplicada a mesma regra da aba **Journals indexed by my center** que filtra pela lista de revistas que possuem no campo **indexer_cc_code** o código do centro do usuário atual.

Vou verificar com a @anakatiacamilo e com a @suelisuga como podemos ajustar esta listagem.

**Comment by renatomurasaki** [comment]
@viniciusandrade será que há algum problema no indexer_cc_code? Estranho nenhum outro usuário ter reclamado desta situação. Me parece que pode ser algo relacionado ao dado.

**Comment by viniciusandrade** [comment]
@renatomurasaki revisei agora a pouco com a @anakatiacamilo e esta tudo OK com o indexer_cc_code dos títulos migrados, estou revisando a lógica do código e já tenho algumas desconfianças do problema.

**Comment by renatomurasaki** [comment]
obrigado @viniciusandrade @anakatiacamilo

**Comment by viniciusandrade** [comment]
@renatomurasaki regra revisada, ao clicar em "New Bibliographic Record" > "Journals (Periodical Series)" agora o sistema  mostra todos os registros fontes de fascículos indexados pelo centro com os respectivos dados de analíticas para escolher o fascículo que receberá a nova analítica ou criar novo fascículo.

**Comment by renatomurasaki** [comment]
@viniciusandrade acabei de testar e parece ok! O erro na regra afetava somente o AIM ou também os demais CC da LILACS?

**Comment by viniciusandrade** [comment]
@renatomurasaki obrigado pela validação ... afetava também os demais CCs mas acredito que só ficou evidente no caso do AIM por não existerem registros LILACS-EXPRESS que eram apresentados para os demais CCs por padrão.

**Comment by renatomurasaki** [comment]
@viniciusandrade entendi. Que bom que esse projeto veio trazer também esta melhoria!
