### ISSUE TITLE
Relatórios da referências bibliográficas: parece não considerar o contexto do usuário e mostra todos os documentos da base

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1248]
Exemplo com usuário associado ao CG1.1
![image](https://user-images.githubusercontent.com/1226218/126343417-6cd61f48-2597-469f-9910-0402454b7185.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki revisei que este comportamento acontece porque seu usuário esta com permissão de superuser no FI-ADMIN devido gestão de listas controladas. 

Para usuários normais será mostrado somente os usuários do mesmo centro.

**Comment by renatomurasaki** [comment]
Ok, @viniciusandrade . Fechando issue, obrigado!
