### ISSUE TITLE
Realizar testes com caracteres especiais nos campos de Título, Resumo e Palavras-Chave

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#125]
Incluir testes com simbolos e caracteres especiais nestes campos para verificar se "quebra" o formulário de entrada de dados.

**Comment by sarahviola** [comment]
Erro ao incluir dois apóstrofos no título.
![image](https://cloud.githubusercontent.com/assets/18355163/15226681/1c733c66-185a-11e6-8d6b-b80ef52a91dd.png)

(Apenas um apóstrofo é salvo normalmente)

**Comment by sarahviola** [comment]
Erro ao incluir aspas duplas no título, palavras-chave e resumo de um tipo específico. 

“breast cancer” >> copiado e colado do PDF: ok
"breast cancer" >> digitado: erro

Exemplo: registro id [160](http://fi-admin.teste.bvsalud.org/bibliographic/edit-analytic/160)

![image](https://cloud.githubusercontent.com/assets/18355163/15228379/45a43d6c-1862-11e6-9794-f2ed56a99cc3.png)

**Comment by sarahviola** [comment]
Vários outros caracteres especiais (exemplo: $ & ± µ ½ ® ω α β χ _ ° ⁿ ⃰ ∞ ≤ ≡ ≠ ≥ ≈_ ²) testados e gravados normalmente.

**Comment by viniciusandrade** [comment]
@sarahviola 

Realizei ajustes para o tratamento das aspas simples e duplas. Favor quando possível validar.

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade 
Testei novamente os exemplos acima na instância de testes e está ok. Testei também o resumo em inglês que um usuário llxp tinha reportado problema e está ok.

Entretanto, tem ainda um resumo em português que está dando erro ao salvar por causa de um caracter, que me parece ser um erro de digitação (não tenho certeza se é uma crase, aspa ou apóstrofo). Deletei esse caractere e consegui salvar o registro. Erro acontece no id [26](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/26). 
[Resumo](http://docs.bvsalud.org/biblioref/2016/05/26/arq-bras-neurocir1-2015pdf5.pdf) com a aspa:
![image](https://cloud.githubusercontent.com/assets/18355163/15680597/b8734e22-272c-11e6-9599-7aae12f1a337.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Obrigado pelos testes. Acredito que o caracter do resumo que estava causando erro era um apóstrofo. Já apliquei uma correção no sistema. 

Quando possível favor verificar.

**Comment by sarahviola** [comment]
Certo, agora consigo salvar o registro com esse caracter.
