### ISSUE TITLE
Relatório de referências bibliográficas: erro na lista de Centros Cooperantes

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#1250]
Erro ocorre com um usuário associado ao centro CG1.1

![image](https://user-images.githubusercontent.com/1226218/126343765-de476107-b077-475c-835e-5f05b7000ec8.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki  apresentação da lista de Centros Cooperantes revisada, quando possível favor validar.
