### ISSUE TITLE
Possibilitar salvar com status APAGADO a partir do status RASCUNHO

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1251]
Atualmente há mais de 9 mil registros com status Rascunho.
![image](https://user-images.githubusercontent.com/13105683/126388149-cc808ba7-7172-4cf6-ab95-dac15979b647.png)

Considerando que o houve consenso na última reunião de coordenação da LILACS para que apaguemos esses registros, ao testar fazer esse processo via sistema FI-Admin, verifiquei que há que publicar o registro antes de apagá-lo, o que implica, finalizar o registro, incluindo campos obrigatórios.

Visando facilitar o processo para o usuário, solicito que seja possível mudar o status de RASCUNHO para APAGADO sem a necessidade de publicá-lo.

A ideia é apagar cerca de 6 mil registros.

Muito obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga realizei ajustes no sistema para permitir a alteração do status para RECUSADO ou APAGADO mesmo que o registro esteja incompleto ou com problemas de validação de campos.

Favor informar se encontrar algum problema.
