### ISSUE TITLE
DeCS - no sistema FI-Admin não está traduzindo os descritores para esp e ing.

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1252]
Bom tarde pessoal,

O DeCS no sistema FI-Admin., não está traduzindo (esp e inglês), mesmo alterando o idioma todos os termos e definições aparecem só no português.

Exemplo: 
Mal Uso de los Servicios de Salud
Estudios Transversales
Variacion Anatómica

Obrigada

**Comment by viniciusandrade** [comment]
@silvalais revisei o sistema e agora acredito que esteja OK.

Por favor, quando possível, validar. Obrigado.

**Comment by silvalais** [comment]
Vini!

Teste ok
Obrigada



Laís Silva
Bibliotecária
LILACS | lilacs.bvsalud.org​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>
Tel +55-11-5576-9831

Todo sucesso é fruto de um grande trabalho em equipe

[cid:bf8989d3-c4b7-4bff-9c0b-ff20a7438dac]

________________________________
De: viniciusandrade ***@***.***>
Enviado: quinta-feira, 22 de julho de 2021 15:19
Para: bireme/fi-admin ***@***.***>
Cc: Silva, Lais Aparecida da (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/fi-admin] DeCS - no sistema FI-Admin não está traduzindo os descritores para esp e ing. (#1252)


@silvalais<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsilvalais&data=04%7C01%7Csilvala%40paho.org%7Cf7723307f4b14265913c08d94d3d47c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637625747878961866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uKpAi71%2FAG%2FvS5hs5INfWDMglPUYwFDgwkDPLiMt6es%3D&reserved=0> revisei o sistema e agora acredito que esteja OK.

Por favor, quando possível, validar. Obrigado.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1252%23issuecomment-885133471&data=04%7C01%7Csilvala%40paho.org%7Cf7723307f4b14265913c08d94d3d47c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637625747878971816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JaRwz%2F6W5I0%2F5X0Zt0YxQDs9bXJkiSuq7zvKFB9mDWc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI3EVCVZGCC4TDADAVPMZJTTZBOL7ANCNFSM5AYPPUAA&data=04%7C01%7Csilvala%40paho.org%7Cf7723307f4b14265913c08d94d3d47c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637625747878971816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CgE8zGDbxBZEJ6HkbE4JqrKWtXDxGs6FAw5MJHQUURg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
OK, obrigado pelo teste.
