### ISSUE TITLE
Geração de arquivos XML bilíngues com a versão definitiva de 2021 para os pedidos de DeCS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#1255]
Como já foram feitos pedidos para uso do XML do DeCS, solicito a geração desses arquivos. Por favor, informar o Marcelo e nós do DeCS quando estiverem prontos para verificação. Obrigado.

**Comment by arthurtreuherz** [comment]
Aprovado! Obrigado.

**Comment by wilsonmoura** [comment]
@arthurtreuherz conforme conversamos, consegui resolver os erros no script que gera os arquivos XML do DeCS.
A execução do script demorou aproximadamente 8h pra finalizar.
Segue a localização dos arquivos que foram gerados para que você possa validar:

serverofi5:/bases/dec.000/cria_xml_decs/wrk/xmls_decs_2021/

Fico à disposição caso necessário.

**Comment by wilsonmoura** [comment]
Arquivos gerados (DeCS, MeSH e qualificadores) e disponibilizados no servidor FTP conforme solicitado.
