### ISSUE TITLE
Bolivia - Saúde dos Povos Indígenas: Incluir opções de idioma do texto na tabela auxiliar

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1257]
Incluir os idiomas do texto abaixo na tabela auxiliar, para poder fazer a migração correta dos dados.

Estándar ISO |  

aymara | ay
guaraní | gn
quechua | qu

**Comment by anakatiacamilo** [comment]
As opções já estavam na instancia de Produção e Curso.

**Comment by suelisuga** [comment]
Somente como referência para futuras inclusões de outras línguas indígenas: https://www.loc.gov/standards/iso639-2/php/code_list.php
