### ISSUE TITLE
Error FI-ADMIN (Server Error 500)

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1263]
Bom dia a todos,

O Sistema FI-Admin em Registros bibliográficos na **Aba Biblioteca** o campo **Número de llamada** para o usuário(Argentina) aparece erro (Server Error 500)
Abaixo tela do usuário 

![image](https://user-images.githubusercontent.com/37112458/133612165-a996e755-5c65-4b7c-bdcd-d8f915a6beea.png)

Testei alterando meu código para o código do usuário e esta funcionando normalmente.
![image](https://user-images.githubusercontent.com/37112458/133612814-197ad053-8713-4c8c-8d9b-0bd21b137c8f.png)

 Uruguay, respondeu o e-mail avisando que está funcionando normalmente

**Comment by suelisuga** [comment]
Erro ao abrir assistente de campo Aba Biblioteca > campo Localização do documento:
Usuário do Brasil.
![image](https://user-images.githubusercontent.com/13105683/133652648-fcf35da6-3c3b-4201-8864-c5f6e275893d.png)

**Comment by suelisuga** [comment]
Erro ao abrir assistente de campo Aba Metadados > campo Autor pessoal de analítica:
Usuário do Brasil.

![image](https://user-images.githubusercontent.com/13105683/133652989-a45a0b91-2e3f-4e27-8330-8da182a5b1d0.png)

**Comment by suelisuga** [comment]
3 usuários da Argentina reportam:

Buenos días:
con mi usuario persiste el error : 
Server Error (500).
Ya cerré sesión y abrí de nuevo, y arroja el mismo error en el campo de carga de metadatos.
Adjunto imagen del error.
Saludos.

=======
Hola buenas tardes, en mi caso persiste el server error 500, cada vez que abro un campo para la carga, como autor, título, etc. Ya probé cerrar sesión y volver a abrir.

=======
Buenas Tardes. Desde el CC AR144.1 me sigue tirando 
Server Error (500) en el campo de número de llamada, de la pestaña Biblioteca.

**Comment by suelisuga** [comment]
Usuarios de Venezuela e El Salvador:

Buenos dias, a mi tambien me esta dando ese problema, el martes ingrese sin ningún inconveniente

Server Error (500)
Estaré pendiente

Gracias
=========

Buenos días, también me está dando error.

Saludos,

**Comment by viniciusandrade** [comment]
@silvalais / @suelisuga  acredito ter localizado e corrigido o problema referente ao assistente de edição que em alguns casos estava retornando o erro código 500.

@silvalais poderia solictar um novo teste a usuária inicial do erro?

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade uma das usuárias da Argentina falou que voltou ao normal. Amanhã enviarei consulta às outras. Muitíssimo obrigada!

**Comment by viniciusandrade** [comment]
OK, estou fechando este issue, caso seja necessário favor reabrir.
