### ISSUE TITLE
Fi-admin relatório das revistas com indexação LILACS

### ISSUE THREAD

**Issue by amilson18** [bireme/fi-admin#1264]
Semanalmente tenho que gerar um relatório das revistas com indexação LILACS, para atualizar pagina Periódicos indexados na LILACS
Hoje ao gerar relatório de revistas LILACS por país, mas está saindo diferente

![image](https://user-images.githubusercontent.com/88335258/134043833-7caf8ff7-64e9-4a17-9d8d-69a356824b00.png)

estou tentando executar e sai um arquivo maior com a letra "b,", impossibilitando fazer a atualização

![image](https://user-images.githubusercontent.com/88335258/134043979-d5365836-6ff7-42bf-9fe3-f713c8277242.png)

O correto seria assim:
![image](https://user-images.githubusercontent.com/88335258/134044130-b58d9458-a4d4-401e-a595-08466160337b.png)

Obrigado !!!
@viniciusandrade 
@wilsonmoura 
@anakatiacamilo

**Comment by viniciusandrade** [comment]
@amilson18 realizei um ajuste no sistema, por favor, quando possível realizar novo teste.

Obrigado

**Comment by amilson18** [comment]
Boa tarde Vinicius,

Foi sanado o problema, fiz a atualização com sucesso.

Obrigado !!!
Amilson Pereira Santos
Unidade SeCS - Portal de Revistas Cientificas
Producao de Fontes da Informacao - PFI
http://portal.revistas.bvs.br/<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fportal.revistas.bvs.br%2F&data=02%7C01%7Cbir.secs%40paho.org%7C3ec45a2e859845a5241c08d7afb9c022%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637171084637194179&sdata=9p4Y0zi5k4ipIQzPOvtTlMjztCG1WnnkwnOdn11juLo%3D&reserved=0>
BIREME/OPS/OMS
***@***.******@***.***>

________________________________
De: viniciusandrade ***@***.***>
Enviado: segunda-feira, 20 de setembro de 2021 14:57
Para: bireme/fi-admin ***@***.***>
Cc: Santos, Amilson Pereira (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/fi-admin] Fi-admin relatório das revistas com indexação LILACS (#1264)


@amilson18<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Familson18&data=04%7C01%7Csantosam%40paho.org%7Cd58961cc2c284be04d7908d97c600c05%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637677574230415903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FJ%2F%2Fq7eVraC70VbhMhNCe1FpXiaLhxKoMKcBY%2FFrqjY%3D&reserved=0> realizei um ajuste no sistema, por favor, quando possível realizar novo teste.

Obrigado

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1264%23issuecomment-923149532&data=04%7C01%7Csantosam%40paho.org%7Cd58961cc2c284be04d7908d97c600c05%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637677574230415903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w61CBvdut00rQVdErX8j%2BfYM5dXbSK4%2ByGNcpEkBpR0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVB6HGRGJLBLNQEKJVW4SCLUC5YWZANCNFSM5EMNSQAQ&data=04%7C01%7Csantosam%40paho.org%7Cd58961cc2c284be04d7908d97c600c05%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637677574230425861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oEoM4Iu3%2Bna3Nph%2Blz0oNA7TPXRfyjoZyVL3Ws06uew%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csantosam%40paho.org%7Cd58961cc2c284be04d7908d97c600c05%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637677574230425861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l%2B6s14%2B4ebj%2Byb0cjH5ottTytCeYg92AFJC0CCV6eUA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csantosam%40paho.org%7Cd58961cc2c284be04d7908d97c600c05%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637677574230435824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=afLt631YGVgfHTecJdeYSkZDsQBe50AW%2BtsN6RX9CF0%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
OK @amilson18, obrigado pela validação.
