### ISSUE TITLE
Erro ao deletar registro de Legislação

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1265]
A usuário que criou o registro #40260, ao tentar deletar o registro, recebeu a seguinte notificação:

![image](https://user-images.githubusercontent.com/47643830/134560259-133d7760-1db4-4728-8715-ac152a1214cd.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula realizei ajustes no sistema referentes a este erro, favor solicitar novo teste para a usuária.

Obrigado
