### ISSUE TITLE
Tese e Dissertação para Tese, Dissertação e Monografia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1268]
Solicito mudança do label Tese e Dissertação para Tese, Dissertação e Monografia no campo 5, atributo T, em todos o locais aplicáveis. Os usuários do sistema FI-Admin frequentemente registram TCCs no tipo Monografia, mas o correto seria em Tese, Dissertação e Monografia.

PT:  Tese e Dissertação => Tese, Dissertação e Monografia
ES: Tesis y Disertación => Tesis, Disertación y Monografía
EN: Thesis / Disertation => Thesis, Disertation and Monography

![image](https://user-images.githubusercontent.com/13105683/134740575-5195da94-9b64-430d-8ad4-13bca6c2ca59.png)

Manual de descrição bibliográfica já está em atualização utilizando esse rótulo/label.

Muito obrigada!

**Comment by viniciusandrade** [comment]
Ajuste realizado no rótulo e traduções.

@suelisuga fiz uma busca no sistema e encontrei este rótulo  na página de criação  registro e no filtro de busca. Caso localize alguma outra página favor reabrir este issue e informar.

Obrigado
