### ISSUE TITLE
Incluir número de Analíticas na visualização dos registros Fonte

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#127]
Na visualização dos registros Fonte, incluir o número de analíticas presentes em cada fascículo.

![image](https://cloud.githubusercontent.com/assets/18355163/14928756/373902e4-0e30-11e6-8d85-4097000f75aa.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

Foi adicionado a informação da quantidade de analíticas na tela de seleção do período.

Favor, quando possível, verificar. Obrigado.

**Comment by sarahviola** [comment]
Tudo certo.
