### ISSUE TITLE
Crear campo para licencias creative commons para registros bibliográficos

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1276]
Solicito incluir no FI-Admin em  todos os tipos de literatura da metodología LILACS campo para Licencias Creative Commons.

Lista de licencias:
EN: https://creativecommons.org/about/cclicenses/
ES: https://creativecommons.org/licenses/?lang=es
PT: https://creativecommons.org/licenses/?lang=pt

Há uma lista controlada utilizada para REA que entendo pode ser reutilizada, se estiver atualizada, pois ocorreram mudanças. Não pude identificar número de campo em REA, somente nome do campo: Licença de direitos

Entendo que o campo já existe (542) para registros bibliográficos e é usado por @anakatiacamilo para cargas de documentos de SciELO.

Chamados relacionados que podem ajudar:
https://github.com/bireme/db-processing/issues/259 
https://github.com/bireme/oer-wp-plugin/issues/14

Abrazos,
Sueli Mitiko Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga campo disponível no ambiente de cursos para validação.

**Comment by viniciusandrade** [comment]
@suelisuga campo disponível no ambiente de produção. Favor, assim que possível criar a lista controlada usando o Django Admin.
