### ISSUE TITLE
Adicionar aba para entrada de dados de pesquisa 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#1277]
Permitir o registro de dados de pesquisa no sistema.

Campos inicialmente identificados: tipo (lista controlada), título, descrição, link e idioma.

Relacionado a linha de ação de ciência aberta.

**Comment by viniciusandrade** [comment]
@suelisuga aba para entrada de dados de pesquisa disponível nos ambientes de teste e curso para avaliação.

**Comment by suelisuga** [comment]
@viniciusandrade segue lista controlada dos tipos de arquivos:
Value Definition
Standard office documents: text documents, spreadsheets, presentations
Networkbased data: websites, email, chat history, etc.
Databases: DBASE, MS Access, Oracle, MySQL, etc.
Images: JPEG, JPEG2000, GIF, TIF, PNG, SVG, etc.
Structured graphics: CAD, CAM, 3D, VRML, etc.
Audiovisual: data WAVE, MP3, MP4, Flash, etc.
Scientific and statistical data formats: SPSS, FITS, GIS, etc.
Raw data: device specific output
Plain text: TXT in various encodings
Structured text: XML, SGML, etc.
Archived data: ZIP, RAR, JAR, etc.
Software applications: modelling tools, editors, IDE, compilers, etc.
Source code: scripting, Java, C, C++, Fortran, etc.
Configuration data parameter settings, logs, library files:
Other -

![image](https://user-images.githubusercontent.com/13105683/143298394-fd345050-e962-4708-b6ed-f3741c0b929f.png)

Para mais informação:
https://gfzpublic.gfz-potsdam.de/rest/items/item_5007395_6/component/file_5007461/content
https://www.re3data.org/browse/by-content-type/

**Comment by viniciusandrade** [comment]
@suelisuga ajustes realizados e disponíveis no ambiente de cursos para validação.

**Comment by suelisuga** [comment]
Teste realizado em:
https://fi-admin-curso.bvsalud.org/bibliographic/edit-analytic/894934

https://fi-admin-curso.bvsalud.org/bibliographic/edit-analytic/1361258

@viniciusandrade Pf checar resultado. Como entrada de dados funcionou.

**Comment by suelisuga** [comment]
@viniciusandrade Ocorreu mensagem de erro de permissão no perfil Editor LILACS-Express (não deixou salvar)

**Comment by suelisuga** [comment]
Solicito **excluir** aba de dados de pesquisa no registro-fonte de Série periódica:
![image](https://user-images.githubusercontent.com/13105683/165143579-0b553945-f713-4951-8c9f-c18516d32b55.png)
Obrigada

**Comment by suelisuga** [comment]
@viniciusandrade solicito mudança do label do campo "**Título**" para "**Título do conjunto de dados**"

![image](https://user-images.githubusercontent.com/13105683/165153759-bba2f256-9554-46c2-b3d9-543236b445c8.png)

**Comment by viniciusandrade** [comment]
@suelisuga ajuste realizado no rótulo.
