### ISSUE TITLE
Listagem de registros com notas de indexação

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1279]
Wilson, por favor, listar IDs dos registros com campo **nota de indexação** contendo as expressões "**como primário**" ou "**como secundário**".

Justificativa: atualização no MeSH que não foi incorporada no DeCS em 2021 ou antes.

**Comment by wilsonmoura** [comment]
@acecampos Relatório gerado conforme solicitado. Favor validar.
[annotation.txt](https://github.com/bireme/fi-admin/files/7749081/annotation.txt)

**Comment by acecampos** [comment]
@wilsonmoura Está excelente! Muito obrigada. Validado.

**Comment by wilsonmoura** [comment]
Segue consulta para recuperar os registros solictados:
select
	b.descriptor_ui,
	a.language_code,
	a.annotation
from
	thesaurus_descriptiondesc as a,
	thesaurus_identifierdesc as b
where
	a.identifier_id=b.id
	and (a.annotation like '%como primario%' or a.annotation like '%como secundario%')
	and b.thesaurus_id='1'
