### ISSUE TITLE
Checar carga de códigos de editor no BIREME Accounts de teste

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#128]
Identifiquei que os códigos de editor abaixo não aparecem no Accounts de teste quando fui criar usuários para os editores (perfis LLXP)

BR1251 - Revista brasileira de crescimento e desenvolvimento humano - 0104-1282
BR1754.9 - Revista de administração em saúde - 	1519-1672
BR1852.9 - Revista de direito sanitário - 1516-4179
BR1857.9 - São Paulo em Perspectiva - 1806-9452
BR1926.9 - Vigilância Sanitária em Debate - 	2317-269X
e outras.

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga 

A @katiacamilo gerou um novo arquivo de centros que foi carregado no ambiente de testes do Accounts. 

Eu fiz uma verificação rápida com os exemplos que você citou e aparentemente todos estes centros foram importados. 

Quando possível favor retomar os testes de criação dos usuários com estes centros para validar este ticket.

**Comment by viniciusandrade** [comment]
@katiacamilo 

No arquivo de exportação o registro **201061** do Centro Cooperante **PA2.9** veio com o campo de país invalido e precisei ajustar manualmente. Poderia por favor verificar e solicitar a correção do dado na  NMail?

Obrigado.

**Comment by suelisuga** [comment]
Registro do PA2.9 corrigido.

Lista de editores com códigos citados e dos participantes do projeto piloto ok.

Obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS
