### ISSUE TITLE
Campo "Projeto - Número" [60] não esta sendo exportado na api no formato isis_id

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1280]
Segue exemplo de registro que na api com o formato isis_id não tem o campo Número do Projeto[60] 312316/2019-4 e que no formato json tem

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1286896
https://fi-admin-api.bvsalud.org/api/bibliographic/?format=json&id=1286896

**Comment by viniciusandrade** [comment]
Campo adicionado no formato ISIS.
