### ISSUE TITLE
Mudar label dos atributos Número inicial e Número final

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1282]
Solicito mudar label do atributos Número inicial e Número final no campo Páginas (analíticas) [14] para:

Número inicial => Página inicial
Número final => Página final

Informo que estamos atualizando o manual de descrição LILACS e realizando esses chamados com o intuito de melhorar a interação dos documentalistas com o sistema FI-Admin e diminuir ruidos que causam confusão.

![image](https://user-images.githubusercontent.com/13105683/145587479-18582bed-ad5f-420a-8935-378f614bfd85.png)

Obrigada

**Comment by viniciusandrade** [comment]
@suelisuga  ajustes realizados.
