### ISSUE TITLE
Mudar label do campo Páginas (nível analítico) para IDENTIFICADOR DE PÁGINAS (nível analítico) 

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1283]
Solicito mudar label do campo Páginas (nível analítico) para IDENTIFICADOR DE PÁGINAS (nível analítico) para compreender o conceito de elocation.

![image](https://user-images.githubusercontent.com/13105683/145587921-8d30ade2-9fca-4bb7-ba7e-8e8ee8468151.png)

Muito obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga ajustes realizados.
