### ISSUE TITLE
Coleta SciELO Colombia - título abreviado não consta na Title

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1286]
@anakatiacamilo a Ana Lorena sinalizou, e eu confirmei, que a coleta da **_Rev. cienc. salud_** está sendo aparecendo com um título abreviado diferente do que está na Title (Rev. cienc. salud (Bogotá)) e, por conta disso, não aparece aos documentalistas.

___________________________________________________________________________________________________________________________
De: Bvs Colombia <bvscolombia@fucsalud.edu.co>
Enviado: terça-feira, 25 de janeiro de 2022 12:38
Para: #BIR:Lilacs <bir.lilacs@paho.org>
Cc: Suga, Sueli Mitiko Yano (BIR) <sugasuel@paho.org>
Assunto: Ayuda Urgente Rev. cienc. salud LILACS Express
 
Buenos dias estimados:

Reciban un cordial saludo

Solicito su amable ayuda para verificar el siguiente caso de la Rev. cienc. salud (CO285.1)
Están haciendo una actualización de LILACS Express, sin embargo cuando ingresamos a su plataforma aparecen solo 3 registros por terminar, sin embargo, cuando yo ingreso a la mía están los 594 de la imagen adjunta.

Estoy observando que antes se encontraba Rev. cienc. salud (Bogotá), será por ello que no aparece en los registros de la Universidad?

Agradeceria su ayuda pronto,

Gracias y quedo atenta

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula a alteração na Title ocorreu no dia 6 de Outubro de 2021 às 10:00 Pelo gabriel.justino	BR1.1	
Título: Revista ciencias de la salud (Bogotá) → Revista ciencias de la salud
**Título abreviado: Rev. cienc. salud (Bogotá) → Rev. cienc. salud**

Alguns fascículos no FI-ADMIN, mostram que os registros que foram importados antes do dia 6 de outubro 2021 eram importado com o título cadastrado na title quando mudaram na title começou a ser importado no título atual.

Registro criado: 15 de Outubro de 2021 às 19:00 pelo usuário import
1347305	Rev. cienc. salud; 19 (2), 2021	

Registro criado: 27 de Agosto de 2021 às 19:00 pelo usuário import
1289162	Rev. cienc. salud (Bogotá); 19 (1), 2021	
1126249	Rev. cienc. salud (Bogotá); 18 (spe), 2020	
1289147	Rev. cienc. salud (Bogotá); 18 (3), 2020	
1126239	Rev. cienc. salud (Bogotá); 18 (2), 2020	
1115524	Rev. cienc. salud (Bogotá); 18 (1), 2020	
1058228	Rev. cienc. salud (Bogotá); 17 (spe), 2019	
1058216	Rev. cienc. salud (Bogotá); 17 (3), 2019	
1013866	Rev. cienc. salud (Bogotá); 17 (2), 2019	
1013854	Rev. cienc. salud (Bogotá); 17 (1), 2019	
959704	Rev. cienc. salud (Bogotá); 16 (spe), 2018	
985420	Rev. cienc. salud (Bogotá); 16 (3), 2018	
959691	Rev. cienc. salud (Bogotá); 16 (2), 2018	
959677	Rev. cienc. salud (Bogotá); 16 (1), 2018	
911783	Rev. cienc. salud (Bogotá); 15 (3), 2017	
900239	Rev. cienc. salud (Bogotá); 15 (2), 2017	
900226	Rev. cienc. salud (Bogotá); 15 (1), 2017	
959660	Rev. cienc. salud (Bogotá); 14 (spe), 2016	
959647	Rev. cienc. salud (Bogotá); 14 (3), 2016

Podemos conversar melhor sobre este problema?

**Comment by AngelicaSAPaula** [comment]
Antes aparecia os registros na aba "Revistas indexadas pelo meu centro" para o CO285.1 e agora, com o novo título, não aparece mais.

![image](https://user-images.githubusercontent.com/47643830/151473643-bddc255f-c519-4180-82ab-5bc6425b2398.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, 

Na Title atualmente esta cadastrado para o Código do Centro Indexador CO285.1 os títulos abreviados: "Rev. cienc. salud" e "Av. psicol. latinoam" então na ABA "Revistas indexadas pelo meu centro" só vão aparece esses dois títulos quando tiver registros com status de LILACS-Express.
O Título abreviado Rev. cienc. salud (Bogotá) não esta mais cadastrado na Title então o Sistema não tem como fazer este relacionamento com o CC CO285.1.

Podemos conversar pessoalmente se a explicação não ficou clara.

**Comment by suelisuga** [comment]
@AngelicaSAPaula pf revisar chamado respondido por @anakatiacamilo

**Comment by AngelicaSAPaula** [comment]
Título abreviado corrigido na Title e fasículos fonte que estavam com o título anterios, corrigidos!
