### ISSUE TITLE
Registros marcados como LILACS não aparecem no iAHx

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1287]
Os registros da **Braz. J. Vet. Res. Anim. Sci. (Online)** estão marcados para LILACS mas, ao realizar a busca no iAHx, eles não são recuperados.

![image](https://user-images.githubusercontent.com/47643830/151182747-f01b53b7-1ea3-4c29-a212-824583c79171.png)

![image](https://user-images.githubusercontent.com/47643830/151182629-04cd7364-372a-4691-8450-28f530cc294f.png)

![image](https://user-images.githubusercontent.com/47643830/151182984-216a266e-274c-49df-8146-b9f1a399f94d.png)

![image](https://user-images.githubusercontent.com/47643830/151182882-f013b0ce-ab2a-4b22-b74c-362d0024d22d.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, eu consegui fazer a pesquisa desta forma ta_cluster:("Braz. J. Vet. Res. Anim. Sci. (Online)") 

Segue o [link](https://pesquisa.bvsalud.org/portal/?u_filter=Array&fb=&output=site&lang=pt&from=1&sort=&format=summary&count=20&page=1&skfp=&index=&where=&range_year_start=&range_year_end=&q=ta_cluster%3A%28%22Braz.+J.+Vet.+Res.+Anim.+Sci.+%28Online%29%22%29%0D%0A) da pesquisa.

Atenciosamente

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo mas não deveria aparecer na forma que realizei a pesquisa? Procurando pelo título abreviado e pelo id dos registros, nenhum está recuperando!

E na pesquisa que vc fez, não consigo selecionar a base, nem pelos filtros, nem quando entramos no registro, ele não mostra as bases de dados em que o registro está indexado

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula os registros tem os campos de "Indexado em" preenchidos corretamente, mas na pesquisa com base de dados não esta aparecendo no iaHx vou ver com o @botturam, o que esta ocorrendo.
Exemplo ID biblio-1348282

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo muito obrigada! Era exatamente isso que estava querendo dizer!

**Comment by botturam** [comment]
Adicionado em tabs/db.pft

/* NOVO - 27/01/2022 - campo db para v904 */
if p(v904)
  then
     (|    <field name="db">|v904|</field>|/),
fi

**Comment by botturam** [comment]
Verificar com @anakatiacamilo  como deve ser o campo "db" do doc abaixo, da FI VETINDEX:

mfn= 83579
  1  "BR1.1"
  2  "biblio-1278467"
  **4  "MEDLINE"
  4  "LILACSEXPRESS"**
  5  "S"
  6  "as"
  8  "^gTrue^uhttp://www.scielo.br/scielo.php?script=sci_arttext&pid=S1519-69842022000100316^ien^qphp^yHTM"
  9  "a"
 10  "Oliveira-J▒nior, G. G. S.^3Programa de P▒s-gradua▒▒o em Ci▒ncia Florestal^2Departamento de Engenharia Florestal^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0001-7836-040X^cDiamantina^sMG"
 10  "Oliveira, D. K. S.^3Programa de P▒s-gradua▒▒o em Produ▒▒o Vegetal^2Departamento de Agronomia^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0002-8856-7663^cDiamantina^sMG"
 10  "Vieira, E. R. D.^3Programa de P▒s-gradua▒▒o em Produ▒▒o Vegetal^2Departamento de Agronomia^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0002-7226-9442^cDiamantina^sMG"
 10  "Souza, M. W. R.^3Programa de P▒s-gradua▒▒o em Produ▒▒o Vegetal^2Departamento de Agronomia^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0003-4684-4842^cDiamantina^sMG"
 10  "Santos, M. M.^3Programa de P▒s-gradua▒▒o em Produ▒▒o Vegetal^2Departamento de Agronomia^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0002-7997-4849^cDiamantina^sMG"
 10  "Assis-J▒nior, S. L.^3Programa de P▒s-gradua▒▒o em Ci▒ncia Florestal^2Departamento de Engenharia Florestal^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0003-2272-4897^cDiamantina^sMG"
 10  "Soares, M. A.^3Programa de P▒s-gradua▒▒o em Produ▒▒o Vegetal^2Departamento de Agronomia^1Universidade Federal dos Vales do Jequitinhonha e Mucuri^pBR^k0000-0002-8725-3697^cDiamantina^sMG"
 12  "First record of the predatory stink bug Podisus sagitta (Hemiptera: Asopinae) in Brazil^ien"
 14  "^ee236863"
 30  "Braz. j. biol"
 31  "82"
 35  "1519-6984"
 38  "^btab"
 38  "^bgraf"
 40  "en"
 64  "2022"
 65  "20220000"
 72  "8"
 84  "2021-07-13"
 91  "2021-07-09T19:00:00"
 92  "import"
 93  "2021-07-09T19:00:00"
 98  "FONTE"
110  "s"
113  "p"
724  "10.1590/1519-6984.236863"
776  "FI-ADMIN^i1278467^bLILACS"
854  "202200"
855  "0001"
899  "1.25.0-13"
**904  "LILACS"
904  "VETINDEX"**
