### ISSUE TITLE
Alterar título abreviado de registros | | Rev. bras. neurol (Online) > Impresso

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1290]
A usuária criou, erroneamente, os registros da _Rev. bras. neurol_ no título online. Seria possível alterar para o impresso?

![image](https://user-images.githubusercontent.com/47643830/153032126-3f8721fd-c3a2-4620-9053-46cfa3378b5a.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, pelo Sistema a usuária reginamaciel consegue fazer esta alteração sem problemas.

Se ela pesquisar o inicio do título da revista "Rev. Subj." e no filtro Tipo de registro:  escolher Revista - Fascículo a busca trazer 27 resultados dos quais 11 ou 12 precisam mudar de Online para Impresso. Eu já mudei alguns é só ela mudar na fonte que automaticamente o sistema mudará nas analiticas (por isto demora um pouquinho para gravar). Seria interessante ela fazer esta correção.

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, era só um fascículo corrigi pelo sistema que é a melhor forma de corrigir, mas pode informar para o usuário luzinetealvarenga se ela precisar corrigir futuros erros é só trocar no registro fonte que as analiticas serão corrigidas também.

**Comment by AngelicaSAPaula** [comment]
Muito obrigada! Já realizei a correção e orientei a usuária!
