### ISSUE TITLE
Erro em país de afiliação - Registros bibliograficos

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1293]
Boa noite!
id:1289255 - Consenso colombiano para la prevención, el diagnóstico y el tratamiento de condiciones trombóticas en adultos con COVID-19: aplicando el Marco de la Evidencia a la Decisión (EtD) GRADE

No campo "Autor pessoal" - Afiliação - País
Alguns autores estão sem marcação de país, ao completar o campo e clicar em gravar aparece o erro **Bad Request (400)**

![image](https://user-images.githubusercontent.com/37112458/154756892-31ac2703-2413-44b2-aaa8-b9f77308ddb8.png)

Alguns autores estão sem o país de afiliação, quando completo o campo, e clico em gravar, aparece o erro abaixo:
![image](https://user-images.githubusercontent.com/37112458/154757343-5e5c0ab9-0f7e-4f3f-b6a1-041ad4002b53.png)

**Comment by suelisuga** [comment]
@anakatiacamilo tem como aumentar o número de autores permitidos para incluir todos os autores?

**Comment by viniciusandrade** [comment]
@suelisuga neste caso temos muito pouco a ser feito pois não é uma configuração do sistema e sim o tempo que o servidor demora para processar o pedido e como este tempo é alto o próprio servidor termina a requisição do usuário para evitar travar todos os demais usuários.

**Comment by suelisuga** [comment]
@viniciusandrade criar o catálogo de autoridades ajudaria a diminuir o tempo de processamento ou aumentaria?

**Comment by viniciusandrade** [comment]
Issue finalizado impossibilidade de implementação.
