### ISSUE TITLE
Permitir preenchimento de autor pessoal e autor institucional

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1295]
Solicito criar regra que permita que os tipos de publicação "Publicação governamental", "Guia de Prática Clínica", "Relatório Técnico", "Estudo de avaliação".

Campos envolvidos:
Nível Monográfico
[16] Autor pessoal
[17] Autor institucional

Nível Analítico
[10] Autor pessoal
[11] Autor institucional

Nível Coleção
[23] Autor pessoal
[24] Autor institucional

Muito obrigada!

Contexto Revisão da MEtodologia LILACS e base de dados BRISA

**Comment by viniciusandrade** [comment]
@suelisuga conforme conversamos analisei a validação do sistema e embora seja possível fazer a permissão somente por alguns tipos de publicação não é possível garantir que ela funcione efetivamente para sempre pois seria uma validação baseada no texto dos tipos de publicação e caso algum destes textos, das listas controladas, sofra qualquer alteração por menor que seja (um acento ou um espaço) em qualquer um dos idiomas do sistema a validação não irá funcionar corretamente.

Também analisei que seria possível, e na minha opinião, mais efetivo retirar a validação que não permite o preenchimento de autor pessoal e institucional de forma simultânea. Desta forma o sistema só ira apresentar a mensagem de autor obrigatório caso um deles não seja preenchido.

Aguardo seus comentários sobre como podemos proceder.

Obrigado

**Comment by suelisuga** [comment]
Vamos implantar possibilidade de preencher os dois campos.

Verificando impactos negativos, revisamos.

**Comment by viniciusandrade** [comment]
@suelisuga ajuste disponível no ambiente de cursos para validação.

**Comment by suelisuga** [comment]
ok. validado
