### ISSUE TITLE
DirEve - Diretorio de eventos, caixa Histórico de mudanças

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1296]
Fonte de Informação: DirEve - Diretório de eventos, a caixa **Histórico de mudanças** que aparece no final da pagina de criação do evento, sumiu.

![image](https://user-images.githubusercontent.com/37112458/158242686-d0a01195-96d9-47ce-9138-e55e63f77141.png)

**Comment by viniciusandrade** [comment]
Olá @silvalais, a fonte diretório de eventos é a única que não tem a função de histórico de mudanças implementada, na época do seu desenvolvimento não se julgou necessário.

**Comment by silvalais** [comment]
Nunca teve? desculpe, tive a impressão que antigamente aparecia

Obrigada


Laís Silva
Bibliotecária
LILACS | lilacs.bvsalud.org​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>
Tel +55-11-5576-9831

Todo sucesso é fruto de um grande trabalho em equipe

[cid:8850fad3-5d9c-4d39-9d1d-2e87d3a3a9e8]
________________________________
De: viniciusandrade ***@***.***>
Enviado: segunda-feira, 14 de março de 2022 17:27
Para: bireme/fi-admin ***@***.***>
Cc: Silva, Lais Aparecida da (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/fi-admin] DirEve - Diretorio de eventos, caixa Histórico de mudanças (Issue #1296)


Olá @silvalais<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsilvalais&data=04%7C01%7Csilvala%40paho.org%7Cb0ed7e4e99c944a8eb7508da05f91746%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637828864655698193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N2i7UI79FR%2Fj9LCb7YHmggxQZzU%2BURH2OiGIDmdT4tY%3D&reserved=0>, a fonte diretório de eventos é a única que não tem a função de histórico de mudanças implementada, na época do seu desenvolvimento não se julgou necessário.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1296%23issuecomment-1067255650&data=04%7C01%7Csilvala%40paho.org%7Cb0ed7e4e99c944a8eb7508da05f91746%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637828864655698193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CAoheVmrITwliQTRJBEvf5wHsjmHN9ePJbyW38sqIDw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI3EVCWLOIVMCLVHWH3W3ZTU76OL3ANCNFSM5QWO2W4A&data=04%7C01%7Csilvala%40paho.org%7Cb0ed7e4e99c944a8eb7508da05f91746%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637828864655698193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gMMgI6SpWqMOqxJow0%2B9oawGV8P1IHMoPoo0XxvcWEs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csilvala%40paho.org%7Cb0ed7e4e99c944a8eb7508da05f91746%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637828864655698193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zKnm3vxlbJ21xorqtuwygpqW8csNfecUFQUis5Qcs1E%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csilvala%40paho.org%7Cb0ed7e4e99c944a8eb7508da05f91746%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637828864655698193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NuK31BV4yjN%2B%2Faefb3LCJCRxjrGuHK6HunCAUXVLBMY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Sem problemas.
