### ISSUE TITLE
fi-admin title campo  ID number

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#13]
O campo ID number deve ser  o primeiro na ordem da Aba dos Metadados,

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
O campo "ID number" agora aparece destacado sobre as abas do formulário após gravar o registro pela primeira vez. O valor desse campo é preenchido automaticamente com o valor da sua respectiva chave primária (PK).
