### ISSUE TITLE
Trocar cor do indicador de status de descritor

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1300]
Issue **zero urgência**, porém, quando possível, seria bom trocar a cor do status "histórico" para facilitar a tarefa de migrar individualmente os termos de registro. No exemplo abaixo, tenho que fazer várias migrações individuais desses termos que estão no "histórico", mas acabo confundindo "histórico" com "migrado" porque ambos são vermelhos. Sugiro mudar a cor do índice de status "histórico" para um rosa claro ou branco.
![image](https://user-images.githubusercontent.com/35345406/159743354-a4530cc1-852a-4edd-ad39-d86962c346fa.png)
Obrigada, Wilson!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no ambiente de testes. Favor validar.
