### ISSUE TITLE
Ajuste na api de Legislação

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1304]
Solicitud de actualización del dataset Legisalud disponible en el portal de datos abiertos del Ministerio de Salud y en el portal de la Nación - Argentina

Tenho um coleta configurada para Legislação. 
Só que para atender a solicitação preciso que:
- o format tenha uma opção de isis_id para poder filtrar por "Indexado em" OU 
-  que quando fizer uma search não tenho "total_count": 38915 para fazer a coleta 

Eles solicitaram um arquivo csv e vimos no site que pode ser json então imagino que qualquer uma das duas opções resolveria a solicitação.

**Comment by viniciusandrade** [comment]
@anakatiacamilo vou fechar porque você já conseguiu identificar o elemento do total na chamada do search e gerar os arquivos.
Obrigado.
