### ISSUE TITLE
Campo Ensaios Clínicos - subcampos obrigatórios

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#131]
Aplicar regra para campo Ensaios Clínicos:
subcampos obrigatórios:
-Base de dados
-Número do registro
![github-ensaio-clinico-campos-obrigatorios-fi-admin](https://cloud.githubusercontent.com/assets/13105683/14930180/502fb812-0e38-11e6-9b01-15522a7c44cc.JPG)

Obrigada
Sueli

**Comment by sarahviola** [comment]
Base de dados e número do registro estão como campos obrigatórios. 

![Uploading image.png…]()

**Comment by sarahviola** [comment]
![image](https://cloud.githubusercontent.com/assets/18355163/15078048/b4c3d2c8-1387-11e6-9e4a-5521a13ffff5.png)
