### ISSUE TITLE
O campo "Indexado em" não aparece a base de dados "selecionada"

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1311]
Prezados!
No navegador Google Chrome e navegador Edge,  o campo "Indexado em" não aparece a base de dados "selecionada"
Segue exemplos teste:
id:1366610 
id:1366587
Segue exemplos de usuário:
id:1366233
id:1366221

O campo "Indexado em" não aparece a base de dados "selecionada"
![image](https://user-images.githubusercontent.com/37112458/163886284-55e34015-95a1-4d9b-9c0f-7d6ad9851830.png)

**Comment by viniciusandrade** [comment]
@silvalais @suelisuga os registros criados desde a última atualização do sistema em 12/04 não gravaram o campo "Indexado em" devido a um efeito colateral dos ajustes realizados para inclusão do campos de relacionamento.

Realizei a correção do sistema e agradeço se puderem confirmar se agora esta OK, inclusive verificando em um documento de teste se todos os campos estão sendo gravados.

Obrigado

**Comment by silvalais** [comment]
Vini!

Deu certo, fiz um teste rápido, depois farei outros com mais calma

[cid:2eb2c308-e541-4cf6-89f2-d8f79e1a8f10]

Aba Retratação

[cid:eb251deb-790e-43f3-a699-29b1a73a5796]


Obrigada


Laís Silva
Bibliotecária
LILACS | lilacs.bvsalud.org​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>
Tel +55-11-5576-9831

Todo sucesso é fruto de um grande trabalho em equipe

[cid:dc7808a0-557e-4b59-9499-46c2c1fe169a]
________________________________
De: viniciusandrade ***@***.***>
Enviado: terça-feira, 19 de abril de 2022 14:14
Para: bireme/fi-admin ***@***.***>
Cc: Silva, Lais Aparecida da (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/fi-admin] O campo "Indexado em" não aparece a base de dados "selecionada" (Issue #1311)


@silvalais<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsilvalais&data=05%7C01%7Csilvala%40paho.org%7C775e45ab7f864af5c14f08da22280660%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637859852567244518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ut8DtQQ%2BzRBAqDB0TKEhiGdKbU5qXjLmrT%2FkAuUf%2FD8%3D&reserved=0> @suelisuga<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuelisuga&data=05%7C01%7Csilvala%40paho.org%7C775e45ab7f864af5c14f08da22280660%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637859852567244518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W7alDD0AfwveGkRcHor2g9g5AA%2BJrPg%2F8dNPG7e2pmU%3D&reserved=0> os registros criados desde a última atualização do sistema em 12/04 não gravaram o campo "Indexado em" devido a um efeito colateral dos ajustes realizados para inclusão do campos de relacionamento.

Realizei a correção do sistema e agradeço se puderem confirmar se agora esta OK, inclusive verificando em um documento de teste se todos os campos estão sendo gravados.

Obrigado

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1311%23issuecomment-1102893898&data=05%7C01%7Csilvala%40paho.org%7C775e45ab7f864af5c14f08da22280660%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637859852567244518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mps6T41fcn%2BgSZrsqxKnTiMnGTpbGUGHXTiVdvsgjiU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI3EVCSZST5FJ24Z7INDOQ3VF3SWJANCNFSM5TXAEFMQ&data=05%7C01%7Csilvala%40paho.org%7C775e45ab7f864af5c14f08da22280660%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637859852567244518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6eCpmdZB9Y22X56K%2FV6Er5HVzVk4sUIq6SrSmFjS%2F4o%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by suelisuga** [comment]
Teste realizado. OK funcionamento
