### ISSUE TITLE
Geração do MeSH Spanish (MSHSPA) e MeSH Portuguese (MSHPOR) 2022 para o UMLS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#1315]

**Comment by wilsonmoura** [comment]
@acecampos segue link do arquivo compactado com os relatórios: [RELATORIOS_TERMOS_BIREME.zip](https://github.com/bireme/fi-admin/files/8544056/RELATORIOS_TERMOS_BIREME.zip)

**Comment by acecampos** [comment]
@wilsonmoura Muitíssimo agradecida!
Os seguintes arquivos foram enviados para a NLM em 23abr22:
[BIREME_MESH_SPANISH_2022_TERMS_AND_SCOPE.zip](https://github.com/bireme/fi-admin/files/8546746/BIREME_MESH_SPANISH_2022_TERMS_AND_SCOPE.zip)
[BIREME_MESH_PORTUGUESE_2022_TERMS_AND_SCOPE.zip](https://github.com/bireme/fi-admin/files/8546747/BIREME_MESH_PORTUGUESE_2022_TERMS_AND_SCOPE.zip)
