### ISSUE TITLE
Lentidão no sistema FI-Admin_ Registros bibliográficos

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1316]
Bom dia!
A três semanas notamos lentidão no sistema FI_Admin., na pesquisa em registros bibliográficos.
Exemplo: 
Pesquisa por título de revista **Acta fisiátrica**  e também quando refinamos por Status
7 min para recuperar a pesquisa
![image](https://user-images.githubusercontent.com/37112458/165098818-c80f7cb6-942d-4c16-8fc9-8b83901cde12.png)

**Comment by viniciusandrade** [comment]
Ajustes em processo de implementação para melhoria da performance do sistema.

- Melhoria implementada para página inicial do sistema (37829c92f66196574bd1c2ce8c3c6ccf00f4dc4c)
- Melhoria implementada para o processo de gravação de um registro (644ce5313f144473671251a349731c96c29fd0cd)

**Comment by viniciusandrade** [comment]
@silvalais, foram realizadas mehorias nos tempos do processo de atualização de registros e na parte de busca do sistema.

Agradeço, quando possível, realizar novos testes na  pesquisa para verificar se agora esta OK.

Obrigado

**Comment by silvalais** [comment]
Bom dia!

Vinicius, realizei dois teste agora as 09:27 me parece ok

Obrigada

Laís Silva
Bibliotecária
LILACS | lilacs.bvsalud.org​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>​<https://outlook.office.com/mail/options/mail/lilacs.bvsalud.org%E2%80%8B>
Tel +55-11-5576-9831

Todo sucesso é fruto de um grande trabalho em equipe

[cid:1c5c3f32-c867-4b9d-9ba0-e766a61b6eb0]
________________________________
De: viniciusandrade ***@***.***>
Enviado: segunda-feira, 2 de maio de 2022 09:11
Para: bireme/fi-admin ***@***.***>
Cc: Silva, Lais Aparecida da (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/fi-admin] Lentidão no sistema FI-Admin_ Registros bibliográficos (Issue #1316)


@silvalais<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsilvalais&data=05%7C01%7Csilvala%40paho.org%7C1aa20870e9ce416dac4108da2c34dbab%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637870902791944209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SweN3WErk40LMjLzsI0axdGEdeDMH98V5ecdtorrHNg%3D&reserved=0>, foram realizadas mehorias nos tempos do processo de atualização de registros e na parte de busca do sistema.

Agradeço, quando possível, realizar novos testes na pesquisa para verificar se agora esta OK.

Obrigado

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F1316%23issuecomment-1114775966&data=05%7C01%7Csilvala%40paho.org%7C1aa20870e9ce416dac4108da2c34dbab%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637870902791944209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WoB5Ws%2FC1xMO4LvJa%2B1Hh5K7pCacWY%2Bb7ebzFn8gaxA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI3EVCT7AFSICCI5RIAVC63VH7A6HANCNFSM5UIS6Q3A&data=05%7C01%7Csilvala%40paho.org%7C1aa20870e9ce416dac4108da2c34dbab%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637870902791944209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fCM6V7P08ixl0raPj6P59%2Fik9RF6WmqWdI2f1wtHjAU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by suelisuga** [comment]
@viniciusandrade @alvesmarilda e meninos estão realizando testes e em breve trarão novos feedbacks.

Pelos relatos, na sexta-feira passada o sistema continuava lento. Como vimos que houve atualização do issue há 5 horas atrás, pode ser que tenhamos melhoras para relatar em breve.

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga, OK ... só para confirmar na semana passada foram realizadas melhorias no processo de gravação/publicação de registros e hoje foi aplicado melhorias na parte de pesquisa.
