### ISSUE TITLE
API do FI-Admin com dados de recursos relacionados

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1318]
Solciito que dados presentes na aba Recursos relacionados sejam incluidos na API do FI-Admin.

Ref #1278 

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1366689

Muito obrigada!

**Comment by suelisuga** [comment]
@viniciusandrade pf priorizar esta atividade pois é relacionada a PTB BIR.03.05

**Comment by anakatiacamilo** [comment]
@viniciusandrade, segue as tags e os subcampos
[787] - Recursos relacionados - https://www.loc.gov/marc/bibliographic/bd787.html

^i	Tipo
^t	Título
^6	Link

**Comment by viniciusandrade** [comment]
@anakatiacamilo obrigado pela documentação. 
Após a implementação inicial usando como exemplo o id: 1366689 o retorno irá ficar desta forma:

**XML**
```
<related_resource type="hash">
    <_6>http://pesquisa.bvsalud.org/portal/resource/pt/biblio-1367220</_6>
    <_i>uin</_i>
    <_t>XXII Congreso Uruguayo de Pediatría, IV Jornadas Uruguayas de Residentes en Pediatría</_t>
</related_resource>
```
**ISIS**
```
!v787!{'_i': 'uin', '_6': 'http://pesquisa.bvsalud.org/portal/resource/pt/biblio-1367220', '_t': 'XXII Congreso Uruguayo de Pediatría, IV Jornadas Uruguayas de Residentes en Pediatría'} 
```

A questão é que o link gerado para o recurso relacionado não esta presente no Portal de Pesquisa da BVS, como é um registro de 25/04/2022 ele já deveria estar indexado mas ele não tem LILACS marcada nas bases indexadas, você poderia dar uma olhada para verificar se este documento deveria estar no índice?

Obrigado

**Comment by anakatiacamilo** [comment]
@viniciusandrade, por favor, mudar de exemplo para teste para estes IDs que estão no portal do pesquisa
1385268 ==>>1385266 LILACS - OK

O Exemplo 1366689  ==>> 1367220 não é real deve ter sido um teste vou pedir para apagarem.

1366689 - Relatório de gestão: 2017-2020 
São Paulo (Cidade). Secretaria da Saúde. Secretaria Executiva de Atenção Básica, Especialidades e Vigilância em Saúde. Coordenadoria de IST/Aids
tipo de relacionamento: Atualização em
1367220 - XXII Congreso Uruguayo de Pediatría, IV Jornadas Uruguayas de Residentes en Pediatría
Sociedad Uruguaya de Pediatría

**Comment by viniciusandrade** [comment]
@anakatiacamilo no caso de relacionamentos entre registros bibliográficos do próprio FI-ADMIN estaremos exportando o ID do documento para correr o risco de gerar um link que pode ser inválido. Poderia informar qual seria o subcampo indicado para esta finalidade? 
Obrigado

**Comment by anakatiacamilo** [comment]
@viniciusandrade, eu indicaria o subcampo "w"

$w - Record control number (R)

**Comment by viniciusandrade** [comment]
@anakatiacamilo perfeito vou seguir com este subcampo.

Obrigado

**Comment by viniciusandrade** [comment]
Implementado na API com elemento **related_resource** no XML e tag **787** no ISIS:

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=xml&id=1385268
https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1385268

**Comment by suelisuga** [comment]
Ok @viniciusandrade 

![image](https://user-images.githubusercontent.com/13105683/194146002-fb2efeb7-efef-4a24-bc69-d55b9a620ba4.png)

![image](https://user-images.githubusercontent.com/13105683/194146152-922bb613-e05e-4942-a986-3adb0f1dab17.png)

Obrigada!
