### ISSUE TITLE
API do FI-Admin com dados da aba Dados de pesquisa

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1319]
Solicito que a API do FI-Admin traga dados da aba Dados de pesquisa

Conforme #1277 

Muito obrigada!

**Comment by suelisuga** [comment]
@viniciusandrade pf priorizar esta atividade pois é relacionada a PTB BIR.03.05

**Comment by anakatiacamilo** [comment]
@viniciusandrade, segue a tag e os subcampos
[786] - Dados de pesquisa - https://www.loc.gov/marc/bibliographic/bd786.html

^6	Link *
^t	Título
^n	Descrição

**Comment by viniciusandrade** [comment]
Implementado na API com elemento **related_research** no XML e tag **786** no ISIS:

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=xml&id=1369642
https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1369642

**Comment by suelisuga** [comment]
Ok @viniciusandrade 
![image](https://user-images.githubusercontent.com/13105683/194144944-0d258ab5-5c02-4843-8056-74f0bb97bb45.png)

![image](https://user-images.githubusercontent.com/13105683/194145194-85b2d022-929e-46f4-a238-7b831c1b18bb.png)

Obrigada!
