### ISSUE TITLE
Apresentação da paginação de modo invertido

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#132]
Paginação incluída em ^f (first) deve aparecer primeiro que ^l (last)
![github-paginacao-invertida](https://cloud.githubusercontent.com/assets/13105683/14930205/8341b58e-0e38-11e6-9c2a-0ff644d1ddec.JPG)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
Duplicado com  #221 e já resolvido
