### ISSUE TITLE
Duplicação de termos com diferentes TermUI e datas de criação

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1320]
@wilsonmoura, a Stephanie da NLM identificou uma duplicação de termos em espanhol que o sistema Fi-Admin não reconheceu como iguais (e, portanto, não teria deixado inserir de novo). Trecho do e-mail dela de 29/04/22:
"Spanish:

Same DUI, MUI, TTY, STRING (different termUI).  Our algorithm is keeping the first one (spad070233) so if you’re ok with that I don’t need a new file, but you probably want to address this in your system.

D054882 M000746024      SPA     ET      Hiperplasia Suprarrenal Congénita Debida a Deficiencia de Citocromo P450 Oxidorreductasa        spad070233

D054882 M000746024      SPA     ET      Hiperplasia Suprarrenal Congénita Debida a Deficiencia de Citocromo P450 Oxidorreductasa        spad070234"

Antes de liberar a edição de 2022, seria prudente eliminar essa duplicação da base de dados, por favor.
Grata!

**Comment by wilsonmoura** [comment]
@acecampos nesse caso, qual dos registros deve ser removido? (spad070233 ou spad070234)

**Comment by wilsonmoura** [comment]
@acecampos nesse caso, o registro com termUI spad070234 deve ser removido, correto?

**Comment by acecampos** [comment]
@wilsonmoura sim, o spad070234 deve ser removido do Fi-Admin agora. Mantive somente para demonstrar a vocês. Removido.

**Comment by wilsonmoura** [comment]
@acecampos registro removido conforme solicitado.
