### ISSUE TITLE
API do FI-Admin com dados de licenças

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1323]
Solicito inclusão de dado de licenças na API de registros bibliográficos do FI-Admin.

![image](https://user-images.githubusercontent.com/13105683/167933219-21a76101-f778-473a-9e1b-b99f77504b0c.png)

Relacionado com #1276 

Muito obrigada!

**Comment by anakatiacamilo** [comment]
@viniciusandrade, a tag sugerida é [540](https://www.loc.gov/marc/bibliographic/bd540.html) para seguir a compatibilidade com o MARC 21

**Comment by viniciusandrade** [comment]
Implementado na API com elemento **license** no XML e tag 540 no ISIS:

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=xml&id=1048744
https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1048744

**Comment by suelisuga** [comment]
Ok @viniciusandrade 

![image](https://user-images.githubusercontent.com/13105683/194147408-fdfbd55b-f8e3-4ad8-ac4f-c6c1f943986e.png)

![image](https://user-images.githubusercontent.com/13105683/194147549-4919783a-759d-46cc-a93a-6cdb59c634d2.png)

Obrigada!
