### ISSUE TITLE
Códigos editores sem "país"

### ISSUE THREAD

**Issue by amilson18** [bireme/fi-admin#1335]
No Fi-admin os códigos editores estão com problema:
Pesquisando  no Fi-admin Instituições "periódicos editor", (principalmente apartir da pag. 2) à 6 vai aparecer os códigos sem o campo país  preenchido (None).
![Cod_edt_pais](https://user-images.githubusercontent.com/88335258/178068187-71338e6a-bf8e-4e02-b05a-2f8d3cb12cad.PNG)

@anakatiacamilo

**Comment by anakatiacamilo** [comment]
A questão foi resolvida. Os registros migrados que na base legado a informação dos país estava na tag 640 ao inves do 620 não foi migrado.(100 e poucos registros a maioria dele de "periódicos editor"). Gostaria de marcar uma reunião com vocês sobre curadoria das bases migradas. @AngelicaSAPaula, @suelisuga @amilson18

**Comment by AngelicaSAPaula** [comment]
Muito obrigada!!! Conferi e parece estar tudo certinho! 

Vou verificar na agenda um horário!
