### ISSUE TITLE
Bloquear e enviar mensagem de erro para preenchimento s.d

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1337]
Metodologia LILACS modificada em 2022:

Não se aceita mais s.d (sem data), pois todos registros devem conter data de publicação.

Quando não souber a data, o documentalista deve pesquisar e preencher campo com dado entre colchetes.

Obrigada

**Comment by suelisuga** [comment]
@viniciusandrade pf implantar conforme PTB BIR.01.04.02

**Comment by suelisuga** [comment]
@viniciusandrade pf implantar conforme PTB BIR.01.04.02

**Comment by viniciusandrade** [comment]
@suelisuga ajustes realizados, quando possível favor validar.
Obrigado.

**Comment by viniciusandrade** [comment]
Issue concluído, caso seja identificado algum problema favor reabrir.

**Comment by suelisuga** [comment]
Ok! Implantação validada.

![image](https://github.com/bireme/fi-admin/assets/13105683/d8ba2290-b923-448f-9030-5940f40c735f)
