### ISSUE TITLE
Valor default Eletrônico para campo Forma do Item para Tipo de periódico Revistas

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1339]
Solicito trocar o valor default do campo Forma do Item de vazio para Revi

![image](https://user-images.githubusercontent.com/13105683/182447650-7da31c7c-3f52-4761-93e4-fe2efcdd4dd5.png)

Considerando que artigos de periódicos devem ter link para o texto completo, segundo os critérios LILACS, solicito que o valor default seja mudado somente para esse tipo de periódico Revistas.

Obrigada
Sueli

PS. atividade solicitada como parte da revisão da metodologia LILACS.

**Comment by suelisuga** [comment]
@viniciusandrade pf implantar conforme PTB BIR.01.04.02

**Comment by suelisuga** [comment]
@viniciusandrade alguma novidade?

**Comment by viniciusandrade** [comment]
@suelisuga ajuste realizado, quando possível favor validar.

**Comment by viniciusandrade** [comment]
Issue concluído, caso seja identificado algum problema favor reabrir.

**Comment by suelisuga** [comment]
ok. validado
![image](https://github.com/bireme/fi-admin/assets/13105683/061301ab-52ad-42af-b0a3-4fada3bfbcb9)
