### ISSUE TITLE
Mudança do nome do campo 530 - Nota de disponibilidade de forma física adicional

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1340]
Solicito mudança do nome do campo Nota de disponibilidade de forma física adicional](https://fi-admin.bvsalud.org/bibliographic/new-analytic?source=1379576#) para **Nota de Outros Formatos Disponíveis**

![image](https://user-images.githubusercontent.com/13105683/182455029-1a71a1db-1da3-4c21-bfed-5e82c82a53c4.png)

Justificativa: campo é conhecido na área com essa nomenclatura.
![image](https://user-images.githubusercontent.com/13105683/182455191-0d499e1f-dcc1-4361-ac5c-f870bc91e6ba.png)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga ajustes realizados.
