### ISSUE TITLE
Recuperação  BR12.1 Arquivo SeCS 001 e 002

### ISSUE THREAD

**Issue by amilson18** [bireme/fi-admin#1341]
Marco Miacci,

Seria possível recuperar o arquivo SeCS (.001 e .002) do BR12.1, pois estamos precisando.
Nestes arquivos contêm o acervo das bibliotecas que nós disponibilizávamos no nosso Portal.
Na mudança que teve dos sistemas foi salvo uma pasta (Renata, Amilson) compartilhada contendo 
vários arquivos que usávamos.

Pesquisei no relatório de 2018 consta a data de envio 20/04/2018

Alpha1\SPD\ROTINASECS

@marcoslmori

**Comment by viniciusandrade** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
