### ISSUE TITLE
Mundança do nome do campo 700 NOME DO REGISTRO DE ENSAIO CLÍNICO 

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1344]
Solicito mudança do nome do campo 700 NOME DO REGISTRO DE ENSAIO CLÍNICO  para 700 REGISTRO DE ENSAIO CLÍNICO .

Muito obrigada!
Sueli

Contexto: atualização do manual de descrição bibliográfica e atualização da metodologia LILACS

**Comment by viniciusandrade** [comment]
@suelisuga ajustes realizados.
