### ISSUE TITLE
Apagar código hierárquico por baixo do sistema D000087642

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1346]
@wilsonmoura 
D000087642
Primary Visual Cortex
por favor, apagar os dois códigos hierárquicos errados
A08.186.211.200.885.287.500.571.735.501
A08.186.211.200.885.287.500.814.953.501

a fim de que possamos (@lucianaPRB) colocar os certos e efetuar as traduções das notas de indexação.
Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Obrigada!

**Comment by wilsonmoura** [comment]
Código hierárquicos apagados: `A08.186.211.200.885.287.500.571.735.501` `A08.186.211.200.885.287.500.814.953.501`
