### ISSUE TITLE
Identificar registros faltando PEP e presente ET

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1348]
@wilsonmoura Recebemos um e-mail da NLM sobre uma violação das regras do MeSH encontrada:
Ausência termo preferido do conceito não preferido e presença de termo não preferido no mesmo conceito.

Recently I discovered that Spanish and Portuguese violate one of our rules:

![image](https://user-images.githubusercontent.com/35345406/187907289-c0e4bccd-2552-47da-94bb-747b57293805.png)

Exemplo:
Descriptor UI: D000209
Concept UI: M0000323

![image](https://user-images.githubusercontent.com/35345406/187908923-7acec3e5-2e76-4cfd-8c0d-0110086582b8.png)

Então, gostaria de solicitar que o sistema Fi-Admin/thesaurus pudesse identificar casos em que existem ET sem PEP. Pode fazer com que o sistema impeça a gravação do registro quando isso ocorrer?

Grata

(@lucianaPRB, para sua ciência)

**Comment by acecampos** [comment]
Alternativa: quando migrar o termo, sempre assumir por padrão PEP (YN). Se o PEP já existir, encaixar o termo migrado como ET (NN).

**Comment by acecampos** [comment]
Pensar numa consulta para identificar casos em que ocorram ETs sem PEP, uma vez que é obrigatório ter PEP.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
Oi, @wilsonmoura 
Testei a migração de um conceito todo, mas não funcionou. O programa não aceitou os termos migrados como PEP.
Também testei a migração de um termo para um novo conceito em que não havia PEP naquele idioma, e também não funcionou.

**Comment by acecampos** [comment]
@wilsonmoura, agora está tudo certo. Validado. Grata.
