### ISSUE TITLE
Fornecer acesso para editar Fi-Admin/thesaurus

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1354]
@anakatiacamilo, por favor, criar contas no BIREME Accounts para os seguintes tradutores do ISCIII no Fi-Admin/thesaurus:

- Elena de Terán Bleiberg: edeteran@telefonica.net
- Elena Primo Peña: eprimo@isciii.es
- Virginia Jimenez Planet: virginiaj@isciii.es
- María Teresa Romera García: mtromera@isciii.es

As restrições são: 
- idioma de edição permitido: espanhol da Espanha (es-es)

Campos que poderão editar:
- campo de descritor es-es
- campo de termo alternativo es-es
- campo de nota de escopo es-es
- campo de nota de indexação es-es
- criação de conceito em es-es

O ideal é ficar parecido com perfil de CL1.1, mas com a possibilidade de edição apenas da nota de escopo de es-es.

Agradecemos muito!
@lucianaPRB e @acecampos

**Comment by anakatiacamilo** [comment]
@acecampos, 
- infelizmente a permissão no FI-ADMIN DeCS não é tão espeficico. 
Temos duas opções  de permissão do Tesaudo DeCS: Documentalista e Editor.
Será que vocês tem uma documentação que lista as atividades possivel dos perfis.
- no Accounts não tem nenhum usuário do centro cooperante CL1.1 que tenha permissão ao DeCS.
- outra questão tem três pessoas do isciii que são do CC ES15.1 e um pessoa da telefonica eu não achei na base de Centros Cooperantes vc sabe qual é a instituição desta pessoal e o CC dela?

**Comment by anakatiacamilo** [comment]
A permissão esta vinculanda com o CC de acordo com as especificações do Arthur (CC e idioma)

Coloquei Editor para todos.
Listo
