### ISSUE TITLE
Criar Pop-Up para alterar status de termo

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1360]
Incluir um pop-up/tela de confirmação para alterar o status dos termos para Apagado ou Histórico - "Tem certeza que deseja apagar o termo xyz?"
Essa demanda foi solicitada pela equipe de tradução da Espanha (ES15.1).

Agradecemos!
Ana e @lucianaPRB

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Obrigada!
