### ISSUE TITLE
Criar novo filtro por categoria

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1361]
Criar menu suspenso (combobox) para filtrar por categoria. Sugestão de um menu mostrando os códigos das categorias. Ex.: A, B, SP, MT.
A figura abaixo representa a ideia geral do que precisamos. 

![image](https://user-images.githubusercontent.com/35345406/196781293-37ad527b-738c-4968-99b9-1c90a29ead1f.png)

Agradecemos!
Ana e @lucianaPRB

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
Oi, @wilsonmoura. Obrigada! 

1. A busca livre, sem opção, (---) em "Campos" traz o total de entradas por idioma. Era disso que necessitávamos ao abrirmos o issue. **Validado**.

2. Trazem erro as buscas em "Campos" por:
-  "Todos os termos" (mas a informação obtida por essa busca pode ser recuperada usando-se (---) em "Campos", conforme validado acima);
- ID de transporte (ok, não faria sentido mesmo);
- ID do tesauro (ok, não faria sentido mesmo).

![image](https://user-images.githubusercontent.com/35345406/204589360-d99800c6-cc59-4a7b-9335-3423ddb66121.png)

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Obrigada!
