### ISSUE TITLE
Remover termo com YY e status "Apagado" no Fi-Admin/thesaurus

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1367]
@wilsonmoura, o registro ficou com o seguinte termo com YY e no status apagado. Por favor, seria possível removê-lo individualmente? 
DescriptorUI: D000092965
ConceptUI: M000752981 
TermUI: spad074513

![image](https://user-images.githubusercontent.com/35345406/212760321-9de157bf-449b-4b9e-9c57-31e417d4b6ee.png)

Muito agradecidas,
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
@wilsonmoura Obrigada.
O registro apagado ainda consta como Y em "termo preferido do registro". Só o primeiro, "termo preferido do conceito", é que foi para N. Tudo bem ficar assim?

**Comment by lucianaPRB** [comment]
Wilson, bom dia!
O issue pode ser considerado concluído para o termo no es (spad074513). A dúvida no comentário anterior seria sobre o termo no es-es (spad074514).
Você acha melhor editar/remover este termo também? Ou ele não afetará o processamento?

**Comment by wilsonmoura** [comment]
@acecampos @lucianaPRB ajustes realizados conforme solicitado.
