### ISSUE TITLE
Criar dados de categorias exclusivas em CSV para HURouen (França)

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1370]
Bom dia, @wilsonmoura!

Por favor, criar um arquivo CSV de todos os registros nos 5 idiomas das categorias exclusivas:
**HP** - Homeopatia
**MT** - Medicinas Tradicionais, Complementares e Integrativas
**SH** - Ciência e Saúde
**SP** - Saúde Pública
**VS** - Vigilância Sanitária

Agradecemos!
@lucianaPRB e @acecampos

**Comment by acecampos** [comment]
@wilsonmoura, Hoje o responsável pela tradução nos enviou um excel com as traduções de que precisávamos. 
Creio que podemos encerrar o issue.

**Comment by wilsonmoura** [comment]
@acecampos sendo assim, creio que podemos encerrar esse issue. Poderia compartilhar essa planilha Excel nesse issue? Para que possamos verificar e, caso necessário, replicar a mesma estrutura de colunas em uma futura demanda desse mesmo tema.

**Comment by wilsonmoura** [comment]
@acecampos antes de encerrarmos esse issue, seria possível compartilhar essa planilha Excel como anexo nesse issue? Para que possamos verificar essa planilha e, caso necessário, replicar a mesma estrutura de colunas em uma futura demanda desse mesmo tema.

**Comment by acecampos** [comment]
[traduction_catégories_MT-SH-SP_FRE.xlsx](https://github.com/bireme/fi-admin/files/10489028/traduction_categories_MT-SH-SP_FRE.xlsx)

@wilsonmoura o arquivo que foi enviado para a França encontra-se anexado. Como imaginei que fariam apenas a tradução no excel, está reduzido em número de colunas. Muito obrigada!

**Comment by wilsonmoura** [comment]
Segue consulta utilizada para recuperar os registros das categorias exclusivas:
```
select
	c.descriptor_ui,
	b.concept_ui,
	a.term_ui,
	a.language_code,
	a.term_string,
	d.tree_number,
	e.scope_note
from
	thesaurus_termlistdesc as a, 
	thesaurus_identifierconceptlistdesc as b,
	thesaurus_identifierdesc as c,
	thesaurus_treenumberslistdesc as d,
	thesaurus_conceptlistdesc as e
where
	a.term_thesaurus='1' and
	a.status='1' and
	a.identifier_concept_id=b.id and
	e.identifier_concept_id=b.id and
	b.identifier_id=c.id and
	d.identifier_id=a.id and
	(
		substring(d.tree_number,1,2)='SP' or
		substring(d.tree_number,1,2)='HP' or
		substring(d.tree_number,1,2)='SH' or
		substring(d.tree_number,1,2)='VS' or
		substring(d.tree_number,1,2)='MT'
	)
group by a.term_string
```
