### ISSUE TITLE
Trazer relatório de registros com 5 ou mais (Y) no "termo preferido do conceito

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1372]
@wilsonmoura 
Boa tarde! Conforme conversado, por favor identificar registros com 5 ou mais (**Y**) no "termo preferido do conceito.

Exemplo:
ID do termo: Txxxxxxxx
Termo preferido do conceito: **Y**
É permutado: N
LexicalTag: NON
Termo preferido do registro: N
Data de criação: x de Janeiro de 1xxx

Agradecemos!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos o relatório não encontrou nenhuma ocorrência de descritores com mais de 5 termos preferidos no mesmo conceito.

Segue consulta utilizada para gerar o relatório solicitado:

```
SELECT
	ti.concept_ui,
	COUNT(*) AS total
FROM
	thesaurus_termlistdesc tt,
	thesaurus_identifierconceptlistdesc ti 
WHERE
	tt.identifier_concept_id = ti.id AND
	tt.concept_preferred_term='Y' AND
	tt.record_preferred_term='N'
GROUP BY tt.identifier_concept_id
HAVING total > 5
```

**Comment by acecampos** [comment]
@wilsonmoura obrigada! 
@lucianaPRB, segue a "evidência" do problema encontrado:
A diferença é só de um nas categorias C, F e VS. 

![image](https://user-images.githubusercontent.com/35345406/215861420-744333ec-420c-473f-a1e2-815b42789767.png)

É possível que apareça uma pista no "file compare" quando da elaboração do txt para a NLM, como @wilsonmoura comentou mais cedo.

**Comment by wilsonmoura** [comment]
@acecampos seguem os dados dos termos ausentes:

**Categoria C**: descriptorUI D000093742
**Categoria F**: descriptorUI D008192
**Categoria VS**: descriptorUI DDCS051540

**Comment by acecampos** [comment]
Uau! Você achou! Obrigada!!!

**Comment by wilsonmoura** [comment]
Segue consulta para gerar o relatório das categorias com termos ausentes:

```
select
	c.descriptor_ui,
	b.concept_ui,
	a.term_ui,
	a.language_code,
	a.concept_preferred_term,
	a.record_preferred_term,
	a.term_string,
	d.tree_number,
	e.scope_note
from
	thesaurus_termlistdesc as a, 
	thesaurus_identifierconceptlistdesc as b,
	thesaurus_identifierdesc as c,
	thesaurus_treenumberslistdesc as d,
	thesaurus_conceptlistdesc as e
where
	a.term_thesaurus='1' and
	a.status='1' and
	a.language_code='en' and
	a.concept_preferred_term='Y' and
	a.record_preferred_term='Y' and
	a.identifier_concept_id=b.id and
	e.identifier_concept_id=b.id and
	b.identifier_id=c.id and
	d.identifier_id=c.id and
	substring(d.tree_number,1,2)='VS'
group by a.term_string
```

**Comment by acecampos** [comment]
@wilsonmoura valeu mesmo! Grata!
O da categoria VS estava até NN...
Validado e fechando o issue.
