### ISSUE TITLE
Diferenciar categorias cujos símbolos começam com letras iguais

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1373]
@wilsonmoura, conforme conversado, por favor, no filtro do Fi-Admin, construir um mecanismo para diferenciar as categorias que começam com o mesmo radical (letra) como símbolo.
Exemplos:
Quando filtramos para contar as quantidades de termos das categorias, acabam sendo quantificadas os registros das que começam com igual letra. Assim, solicitamos poder diferenciar:
VS de V; 
MT de M e 
HP de H.
Agradecemos!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
@wilsonmoura validado no ambiente de testes do Fi-Admin. Muito obrigada!
