### ISSUE TITLE
Eliminar repetições de termos na contagem geral de descritores

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1374]
@wilsonmoura, conforme conversado, por favor, ao realizar a contagem geral de termos com status "Publicado" no Fi-Adminwilson, por favor, eliminar as repetições de descritores que ocorrem em mais de uma categoria, a fim de que a contagem seja igual à das 16 categorias da NLM.

Agradecemos!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos seria possível compartilhar um print da planilha com os números consolidados de termos autorizados (MeSH e DeCS)? Vamos utilizar essa informação como base para os possíveis ajustes. Desde já eu agradeço.

**Comment by acecampos** [comment]
@wilsonmoura essa planilha, certo?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/HP/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/HP/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | MeSH | \| |   | DeCS |  
-- | -- | -- | -- | -- | --
  | idioma | \| | idioma
CAT | en | \| | en | es | pt-br
A | 1765 | \| | 1896 | 1896 | 1896
B | 3914 | \| | 3936 | 3936 | 3936
C | 4745 | \| | 5004 | 5004 | 5004
D | 10108 | \| | 10408 | 10408 | 10408
E | 2293 | \| | 3078 | 3078 | 3078
F | 905 | \| | 1201 | 1201 | 1201
G | 2083 | \| | 2399 | 2399 | 2399
H | 328 | \| | 764 | 764 | 764
I | 438 | \| | 736 | 736 | 736
J | 547 | \| | 639 | 639 | 639
K | 145 | \| | 207 | 207 | 207
L | 398 | \| | 439 | 439 | 439
M | 225 | \| | 346 | 346 | 346
N | 1967 | \| | 1969 | 1969 | 1969
V | 187 | \| | 187 | 187 | 187
Z | 404 | \| | 404 | 404 | 404
total contagem por excel enviado por NLM | 30452 | \| |   |  
total de registros com Fem & Male | 30454 | \| |   |  
  |   | \| |   |  
HP | n.a. | \| | 1907 | 1907 | 1907
MT | n.a. | \| | 45 | 45 | 45
SH | n.a. | \| | 330 | 330 | 330
SP | n.a. | \| | 2759 | 2759 | 2759
VS | n.a. | \| | 818 | 818 | 818



</body>

</html>

**Comment by acecampos** [comment]
![image](https://user-images.githubusercontent.com/35345406/216135244-690743c7-521d-44ee-8b0f-fa9c9cbd8641.png)

**Comment by acecampos** [comment]
@wilsonmoura A pesquisa do tesauro está correta, pois recupera os descritores que foram marcados na respectiva categoria, independente se este registro está marcado em uma ou mais categorias, diferente do critério utilizado pela fonte de dados do MeSH de que dispomos para quantificar os descritores por categoria.
Vale ressaltar que o MeSH mostra o descritor em apenas uma das categorias em que ele aparece (com exclusão). 
Sendo assim, não será necessária nenhuma ação da nossa parte no Fi-Admin.
Obrigada!
