### ISSUE TITLE
Colocar mensagem de alerta para impedir duplicidade de conceito preferido do registro

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1375]
@wilsonmoura por favor, criar mensagem de alerta quando da edição de novo registro (**YN**) como a da ilustração abaixo, conforme já é disparado no caso de editarmos (**YY**), a fim de immpedir a duplicidade de "conceito preferido do registro".

![image](https://user-images.githubusercontent.com/35345406/215841684-66879c32-b7b1-47f7-a2dc-3320497638c0.png)

![image](https://user-images.githubusercontent.com/35345406/215841892-ee07dc80-218a-40e9-9e0f-fc136c744987.png)

Agradecemos!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
@wilsonmoura muito obrigada! Validado.
