### ISSUE TITLE
Links de texto completo enviam para https://fi-admin2.bvsalud.org/

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1376]
Verificamos que há documentos em texto completo que não estão sendo abertos por algum tipo de problema com redirecionamento do link para https://fi-admin**2**.bvsalud.org/.

Lembrei-me de uma atualização da plataforma FI-Admin na qual foi utilizada a URL FI-Admin2 e entendi que por ocasião dessa atualização, uma certa quantidade de registros apresentam essa anomalia.

Exemplo:
https://sites.bvsalud.org/redetsa/pt/brisa/resource/?id=biblioref.referencesource.1281512

Link no plug-in registros bibliográficos: https://fi-admin2.bvsalud.org/document/view/wtw2m
![image](https://user-images.githubusercontent.com/13105683/216076936-c7ee4031-e60e-4c68-aff4-145ae37441d4.png)

Link que funciona: https://fi-admin.bvsalud.org/document/view/wtw2m
Link no FI-Admin: https://docs.bvsalud.org/biblioref/2021/07/1281512/sre_impuestos-a-alimentos-solidos-altos-en-nutrientes-criticos_2021.pdf
![image](https://user-images.githubusercontent.com/13105683/216077038-22983941-d1ec-4f1c-94f9-7d151a0d495c.png)

Já identificamos outros documentos do Minsal Chile, porém por se tratar de uma rede, entendo que outros registros de outros Centros Cooperantes que cooperavam com qlq das bases geridas no FI-Admin podem ter sido afetados. Poderiam diagnosticar a quantidade de registros que apresentam esse comportamento e corrigir todos de forma automática?

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga com a normalização do ambiente e com a reindexação da base BRISA estes links foram atualizados para o endereço correto. 
Estou fechando este issue mas caso encontre algum outro exemplo com este problema favor reenviar.
