### ISSUE TITLE
Iniciar processamento teste para códigos hierárquicos órfãos

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1378]
Wilson,
Conforme conversado, por favor, fornecer a base DeCS no Fi-Admin para ser submetida pelo @botturam ao um processamento de teste para detecção de hierarquia órfã. 

Motivo: faltam os códigos hierárquicos de categorias exclusivas do DeCS em registros que são também do MeSH.

**Aparentemente**, aconteceu somente com códigos hierárquicos que começam com **MT**.

Caso: descritor Ayurveda
![image](https://user-images.githubusercontent.com/35345406/217368103-ab08a4fb-74bd-40f3-aa12-1d22b7f56230.png)

E esse código hierárquico não foi removido ou modificado, visto que não houve log de modificação depois da publicação do DeCS 2022:
![image](https://user-images.githubusercontent.com/35345406/217368788-ae06177a-4788-4f53-8eb6-e384b2e55ff0.png)

e que consta na hierarquia do DeCS2022: 
![image](https://user-images.githubusercontent.com/35345406/217369106-43e4c86e-54e4-420d-8f4f-88aa75c5bed0.png)

Muito obrigada!

**Comment by acecampos** [comment]
@wilsonmoura, @botturam e @lucianaPRB 
Os códigos hierárquicos que faltavam já foram inseridos no Fi-Admin de produção. 
Não sabemos o que pode ter ocasionado esse problema, mas foi pontual para os códigos hierárquicos de MTCI, que começam com MT. A seguir, a lista dos códigos inseridos com os respectivos descritores em pt-br:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ANACRI~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ANACRI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



DESCRITOR   pt-br | CÓDIGOS HIERÁRQUICOS   MT PARA INSERIR
-- | --
Acupressão | MT3.575.117 |  
Acupuntura | MT1.388.585.520.014 |  
Acupuntura Auricular | MT1.388.585.520.014.133 |  
Analgesia por Acupuntura | MT1.388.585.520.014.105 |  
Apiterapia | MT3.465.101 |  
Aplicação de Sanguessugas | MT3.465.111 |  
Aromaterapia | MT3.465.121 |  
Arteterapia | MT3.795.062 |  
Ayurveda | MT1.388.515 |  
Balneologia | MT3.465.141 |  
Biorretroalimentação Psicológica | MT3.795.186 |  
Cromoterapia | MT3.685.184 |  
Dançaterapia | MT3.795.062.769 |  
Drenagem Linfática Manual | MT3.575.510.219 |  
Eletroacupuntura | MT1.388.585.520.014.244 | MT3.685.237
Essências Florais | MT3.685.759.244 |  
Fitoterapia | MT3.465.265 |  
Hidroterapia | MT3.465.333 |  
Hipnose | MT3.795.310 |  
Homeopatia | MT2.201 |  
Magnetoterapia | MT3.685.506 |  
Manipulação Quiroprática | MT3.575.541 |  
Manipulações Musculoesqueléticas | MT3.575 |  
Massagem | MT3.575.510 |  
Medicina Arábica | MT1.388.510 |  
Medicina Integrativa | MT4 |  
Medicina Kampo | MT1.388.585.600.600 |  
Medicina Osteopática | MT2.704 |  
Medicina Tradicional Chinesa | MT1.388.585.520 |  
Medicina Tradicional Coreana | MT1.388.585.700 |  
Medicina Tradicional da Mongólia | MT1.388.585.850 |  
Medicina Tradicional do Leste Asiático | MT1.388.585 |  
Medicina Tradicional Tibetana | MT1.388.875 |  
Medicina Unani | MT1.388.510.500 |  
Meditação | MT3.795.372 |  
Meridianos | MT1.388.585.520.400.555 |  
Moxibustão | MT3.685.529 |  
Musicoterapia | MT3.795.062.530 |  
Naturologia | MT2.805 |  
Oncologia Integrativa | MT4.583 |  
Osteopatia | MT3.575.583 |  
Oxigenoterapia Hiperbárica | MT3.465.567 |  
Peloterapia | MT3.465.615 |  
Pontos de Acupuntura | MT1.388.585.520.400.555.035 |  
Programação Neurolinguística | MT3.795.434 |  
Psicodrama | MT3.795.062.624 |  
Qigong | MT1.388.585.520.500 | MT3.795.496
Reflexoterapia | MT3.575.667 |  
Relaxamento | MT3.795.558 |  
Tai Chi Chuan | MT3.795.744 |  
Terapia Baseada em Meditação | MT3.795.806 |  
Terapia Biológica | MT3.465 |  
Terapia com Luz de Baixa Intensidade | MT3.685.735 |  
Terapia do Riso | MT3.795.682 |  
Terapia Nutricional | MT3.465.763 |  
Terapia Ortomolecular | MT3.465.740 |  
Terapia por Acupuntura | MT3.575.741 |  
Terapias Espirituais | MT3.795.930 |  
Terapias Mente-Corpo | MT3.795 |  
Toque Terapêutico | MT3.685.766 |  
Ventosaterapia | MT1.388.585.520.791 | MT3.575.822
Yin-Yang | MT1.388.585.520.967 |  
Yoga | MT3.795.992 |  



</body>

</html>

**Comment by wilsonmoura** [comment]
@acecampos segue relatório com a lista parcial dos códigos órfãos identificados via processamento: [LISTA_ORFAOS.txt](https://github.com/bireme/fi-admin/files/10775520/LISTA_ORFAOS.txt)

Documentação dos passos para executar o script de verificação de registros órfãos:

    $ cd /bases/decs.django/tools/wrk/
    $ nohup python ../tpl/verifica_ORFAO.py &> ../outs/verifica_ORFAO.YYYYMMDD.out &

**Comment by wilsonmoura** [comment]
## Documentação dos passos para checagem de códigos hierárquicos órfãos

No servidor de processamento, executar os comandos abaixo para iniciar o processo de checagem dos códigos hierárquicos órfãos:

```
$ cd /bases/decs.django/tools/wrk/
$ # nohup python ../tpl/verifica_ORFAO.py &> ../outs/verifica_ORFAO.YYYYMMDD.out &
```

**OBS:** Antes de executar o carregamento, certificar que os dados do ambiente de testes do Tesauro FI-ADMIN estão atualizados de acordo com o ambiente de trabalho/produção.

**Comment by acecampos** [comment]
Obrigada, @wilsonmoura.
Creio que seria bom realizar outra conferência após ajuste manual.

**Comment by acecampos** [comment]
@wilsonmoura, com base na lista, já fiz os ajustes referentes aos códigos órfãos. O Fi-Admin está liberado, de minha parte.

**Comment by wilsonmoura** [comment]
@acecampos fizemos uma nova conferência de códigos órfãos. Segue relatório:

| descriptor_ui | tree_number | term_string |
| ----------------- | ----------------- | --------------- |
| DDCS060068 | MT1.388.587.014.115 | Abdominal Acupuncture |
| DDCS059930 | MT1.388.587.014.120 | Scalp Acupuncture |
| D011204 | SP3.031.057 | Poverty Areas |
| DDCS032493 | SP4.707.368.630.749.180 | Urban Area |
| D000068316 | SP4.707.368.780.408.459 | Parks, Recreational |
| DDCS051715 | SP4.707.368.780.408.510 | Marine Conservation Area |
| DDCS032489 | SP8.665.152.379.587.314.622 | Disaster Risk Zone |
| DDCS034760 | SP8.665.152.379.587.314.755 | Seismic Zone |
| DDCS034719 | SP8.665.152.379.587.314.866 | Floodplain Zoning |

**Comment by acecampos** [comment]
@wilsonmoura, obrigada! 
Ajustes realizados:

- De MT1.388.587.014.115 => para MT1.388.585.520.014.115
- De MT1.388.587.014.120 => para MT1.388.585.520.014.120
- De SP3.031.057 => para SP8.950.891.235
- De SP4.707.368.630.749.180 => para SP4.707.368.780.204
- De SP4.707.368.780.408.459 => SP4.707.368.780.357.459
- De SP4.707.368.780.408.510 => SP4.707.368.780.357.510
- De SP8.665.152.379.587.314.622 => SP8.570.498.526.628.066.299.304.166
- De SP8.665.152.379.587.314.755 => para SP8.665.152.136.597.480
- De SP8.665.152.379.587.314.866 => para SP8.665.152.136.597.619

**Comment by wilsonmoura** [comment]
@acecampos fizemos outra conferência de códigos órfãos e dessa vez o relatório não registrou nenhuma ocorrência. Sendo assim, creio que conseguimos resolver essa demanda.

**Comment by acecampos** [comment]
@wilsonmoura muito obrigada!
