### ISSUE TITLE
Filtro por status Rascunho não está funcionando

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#138]
Filtro por status Rascunho, testado nos perfis documentalista e editor, não está funcionando corretamente. Está filtrando por LILACS-Express.

Filtros "LILACS-Express", "Todos", "Publicado" e "Recusado" parecem estar funcionando corretamente.

Filtro todos:
![image](https://cloud.githubusercontent.com/assets/18355163/15076876/313d254e-1382-11e6-9467-76c86ee5c9b0.png)

Filtro rascunho:
![image](https://cloud.githubusercontent.com/assets/18355163/15076918/68e9ae54-1382-11e6-8780-66e28899cd80.png)

Filtro LILACS-Express:
![image](https://cloud.githubusercontent.com/assets/18355163/15076947/869c05b4-1382-11e6-9ed8-6695bde69a7a.png)

Filtro Publicado:
![image](https://cloud.githubusercontent.com/assets/18355163/15077017/c82f6d22-1382-11e6-9ad3-78f8f429d9da.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado. Quando possível favor verificar.

Obrigado

**Comment by sarahviola** [comment]
Filtro funcionando.
