### ISSUE TITLE
Reparação de erro causado por apagar dado (es-es)

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1380]
Referência: https://github.com/bireme/Gestao-DeCS/issues/59#issue-1576883530
ID de transporte: D000094783
descritor: paramédico (es-es)

Por favor, Wilson, liberar o campo de edição em es-es cujo conteúdo foi apagado como YY e, por isso, não é permitido editar novamente.
Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do FI-ADMIN.

**Comment by acecampos** [comment]
Validado, @wilsonmoura. Obrigada!
