### ISSUE TITLE
Gerar base ISIS do FI-ADMIN Tesauro

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#1382]

**Comment by lucianaPRB** [comment]
Wilson,
Foram feitas as verificações necessárias no ambiente de produção e não foram encontradas inconsistências.
Obrigada!

**Comment by wilsonmoura** [comment]
@lucianaPRB foi corrigida a inconsistência no termo Iron Deficiency? Favor confirmar para que possamos prosseguir com essa atividade.

**Comment by wilsonmoura** [comment]
@acecampos @lucianaPRB foi corrigida a inconsistência no termo Iron Deficiencies? Favor confirmar para que possamos prosseguir com essa atividade.

**Comment by acecampos** [comment]
@wilsonmoura Sim, foi corrigida. O termo Iron Deficiencies **não** deve apresentar precoord (entry combination). Seu registro deve apresentar somente "previous indexing", de acordo com o MeSH (https://meshb.nlm.nih.gov/record/ui?ui=D000090463).

**Comment by acecampos** [comment]
@wilsonmoura corrigindo: nem "previous indexing" tem no Iron Deficiencies.

**Comment by wilsonmoura** [comment]
## Documentação dos passos para geração da base ISIS do FI-ADMIN Tesauro

No servidor de processamento, executar os comandos abaixo para iniciar o processo de geração da base ISIS:

```
$ cd /bases/dec.000/get_thesaurus/
$ mv wrk_ths_1 wrk_ths_1_YYYYMMDD
$ mkdir wrk_ths_1
$ cd /bases/dec.000/get_thesaurus/tpl/
$ # nohup ./harv_thesaurus.sh 1 &> ../outs/harv_thesaurus.YYYYMMDD.out &
```

**OBS 1:** Antes de executar o carregamento, certificar que os dados do ambiente de testes do Tesauro FI-ADMIN estão atualizados de acordo com o ambiente de trabalho/produção.

**OBS 2:** Após finalizar o processamento, a nova base ISIS vai estar disponível no diretório `/bases/dec.000/get_thesaurus/wrk_ths_1/`
