### ISSUE TITLE
Buscar por status "Migrado" no Fi-Admin/thesaurus

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#1385]
@wilsonmoura, por favor, acrescentar "Migrado" nas opções de seleção por status, conforme ilustrado:
![image](https://user-images.githubusercontent.com/35345406/221569308-968065b5-c07d-4a0f-94a3-4ca37d16ba86.png)
Obrigada!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes no FI-ADMIN.

**Comment by acecampos** [comment]
@wilsonmoura Validado. Obrigada! 
Informação transmitida verbalmente: filtro "Campos" precisa estar selecionado em alguma opção diferente de ---.
