### ISSUE TITLE
Exportação dos registros bibliográficos status "LILACS-Express"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#139]
Exportar todos os registros em formato I2I para alimentar o processo de publicação na LILACS.

Relacionado ao #5

**Comment by viniciusandrade** [comment]
@katia,

Para exportação ID2I dos registros utilizar a seguinte URL:

http://fi-admin.bvsalud.org/api/bibliographic/?status=0&format=isis_id&limit=0

Parâmetros:

* format = isis_id (ID2I)
* status = 0 (somente registros bibliográficos LILACS-Express)
* limit = 0 (todos os registros)

Pode-se utilizar a coleta por faixa de registros utilizando os parâmetros:

* offset = número inicial
* limit = quantidade

**Comment by anakatiacamilo** [comment]
@viniciusandrade,

Campos de não estão no arquivo.id:

Base de dados [04];
Data de publicação [64];
Data de publicação ISO [65];
------
Data de criação [91];
Documentalista [92];
Data de modificação [93];
Versão [899]

Katinha

**Comment by viniciusandrade** [comment]
@anakatiacamilo,

Katinha, os campos foram adicionados na exportação. Os campos 91 e 93 usam o formato do sistema novo, por favor verifique se é possível converter os valores para serem compatíveis com os sistemas antigos.

[]s

**Comment by anakatiacamilo** [comment]
Vini, aparentemente não deve problema
