### ISSUE TITLE
Criar campo Modalidade do evento

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1395]
Criar campo Modalidade do evento: presencial, híbrido ou online

Criar campo controlado com as 3 opções.

Campo obrigatório

**Comment by wilsonmoura** [comment]
@viniciusandrade conforme conversamos, existe uma atividade relacionada com essa demanda: https://github.com/bireme/direve-wp-plugin/issues/39

**Comment by suelisuga** [comment]
@viniciusandrade pf informar onde posso fazer a gestão e tradução do campo. Procurei no Admin e não consegui localizar. Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga as opções para este campo foram informadas na descrição do issue e não foi descrito que era necessário a gestão posterior das opções, desta forma o @wilsonmoura implementou como uma lista fixa com as 3 opções informadas.

Se realmente for necessário gerenciar esta lista será necessário re-implementar o campo com a perda das informações já preenchidas, caso sejam opções pontuais pode solicitar por issue a inclusão de uma nova opção. Favor verificar e informar. Obrigado.

**Comment by suelisuga** [comment]
@viniciusandrade em princípio gostariamos de colocar as traduções. 

Não há intenção de incluir novas opções agora pq penso que as solicitadas atendem às necessidades dos eventos como são realizados hoje.

Considerando desenvolvimentos anteriores, se presumiu que o campo estaria na interface administrativa do FI-Admin para ajustes necessários.
![image](https://github.com/bireme/fi-admin/assets/13105683/f7ad51d9-9f27-4bcc-b13c-16ff7bd745a5)

Seria bom se tivéssemos alguma documentação sobre a forma como o desenvolvimento, processamento e publicação acontece (governança?), pois para não-analistas, isso não é claro. Embora busquemos criar os issues com a informação necessária, nem sempre temos o conhecimento para avaliar essa complexidade e, algumas vezes, o ciclo completo da correção de bugs e implantação de melhorias não se fecha.

Fico no aguardo de instruções.

Obrigada

**Comment by viniciusandrade** [comment]
@suelisuga OK, de acordo ... enquanto não temos esta documentação seria importante informar no issue ou na validação do mesmo esta necessidade.
Para este campo em específico como serão poucos valores acho que não vale a pena mudar agora.
Favor informar por aqui mesmo a tradução adequada para cada opção que estarei ajustando no sistema.

**Comment by suelisuga** [comment]
Segue tradução

Modalidade do evento: presencial, híbrido, online
Modalidad del evento: presencial, híbrido, en linea
Event modality: in-person, hybrid, online

**Comment by suelisuga** [comment]
Colegas,

Inclui nota no sistema FI-Admin informando da criação do novo campo.

Solicito tradução da tabela controlada conforme mensagem anterior.
Para não parar o processo, inclui a msg com a versão em inglês no aviso.

![image](https://github.com/bireme/fi-admin/assets/13105683/f13f5db3-2730-4dec-b830-234c5d381dec)

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga foi realizado a atualização do sistema com as traduções informadas.
