### ISSUE TITLE
fi-admim title Campos title Online resources (NewURL) retirar opcao controle de acesso

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#14]
Não precisamos da opção do campo Controle de acesso (retirar todo o campo).

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
O respectivo campo foi retirado do formulário e ficará como histórico.
