### ISSUE TITLE
ID duplicado no Fi-admin

### ISSUE THREAD

**Issue by amilson18** [bireme/fi-admin#1405]
Solicito por gentileza deletar um dos ID 23231, que foi duplicado por um problema no Fi-admin que estava demorando pra finalizar o registro da revista e quando foi finalizado ficou duplicado, e eu não consigo deletar no meu sistema.

Obrigado

@wilsonmoura

**Comment by wilsonmoura** [comment]
@amilson18 registro deletado conforme solicitado.
