### ISSUE TITLE
Adicionar o Código do Google Analytics 4

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#1411]
Adicionar a linha do GA-4 "G-YFLLB04JBR" relacionado ao GAU (UA-65975016-1)

**Comment by viniciusandrade** [comment]
@marcoslmori código adicionado, favor validar o recebimento dos dados no GA. 

Para este caso não irei manter os dois códigos, somente o GA4.

**Comment by marcoslmori** [comment]
Estranho - muita diferença entre os dois analytics,
