### ISSUE TITLE
Desenvolver procedimento de importação ID2I para LILACS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#142]
Relacionado ao #5 e #82

Implementar para tipo Sas o procedimento de conversão e importação para LILACS gravando o ID do FI-ADMIN para ser utilizado no controle de troca.

**Comment by anakatiacamilo** [comment]
O processo que consome registros LILACS-Express do FI-Admin no formado de id esta no serverofi5:/bases/lilG4/lxp.lil/lxp.fia 

Dados da primeira coleta:
8|Arq. bras. neurocir|33|4|0103-5355|2014
4|Arq. bras. neurocir|34|1|0103-5355|2015
14|Rev. Soc. Bras. Clín. Méd|14|1|1679-1010|2016
