### ISSUE TITLE
Erro no resultado de busca com aplicação de filtro

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#1423]
Com código e perfil  LILACS-Express editor, ao colocar o filtro  de Tipo de registro como "Revista - Artigo" e Status "LILACS-Express", não retorna nada, mas quando tiro o filtro, a busca resulta em 367 registros. Demais perfis retornam a busca corretamente.

![image](https://github.com/bireme/fi-admin/assets/47643830/68c2bf93-4788-4f61-a156-cc33c2ed805c)

![image](https://github.com/bireme/fi-admin/assets/47643830/a943b3c4-f126-4ba0-ba0c-a0cb38889188)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula pesquisa com filtro revisado para esta condição específica (perfil lilacs express), quando possível favor valdar. Obrigado.

**Comment by AngelicaSAPaula** [comment]
Realizei os testes e foi possível realizar a busca corretamente!
