### ISSUE TITLE
Incluir parâmetro offset nas chamadas das APIs dedicadas aos plugins WP (LIS, DirEVE, Multimedia, LeisRef, etc)

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#1429]
Esse parâmetro será usado para excluir os primeiros N itens em cada consulta feita nas APIs dedicadas aos plugins WP.

**Comment by viniciusandrade** [comment]
@wilsonmoura foi implementado o parâmetro **fb** (filter browse) que permite informar a quantidade de ocorrências a serem recuperadas para um determinado filtro, exemplo:

fb=database:50 (irá retornar as 50 primeiras ocorrências do filtro database).

Qualquer dúvida favor entrar em contato. Abraços.

**Comment by wilsonmoura** [comment]
@viniciusandrade validado!

**Comment by wilsonmoura** [comment]
@viniciusandrade favor também incluir parâmetro na API do plugin LeisRef.

**Comment by viniciusandrade** [comment]
@wilsonmoura já foi implementado, exemplo de chamada:

https://fi-admin-api.bvsalud.org/api/leisref/search/?q=saude&fb=act_type:50

**Comment by wilsonmoura** [comment]
7f5edb18ed8efb85b77f68728d1358bdecbeff5b
