### ISSUE TITLE
Lista de tipo de fonte na interface administrativa do FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1430]
Solicito inclusão da lista de tipos de fontes do LIS na interface administrativa do FI-Admin.

Campo no LIS:
![image](https://github.com/bireme/fi-admin/assets/13105683/04069632-eff5-4fb4-b40b-26cd4d0c6616)

Administração do FI-Admin
![image](https://github.com/bireme/fi-admin/assets/13105683/af4a0743-af22-4b65-a3ef-2623124e362c)

Obrigada!

**Comment by viniciusandrade** [comment]
Recurso disponibilizado na interface administrativa do FI-ADMIN.
