### ISSUE TITLE
Serviço do DeCS não abre descritor já selecionado

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1432]
Quando queremos consultar um descritor já selecionado na indexação o registro não está aparecendo. O comportamento normal seria que, ao clicar, o registro completo com qualificadores poderia ser consultado.

![image](https://github.com/bireme/fi-admin/assets/13105683/179f9d70-698e-427b-8b51-7adccc5c1d21)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga só encontrei o erro reportado para a fonte multimídia e realizei a correção. Favor verificar se é isso mesmo ou se o problema ocorre também em outras fontes. 
Obrigado.

**Comment by viniciusandrade** [comment]
Finalizado por não ser informado problema no ajuste implementado.
