### ISSUE TITLE
Tornar o Registro Fonte clicável no registro da analítica

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1437]
Toda vez que quero acessar o registro fonte a partir da analítica preciso pesquisar no FI-Admin pelo Fonte na aba "Todos os registros", porém seria melhor clicar e já acessar esse registro para tornar o processo de revisão mais fluido.

![image](https://github.com/bireme/fi-admin/assets/13105683/e058622b-f10a-45cd-b732-2db116747647)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga ajuste implementado. 

Quando possível favor validar. 

Obrigado.

**Comment by viniciusandrade** [comment]
Finalizado por não ser informado problema no ajuste implementado.
