### ISSUE TITLE
Normalização de campos da SeCS para importação dos dados na Title FI-ADMIN

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#144]
Esta atividade é necessária para ocorrer a migração de fato #143

**Comment by anakatiacamilo** [comment]
Wilson,

Segue a lista:

Sigla==>>	Extenso
AHCI	==>>Arts & Humanities Citation Index
BDENF==>>Base de dados de enfermagem 
NAR	==>>Nutrition Abstracts and Reviews
SCI	==>>Science Citation Index
BBO	==>>Bibliografia Brasileira em Odontologia
PSYCINFO ==>> PSYCINFO
JCR	==>>Journal Citation Reports
ISI ==>>Institute for Scientific Information/Web of Science
CA==>>Chemical Abstracts
IBECS==>>Indice Bibliográfico Español de Ciencias de la Salud
IL==>>Index Medicus Latino Americano
SCOPUS==>> SCOPUS
SCIELO==>>Scientific Electronic Library Online
LATINDEX==>>Sistema Regional de Información en Línea para Revistas Científicas de América Latina, el Caribe, España y Portugal
LL	==>>LILACS
BA	==>>Biological Abstracts
EM	==>>Embase/Excerpta Medica
MEDLINE	 ==>>MEDLINE
PUBMED	==>> PUBMED
IM	==>>Index Medicus

Katinha
