### ISSUE TITLE
Alterar cor do status Migrado do registros bibliográficos no FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1440]
Solicito alteração das cor do status Migrado dos registros bibliográficos no FI-Admin:

Migrado => vermelho  => outra cor (azul escuro, lilás, etc)

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga ajuste realizado, é necessário realizar um SHIFT+REFRESH no navegador para atualizar as cores

![image](https://github.com/bireme/fi-admin/assets/349287/046706ae-588d-4f79-8951-847c7f352cdd)
