### ISSUE TITLE
Incluir o campo Status do Registro na API - formato ISIS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#1443]
Solicito inclusão do Status do Registro [775] na API do FI-Admin, formato ISIS.

Essa solicitação gera pendência para continuidade do chamado 1000: https://github.com/bireme/db-processing/issues/1000

![image](https://github.com/bireme/fi-admin/assets/13105683/b362cc18-a3ba-472a-abc3-e374a77931ee)

Versão XML

<status type="integer">3</status>

![image](https://github.com/bireme/fi-admin/assets/13105683/c5c4c91a-7dd9-485d-a905-90b057af59bd)

Muito obrigada!

**Comment by viniciusandrade** [comment]
Campo adicionado no formato ISIS.
Exemplo:
https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=1284287

**Comment by viniciusandrade** [comment]
@botturam campo adicionado na API para o formato ISIS.
