### ISSUE TITLE
 Thesaurus API - IndexError: list index out of range

### ISSUE THREAD

**Issue by apendindan** [bireme/fi-admin#1445]
@viniciusandrade 

A API de produção e de teste estão dando o problema "list index out of range" quando é pedido um número de dados maior do que 77. Segue abaixo as mensagens do Wilson para uma possível solução:

"Encontrei a solução aqui
https://github.com/bireme/fi-admin/pull/1329/commits/0968751d9734779d380b457831d7a2b00180f906
Aplicar a mesma solução no arquivo thesaurus_api_qualif.py"

"Na verdade, pede pra ele olhar o arquivo thesaurus_api_desc.py e aplicar a mesma solução
Os ajustes foram feitos na linha 107 desse arquivo
Eu tinha colocado uma mensagem de retorno com o erro "invalid request"
Mas depois eu vi que não funcionou bem
Então eu faço a validação e peço pra retornar o objeto "bundle"
Ou seja, é só trocar a linha 104 do arquivo thesaurus_api_qualif.py por:
if id_concept:
    id_concept = id_concept[0].get('id')
else:
    return bundle
Esse ajuste vai resolver o problema"

**Comment by viniciusandrade** [comment]
@apendindan ajuste aplicado nos ambiente de teste e produção. 

Teste realizado usando seguinte url:
https://fi-admin-api.bvsalud.org/api/qualifiers/thesaurus/?format=json&ths=1&limit=20&offset=70
