### ISSUE TITLE
Erro no DeCS no Fi-admin

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-admin#1456]
Mensagem recebida hoje (01/07/24)  da BVS SMS-SP > Desde sexta-feira estamos tendo problemas ao utilizar o DeCS no FI-Admin. Hoje, ao tentar acessar o mesmo, apareceu essa mensagem como está na imagem anexada.

![Captura de tela 2024-07-01 104049](https://github.com/bireme/fi-admin/assets/13439949/5ceac925-6dec-42e6-a4b2-3bbecfb84bbc)

**Comment by viniciusandrade** [comment]
Sistema revisado, favor solicitar novo teste. Obrigado.

**Comment by viniciusandrade** [comment]
Obrigado por informar. Qualquer coisa pode re-abrir este issue informando o termo que foi buscado.
