### ISSUE TITLE
Na API da title criar um parâmetro de filtro no campo thematic_area

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1459]
No projeto do pluing do Portal de Revista https://github.com/bireme/portalrev-wp-plugin, precisamos de um parâmetro novo na API para fazermos o filtro inicial e vamos usa o campo thematic_area da tabela title_title.
Imagino que seria bom incluir este mesmo campo no índice do MySQL do FI-DMIN.

**Comment by viniciusandrade** [comment]
@gabrielszz e @anakatiacamilo filtro disponível no endpoint de pesquisa.

Exemplo de chamada:

https://fi-admin-api.bvsalud.org/api/title/search/?q=saude&fq=thematic_area:"CIENCIAS%20BIOLOGICAS"

Note que o recomendado é usar o parâmetro **fq** (filter query) para usar este filtro ... este mesmo tipo de chamada já esta implementado no plugin de centros, qualquer dúvida favor entrar em contato.

**Comment by anakatiacamilo** [comment]
Obrigada @viniciusandrade
