### ISSUE TITLE
Campos necessários para a primeira página do Plugin do Portal de Revista 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1460]
No projeto do pluing do Portal de Revista https://github.com/bireme/portalrev-wp-plugin, precisamos dos seguintes campos:

  [title], [section]: [subtitle] - [section_title] Vol. [initial_volume], nº.[initial_number] ([initial_date]), Vol. [final_volume], nº.[final_number] ([final_date]) - [city] ISSN [issn]
  Título Abreviado: [shortened_title]
  País: [country]
  Publicação de: [responsibility_mention]

  Formato eletrônico [online/value^b]
  Mais detalhes [id]
  
https://fi-admin-api.bvsalud.org/api/title/22950/

![image](https://github.com/user-attachments/assets/f33c835b-f7ea-4536-a1d7-e7486bacb9bc)

**Comment by anakatiacamilo** [comment]
Precisamos deste campos para os cluster 

status
text_language
online
index_range

collection que será migrado

**Comment by viniciusandrade** [comment]
@anakatiacamilo os campos foram adicionados na saída do método de search da API exceto pelos campos:
**online** e **index_range** pois se referem a tabelas relacionadas com vários campos cada um então precisamos definir melhor como exportar estes dados.

**Comment by viniciusandrade** [comment]
@anakatiacamilo estou encerrando este issue porque os campos adicionais foram solicitados também no #1461.
