### ISSUE TITLE
Campos para a busca no portal de Revista

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1461]
No projeto do pluing do Portal de Revista https://github.com/bireme/portalrev-wp-plugin, precisamos inicialmente dos campos para busca:

- title;
- subtitle;
- shortened_title;
- issn;
- country/value

https://fi-admin-api.bvsalud.org/api/title/search/?count=1&f=id:title.title.22948

**Comment by viniciusandrade** [comment]
Pessoal, campos adicionados e disponíveis no endpoint de search.

**Comment by anakatiacamilo** [comment]
@viniciusandrade, precisamos dos campos abaixo para fazer o cluster, por favor, incluir este campos na busca.

status
text_language
online
index_range



Grata

**Comment by anakatiacamilo** [comment]
@viniciusandrade, a @alvesmarilda me alertou que o Cluster de País de Publicação não esta bom e estou em duvida quanto ao elemento que devemos indexar.

No exemplo https://fi-admin-api.bvsalud.org/api/title/search/?count=1&f=id:title.title.22948 no FI-ADMIN este registros foi publicado no Reino Unido então imagino que  devemos mudar para este elemento 

<response type="hash">
<docs type="list">
<object type="hash">
<_version_ type="integer">1809953925197987840</_version_>
<country>en^United kingdom|pt-br^Reino Unido|es^Reino Unido</country>

Mas tem um outro elemento neste XML 
<publication_country type="list"/>
que neste exemplo não tem conteúdo, por isto a duvida.

**Comment by anakatiacamilo** [comment]
Por favor, incluir o título MEDLINE abreviado na indíce de busca, por causa dos títulos que vem direto do iaHx 

medline_shortened_title

**Comment by viniciusandrade** [comment]
- Campo **medline_shortened_title** adicionado para recuperação e também pode eventualmente ser apresentado
- Campo **text_language** disponível como filtro no campo **language**
- Campo **status** disponível como filtro

Obs: o retorno da API ainda esta filtrando por revistas com status 1 - Corrente. Estarei realizando a atualização da API para remove este filtro e informo novamente aqui.

**Comment by viniciusandrade** [comment]
Removido filtro do método de pesquisa da API e contabilizado no cluster de status as revistas com status 1 (corrente) = 14878 e 0 (não corrente) = 6501 para um total de 21379 títulos indexados.

**Comment by anakatiacamilo** [comment]
Obrigada Vini
