### ISSUE TITLE
Registro  com Status publicados, não aparecem na busca de pesquisa no portal regional da BVS

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#1463]
Bom dia!

Por favor, verificar os registros abaixo;

Registros com Status publicados no sistema FI-Admin., não aparecem na busca de pesquisa no portal regional da BVS
Não são recuperaveis por título do documento "Boletim informativo da Área Técnica de Alimentação, Nutrição, Atividade Física e Câncer" e nem por título da Série "INCA boletim Informativo"

![image](https://github.com/user-attachments/assets/c3411fc9-3f36-4bc2-9925-dfa5c01a880f)

https://fi-admin.bvsalud.org/bibliographic/edit-source/**1537699**

**Comment by Andreanaslund** [comment]
Olá @marcoslmori e @botturam temos alguma novidade sobre este problema com a BVS INCA?

**Comment by botturam** [comment]
@silvalais @suelisuga a base INCA não faz parte do Portal Regional. Ela aparece apenas na IAHx-ControleCancer. 

Muitos registros do INCA são LILACS, portanto aparecem no Portal Regional, mas o doc id:biblio-1570336, por exemplo, que é apenas INCA, aparece na IAHx-ControleCancer.

**Comment by silvalais** [comment]
Marcelo, 
Muito Obrigada
Não estava aparecendo no portal de pesquisa do PrevCan: https://pesquisa.bvsalud.org/**controlecancer**
Agora está ok

<img width="644" alt="image" src="https://github.com/user-attachments/assets/5f7cd4e7-1a57-4930-a823-6a43bcc9ac34">

**Comment by botturam** [comment]
Perfeito. Concluído.
