### ISSUE TITLE
Alterar API da title para receber o parâmetro fb

### ISSUE THREAD

**Issue by gabrielszz** [bireme/fi-admin#1464]
Alterar API da title para receber o parâmetro fb

url para teste

https://[fi-admin-api.bvsalud.org/api/title/search/?fb=country:3](https://fi-admin-api.bvsalud.org/api/title/search/?fb=country:3)

será utilizado também para descriptor_filter e language além de country.

**Comment by viniciusandrade** [comment]
@gabrielszz, ajuste realizado, favor realizar o teste.

https://github.com/bireme/fi-admin/commit/d19b30e7b3ffcdd6032998e336f662bdf0eef8d7

**Comment by gabrielszz** [comment]
@viniciusandrade Está funcionando perfeitamente.
