### ISSUE TITLE
Ajusta no api da title 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1465]
Por favor, na api da title alterar o elemento index_range o valor do index poderia trocar do code para o name ?

https://fi-admin-api.bvsalud.org/api/title/24581/

<img width="322" alt="image" src="https://github.com/user-attachments/assets/4a79f865-c7fa-41e6-9682-41c9921f60c1">

<img width="542" alt="image" src="https://github.com/user-attachments/assets/47c7087a-5cb4-4141-8e05-bdce46dabcbf">

**Comment by viniciusandrade** [comment]
@anakatiacamilo verifiquei no código e achei arriscado trocar o código pelo nome pois eu não saberia identificar se este campo esta sendo usado em algum outro lugar. Posso adicionar um subcampo (^n) com o valor do camp nome?

**Comment by anakatiacamilo** [comment]
@viniciusandrade, Sim seria perfeito

**Comment by viniciusandrade** [comment]
@anakatiacamilo, @gabrielszz ajuste disponível na API em produção.
