### ISSUE TITLE
TITLE - API Cobertura de indexação

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#1467]
Por favor, 

Criar o elemento indexed_database de buscar(para o cluster) na API da TITLE , se presente index.indexer_cc_code  indexar o index.index_code.name

Grata

**Comment by viniciusandrade** [comment]
@anakatiacamilo e @gabrielszz cluster disponível na API de busca da TITLE, favor quando possível validar. Obrigado.

![image](https://github.com/user-attachments/assets/7a004613-3541-4850-ae38-1193600bde1d)

**Comment by gabrielszz** [comment]
@viniciusandrade e @anakatiacamilo cluster validado e adicionado, obrigado
