### ISSUE TITLE
Realizar exportação Title FI-ADMIN para Title ISIS (SeCS)

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#147]
Necessário garantir a continuidade do processo de atualização dos sistemas atuais que dependem da base title da SeCS.

**Comment by anakatiacamilo** [comment]
- Verificar com o Marcelo o que impacta no processamento já que os dados da title virão com a informação da NewRUL com a mudança do campo de observação [880] estará em subcampos do campo Recursos online [999] e não mais separado - compatibilização com os subcampos do idioma.
- Verificar impacto no Portal de Revista

URL para coleta de 20 em 20, verificar parâmetro para aumentar a quantidade.
http://fi-admin.teste.bvsalud.org/api/title/?format=isis_id
URL para fazer a coleta em json por ID [30]
http://fi-admin.teste.bvsalud.org/api/title/6490/?format=json

**Comment by wilsonmoura** [comment]
Em fase de validação pelo OFI.

**Comment by anakatiacamilo** [comment]
Ontem finalizamos a coleta e o processamento da title até a publicação do portal de revista e a atualização das bases auxiliares.
