### ISSUE TITLE
Expor publicamente com token a API dos dados da title do portal de revistas

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#1471]
Por favor, expor publicamente com token a API do portalrev para ser utilizado no projeto TMGL no front end com desenvolvimento em REACT

**Comment by viniciusandrade** [comment]
@marcoslmori e @jeffersonalopes API da fonte de informação publicada e documentação básica disponível em:

https://docs.api.bvsalud.org/?urls.primaryName=Journals%20on%20Health%20Sciences

**Comment by suelisuga** [comment]
Após reunião com @Jefferson entendi que está implantado.
