### ISSUE TITLE
[TMGL] Expor publicamente com token a API do LIS

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#1475]
Por favor, expor publicamente com token a API do LIS para ser utilizado no projeto TMGL no front end com desenvolvimento em REACT

**Comment by viniciusandrade** [comment]
@marcoslmori e @jeffersonalopes API da fonte de informação publicada e documentação básica disponível em:

https://docs.api.bvsalud.org/?urls.primaryName=Web%20resources%20(LIS)

**Comment by suelisuga** [comment]
Após reunião com @jeffersonalopes entendi que está implantado.
