### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Não Convencional"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#148]
Relacionado ao backlog #76 e #78 

Combinações previstas na metodologia:

- [x] Tipo de literatura "N" / nível de tratamento "m"
- [x] Tipo de literatura "NC" / nível de tratamento "m"
- [x] Tipo de literatura "NC" / nível de tratamento "am"
- [x] Tipo de literatura "N" / nível de tratamento "am"
- [x] Tipo de literatura "NP" / nível de tratamento "m"
- [x] Tipo de literatura "NP" / nível de tratamento "am"
- [ ] Tipo de literatura "N" / nível de tratamento "mc"

**Comment by viniciusandrade** [comment]
O tipo de registro Tipo de literatura "N" / nível de tratamento "mc" não será implementado pois não foi encontrado formulário de entrada no LILDBIWeb. 

Foi criado o issue #222  para verificar este caso.

**Comment by viniciusandrade** [comment]
@sarahviola 

Quando possível por favor realizar os testes para estes tipos de registros.

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade 

Não aparece a aba Indexação em registros tipo "Não convencional" nível fonte. Nas analíticas está aparecendo.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado no formulário de fonte.

[]s

**Comment by sarahviola** [comment]
ok.
