### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Monografia"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#149]
Relacionado ao backlog #74 e #78 

Combinações previstas na metodologia:

- [x] Tipo de literatura "M" / nível de tratamento "m"
- [x] Tipo de literatura "M" / nível de tratamento "am"
- [x] Tipo de literatura "MC" / nível de tratamento "m"
- [x] Tipo de literatura "MC" / nível de tratamento "am"
- [x] Tipo de literatura "MP" / nível de tratamento "m"
- [x] Tipo de literatura "MP" / nível de tratamento "am"
- [x] Tipo de literatura "MCP" / nível de tratamento "am"
- [x] Tipo de literatura "MCP" / nível de tratamento "m"

**Comment by viniciusandrade** [comment]
@sarahviola 

Conforme conversamos atualizei o ambiente de testes com a opção de criação de registros bibliográficos para o tipo **Monografia** (tipo "M")  para fonte e analíticas, bem como as combinações acima checadas (Evento/Projeto).

Por favor quando possível realizar os testes de entrada de dados e validações para estes tipos.

Obrigado

**Comment by sarahviola** [comment]
![image](https://cloud.githubusercontent.com/assets/18355163/15826411/c710d354-2bdd-11e6-8a1a-daf04c29e482.png)

**M** vs. **Mm**
Confirmar com @anakatiacamilo 
Creio que registros **Fonte de monografia** (M) devem ser salvos como **Mm**, com o nível bibliográfico m, porque eles também são incluídos na LILACS no nível monográfico.

(Só incluímos na LILACS Fonte de seriados (S) quando em nível analítico (Sas), por isso Fonte de seriado é salvo somente como S, sem o nível bibliográfico).

**Comment by sarahviola** [comment]
Analítica de monográfico (**Mam**) - ok

![image](https://cloud.githubusercontent.com/assets/18355163/15826867/9fe0e574-2bdf-11e6-9769-3175e1fa6cc3.png)

**Comment by sarahviola** [comment]
MCm - gravado como MC
MPm - gravado como MP
MCPm - gravado como MCP

**Comment by sarahviola** [comment]
**MCam** - ok
**MPam** - ok
**MCPam** - ok

----

![image](https://cloud.githubusercontent.com/assets/18355163/15832504/eb37a472-2bf8-11e6-8aeb-94d7535a2a1b.png)

![image](https://cloud.githubusercontent.com/assets/18355163/15832471/c02f9352-2bf8-11e6-8085-cb4be8854c0a.png)

![image](https://cloud.githubusercontent.com/assets/18355163/15832433/99ee311c-2bf8-11e6-84bd-afcdcd608650.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

OK, realizei a revisão da gravação para os registros do tipo **Mm**, conforme comentei é necessário avaliar se teve efeito colateral em algum outro tipo dos mapeados acima.

Quando possível favor verificar.

Obrigado

**Comment by sarahviola** [comment]
Mm - ok
MCm - ok
MCPm - ok
MPm - ok

**Comment by sarahviola** [comment]
Depois das alterações para gravar registros no nível monográfico **Mm** corretamente, testei novamente os registros no nível analítico e continuam sendo salvos corretamente.
**Mam** - ok
**MCam** - ok
**MPam** - ok
**MCPam** - ok
