### ISSUE TITLE
Incluir novos campos no modelo de dados do módulo Title

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#153]
Tarefa ligada à issue #146

**Comment by anakatiacamilo** [comment]
Wilson, foi criando somente dois subcampos o ^v de volume e ^n de número do campo Título Paralelo [230] a documentação esta na wiki
http://wiki.bireme.org/pt/index.php/Campos_da_base_Title#T.C3.ADtulo_paralelo_.5B230.5D
