### ISSUE TITLE
Exibir no DeCS do FI-Admin campos do DeCS utilizados para indexação

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#156]
Exibir no DeCS do FI-Admin campos do DeCS utilizados para indexação, como:
- Veja também termos em:
- Precoord: 
- Relacionados:

Descritor Medula Espinhal no DeCS do fi-admin:
![image](https://cloud.githubusercontent.com/assets/18355163/15439035/6b8ac5b6-1ea5-11e6-98df-d1d9ac9b5edc.png)

Descritor Medula Espinhal na página do DeCS:
![image](https://cloud.githubusercontent.com/assets/18355163/15439107/df08b3c2-1ea5-11e6-8d25-d139c35a5421.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustes realizados. Quando possível favor validar.

[]s

**Comment by sarahviola** [comment]
ok.
![image](https://cloud.githubusercontent.com/assets/18355163/17595098/18b2ca9c-5fc2-11e6-9e3f-10bd5d1d3120.png)
