### ISSUE TITLE
Validação campo endereço eletrônico e paginação

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#159]
@sueli,

Conforme verificamos a metodologia indica que caso seja informado paginação o campo de meio eletrônico passa a ser opcional.

A proposta é alterar esta validação para sempre que for um documento do tipo "Sas" exigir a informação de meio eletrônico ou upload de documentos e também remover a validação.

Favor informar se podemos realizar esta alteração.

Relacionado ao #158

**Comment by suelisuga** [comment]
Vinícius,

Conforme decisão tomada na reunião de acompanhamento de sprint do dia 20/05/16, confirmo que registros LILACS Sas (Artigos de Revistas) devem obrigatoriamente incluir link ou PDF para texto completo no campo [08], independente de inclusão de paginação do artigo.

A medida visa corrigir desvio de publicação de artigos LILACS-Express Editor sem a carga de PDF de texto completo e torna efetiva a adesão de toda Rede LILACS e BVS à Declaração de Salvador sobre o acesso aberto [(2005)](http://www.icml9.org/public/documents/pdf/pt/Dcl-Salvador-AcessoAberto-pt.pdf ) e a Recomendação sobre Acesso Aberto e Conteúdo Online na LILACS [(2012).](http://metodologia.lilacs.bvsalud.org/php/level.php?lang=pt&component=74&item=65).

Abraços,
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga,

Implementado.

@sarahviola.

Quando possível favor validar.

Obrigado.

**Comment by sarahviola** [comment]
ok. Sas exige o preenchimento do campo de endereço eletrônico com URL ou envio de PDF para status que não seja rascunho.
