### ISSUE TITLE
fi-admin title formulario

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#16]
Precisamos que  no formulário ao inserir um novo  registro o numero ID  ou MFN seja inserido automaticamente e seja visível , pois usamos esse mesmo número para o campo 37 Numero Secs quando necessário.

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
O ID do registro agora aparece destacado sobre as abas do formulário após gravar o registro pela primeira vez. O valor desse campo é preenchido automaticamente com o valor da sua respectiva chave primária (PK).
