### ISSUE TITLE
Validação campos endereço eletrônico e paginação com tipo de registro

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#160]
@sueli,

A validação atual da metodologia para os campos de página e endereço eletrônico leva em consideração a seguinte condição:

- Se o tipo de registro for **a, c, d, e, f, t**  e o atributo **a** for  **cd-rom** ou **disquete** o sistema permitirá o registro de um registro sem informação no campo de páginas ou endereço eletrônico.

Favor informar se devemos ajustar esta validação para tornar a validação levando em consideração a preferência por registros com acesso ao texto completo.

Relacionado ao #158

**Comment by suelisuga** [comment]
Vinícius,

Considerando que os últimos documentos dessa natureza datam de 2004 e que essas mídias estão em desuso, penso que é desnecessária a manutenção dessa regra, tonando impossível a descrição desse tipo de documento em qualquer tipo de literatura em LILACS.

Abraços,
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga,

OK. Para os documentos que não forem **Sas** é feita a validação de obrigatório para os campos endereço eletrônico ou paginação.

@sarahviola,

Quando realizar teste para verificar se esta OK.

Obrigado.

**Comment by sarahviola** [comment]
Ok para **Sas**.

Creio que para os outros tipos de documento é só não criar exceção para disquete ou cd-rom.
