### ISSUE TITLE
Criar uma tabela de controle para o campo cobertura de indexação no subcampo de base ^*

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#164]
Por favor, criar uma tabela de controle para este campo.

**Comment by wilsonmoura** [comment]
Criar tabela com base nos valores da lista documentada na issue #144

**Comment by wilsonmoura** [comment]
- [ ] Incluir tabela no modelo de dados
- [ ] Atualizar o procedimento de exportação ID2I
