### ISSUE TITLE
Preencher campo ISSN automáticamente ao selecionar título da revista

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#165]
Carregar a informação do ISSN quando o usuário selecionar o título da lista.

* O campo ISSN é um campo oculto para o perfil editor LILACS-Express e um campo livre para os demais perfis.

**Comment by viniciusandrade** [comment]
@sarahviola 

Quando possível favor realizar testes. A Katinha identificou que os registros LLXP estavam vindo sem o campo ISSN.  

Eu alterei para carregar esta informação baseado no título selecionado para todos os perfis.

**Comment by sarahviola** [comment]
Preenchimento automático no para perfis documentalista e editor funcionando corretamente. Ao selecionar os títulos, o campo de ISSN é preenchido com o ISSN do título selecionado.

Editei, utilizando meu usuário com perfil editor, os quatro registros Fonte já incluídos por usuários LLXP para gravar o ISSN nos registros.

Assim que algum dos llxp incluir um registro Fonte novo, vou verificar se está vindo com ISSN preenchido corretamente.

**Comment by sarahviola** [comment]
Preenchimento automático do ISSN em registros criados pelo perfil **llxp** também ok.
