### ISSUE TITLE
Validação do campo tipo de periódico

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#167]
@sueli,

O campo **tipo de periódico [113]** possui a seguinte validação:

Caso o campo tipo de de registro [09] contenha 'a' e o campo nivel de tratamento [06] contenha  'as' e o registro for LILACS:
- caso o tipo de periódico [113] = 'u'  e o campo 450 da Title NÃO CONTER o texto 'Sep' então ele mostra a seguinte mensagem de erro:
  **Se Título[30] é LILACS, o Tipo de Periódico[113] deve ser Revista(p) e não Separata(u)**
- caso tipo de periódico [113] = 'p' E campo 450 da Title CONTER o texto 'Sep' então ele mostra a seguinte mensagem de erro:
  **Se TÍtulo[30] não é LILACS, o Tipo de Periódico[113] deve ser Separata(u) e não Revista(p)**

Eu e a Katinha não conseguimos identificar se é importante manter esta regra uma vez que na nossa TITLE no campo 450 não existe nenhuma ocorrência do texto 'Sep' no campo 450.

Caso seja necessário manter vou precisar sempre consultar a TITLE do FI-ADMIN para este campo mas antes de implementar gostaria de validar se esta regra continua importante.

Relacionado ao #158

**Comment by suelisuga** [comment]
Entendo que podemos encerrar esse chamado pois o campo [450] - Cobertura de indexação da TITLE realmente não traz essa informação.

Abrirei outro chamado informando o comportamento esperado.

Obrigada!

Sueli

**Comment by suelisuga** [comment]
novo issue aberto: #658
