### ISSUE TITLE
Incluir na tabela de bases de dados de ensaios clínicos o REBEC

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#168]
Incluir no campo "Registro do Ensaio Clínico", subcampo "Base de dados" o ReBEC:

ReBEC - Registro Brasileiro de Ensaios Clínicos

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga 

Esta lista esta disponível para administração através do módulo Django Admin do sistema na opção **Auxiliary codes** e informando no campo _Nome do campo_ a informação **clinical_trial_database**.

Qualquer dúvida favor informar.

**Comment by sarahviola** [comment]
@viniciusandrade 

Inclui o ReBEC na lista, mas ainda não apareceu no sistema. Desloguei, loguei de novo, fechei e abri o navegador e não aparece.
Você precisa atualizar algo no ambiente, assim como foi feito em outros campos?

**Comment by viniciusandrade** [comment]
@sarahviola 

Sim, foi necessário reiniciar o sistema para o novo valor ficar disponível. 

Sempre que for atualizado alguma tabela auxiliar por favor me avise para que eu possa efetuar este processo, infelizmente não sei porque este processo não é automático.

[]s

**Comment by sarahviola** [comment]
Agora está certo!
Obrigada.

![image](https://cloud.githubusercontent.com/assets/18355163/15721623/23610362-2810-11e6-8b62-aa88faf5799a.png)
