### ISSUE TITLE
Fi-admin title campo publish e campo data inicial

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#17]
O campo Publish Status tem que esta vinculado aos Campos (Data Inicial Data Final), ou seja caso um título seja corrente tem que ser informado o campo Data Inicial , e caso um título seja descontinuado tem que informar o campo Data Final. Esses campos tem quer esta vinculado obrigatorio

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
Os campos foram vinculados através das validações especificadas.
