### ISSUE TITLE
Habilitar botão "Publicar como LILACS-Express" somente após preenchimento de campos obrigatórios

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#170]
Ao realizar testes tentei clicar no botão "Publicar como LILACS-Express" antes de preencher campos obrigatórios e perdi todo o preenchimento realizado.
Considerando que os dados que perdi foram os de autoria e afiliação dos autores, perdi muita coisa...

É possível disponibilizar/habilitar esse botão somente após o registro ter os campos obrigatórios preenchidos?

Obrigada! 
Sueli M Yano Suga

**Comment by viniciusandrade** [comment]
@sarahviola 

Não consegui reproduzir este problema mencionado pela Sueli de perda dos dados digitados. 

Acho que este erro estava relacionado com o #187 que foi resolvido.

Quando possível poderia verificar se agora esta OK?

[]s

**Comment by sarahviola** [comment]
Com a correção do problema reportado #187 esse também está resolvido.
