### ISSUE TITLE
Mensagem de erro do Autor institucional

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#172]
No autor institucional, ao digitar BIREME e não incluir nenhuma indicacao de responsablidade, recebi a mensagem abaixo:
Autor 1:Grau de responsabilidade incompatível com LILACS

Não consegui identificar o erro.

Obrigada
Sueli

**Comment by sarahviola** [comment]
@viniciusandrade 

Grau de responsabilidade não deve ser obrigatório para Autor Institucional (assim como não é para autor pessoal).

**Comment by viniciusandrade** [comment]
@sarahviola,

Correção realizada. Quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
ok, grau de responsabilidade de autor institucional não obrigatório.
