### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Monografia Pertencente a uma Coleção" 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#175]
- [x] Tipo de literatura "M" / nível de tratamento "mc"
- [x] Tipo de literatura "M" / nível de tratamento "amc"
- [x] Tipo de literatura "MC" / nível de tratamento "mc"
- [x] Tipo de literatura "MC" / nível de tratamento "amc"
- [x] Tipo de literatura "MP" / nível de tratamento "mc"
- [x] Tipo de literatura "MP" / nível de tratamento "amc"
- [x] Tipo de literatura "MCP" / nível de tratamento "amc"

Relacionado ao backlog #74 e #78

**Comment by viniciusandrade** [comment]
@sarahviola,

O formulário para a entrada de dados deste tipo de registro esta disponível para verificação no ambiente de testes.

Favor verificar se os campos estão corretos no form, a validação e também se as combinações acima são gravadas corretamente nos registros fonte e analítica.

[]s

**Comment by sarahviola** [comment]
ok:
Mmc
MPmc
MCPmc
MCmc

Faltam checar analíticas.

**Comment by sarahviola** [comment]
Sobre os registros Fonte de Monografia Pertencente a uma Coleção, na lista de registros é exibido o _título do nível coleção_ (antiga tag 25). 
![image](https://cloud.githubusercontent.com/assets/18355163/16925005/7a97a4e4-4cf8-11e6-8329-461b2384b792.png)

Para melhor identificação do documento, **exibir o título nível monográfico (antiga tag 18)**. 
![image](https://cloud.githubusercontent.com/assets/18355163/16925037/a985888e-4cf8-11e6-9337-977ef99b790c.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

OK. Alterei na listagem para mostrar exibir o título monográfico.

**Comment by sarahviola** [comment]
Analíticas ok.
 Tipo de literatura "M" / nível de tratamento "amc" >> ok
 Tipo de literatura "MC" / nível de tratamento "amc" >> ok
 Tipo de literatura "MP" / nível de tratamento "amc" >> ok
 Tipo de literatura "MCP" / nível de tratamento "amc" >> ok
