### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Coleção de Monografias"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#176]
- [x] Tipo de literatura "M" / nível de tratamento "c"

Relacionado ao backlog #74 e #78

**Comment by viniciusandrade** [comment]
@sarahviola,

Quando possível por favor verificar a entrada de dados para este tipo de registro.

Obrigado.

**Comment by sarahviola** [comment]
Comparando com a planilha de entrada de dados do LILDBI-Web: 

Retirar os campos:
- Páginas
- Volume

Incluir: 
- Número Total de Volumes [27]

**Comment by sarahviola** [comment]
@viniciusandrade ,

Vi que as tags de autores e títulos estão como _nome_do_campo__**monographic**, mas acho que deveriam ser _nome_do_campo__**collection** porque registros de outros tipos (vi em Mmc) tem campos de autor (pessoal e institucional) e título (título e título traduzido para inglês) nos **níveis monográficos e coleção simultaneamente**.


Exemplo um registro Mmc na LILACS que tem simultaneamente:
- Título (nível monográfico) [18] e Título nível coleção [25]
- Autor institucional (nível monográfico) [17] e Autor institucional (nível coleção) [24]

![image](https://cloud.githubusercontent.com/assets/18355163/16097004/ee59c7ea-3321-11e6-9edc-3774d6fd2606.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Você esta certíssima. Obrigado por ter inspecionado a página e visto que as tags estavam erradas. 

Refiz o formulário usando os campos referentes ao nível de coleção. Quando possível favor realizar nova verificação.

Obrigado.

**Comment by sarahviola** [comment]
Agora está ok.
