### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Tese/Dissertação"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#177]
- [x] Tipo de literatura "T" / nível de tratamento "m"
- [x] Tipo de literatura "T" / nível de tratamento "am"

Relacionado ao backlog #75 e #78

**Comment by viniciusandrade** [comment]
@sarahviola 

Entrada de dados para fonte e analítica de Tese/Dissertação disponível no ambiente de testes. Quando possível favor realizar testes.

Obrigado

**Comment by sarahviola** [comment]
Tipo **Tm** ok.

**Comment by sarahviola** [comment]
Teses nível analítico (**Tam**) também ok
