### ISSUE TITLE
Implementar formulário de entrada de dados e validação para tipo "Tese, Dissertação pertencente a uma série monográfica"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#178]
- [x] Tipo de literatura "TS" / nível de tratamento "ms"
- [x] Tipo de literatura "TS" / nível de tratamento "ams"

Relacinado ao backlog #75 e #78

**Comment by viniciusandrade** [comment]
@sarahviola,

Quando possível favor realizar a validação da entrada deste tipo de registro.

Obrigado.

**Comment by sarahviola** [comment]
Em **TSms** corrigir obrigatoriedade dos campos:
- volume ou número: não obrigatório
- Título (nível série) [30]: deveria ser obrigatório.

**Comment by viniciusandrade** [comment]
Ajustes realizados.

**Comment by sarahviola** [comment]
Sobre o formulário de entrada de dados de **TSams**, uma observação: 

Ao registrar a analítica de Tese pertencente a série monográfica (TSams), o LILDBI-Web exibe vários campos dos níveis Série e Monográfico sem possibilidade de edição. O FI-Admin exibe apenas título nível monográfico. 

Exibir todos pode ser cansativo, mas por outro lado pode ajudar o documentalista a se localizar ou de alguma forma. Não sei qual a melhor opção, então apenas estou registrando que existe a diferença. 

![image](https://cloud.githubusercontent.com/assets/18355163/16458646/35b3e420-3df6-11e6-95b0-c674a1fe6dfc.png)
![image](https://cloud.githubusercontent.com/assets/18355163/16458687/5b332c60-3df6-11e6-8e1f-c07b76485935.png)

**Comment by sarahviola** [comment]
Em analíticas de tese pertencente a série monográfica (TSams), assim como em analíticas de teses (Tam), o LILDBI não faz nenhuma validação na afiliação do autor, sendo possível incluir ou não afiliação no campo de Autor. 
Existe validação para não preencher afiliação no campo de Autor apenas em nível monográfico (Tm e TSms)

O FI-Admin exige que a afiliação não seja preenchida no campo de autor tanto no nível monográfico como no analítico.

**Comment by sarahviola** [comment]
@viniciusandrade 
Validação dos obrigatórios para **TSms** ok.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustei o form para apresentar título e autor do nível de série e monográfico e também alterei a validação da afiliação para não aplicar validação em analíticas.

Quando possível favor validar.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

No formulário da analítica, na parte da visualização dos dados incluídos no registro fonte, onde deveria ser exibido o título nível série é exibido novamente o título nível monográfico. 

registro fonte: 
![image](https://cloud.githubusercontent.com/assets/18355163/16527317/8493648e-3f8c-11e6-9eae-d56b47aa9b27.png)

registro analítico:
![image](https://cloud.githubusercontent.com/assets/18355163/16527330/9a6bb7f2-3f8c-11e6-9872-47977af3531f.png)

**Comment by viniciusandrade** [comment]
OK, realizei novo ajuste. Quando possível favor validar.

[]s

**Comment by sarahviola** [comment]
ok.
