### ISSUE TITLE
Desenvolver procedimento de comparação do ID2I exportado pelo FI-ADMIN com o ID2I da LILACS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#179]
O objetivo do prrocedimento é garantir que não ocorra perda de dados na migração da LILACS para o FI-ADMIN.

Realizar o teste utilizando os registros do tipo **Sas**

**Comment by renatomurasaki** [comment]
@falbrito desenvolver procedimento estandar para realizar check de consistência da exportação da LILACS para o FI-ADMIN.

@viniciusandrade por favor, verificar alteração do procedimento de exportação FI-ADMIN -> id2i para utilizar como critério de exportação o id da lilacs.

**Comment by falbrito** [comment]
Concluído e disponibilizado no git o código ComparaIds.sh, 
Tem o propósito de fazer comparação e verificar diferença entre o arquivo denominado ID criado através do aplicativo i2id da biblioteca ISIS, e o arquivo texto de Exportação no mesmo formato criado pelo sistema FI-Admin.

**Comment by viniciusandrade** [comment]
@falbrito 

A API agora aceita o parâmetro LILACS_original_id para retornar somente um registro. Também é possível passar uma lista usando a seguinte sintaxe:

/api/bibliographic/?LILACS_original_id__in=1&LILACS_original_id__in=2&LILACS_original_id__in=3&format=isis_id

**Comment by falbrito** [comment]
Refatorado o código ComparaIds.sh. 
Foi incorporado ao processo a coleta via wget seguindo a URL /api/bibliographic/?LILACS_original_id__in=1&LILACS_original_id__in=LILACS_original_id.
Agora o processo cria uma lista com o conteúdo do campo v2 do arquivo ID de origem. Esta lista serve de insumo para possibilitar a coleta dos registros a partir da API.
