### ISSUE TITLE
fi-admin title campo Areas Tematicas

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#18]
Neste campo poderia ter algumas áreas padrão com a opção de marcar as de interesse como

CIENCIAS DA SAUDE
CIENCIAS HUMANAS
CIENCIAS BIOLOGICAS

CIENCIAS DA SAUDE, (ESTA MARCAÇÃO DEFINE SE O TÍTULO SERA RECUPERADO NO PORTAL DE REVISTAS)

**Comment by wilsonmoura** [comment]
Tornar esse campo em lista controlada com multiseleção.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade.
