### ISSUE TITLE
Aba "Texto completo" não disponível para Monografia

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#180]
Aba **Texto completo** não disponível para tipo de literatura **Monografia (M)** no nível **Fonte**.
Aba aparece em nível analítico. 

_Monográfico (M)_
![image](https://cloud.githubusercontent.com/assets/18355163/15751289/f6ea655c-28bf-11e6-913d-a2ccf286c6cb.png)

_Analítica de série monográfica (Mam)_
![image](https://cloud.githubusercontent.com/assets/18355163/15751522/c8bc0b30-28c0-11e6-94f7-124d3ef5bc21.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

OK. Quando possível realizar nova validação.

[]s

**Comment by sarahviola** [comment]
Aba disponível para documentalista e editor.

**Comment by sarahviola** [comment]
Observação: continua funcionando corretamente com as alterações para gravar registro **Mm** corretamente,
