### ISSUE TITLE
Criação de validação de conteúdo para campo de data normalizada

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#181]
Data de publicação normalizada deve **sempre** ter nos 4 primeiros dígitos os últimos quatro dígitos da Data de publicação.

Exemplo: 
Data de publicação: abr.-jun. **2016**
Data de publicação normalizada: **2016**0600

Data de publicação: jun. **2016**
Data de publicação normalizada: **2016**0600

Data de publicação: **2016**
Data de publicação normalizada: **2016**0000

**Comment by viniciusandrade** [comment]
@sarahviola,

Implementado. Favor quando possível validar.

[]s

**Comment by sarahviola** [comment]
ok. 

Incluído exceção para os casos em que o ano não está nos últimos quatro caracteres:
- data de publicação incerta: ano publicado entre colchetes, mas data normalizada registrada normalmente.
- sem data de publicação: s.d - campo de data normalizada deve estar vazio.
