### ISSUE TITLE
Campo de autor deve ser obrigatório para Monográfico (M)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#183]
Para registros **monográficos (M)** deve ser **obrigatório**: Autor Pessoal (nível monográfico) [16] **ou** Autor Institucional (nível monográfico) [17].

Atualmente campo de autor não é obrigatório para registros em status de Rascunho nem para Publicado.

![image](https://cloud.githubusercontent.com/assets/18355163/15780167/b6baf598-2976-11e6-9944-4754a1d785c6.png)

_Observação:_
Validação de autor para **Sas** (que já está ok no FI-Admin): Autor pessoal (nível analítico) [10] ou Autor institucional (nível analítico) [11].

**Comment by viniciusandrade** [comment]
@sarahviola 

OK. Quando possível realizar nova validação.

[]s

**Comment by sarahviola** [comment]
ok.

**Comment by sarahviola** [comment]
Observação: continua funcionando corretamente com as alterações para gravar registro **Mm** corretamente,
