### ISSUE TITLE
Incluir Fonte do artigos de periódicos na Lista de "Indexados pelo meu centro"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#185]
Para o documentalista revisar dados do fascículo ele precisa pesquisar o Fonte em "Todos registros", porém o ideal seria que o fonte estivesse disponível na lista "Indexado pelo meu centro"

![revisar-fonte](https://cloud.githubusercontent.com/assets/13105683/15788645/e43752fa-299e-11e6-984d-06b4beba0357.JPG)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga / @sarahviola,

Ajustes realizado. Quando possível favor validar.

Obrigado.

**Comment by sarahviola** [comment]
Ok na produção. 
![image](https://user-images.githubusercontent.com/18355163/29179197-2db53e58-7dca-11e7-9c2a-de95e57231da.png)

@viniciusandrade , tenho dúvida sobre impacto disso. 
Como os registros Fonte não tem status LILACS-Express ou Publicado, eles vão sempre aparecer na aba de "Indexado pelo meu centro", mesmo que já tenham sido revisados? É importante o registro Fonte aparecer nessa aba para o CC não se esquecer de revisar os dados do Fonte (o que já está acontecendo), mas se eles não saírem da aba, ela ficará poluída.

**Comment by viniciusandrade** [comment]
@sarahviola 

Sim, os registros fontes serão sempre apresentados na lista uma vez que eles não possuem um status diferente. Favor verificar com a @suelisuga se devemos manter as fontes na listagem. 

Vou deixar como encerrado este ticket pois esta implementado e em produção. Caso seja necessário retirar da lista favor criar novo ticket.

[]s

**Comment by sarahviola** [comment]
Certo, @viniciusandrade . Vou falar com a Sueli.
