### ISSUE TITLE
Perfil documentalista não consegue editar seus registros Monográficos (M) com status publicado

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#186]
De acordo com as [permissões definidas para usuários do Fi-admin](https://github.com/bireme/fi-admin/wiki/Permiss%C3%B5es), usuário documentalista deve: "Criar e editar referências criadas por ele e por usuários do seu centro cooperante (qualquer status)".

Atualmente documentalista não consegue editar seus registros depois de alterar o status para **publicado**

_Exemplo_: 
Registro id [192](http://fi-admin.teste.bvsalud.org/bibliographic/edit-source/192), criado e publicado pelo usuário doc1, mas que o usuário não pode editar.

![image](https://cloud.githubusercontent.com/assets/18355163/15790670/084413c2-29a9-11e6-9bbb-eafa6afcde4a.png)

**Comment by viniciusandrade** [comment]
Conforme discutimos na reunião do dia 14/07 vamos tentar implementar uma mensagem de confirmação antes do registro ser publicado.

**Comment by viniciusandrade** [comment]
Implementado mensagem de confirmação para usuários do perfil documentalista antes do registro ser publicado.

Disponível para validação no ambiente de testes.

**Comment by sarahviola** [comment]
Mensagem está aparecendo ao publicar artigos de revista,
![image](https://cloud.githubusercontent.com/assets/18355163/21617363/de830698-d1cc-11e6-9822-3084c9230b53.png)
Sugestão: alterar de texto de "editor" para "usuário com perfil de editor".

Ao publicar monográficos e teses não aparece a mensagem.

**Comment by viniciusandrade** [comment]
@sarahviola,

OK, texto alterado e mensagem implementada para monográficos e teses.  Quando possível favor realizar novo teste.

**Comment by sarahviola** [comment]
Mensagem aparecendo para todos os tipos de documento.
