### ISSUE TITLE
Depois de clicar em "Publicar" não é mais possível salvar o registro sem preencher todos os campos obrigatórios para status publicado

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#187]
Quando clicamos em "Publicar" mas o registro ainda tiver erros que não deixem gravar o registro com status publicado não é possível salvar as alterações feitas no registro clicando em "Gravar como LILACS-Express" ou "Gravar como Rascunho" porque o sistema continua exibindo as validações para status publicado e não salva os dados como rascunho ou LILACS-Express.

Problema identificado com perfil documentalista e não testado com perfil editor.

![image](https://cloud.githubusercontent.com/assets/18355163/15790892/6b42d6e2-29aa-11e6-8179-7ee8715d7446.png)

**Comment by sarahviola** [comment]
Quando o registro ainda não está com todos os campos obrigatórios para status publicado preenchidos, ao clicar em "Publicar", visualizar todos os erros, corrigir todos e clicar em "Gravar como Rascunho", o registro é salvo como "Publicado".

**Comment by viniciusandrade** [comment]
@sarahviola 

Alterei esta parte do sistema, quando possível realizar novos testes.

Obrigado

**Comment by sarahviola** [comment]
Ok, agora:
- é possível salvar o registro como LILACS-Express depois de ver os erros para status publicado, sem perder os dados incluídos. 
- o registro não é mais salvo como publicado depois de ter tentado publicar, corrigir os erros e clicar no salvar como LILACs-Express.
