### ISSUE TITLE
Na visualização por tipo de documento M documentalista pode deletar registro

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#188]
Na visualização geral dos registros o documentalista não tem como deletar registros fonte de monográficos (M):
![image](https://cloud.githubusercontent.com/assets/18355163/15791364/47ce635e-29ad-11e6-86c3-8fa4ab0fd54f.png)

Ao selecionar criar um novo registro monográfico é exibida a lista de monográficos já incluídos. Nessa visualização o documentalista tem acesso a opção de deletar registros Fonte de monográficos criados por ele, inclusive quando com status publicado.
![image](https://cloud.githubusercontent.com/assets/18355163/15791404/80e5ac24-29ad-11e6-9422-bc0e17951fd9.png)

Na [descrição das permissões do Fi-admin ](https://github.com/bireme/fi-admin/wiki/Permiss%C3%B5es)ainda não definimos se o documentalista poderá deletar monográficos.

**Comment by sarahviola** [comment]
@viniciusandrade 

A mesma coisa está acontecendo com os registro de Teses/dissertações nível monográfico (**Tm**).

**Comment by viniciusandrade** [comment]
@sarahviola 

Achei melhor não mostrar o botão de apagar nas listas apresentadas quando o usuário esta inserindo um novo documento. Não tem muito a ver.

OK?

**Comment by sarahviola** [comment]
Beleza! 
Ok tanto para monográficos como para teses,
