### ISSUE TITLE
Erro ao gravar rascunho de registros Fonte (M e S) sem todos os campos obrigatórios

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#189]
Ao validar as issues #182 e #183 , notei que ao salvar Rascunho registro tipo M (Fonte de monográfico) sem algum dos campos obrigatórios para rascunho, aparece o erro abaixo:
![image](https://cloud.githubusercontent.com/assets/18355163/15824071/d4c8ba0c-2bd3-11e6-9066-9f5957784365.png)

Testei então também com registro tipo S (Fonte de seriado). Ao tentar gravar rascunho sem incluir dado nenhum, apenas para ver os campos obrigatórios, também aparece:
![image](https://cloud.githubusercontent.com/assets/18355163/15824137/17fe86ee-2bd4-11e6-81a3-b86dabafcf98.png)

Testei também salvar rascunho de Sas e Mam (analíticas de seriado e monográfico) sem incluir dado nenhum, só para ver os campos obrigatórios, e não dá este erro.

**Comment by viniciusandrade** [comment]
@sarahviola,

Efeito colateral da correção do #187. Acho que consegui resolver, por favor validar.

[]s

**Comment by sarahviola** [comment]
Agora está ok!

Imaginei que estivessem relacionados, mas como deu erro também em registros tipo S, abri outra issue.
