### ISSUE TITLE
fi-admin  campo Estado (localidade)

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#19]
Na Secs-dos quando o título for do Brasil o campo estado se torna obrigatório o preenchimento. inserir na nova versão.

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971

**Comment by wilsonmoura** [comment]
Os campos foram vinculados através das validações especificadas.
