### ISSUE TITLE
Alterar data de publicação para obrigatório em registros Fonte de série periódica (S)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#191]
Alterar campos de data de publicação [64] e data de publicação normalizada [65] para obrigatórios em registros Fonte de série periódica (**S**). 
(Como definido na issue #98 , registros fonte de séria periódica sempre devem ter status de publicado mas aparecer label Fonte, já que esse tipo de documento não é publicado sozinho e manter com status "rascunho" causaria confusão)

Problema: atualmente perfil llxp consegue criar registros sem datas de publicação. A data de publicação só aparece como obrigatória caso o usuário llxp tente editar o registro fonte.

**Comment by viniciusandrade** [comment]
@sarahviola 

Realizei o ajuste nesta parte. Favor validar.

Obrigado.

**Comment by sarahviola** [comment]
ok, agora data de publicação é obrigatória na criação do registro.
