### ISSUE TITLE
Perfis documentalista e editor tem opção de alterar status de registros Fonte de séria periódica (S)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#192]
Como definido na issue #98 , registros fonte de séria periódica sempre devem ter status de publicado mas aparecer label Fonte, já que esse tipo de documento não é publicado sozinho e manter com status "rascunho" ou "publicado" causaria confusão

Perfil documentalista:
![image](https://cloud.githubusercontent.com/assets/18355163/15836282/72b5d890-2c0a-11e6-91e3-abc0d1d1fab6.png)

Perfil editor:
![image](https://cloud.githubusercontent.com/assets/18355163/15836256/47a85d9e-2c0a-11e6-9186-a22e17d3c9ea.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado, quando possível avaliar em teste ou produção.

Obrigado

**Comment by sarahviola** [comment]
Problema resolvido.

Problema relacionado a essa correção registrado na issue #337 .
