### ISSUE TITLE
Alterar validação de campos para Projeto

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#193]
Atualmente FI-Admin grava registros como projeto (tipo de literatura **P**) quando preenchemos os campos "Nome do projeto" ou "Número do Projeto". Quando preenchemos apenas "Projeto - Instituição patrocinadora", que não é um campo obrigatório para P, não é exibida mensagem, mas o registro também não é salvo com o tipo P.

Incluir checagem para exigir que quando "Projeto - Instituição patrocinadora" for preenchido, seja preenchido também "Nome do projeto" ou "Número do Projeto".

Mensagem de erro do LILDBI-Web:
![image](https://cloud.githubusercontent.com/assets/18355163/15864963/5efbb18a-2caf-11e6-91d2-991c9c501d6e.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado, quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
ok.
