### ISSUE TITLE
Alterar validação de campos para Evento (C)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#194]
Atualmente FI-Admin exige os campos obrigatórios Evento (tipo de literatura **C**) e marca o tipo C apenas quando preenchemos o campo "Nome do evento". Então, quando preenchemos algum campo que não "Nome do evento", não são exigidos os campos obrigatórios e o registro não é salvo como tipo C.

O ideal seria exigir o preenchimento dos campos obrigatórios para Evento quando qualquer um dos campos de Evento for preenchido.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado, quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
ok.
