### ISSUE TITLE
Alterar validação para não aceitar afiliação em Teses e Dissertações (Tm)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#196]
De acordo com o manual da Metodologia LILACS:
![image](https://cloud.githubusercontent.com/assets/18355163/15871230/e261fa60-2cc9-11e6-8a5d-5efc12ca31f2.png)

Então, alterar a validação do campo de autor pessoal [16] em registros de teses (Tm) para não aceitar dados nos campos de afiliação.

Mensagem de erro do LILDBI-Web em caso de preenchimento de afiliação para autor pessoal em teses e dissertações (que não é muito clara; melhor usar o texto do manual):
![image](https://cloud.githubusercontent.com/assets/18355163/15871131/637a5936-2cc9-11e6-8045-160b9da6d336.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado. Favor quando possível verificar.

[]s

**Comment by sarahviola** [comment]
Validação ok. 
![image](https://cloud.githubusercontent.com/assets/18355163/15899077/fe63bed6-2d70-11e6-983e-5e2f93d50601.png)

Acho que fica melhor especificar na mensagem de erro que isso é só para teses, apesar de ser óbvio:

"Informação de afiliação em **Teses e dissertações** deve ser informada no campo 'Instituição a qual se apresenta'"

**Comment by viniciusandrade** [comment]
OK, ajuste da mensagem realizado.

**Comment by sarahviola** [comment]
ok.
