### ISSUE TITLE
Incluir tabela no subcampo de País da afiliação de orientadores em registros de Teses

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#198]
Assim como feito no campo de autor pessoal, incluir **tabela de países** no subcampo de **País da afiliação de Orientador** [49^p].

![image](https://cloud.githubusercontent.com/assets/18355163/15898659/88579a6a-2d6f-11e6-8bdd-2ed4832f4448.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

Tabela incluída, quando possível favor validar.

[]s

**Comment by sarahviola** [comment]
ok.

![image](https://cloud.githubusercontent.com/assets/18355163/15899953/f44ea3fe-2d73-11e6-9209-cca998b9357a.png)
