### ISSUE TITLE
Retirar campo de autor institucional do formulário de analíticas de Tese (Tam)

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#199]
Assim como registros de Tese nível monográfico (Tm), teses em nível analítico (Tam) também não devem ter campo de autor institucional.

Então, **retirar** o campo de **autor institucional** do formulário de registros tipo **Tam** e alterar mensagem de erro para obrigatoriedade somente para autor pessoal.

_formulário de Tam_
![image](https://cloud.githubusercontent.com/assets/18355163/15908988/b85d3e74-2d9a-11e6-9968-c26e576cbed5.png)

_formulário de Tm_
![image](https://cloud.githubusercontent.com/assets/18355163/15909062/0332e0d4-2d9b-11e6-8cb5-8ffcd7d5189e.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Campo removido do form. Quando possível favor validar.

[]s

**Comment by sarahviola** [comment]
ok.
