### ISSUE TITLE
Permitir carregar mais de um documento em Texto Completo

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#202]
Atualmente o FI-Admin só permite carregar um arquivo por registro. Há um editor de revista que está utilizando o sistema que publica o mesmo artigo em inglês e em português, ou seja, ele tem dois PDF para subir no sistema.

Então, alterar para pelo menos dois o número de arquivos que podemos carregar em um registro. 

Fiz uma pesquisa na LILACS por documentos que estão em inglês, espanhol e português simultaneamente e temos 1041 registros. Não sei se vale a pena alterar para mais de 2 documentos.

**Comment by sarahviola** [comment]
Revisando a questão, alterei a categoria de "task" para "bug" porque existe no sistema a opção "Adicionar arquivo" e é possível selecionar um novo arquivo para ser carregado, entretanto o segundo arquivo não é salvo.

**Comment by viniciusandrade** [comment]
@sarahviola 

Acredito ter resolvido este problema. Quando possível favor verificar no ambiente de testes.

[]s

**Comment by sarahviola** [comment]
ok no ambiente de testes.
Sistema está permitindo carregar vários PDF (testei até 4 arquivos).
![image](https://cloud.githubusercontent.com/assets/18355163/16080479/6ebec284-32df-11e6-91c1-3377de0bab58.png)

@viniciusandrade , vc por favor me avisa quando estiver ok na produção para eu responder para o usuário que reportou o problema?

**Comment by viniciusandrade** [comment]
@sarahviola 

:+1:  Sistema atualizado em produção.

**Comment by sarahviola** [comment]
Obrigada! 
Usuário informado.
