### ISSUE TITLE
Problema na edição de dados do campo Endereço Eletrônico, subcampo Tipo de arquivo

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#203]
Depois de incluir e gravar dados do campo de Endereço eletrônico, ao abrir novamente o assistente para editar os dados, no subcampo **Tipo de arquivo** vem preenchido a primeira opção da tabela, e não o dado que estava gravado no registro.

![image](https://cloud.githubusercontent.com/assets/18355163/15977817/0b1cd18c-2f31-11e6-98bd-33ea90f68975.png)

![image](https://cloud.githubusercontent.com/assets/18355163/15977862/3405b852-2f31-11e6-9286-325b939f0be5.png)

Além disso, ao abrir o assistente para incluir dados no campo de endereço eletrônico, os subcampos **Tipo de arquivo** e **Extensão do arquivo** já aparecem preenchidos com o primeiro dado da tabela. 
O ideal seria que esses subcampos viessem vazios ao abrir editor para incluir dados.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustes realizados, quando possível favor validar no ambiente de testes.

Obrigado.

**Comment by sarahviola** [comment]
Ok.
Edição de dados de Endereço Eletrônico pelo assistente mostra o dado que havia sido gravado anteriormente e ao incluir nova URL os subcampos Tipo de arquivo e Extensão do arquivo estão vazio, para o usuário selecionar.

@viniciusandrade , quando estiver atualizado na produção por favor me avisa para eu dar retorno para o usuário que reportou o problema?

**Comment by viniciusandrade** [comment]
@sarahviola 

Sistema atualizado em produção.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

Obrigada. Estou informando o usuário.
