### ISSUE TITLE
Incluir editor de texto na área de Ajuda da administração do site

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#204]
Incluir editor de texto html na área de **Ajuda** da administração do site (django admin). Se possível, incluir também edição de tabelas. 
(Editor já incluído na área **Text blocks** #121 )

_Observação_: editor de texto para Text blocks só disponível no ambiente de teste, e não produção. Depois de incluir e validar o editor para a Ajuda, atualizar também na produção.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustes realizados e aplicados em teste e produção. Favor avaliar.

[]s

**Comment by sarahviola** [comment]
ok.
