### ISSUE TITLE
Ajuda do sistema: necessidade de segunda página 

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#205]
Na ajuda de alguns campos é necessária uma segunda página com mais informações.

Nos casos em que o texto da página secundária é curto, creio que vale a pena colocar o texto na primeira página mesmo. Exemplo: Ajuda do campo de data de publicação.
Texto da ajuda do campo: http://lildbi.bvs.br/lildbi/p/help/help64.htm
Página secundária, que inclui na primeira página: http://lildbi.bvs.br/lildbi/p/help/anexoIII.htm

Em outros campos, o texto da ajuda do campo já é bastante extenso e o texto das páginas secundárias também não é pequeno, então não vale a pena colocar tudo em uma página. Exemplo: campo de autor pessoal. 
Texto de ajuda do campo: http://lildbi.bvs.br/lildbi/p/help/help10.htm
Páginas secundárias da ajuda deste campo: 
- anexo I: http://lildbi.bvs.br/lildbi/p/help/anexoI.htm
- anexo IX: http://lildbi.bvs.br/lildbi/p/help/anexoIX.htm

Então, a dúvida é: 
Como fazer nas ajudas em que é necessária uma página secundária?

**Comment by viniciusandrade** [comment]
Fiz alguns ajustes para permitir o gerenciamento e apresentação destas páginas de segundo nível no FI-ADMIN. Os passos para criação são:

Pelo Django Admin >  opção Ajudas > Criar nova ajuda indicando a fonte e o nome do campo com um sufixo que indique a página de segundo nível. Exemplo: 

individual_author_anexo_1

Criar o texto da página do anexo nos idiomas disponíveis e salvar.

Na ajuda do campo que esta relacionado o anexo (no exemplo o campo "individual_author") adicionar um link para a página de ajuda usando a seguinte regra para o campo de URL:

/help/view/biblioref/individual_author_anexo_1/?page=true

onde:
/help/view/  - é fixo e indica o sistema de ajuda
biblioref      - indica para qual fonte é a página de ajuxa
individual_author_anexo_1/ - indica qual o campo e página se deseja mostrar
?page=true    - indica que será mostrado como uma página 

Também é importante escolher a opção Target > New window  para que a página seja aberta em uma nova aba do navegador.

Quando possível favor validar no ambiente de testes.

[]s

**Comment by sarahviola** [comment]
Ótimo!

@viniciusandrade 
Tem que atualizar algo na produção, ou já posso fazer criar as páginas secundárias lá também?

**Comment by viniciusandrade** [comment]
@sarahviola,

O recurso já esta disponível no ambiente de produção.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade, ótimo!
