### ISSUE TITLE
Traduzir formulário de entrada de dados do perfil llxp (editores de revista) para espanhol

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#206]

**Comment by viniciusandrade** [comment]
Implementado em ada372fbbadcb3f7e63c082297b1f5a208a15b1a

**Comment by viniciusandrade** [comment]
@sarahviola 

Tradução realizada. Quando possível favor verificar.

[]s

**Comment by sarahviola** [comment]
Ok!

**Comment by sarahviola** [comment]
@viniciusandrade, quando estiver ok na produção vc pode favor me avisae para incluir as revistas em espanhol?

**Comment by viniciusandrade** [comment]
@sarahviola 

Ambiente de produção atualizado. Favor verificar e se OK fechar o issue.

Obrigado

**Comment by sarahviola** [comment]
@viniciusandrade 

Tudo ok! Vamos começar a incluir as revistas de fora do Brasil.
