### ISSUE TITLE
Incluir informações do DeCS nos campos Tipo de publicação e Descritores Pré-codificados

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#207]
Nos campos *Tipo de publicação** e **Descritor pré-codificado**, que são preenchidos com termos do DeCS, incluir alguma forma de visualizar a definição e demais informações do DeCS.

No LILDBI-web há essa opção selecionando o(s) termo(s) e clicando em "DeCS Server":
![image](https://cloud.githubusercontent.com/assets/18355163/16092596/e4115978-330e-11e6-8915-fa6ed9653e21.png)

![image](https://cloud.githubusercontent.com/assets/18355163/16092611/f5ee0682-330e-11e6-9a2c-5b682eae5f70.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

Disponível no ambiente de testes para validação.

[]s

**Comment by sarahviola** [comment]
ok!
![image](https://cloud.githubusercontent.com/assets/18355163/17592742/cb7f08ba-5fb9-11e6-8663-34c8c9bfb5a5.png)
