### ISSUE TITLE
Adicionar  campo "Indexado em" para controle da informação de bases de dados

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#208]
O objetivo do campo "indexado em" é a criação de uma lista controlada com as principais bases de dados e com isso a normalização parcial do campo 04 (base de dados).

Deve ser implementado, de preferência, utilizando duas caixas onde o usuário escolhe uma base da lista controlada e clique em uma seta para mover esta informação para a caixa de bases selecionadas.

* Em um primeiro momento o controle da lista será de responsabilidade da BIREME e posteriormente pode-se estudar em abrir a edição desta lista pelos centros coordenadores.

* As bases de dados locais de controle da instituição não serão colocadas neste campo, permanecendo no campo local "base de dados".

**Comment by viniciusandrade** [comment]
Possível plugin para utilização neste issue:

https://crlcu.github.io/multiselect/

**Comment by viniciusandrade** [comment]
@sarahviola 

Implementei o novo campo para controle da base de dados onde o registro é indexado (antigo campo 04).

Neste primeiro momento esta disponível apenas no formulário de "Sas", poderia quando possível avaliar se esta OK para os perfis de editor LLXP, documentalista e editor?

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade

Tem um problema. Nos perfis documentalista e editor, quando clico em gravar mas o registro tem algum erro que não permite gravar o registro, o sistema está esvaziando o dado das bases de dados selecionadas.

**Comment by viniciusandrade** [comment]
@sarahviola 

Realizei alguns ajustes para resolver este problema. Por favor quando possível realizer novos teste.

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade 

Agora está ok. Quando llxp cria registros, eles já vem para o documentalista com LILACS no campo Bases de dados. Documentalista pode adicionar e gravar outras bases. Quando tento salvar registro que tem alguma pendência, o dado do campo não é perdido.

Só precisa melhorar a visualização do dado do campo "Indexado em" em registros publicados no perfil de documentalista, que atualmente não está aparecendo:
![image](https://cloud.githubusercontent.com/assets/18355163/16768684/b4bfaf2c-481b-11e6-831d-19b2000a2cff.png)

No django admin, eu tinha criado as bases de dados como vc tinha criado a LILACS, só preenchendo nome e sigla. Depois testei preencher o campo "índice de centro cooperante" na BDENF, mas a visualização no perfil do documentalista continuou igual.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado na visualização do documento. Favor verificar.

**Comment by sarahviola** [comment]
@viniciusandrade 
ok! 

Agora acho que falta incluir nos outros tipos de documentos para concluir, certo?

**Comment by viniciusandrade** [comment]
@sarahviola 

Correto. Acabo de adicionar o campo para todos os tipos de documentos. 

Quando possível favor validar.

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade

Não está funcionando em alguns registros. Pelo que vi, o problema são só os registro Fonte. As analíticas estão todas ok.
Exemplos:  
id 190, MCPm
id 214, Tm
id 232, Tsms

Notei que nos registros fonte de série periódica (S) não aparece o campo de base dados, o que faz sentido, já que esse tipo de registro não aparece no resultado de pesquisa, somente as analíticas, mas no LILDBI-Web o campo base de dados aparecia para esse tipo de registro.

**Comment by viniciusandrade** [comment]
@sarahviola 

Realmente faltava uma parte do código para o formulário de fonte. Agora deve estar OK.

Sobre o fonte de série períodica, sugiro deixarmos sem mostrar o campo de base de dados por não fazer sentido. Caso apareça a necessidade adicionamos no formulário.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

Agora está funcionando nos registros fonte.

Ok sobre os registros tipo S.
