### ISSUE TITLE
Integração com o Dedup para inclusão de novos registros

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#209]
Na criação de novos registros enviar os dados para o serviço Dedup.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ao registrar um novo artigo o sistema deve enviar os metadados de título, revista e ano para o serviço de deduplicação, desta forma caso o usuário tente criar um registro duplicado o sistema deve apresentar  a caixa de alerta.

Quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade , 

Aparece o alerta que o artigo pode estar duplicado, mas mesmo assim o registro é salvo, duplicando o registro. Esse é o comportamento correto?

Também existe essa validação de duplicados para registros Fonte? Não testei porque não posso apagar registros Fonte, aí não quis sujar a base em produção com testes.

**Comment by sarahviola** [comment]
@viniciusandrade 

Ao criar um novo registro ([id 833276](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/833276)), o sistema exibe a mensagem "Possível artigo duplicado (verificar)". 

Clicando no "verificar" e depois em no título do possível artigo duplicado, o sistema exibiu o próprio registro que eu estava criando, que era o id 833276.

O correto seria exibir outro registro, que no caso seria o id [833203](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/833203).

Além disso notei que ao editar o registro duplicado, aparece mensagem de erro somente quando abro o assistente do campo título e salvo. Se a alteração for em outro campo, não é exibida o aviso de duplicado.

**Comment by suelisuga** [comment]
Pergunta: comportamento esperado é que identifique duplicação com registros em quais status? Publicado, LILACS-Express, Apagado, Recusado, Rascunho?

No meu teste eu estava copiando e colando todos dados de um registro em rascunho e até o o momento não recebi mensagem de duplicação.
![image](https://user-images.githubusercontent.com/13105683/45045861-bd9c3680-b04a-11e8-991f-a37591d46944.png)

**Comment by viniciusandrade** [comment]
Como para cada tipo de registro bibliográfico e fonte (eventos, recursos de internet, etc) é necessário a criação de configuração específica no DeDup foram criados issues separados para tratar da integração com cada tipo/fonte. 

Exemplos: #285, #1068, #130.
