### ISSUE TITLE
Alterar o campo Title Serial para trazer somente revistas atualmente indexadas na LILACS

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#213]
Campo Title Serial do FI-Admin atualmente apresenta as revistas para os usuários de acordo com o campo da title **Código do editor [930]**. Como revistas que saíram da LILACS continuam com o campo 930 preenchido, o FI-Admin exibe revistas que não são mais indexadas na LILACS. 

Então, alterar o campo Title Serial do FI-Admin para apresentar somente as revistas com o campo **Código do centro indexador [920] da title preenchido**, que significa que a revista está indexada na LILACS.

_Exemplo:_
Código de editor BR153, que tem 5 revistas na title das quais 3 estão com a indexação finalizada na LILACS (sem 920) e duas atualmente indexadas (com 920 preenchido).

---

**Observação**
Quando o controle de títulos abreviados e atribuição de CC indexador nas bases da BVS for implantado ( #211 ), este campo terá que ser novamente alterado.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado e disponível no ambiente de testes. Quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
ok.

Usuário do BR153 no FI-Admin teste exibindo apenas as 2 revistas atualmente indexadas.
