### ISSUE TITLE
Comportamento do campo SeCS Number (v37)

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#214]
Verificamos que o conteúdo desse campo corresponde a mesmo valor do campo ID (v30).
Sendo assim, devemos ajustar o sistema para que esse campo seja preenchido automaticamente com o valor do ID?

**Comment by renatomurasaki** [comment]
Decisão de manter o V30 e V37 na mesma situação da Title / SeCS atual.
