### ISSUE TITLE
O campo de Localização do Documento na Aba de Biblioteca esta com problema no assist

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#215]
Quanto clico no campo Localização do Documento na Aba de Biblioteca para abrir a pagina de assist aparece o Erro "Server Error (500)" na instância de curso também esta com este problema.

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Acredito ter encontrado e corrigido o problema.  Por favor verifique se agora esta OK.

* É necessário realizar um refresh na página do formulário para atualizar o javascript.

**Comment by anakatiacamilo** [comment]
@viniciusandrade 
Vini, o da instância de curso esta OK, mas o da produção ainda esta com o mesmo problema realizei um refresh e testei em dois browsers (google chrome e firefox).
Katinha

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Desculpe não te avisei mas combinamos de só atualizar a produção após o OK que o problema foi solucionado na teste.

Acabei de atualizar a produção. Por favor quando possível dê uma olhada e se OK pode fechar o issue.

Obrigado.
