### ISSUE TITLE
Check de Projeto

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#216]
Vini,
Estou incluindo os registros para teste de migração na instância de curso e notei que tem um Aviso de erro que informa "Nome do Projeto ou Número do Projeto obrigatório" e mesmo que o Número do projeto esteja preenchido o aviso permanece.
Katinha

**Comment by viniciusandrade** [comment]
Katinha,

Obrigado. Acredito ter corrigido o erro. Por favor quando possível favor validar e se OK fechar o issue.

[]s

**Comment by anakatiacamilo** [comment]
OK
