### ISSUE TITLE
Incluir campo Título Paralelo Abreviado (v235)

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#22]
Falta inserir a opção do título abreviado nesta interface. Usamos muito quando um título Lilacs muda de nome, usado pelo Marcelo e Katia fazer processamento necessários dentro da base Lilacs.

**Comment by wilsonmoura** [comment]
Verificar a inclusão do campo 235 (campo não foi identificado nas reuniões de validação dos campos da SeCS).

**Comment by anakatiacamilo** [comment]
Wilson este campo é necessário e esta documentado na Wiki
http://wiki.bireme.org/pt/index.php/Campos_da_base_Title#T.C3.ADtulo_paralelo_abreviado_.5B235.5D

**Comment by wilsonmoura** [comment]
Resolvido em ee9fd65d6f8504b9990db4bf212eb58add783e30, b17e50831e491316e37f47767e60df57e733f070 e 857f8ec443dce447b9fa86c0f59eb3c7b2eb9b1f
