### ISSUE TITLE
Erro na visualização da próxima página de analíticas

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#220]
A página das analíticas exibe 20 registros, e ao final da página há o link para ir para a página anterior. Entretanto, o **link para visualizar a próxima página de analíticas não funciona**.

Problema identificado na [Rev. bras. cir. plást; 29 (1), 2014](http://fi-admin.bvsalud.org/bibliographic/analytic?source=63).

![image](https://cloud.githubusercontent.com/assets/18355163/16338050/67d49dd2-39f0-11e6-9b74-30c1fe989c1c.png)

Ainda não testei a paginação de registros Fonte.

**Comment by sarahviola** [comment]
Só dá esse erro quando acessamos a **lista das analíticas a partir do registro Fonte** . 

A navegação na visualização dos registros por abas do perfil editor (_meus registros_, _todos os registros_, entre outras) funciona normalmente.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustei o código mas não tenho uma quantidade de registros no meu ambiente local para teste.  

Você consegue avaliar com os registros da teste? 

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade 

Criei mais algumas analíticas em um Fonte que já tinha um bom tanto e consegui testar. Agora a navegação nas páginas está funcionando.
