### ISSUE TITLE
Problema na ordem da visualização dos dados do campo Páginas

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#221]
O campo de páginas exibe primeiro a página final (dado do atribuito **l**, _last_) e depois a página inicial (atributo **f**, _first_), o que causa confusão. 

![image](https://cloud.githubusercontent.com/assets/18355163/16340289/b123c622-39fd-11e6-8902-628246f071f1.png)

(Pensei que a @suelisuga já havia reportado esse problema, mas não encontrei a issue. Caso encontrem, por favor fechar esta).

**Comment by viniciusandrade** [comment]
Ajustes realizado na visualização do campo, quando possível favor avaliar.

**Comment by sarahviola** [comment]
ok.
![image](https://cloud.githubusercontent.com/assets/18355163/16527016/ae84a908-3f8a-11e6-95c2-41be3bb859cb.png)
