### ISSUE TITLE
Incluir campo Número DOI em Sas

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#224]
Na aba Metadados de Sas, inclui campo **Número DOI** (724).

Características do campo:
![image](https://cloud.githubusercontent.com/assets/18355163/16532054/e0c099ac-3fa5-11e6-80ed-9d84e20ca6fc.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado. Quando possível favor validar.

**Comment by sarahviola** [comment]
Campo ok.
