### ISSUE TITLE
Duplicação do campo Nota interna no formulário de entrada de dados

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#225]
O campo **Nota interna** aparece na aba _Metadados_ e também em _Biblioteca_. Não há deveria apenas aparecer em Biblioteca??

**Comment by viniciusandrade** [comment]
@sarahviola 

Sim, deveria constar somente na aba Biblioteca. Fiz o ajuste. Quando possível favor validar.

**Comment by sarahviola** [comment]
Ok, aparece agora apenas na aba biblioteca.
