### ISSUE TITLE
Relatórios-1 : apresentar Fonte de Informação antes de tipo de Relatório

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#227]
Considerando inclusão de novos tipos de relatórios que são específicos por fonte de informação, solicito inversão da apresentação atual:

Primeiro apresentar as fontes de informação para depois apresentar os tipos de relatório disponíveis conforme o tipo de fonte selecionada.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste disponível no ambiente de teste. Quando possível favor avaliar.

Obrigado

**Comment by sarahviola** [comment]
OK, Fonte de Informação aparece primeiro.

Entretanto, falta ajuste quando seleciono fonte de informação **Registro bibliográfic**o e clico em **Filtros**

- Status: não aparece status _LILACS-Express_, que é exclusivo do tipo bibliográfico.
- Áreas temáticas: não deveria aparecer porque não é aplicável para este tipo.

![image](https://cloud.githubusercontent.com/assets/18355163/17636498/d801d4be-60b3-11e6-8def-0adb911eb6cb.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Adicionado rótulo LILACS-Express e alterado mensagem quando a combinação não é válida de acordo com discutido em reunião.

Favor quando possível verificar.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

Status LILACS-Express foi adiciono junto com status Pendente. É adicionar status LILACS-Express como um novo status, sozinho?

Status LILACS-Express e Pendente não deveriam ficar juntos porque são bastante diferentes. Registros com status Pendente não irão aparecer na página de pesquisa, enquanto os LILACS-Express irão aparecer.

![image](https://cloud.githubusercontent.com/assets/18355163/17668245/c2fe310c-62de-11e6-897f-bcae1075abc7.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

OK, adicionado opção em separado para LILACS-Express.

[]s

**Comment by sarahviola** [comment]
Ótimo!
