### ISSUE TITLE
Relatórios-2: Incluir "Registros Bibliográficos" e "Revistas" entre as Fontes de informação

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#228]
Incluir "Registros Bibliográficos" e "Revistas" na lista de fontes do campo "Fonte de informação"

Obrigada 
Sueli

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste disponível no ambiente de teste. Quando possível favor avaliar.

Obrigado

**Comment by sarahviola** [comment]
"Revistas" foi criado como "Título". É possível mudar para **Revistas**? Título é pouco significativo.

**Comment by viniciusandrade** [comment]
Alterado rótulo da fonte de informação para Revistas. Favor validar.

**Comment by sarahviola** [comment]
ok.
