### ISSUE TITLE
Incluir validação para grau de responsabilidade (subcampo r) no campo de autor pessoal

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#229]
Para documentos validação LILACS devem ser aceitos somente os graus de responsabilidade abaixo:
![image](https://cloud.githubusercontent.com/assets/18355163/16769984/392027f6-4821-11e6-8f1c-c8cb9095f693.png)

**Comment by viniciusandrade** [comment]
Validação incluída, quando possível favor validar.

**Comment by sarahviola** [comment]
Ok com _Validar usando metodologia LILACS_ marcado; permite gravar registro somente com os quatro graus de responsabilidade da tabela.

Falta ajustar com a opção _Validar usando metodologia LILACS_ desmarcada, que deveria poder gravar registro com qualquer um dos graus de responsabilidade da tabela, mas está permitindo apenas os 4 da Metodologia LILACS.

**Comment by viniciusandrade** [comment]
@sarahviola 

Correto, falha minha. Quando puder favor realizar nova verificação.

[]s

**Comment by sarahviola** [comment]
Agora está ok.
