### ISSUE TITLE
Saída do arquivo de exportação ID

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#231]
O arquivo de exportação do sistema no formato texto (ID) está com uma mascara diferente do arquivo ID criado através da ferramenta "i2id". No arquivo de exportação está com 3 caracteres porém o certo são 4.

Exemplo
Arquivo criado pelo i2id
 !v001!BR1.1

Arquivo criado pela exportação
 !v01!BR1.1

**Comment by viniciusandrade** [comment]
@falbrito 

Ajuste realizado. Favor verificar.

[]s

**Comment by falbrito** [comment]
Correção realizada.
