### ISSUE TITLE
Incluir subcampo "e" no campo [14] Páginas para <elocation id>

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#232]
Nome do subcampo: Identificador de Localização Eletrônica
Definição: paginação ou identificador bibliográfico para documentos que não tem paginação nos moldes tradicionais da publicação impressa.
O valor do campo pode ser um identificador do  artigo, DOI, ou por exemplo, um número precedido pela letra "e": E70; e51467

No caso de revistas online com publicação contínua (sem fascículos) essa modalidade de paginação é a mais utilizada e recomendada.

Ações:
1. Criar subcampo "e" no campo Páginas [14] para dado de paginação eletrônica.
2. Criar regra de consistência, não permitir que subcampo "e" seja preenchido em conjunto com subcampos "f" e "p" no campo [14].

Documentação de apoio:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-elocation-id.html
http://www.scielo.org/local/Image/guiarpass.pdf
http://dtd.nlm.nih.gov/publishing/tag-library/n-n6a0.html
http://wiki.bireme.org/intranet/index.php/Publicação_continuada_de_artigos_em_revista_LILACS

**Comment by viniciusandrade** [comment]
@sarahviola 

Disponível para avaliação no ambiente de testes.

[]s

**Comment by sarahviola** [comment]
Campo elocation ok.

@viniciusandrade 
Falta validação para quando preencher elocation não permitir preencher páginas ou número inicial e número final.

**Comment by viniciusandrade** [comment]
@sarahviola 

Validação incluída. Favor validar.

[]s

**Comment by sarahviola** [comment]
Validação ok.

Conversei com @suelisuga sobre possível necessidade de incluir campo elocation id também no nível monográfico [antigo campo 20], Se necessário, abriremos outra issue.
