### ISSUE TITLE
Criar campo "Origem - interoperabilidade"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#233]
Criar campo para receber dados de interoperabilidade:

Nome do campo: Origem - interoperabilidade
atributo i: ID de origem
atributo b: base de dados

Dependendo de origem do dado, campo "Status" será modificado.

Considerando que atualmente toda interoperabilidade vigente é relativa a LILACS-Express não é necessária nenhuma modificação nesse campo, porém no futuro haverá criação de novos tipos de status para acomodar os diferentes tipos de qualidade de dados coletados.

Exemplos de preenchimento adotados atualmente:

Coleta de Bioética e Diplomacia
Status:  "LILACS"
Origem - interoperabilidade:  "Dublin Core Extended - Bioética^i340"

Coleta de Fiocruz oriundo do isis oai provider
Status:  "LILACS-Express"
Origem - interoperabilidade:  "isis oai provider - Fiocruz^i1^bacervofar"

Fiocruz ARCA
Status:  "LILACS-Express"
Origem - interoperabilidade:  "MODS - ARCA^iID^bBASE

Considerando ser campo administrativo e seu preenchimento ser determinado internamente, ele:
-Não precisa ser editado pelo CC mas seria interessante de ser **visualizado** por ele.
-Não precisa de tabela de controle para preenchimento, pois ele é preenchido por ocasião da carga da coleta) - checar com @anakatiacamilo  mudança no procedimento
-Precisa aparecer em:

- "Todos registros"
- "Registros da minha rede", de acordo "Redes" do "Accounts" ou "Área Temática" @viniciusandrade como é atribuido aqui?
- "Registros de meu CC", de acordo com "Código do CC"
- "Indexado pelo meu centro" se status "LILACS-Express"
- Informes/Relatórios de contribuição do CC

Informações adicionais:
- http://wiki.bireme.org/intranet/index.php/Status_registros

**Comment by viniciusandrade** [comment]
Campo criado na estrutura do modelo de registro bibliográfio.
