### ISSUE TITLE
Criação de novos filtros para série peródica na visualização dos registros

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#234]
Para facilitar o acompanhamento da entrada de entrada de dados, criar filtros **Série periódica - Fonte** e **Série periódica - analíticas**.

Necessidade de FIR e talvez das coordenações nacionais e temáticas: 
- ter uma visão geral de que fascículos estão sendo incluídos na LILACS. (Como o sistema exibe a lista de analíticas, fica difícil ter essa visão).

**Comment by viniciusandrade** [comment]
@sarahviola 

Criado filtro por tipo de registro. Favor verificar se esta OK.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

Filtro ok. 

Com tinha conversado com vc, quando/se conseguir implementar o #127  , facilitará bastante para ter uma visão geral da entrada de dados.
