### ISSUE TITLE
Criar atributo k (Identificador de Autor) para Autor Pessoal

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#236]
Incluir no campo autor pessoal [10] o atributo "k" para inclusão de identificador persistente de autores pessoais (código ORCID).

Checar @anakatiacamilo outros IDs como VIAF, ISNI, ResercherID.

Link de referência:
http://wiki.bireme.org/intranet/index.php/ORCID

**Comment by viniciusandrade** [comment]
Levando em consideração que somente um subcampo não atende a necessidade pois um autor pode ter mais de um identificador (ex. Scopus e ORCID) e também que tenho dúvidas se este tipo de informação deve estar a nível de registro ou em separado em uma tabela somente de autoridades sugiro que este issue seja discutido quanto a melhor implementação.

**Comment by suelisuga** [comment]
@viniciusandrade sugiro criar subcampos no qual o documentalista informa a origem do identificador. Se ORCID, ResearcherID, Scopus ou outro.

Idealmente uma tabela controlada seria fundamental, mas estou me recordando que não era possível fazer isso em subcampos... ou estou enganada?

Outra possibilidade seria incluir os links, mas se o dado nao vem como link pronto também inviabilizaria...
![image](https://user-images.githubusercontent.com/13105683/53516360-e73e9380-3aaa-11e9-9c7f-3a67771c202d.png)
https://www.dur.ac.uk/library/research/disseminate/footprint/orcid/

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Quando possível favor validar esta implementação com a Suelli no ambiente de testes. 

Inicialmente foram criados 2 novos atributos para o autor: **ORCID** (k) e **Web of Science ResearcherID** (s).

Como não é possível implementar uma lista de tipos de ID's para o documentalista escolher teremos que priorizar os mais usados para adicionar no formulário. Caso tenha outro provedor de IDs que seja importante adicionar favor informar, evitando obviamente informar uma lista de provedores pouco usados.

Também foi implementado a validação para que o documentalista não insira nestes campos a url para o ID do autor, exemplo: https://orcid.org/0000-0001-99999-99999 não é valido, ele teria que informar 0000-0001-9999-9999.

A mensagem de erro para quando o usuário informar uma URL esta sem tradução pois somente consigo adicionar quando a implementação estiver OK.

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade verificamos e nos parece bem.
Pf. publicar na produção para que possamos finalizar a traducão e também o HELP.

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga ajuste publicado em produção.

Textos de ajuda devem ser adicionados diretamente em produção.

Abraços

**Comment by suelisuga** [comment]
@viniciusandrade estava em contato com o @falbrito agora e ele reportou que o atributo s já está em uso no campo 10. Vamos encontrar outro para o ResearcherID?

**Comment by viniciusandrade** [comment]
@suelisuga foi alterada o atributo para **w**.
