### ISSUE TITLE
Alterar a pesquisa de registros bibliográficos para não diferenciar maiúsculas de minúsculas

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#237]
![image](https://cloud.githubusercontent.com/assets/18355163/16986254/da1df5f8-4e5b-11e6-9f22-bbddfeeeab8f.png)

![image](https://cloud.githubusercontent.com/assets/18355163/16986273/f4097118-4e5b-11e6-8c21-e7901f44506d.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Alterado. Lembrar que a busca interna do sistema é bastante limitada comparada com as buscas das nossas interfaces não considerando operadores booleanos e buscas com aspas. 

[]s

**Comment by sarahviola** [comment]
Certo!

@viniciusandrade 
Falando nisso, está documentado em algum lugar como a pesquisa funciona? Dá pra usar prefixos de pesquisa ou fazer pesquisa por campos de alguma outra forma?
Sei que a pesquisa é mais limitada, mas a gente precisa pesquisar por outros campos além de título. Por exemplo, pesquisar por id.

**Comment by viniciusandrade** [comment]
@sarahviola 

Infelizmente não é possível a busca por campos, mas para auxiliar na recuperação eu adicionei a busca pelo ID do FI-ADMIN e pelo ID da LILACS (quando os registros forem importados). A sintaxe é:

id:<id FI-ADMIN>

LILACS_original_id:<LILACS ID>

**Comment by sarahviola** [comment]
Certo!
