### ISSUE TITLE
Não apresentar mensagem de duplicação quando é o próprio registro

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#241]
Somente ativar a verificação de duplicados se o usuário alterar o título do documento.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado para verificar possível duplicação quando o usuário entrar ou editar o campo de título para evitar mostrar a caixa de possível duplicação ao editar um registro que já foi publicado na LILACS.

**Comment by sarahviola** [comment]
Ok, não vi mais a mensagem de registro duplicado em registros que já estão na LILACS.
