### ISSUE TITLE
Filtro Tipo de registro só funciona para "Todos os registros"

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#242]
O resultado da pesquisa pelo filtro **Tipo de registro** sempre é aplicado na aba "_Todos os registros_", não importa em qual aba eu tenho feito a pesquisa. 

Por exemplo, ao filtrar, por "**Tipo de registro: Revistas - Fascículo**" na aba "_Meus registros_", o resultado exibido é para "Todos os registros", e não para os "Meus registros".

![image](https://cloud.githubusercontent.com/assets/18355163/17370846/135e6bd6-5974-11e6-95bc-21e1e1a8dc11.png)

![image](https://cloud.githubusercontent.com/assets/18355163/17370904/4f75d80c-5974-11e6-8b14-ca4a0e336f9c.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado. Quando possível favor avaliar.

[]s

**Comment by sarahviola** [comment]
Ok, filtro funcionando em todas as abas.
