### ISSUE TITLE
Fi-admin title duvidas de campo

### ISSUE THREAD

**Issue by menezesre** [bireme/fi-admin#25]
Na Base Title microisis, aparece os campos

005 tipo de registro é preenchido automaticamente (S)
006 Nivel de tratamento é  preenchido automaticamente (s)
010 Codigo do centro   preenchido automaticamente BR1.1
941 DATA DE MODIFICAÇÃO DO REGISTRO preenchido automaticamente
951 DOCUMENTALISTA QUE ALTEROU preenchido automaticamente

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade.
