### ISSUE TITLE
Habilitar criação de helps no Django Admin para LIS, DirEve e Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#251]
Pf. habilitar criação de helps no Django Admin para LIS, DirEve e Multimedia

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga,

Ajustes realizados. Quando possível favor validar.

Obrigado

**Comment by sarahviola** [comment]
Habilitado e funcionando corretamente.
