### ISSUE TITLE
Criar relatório de Revistas LILACS-Express por país

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#255]
#Solicito criação de relatório de revistas LILACS

Campos:
|Revistas (título abreviado) | Usuários (LLLXPEDT) | País | Código Editor | Código CC Indexador |

sendo Usuários: LILACS-Express Editor - FI-Admin ou LLXPEDT-FIA

Chamado relacionado a chamado: #35

Muito obrigada

Suel M Yano Suga
BIREME/OPAS/OMS

**Comment by wilsonmoura** [comment]
Realizado em #35

**Comment by wilsonmoura** [comment]
Realizado em #254 #255 #258
