### ISSUE TITLE
Implantar auditoria/histórico de mudanças realizadas nos registros TITLE

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#256]
Implantar "serviço" de auditoria/histórico de mudanças realizadas nos registros TITLE.
Realizar da mesma maneira como ocorre em Registros Bibliográficos:
Data, nome de usuario e mudanças realizadas.

Obrigada

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by wilsonmoura** [comment]
Realizado em #510
