### ISSUE TITLE
Checar se existem campos 30 diferentes de 37 na base de dados da Title

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#257]
Impacto: todos os arquivos 001 e 002 enviado pela rede é baseado no campo 37 da secs. Se o processamento da geração da base isis da SECS for baseado no campo 30 pode ter relacionamentos equivocados.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
