### ISSUE TITLE
Criar relatório de Revistas por Situação da Publicação

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#258]
Criar relatório de Revistas por Situação de Publicação
Campo:
*Situação da publicação: Corrente, Desconhecido, Suspenso ou Encerrado

Relacionado com chamado #35 

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by wilsonmoura** [comment]
@suelisuga favor validar relatório conforme solicitado.

**Comment by sarahviola** [comment]
Relatório funcionando.
