### ISSUE TITLE
Traduzir campos para espanhol e português em Eventos e Multimídia

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#265]
**Eventos**
- Start date
 - Português = Data de início
 - Espanhol = Fecha inicial

- End date
 - Português = Data de término
 - Espanhol = Fecha final

**Multimídia**
- Publication date
 - Espanhol = Data de publicación
 - Português = Data de publicação

- Publisher
 - Espanhol = Editorial

**Comment by sarahviola** [comment]
@viniciusandrade 
A @suelisuga pediu a tradução desses campos para produzir materiais para os cursos das Fontes de Informação. Então, se possível, dar prioridade a essa issue.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/dec069723cdb5d90b0aab9e2bbcf9a5ddc052049
