### ISSUE TITLE
Incluir help no formulário: campo Autor

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#271]
Incluir no campo Autores:

Insira um por linha. Somente preenchido se diferente do originador do recurso.
Enter one per line.  Only filled if different from the originator of the resource.
Introduzca uno por linea. Llenado sólo si diferente del originador del recurso.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/c445519f66c42767eed9133e3cf007190694c385
