### ISSUE TITLE
Incluir help no formulário: campo Resumo

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#272]
Campo Resumo:

Incluir informações sobre o conteúdo e funcionamento do recurso de internet
Include information on the content and operation of the internet resource
Incluir información sobre el contenido y el funcionamiento del recurso de Internet

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/c445519f66c42767eed9133e3cf007190694c385
