### ISSUE TITLE
Incluir help no formulário do DirEve: campo Título

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#280]
Texto do help para campo Título:

Incluir nome completo do evento, da forma como aparece e no mesmo idioma. Ex: XIX Congresso Brasileiro de Arritmias Cardíacas. XVII Simpósio Nacional do DECS-SBCC

Enter the full name of the event, as it appears and in the same language. Ex: XIX Congresso Brasileiro de Arritmias Cardíacas. XVII Simpósio Nacional do DECS-SBCC

Incluir el nombre completo del evento, tal como aparece y el mismo idioma. Ex: XIX Congreso Brasileño de arritmias cardíacas. XVII Simposio Nacional DECS-CCSYC

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/12412268b89144d93e999bb071395a9d8c78a5f5
