### ISSUE TITLE
Incluir help no formulário do DirEve: campo Observações

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#283]
Incluir informações de instituições que organizam e/ou patrocinam o evento, prazo para submissão de trabalhos, serviço de tradução simultânea, programa do evento, etc.

Enter information about institutions that organize and/or sponsor the event, deadline for submission of papers, simultaneous translation service, event program, etc.

Incluir información de instituciones que organizan y/o financian el evento, fecha límite para la presentación de manuscriptos, servicio de traducción simultánea, programa del evento, etc.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/12412268b89144d93e999bb071395a9d8c78a5f5
