### ISSUE TITLE
Campo Endereço do DirEve completa com Undefined e não apresenta mapa do Google

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#284]
Eventos descritos com endereço estão apresentando mudança de dado para Undefined e mapa do Google não é apresentado.

-ID 19214 - VI Simpósio da Primavera - undefined, sn, undefined - mapa apresentava marco zero de SP.
-ID19129 - South Summit: innovation is now! - Calle Cifuentes, 5, undefined - não apresentava mapa

**Comment by viniciusandrade** [comment]
@suelisuga 

Ajustes realizado no formulário de entrada de dados. Favor realizar novos testes para validar se agora esta OK.

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade realizei 3 testes e tudo funcionou bem.

Agradeço correção

Sueli

**Comment by suelisuga** [comment]
Olá Vinicius,

O mesmo problema voltou a acontecer.

Um exemplo: ID 22313

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Testes realizados na data de hoje não apresentam problema com o preenchimento do campo de endereço para eventos.

Caso o problema ocorra novamente favor informar navegador e versão para que eu possa realizar novos testes.
