### ISSUE TITLE
Incluir check de duplicados no DirEve

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#285]
Um mesmo evento é incluido no DirEve pelo menos 4 vezes.
Possuem mesma data de inicio e fim, mesma URL porém titulo varia um pouco.

Exemplo:
-ID 19132 - 21ª Conferência Mundial dos Médicos de Família da WONCA - BR440.1
http://www.wonca2016.com/index.php

-ID 18862 - 21 ª Conferência Mundial WONCA de Médicos de Família - BR15.3
http://www.wonca2016.com/index.php

-ID 16205 - 21 ª Conferência Mundial WONCA de Médicos de Família - BR79.1
http://www.wonca2016.com/index.php

-ID16091 - WONCA 21 ª Conferência Mundial - BR440.1
http://www.wonca2016.com/index.php

Obrigada

Sueli

Ps. Não sabia quem marcava, inclui @viniciusandrade e @heitorbarbieri

**Comment by viniciusandrade** [comment]
Criado issue para uso do serviço DeDup: https://github.com/bireme/DeDup/issues/14

**Comment by viniciusandrade** [comment]
@suelisuga 
Integração com serviço de verificação de duplicados realizado para eventos.

Favor, quando possível validar.

**Comment by AngelicaSAPaula** [comment]
Criei um novo evento com as mesmas informações de um já existente

![image](https://user-images.githubusercontent.com/47643830/82921417-bae42200-9f4e-11ea-9fbc-0f5ef19815d1.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula, 

Desculpe agora que percebi pelo seu print que atualizei o ambiente de produção e havia esquecido de atualizar a teste.

Poderia, quando possível, verificar novamente?

Obrigado e desculpe.

**Comment by AngelicaSAPaula** [comment]
Uma vez que preencho o nome e a data do evento, ele dá o recado de possível duplicação!

![image](https://user-images.githubusercontent.com/47643830/82941679-2a690a00-9f6d-11ea-8c3e-0a2eb4ac77fc.png)

**Comment by viniciusandrade** [comment]
OK, este é o comportamento esperado. Ajuste já se encontra em produção. 
Obrigado pelo teste
