### ISSUE TITLE
Inclusão de horario na data do evento

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#286]
Solicito que ao definir o dia de inicio e fim do evento, fosse possível incluir horário de início e fim da programação do evento.

Obrigada

Sueli

**Comment by viniciusandrade** [comment]
Razões para não implementação:
1. Para eventos que ocorrem em múltiplos dias não ficaria claro para o usuário o horário de ínicio e término
2. Seria mais um campo não obrigatório que o documentalista pode não informar
3. O objetivo do diretório é redirecionar o usuário para ver os detalhes e programação no site do evento.
