### ISSUE TITLE
Criar Tabela de ID

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#288]
Criar uma lista para controlar os ID do mesmo documento que está em diferentes bases de dados.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/fbc1ddd09ab141bfb9dd900d1362eed75a8a5368 

@anakatiacamilo 

Por favor verifique a solução no ambiente de testes do FI-Admin para validar se atende a necessidade de armazenamento dos ID's alternativos.

Para efeito de visualização esta disponível no Django Admin o link para verificar a tabela criada.


[]s

**Comment by viniciusandrade** [comment]
Adicionado na saída da API o campo 779 com os ID's alternativos de uma referência.

**Comment by anakatiacamilo** [comment]
Vini, importamos o dado na instância de curso e tudo esta funcionando bem.
