### ISSUE TITLE
Filtro de data de modificação na API

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#291]
Na API da fonte de Referencia Bibliográfica incluir um filtro de data de modificação

**Comment by viniciusandrade** [comment]
@anakatiacamilo e @falbrito 

Favor avaliar a aplicação do filtro por data de atualização do registro. O parâmetro é o **updated_time** e esta documentado na [wiki](https://github.com/bireme/fi-admin/wiki/API).

[]s

**Comment by falbrito** [comment]
Testes funcionaram corretamente

* Utilizando updated_time__gte:
http://fi-admin.curso.bvsalud.org/api/bibliographic/?status=1&format=isis_id&limit=10&updated_time__gte=2016-11-10

* Utilizando updated_time__lte:
http://fi-admin.curso.bvsalud.org/api/bibliographic/?status=1&format=isis_id&limit=10&updated_time__lte=2016-11-10

**Comment by viniciusandrade** [comment]
OK, obrigado pela validação.
