### ISSUE TITLE
Na API da Referencia Bibliográfica no campo de Descritores exportar o texto

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#292]
Na API da Referencia Bibliográfica no campo de descritores primários e secundários quando não tiver o código exportar o texto segue exemplos do XML do iahx.  

```
<field name="mj">^dBALLOON DILATATION</field>
<field name="mj">^dNEOPLASMAS DE LA TRAQUEA</field>
<field name="mj">^dBALLOON DILATATION</field>
<field name="mj">^dSAUDE INFANTIL (SAUDE PUBLICA)</field>
```

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Ajuste realizado na API e disponível nos ambientes de teste e cursos, por favor quando possível realizar a validação.

[]s
