### ISSUE TITLE
Incluir em Relatórios a opção Relatório: Documentos por Revista

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#293]
Criar relatório para "Registros Bibliográficos" a opção Relatório: Documentos por Revista e apresentar:

Campos:
Revista (Título abreviado) | Volume | Número | Quantidade de Registros Pendentes (Indexado pelo meu CC) | CC indexador | Código Editor | 

Justificativa: criar relatório de acompanhamento de cooperação LILACS-Express por revista e CC

**Comment by viniciusandrade** [comment]
Disponível no ambiente de testes para avaliação. Favor realizar testes e informar se esta OK.

**Comment by sarahviola** [comment]
@viniciusandrade  
Não entendi muito bem esse relatório (ou o resultado não está correto mesmo).

Executando o relatório "**LILACS-Express por revista**" na instância de teste com o meu usuário sarah.viola do BR1.1, perfil editor, é exibido no relatório somente:
![image](https://cloud.githubusercontent.com/assets/18355163/24770679/31b9641c-1ae1-11e7-88c8-5b7327916853.png)

A instância de teste tem hoje 3365 registros com status LILACS-Express. Não deveria ter aparecido todas as revistas? Ou é feito algum filtro por revistas do meu país, ou dos CC da minha rede?

**Comment by viniciusandrade** [comment]
@sarahviola 

Realmente o código estava com o filtro errado. Revisei e também ajustei para pegar o código do centro responsável pela indexação da aba "Cobertura de indexação" da Title.

Quando possível favor realizar novo teste. Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade ,

Quando eu executo o relatório LILACS-Express por revista, o sistema exibe, depois de bastante tempo, a mensagem de erro "Server Error (500)".

Pensei que poderia ter relação com as alterações no servidor de ontem/hoje, mas os outros relatórios estão funcionando.

**Comment by viniciusandrade** [comment]
@sarahviola 

Conforme conversamos em conjunto com a @suelisuga o agrupamento do relatório foi alterado para título da revista para ser possível a geração do relatório em produção.

Já esta disponível no ambiente de produção para testes.

**Comment by sarahviola** [comment]
@viniciusandrade 

Ok, agora está correto. 

Seria possível traduzir os nomes dos campos de acordo com o idioma em uso?
Indexer_cc
Source__title_serial
Num_pending

![image](https://cloud.githubusercontent.com/assets/18355163/25341736/39ed887c-28e0-11e7-8827-0b5989cabe29.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

OK, tradução dos campos realizada e disponível para validação no ambiente de testes.

**Comment by sarahviola** [comment]
@viniciusandrade 

No inglês, alterar o nome do relatório de LILACS-Express by serial por **LILACS-Express by journal**.

Além disso, alterar também os nomes dos campos:
* Indexer_cc > **Indexer center**
* Source__title_serial > **Journal title**
* Num_pending > **Total pending**

**Comment by viniciusandrade** [comment]
@sarahviola 

Infelizmente o sistema não esta permitindo alterar o nome original dos campos que são apresentados no idioma inglês. Terá que ficar desta forma até que eu encontre uma forma e então posso revisar mais para frente este código.

**Comment by sarahviola** [comment]
@viniciusandrade 

Ok.

Mas o nome do relatório de "LILACS-Express by serial" para **LILACS-Express by journal** dá pra alterar, certo? Foi alterado no relatório de revistas por país.

**Comment by viniciusandrade** [comment]
@sarahviola 

OK,corrigido nome do relatório no idioma inglês. (disponível no ambiente de testes)

[]s
