### ISSUE TITLE
Tirar "Sugestões" do menu "Fontes de Informação"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#299]
Atualmente "Sugestões" está no menu "Fontes de Informação".
Penso que deveria ficar antes ou depois de "Relatórios".

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@sarahviola / @suelisuga 

Ajuste realizado. Quando possível favor validar.

Obrigado.

**Comment by sarahviola** [comment]
Ok na produção. Obrigada.

![image](https://user-images.githubusercontent.com/18355163/29178873-381641c2-7dc9-11e7-915f-2e05fcda61c6.png)
