### ISSUE TITLE
Histórico de mudanças não está registrando alterações no campo Indexado em

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#302]
Ao incluir ou excluir alguma base de dados do campo **Indexado em**, as alterações não são registradas no **Histórico de mudanças**. 

Exemplo: registro ID [1834](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/1834). Algum usuário (provavelmente o doc1, que fez outras alterações em 25 de novembro de 2016) selecionou a base de dados **Sec. Munic. Saúde SP** no campo **indexado em**. Em 9 de dezembro de 2016, katia.camilo retirou essa base de dados desse campo. Ambas as alterações não apareceram no histórico de mudanças.

**Comment by viniciusandrade** [comment]
@sarahviola 

Quando possível favor verificar no ambiente de testes se agora esta registrando as alterações no campo **indexado em**.

Obrigado

**Comment by sarahviola** [comment]
Alterações estão sendo salvas.
Favor atualizar na produção.
![image](https://cloud.githubusercontent.com/assets/18355163/21504411/e0ef27ae-cc45-11e6-9c16-0b9e2e2d67ed.png)

Obrigada.

**Comment by viniciusandrade** [comment]
Atualizado em produção. 

Obrigado.
