### ISSUE TITLE
Criar campo coleção

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#303]
Objetivo do campo é facilitar a categorização das normas, deve ser do tipo lista controlada.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/02649fbfd8685151cb14ddb01530c6f982e5295f

**Comment by renatomurasaki** [comment]
Para registro, o campo coleção foi criado para auxiliar na categorização temática das normas, tais como tabagismo, nutrição, álcool etc.
