### ISSUE TITLE
Não permite alterar e salvar alguns registros provenientes da importação LILACS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#308]
Ao editar o registro e tentar salvar apresenta o erro:

Para status "Publicado"  é necessário ter pelo menos um descritor primário.

Exemplo de ID com problema: 251859.

**Comment by viniciusandrade** [comment]
Identificado que o problema nestes tipos de registros é que na conversão os descritores não foram corretamente identificados no DeCS e portanto não foi informado o código do termo ficando somente o campo de texto com o termo. Isto impacta a validação no arquivo de validação cruzada de campos "cross_validation".

**Comment by viniciusandrade** [comment]
@suelisuga 

Realizado ajuste no sistema. Poderia validar no ambiente de testes usando como exemplo o mesmo registro ID: 251859 que também esta disponível neste ambiente.

Obrigado

**Comment by sarahviola** [comment]
Agora é possível editar o registro id 251859.

**Comment by viniciusandrade** [comment]
Atualizado em produção. Obrigado.
