### ISSUE TITLE
Registros publicados em LILACS estão apresentando mensagem de erro de inexistência de descritores primários

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#309]
Registros publicados em LILACS estão apresentando mensagem de erro de inexistência de descritores primários.
O comportamento esperado é que todo registro publicado já identifique a presença de descritores primários (conforme informado por desenvolvedor, com status admitido).

Obrigada!

Sueli Mitiko Yano Suga

**Comment by viniciusandrade** [comment]
@suelisuga 

Identifiquei que o problema é que no processo de conversão estes descritores não foram localizados no DeCS e portanto não foi assinalado o código do descritor correspondente.

Criei o ticket #308 para tratar flexibilizar a validação e não exigir que o descritor tenha código para contemplar estes casos. 

Estou fechando este ticket e você pode acompanhar a solução do problema  #308.
