### ISSUE TITLE
Incluir na API que exporta registros isis_id o campo de Localidade.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#310]
Na LILACS o campo Localidade [3] - No FI-ADMIN na tabela `biblioref_referencelocal` o campo  `call_number`;

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Quando possível favor validar no ambiente de testes. 

Obrigado.

**Comment by viniciusandrade** [comment]
Atualizado em produção com a correção conforme exemplo abaixo:

http://fi-admin.bvsalud.org/api/bibliographic/?format=isis_id&LILACS_original_id__in=205
