### ISSUE TITLE
Criar mensagem de recomendação de uso de browser Firefox ou Chrome

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#311]
Solicito criação de mensagem no FI-Admin para uso de browser Firefox ou Chrome.

A atividade de indexação dentro do sistema não responde bem dentro do browser Internet Explorer.
![image](https://cloud.githubusercontent.com/assets/13105683/21427517/307f66b6-c83c-11e6-82f1-d4871167885c.png)

**Comment by viniciusandrade** [comment]
@sarahviola / @suelisuga 

Foi adicionado informação de navegadores preferidos na tela inicial do sistema. Favor verificar.

Obrigado

**Comment by sarahviola** [comment]
ok. Obrigada. 

![image](https://user-images.githubusercontent.com/18355163/29178706-bd3229f8-7dc8-11e7-8ef8-6b5b57d5d62f.png)
