### ISSUE TITLE
A definição do nome da base de dados no campo "Indexado em" deve ser obrigatório?

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#312]
Prezados,

Estamos tendo ocorrência de criação de registros LILACS sem a seleção desse nome de base no campo "Indexado em". Sabemos que são registros LILACS porque ainda não temos no FI-Admin registros criados para bases externas.

Penso que esse campo deveria ser obrigatório e sempre que o usuário do sistema esquecer de selecionar a base, apresentar uma mensagem de erro do tipo "Selecionar em qual base de dados esse registro será publicado no campo "Indexado em"."

A dúvida que persiste para a obrigatoriedade desse campo é para os casos em que houver criação de registros de um acervo local, pois não haveria uma opção de base para elas nessa lista controlada de bases de dados. Minha sugestão é que se crie um nome de base genérico no qual todas as bases institucionais serão incluídas e, depois, especificadas na aba Biblioteca. Sugestões de nome da base:  Base Institucional, Base Local, Acervo Local ou Acervo Institucional.

Outra opção seria deixar o campo não obrigatório, mas criar uma mensagem de alerta que lembre o usuário de fazer a seleção da base. Ex: "Ao gravar esse registro você está criando um registro que não será publicado em nenhuma base de dados da BVS. Verificar o campo "Indexado em" para correção, se necessário".

![fi-admin-indexado-em](https://cloud.githubusercontent.com/assets/13105683/21435546/8fa2e710-c861-11e6-9876-91e7795acb29.JPG)
.
Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Em consulta ao Renato ele concordou com sua sugestão de tornar o campo obrigatório e também na criação de uma nova opção para que o usuário possa informar caso seja um registro do acervo local.

Ele também sugeriu que para as revistas indexadas em LILACS ao carregar o formulário de ingresso de uma nova analítica o valor LILACS seja automáticamente selecionado para o campo "indexado em". Foi criado o issue #319 para este tema.

Foi alterado o campo para obrigatório no ambiente de teste. Favor criar o novo valor para acervo local no Django admin e proceder com a validação para que eu aplique a alteração em produção.

Obrigado.

**Comment by sarahviola** [comment]
Validação de campo obrigatório ok.

Entretanto, o campo já é obrigatório para salvar registros com status rascunho. Sugiro que validação seja alterada para ser obrigatório apenas para status **LILACS-Express** (que devem ser sempre indexado em LILACS) e **Publicado**.

Para criação do valor para o acervo local já no Django Admin da produção, sugiro esperar a Sueli voltar de férias para definir um dos nomes sugeridos. Como por enquanto os CC só estão usando o FI-Admin para cooperação com LILACS, creio que não terá problema esperar.

Nomes sugeridos:
* Base Institucional (eu escolheria esse nome)
* Base Local
* Acervo Local
* Acervo Institucional

**Comment by viniciusandrade** [comment]
@sarahviola 

Foi alterado para obrigatório somente quando o registro for publicado. Favor confirmar com a @suelisuga o nome da base local e registrar no Django Admin para que possamos encerrar este ticket.

Obrigado

**Comment by sarahviola** [comment]
Registrada sigla **InstitutionalDB** no django admin.
