### ISSUE TITLE
Possível perda de dados em edição de registros migrados da LILACS

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#313]
Ao editar o registro id **251859**, migrado da LILACS para o FI-Admin, notei que aparece em "Histórico de mudanças" alteração do dado registrado para vazio nos seguintes campos:
Data de transferência para base de dados: 2013-06-13 → 
Data de publicação normalizada: 20130400 → 
Data de publicação: Mar-Apr/2013 → 

O primeiro campo é não editável pelo sistema, O segundo e terceiro campos são editáveis via sistema apenas no registro fonte, mas esse registro é uma analítica.

![image](https://cloud.githubusercontent.com/assets/18355163/21507027/2323ef04-cc5c-11e6-90fd-d88eef767d3a.png)

Problema identificado ao validar a issue #308 .

**Comment by viniciusandrade** [comment]
Acredito que identifiquei o problema juntamente com a @anakatiacamilo:

Ao migrar os registros da LILACS para o FI-ADMIN os registros das analíticas foram com os dados completos, incluindo informações do FONTE, como os campos de data de publicação e data de publicação normalizada, mas na realidade estes campos devem ser lidos do FONTE somente no momento de exportar este registro e por isso eles não devem aparecer no formulário de entrada.

O sistema assume que houve a remoção do conteúdo destes campos por eles não estarem no formulário, o que esta OK uma vez que na exportação eles serão copiados novamente do FONTE.

A única exceção era o campo de data de transferência para base de dados que estava realmente perdendo o conteúdo mas foi corrigido.

Portanto, resumindo quando for a edição de um registro migrado da LILACS deve ocorrer este comportamento, nos registros novos não. A Katia irá ajustar a migração para nos próximos registros importados já não importar estes campos de data.

[]s
