### ISSUE TITLE
Implementar regra de campos do registro FONTE que devem ser exportados nas analíticas

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#317]
Atualmente o sistema exporta todos os campos do registro FONTE que não possuem valor no registro da analítica. 

É necessário restringir os campos que são exportados do FONTE de acordo com o tipo de literatura/nível de tratamento.

**Comment by anakatiacamilo** [comment]
Por Tipo:
- Série Periódica (Sas)
Base de dados [4];
Título (Nível Série) [30];
Volume (Nível Série) [31];
Número do fascículo (Nível Série) [32];
ISSN (Nível Série) [35];
Data da Publicação [64];
Data Normalizada [65].

- Série Monográfica (MS)
Base de dados [04];
Tipo de registro [09];
Título (Nível Série) [30];
Volume (Nível Série) [31];
Número do fascículo (Nível Série) [32];
ISSN (Nível Série) [35];
Autor Pessoal (Nível Monográfico) [16];
Autor Institucional (Nível Monográfico) [17];
Título (Nível Monográfico) [18];
Título Traduzido para o Inglês (Nível Monográfico) [19];
Páginas (Nível Monográfico) [20];
Editora  (Imprenta) [62]
Edição  (Imprenta) [63]
Data de Publicação  (Imprenta) [64]
Data Normalizada  (Imprenta) [65]
Cidade de Publicação  (Imprenta) [66]
País de publicação  (Imprenta) [67]
Símbolo  (Imprenta) [68]
ISBN  (Imprenta) [69]

**Comment by viniciusandrade** [comment]
@anakatiacamilo,

Dei uma simplificada criando uma única lista com todos os campos que você informou acima, pois acredito que como a regra dos campos já esta no sistema na entrada da dados não seria necessário implementar novamente na exportação. Será que estou correto?

O ajuste esta aplicado nos ambientes de teste e curso.

@falbrito, quando puder você pode realizar alguns testes usando aqueles casos que você identificou por email e também alguns outros de outros tipos de documentos?

Obrigado
Vinicius

**Comment by falbrito** [comment]
Ok, trazendo agora o registro correto. Obrigado
