### ISSUE TITLE
Opções do campo Título acadêmico aparecem sempre somente no idioma principal

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#322]
As opções do campo **Título acadêmico** foram criadas em inglês e foram adicionadas as traduções para espanhol e português, como no exemplo abaixo:
![image](https://cloud.githubusercontent.com/assets/18355163/22346996/46edd000-e3ed-11e6-9af7-07a7a6a313a2.png)

Entretanto, as opções são exibidas sempre em inglês, mesmo utilizando a interface do FI-Admin em português:
![image](https://cloud.githubusercontent.com/assets/18355163/22347223/4eb0159a-e3ee-11e6-9ad6-c368fe2d2ba1.png)

O sistema deveria exibir os rótulos no idioma em uso na interface do sistema.

**Comment by viniciusandrade** [comment]
Ajuste realizado. Quando possível favor validar.

**Comment by sarahviola** [comment]
Agora está a lista está aparecendo corretamente, com os títulos de acordo com os idiomas.

Entretanto, só é possível gravar registros utilizando a interface em inglês. Usando as interfaces em português ou espanhol, que usam as traduções da tabela, ao gravar o registro aparece uma mensagem de erro que o dado é incompatível com a LILACS.

![image](https://cloud.githubusercontent.com/assets/18355163/22928387/6148e9a8-f29d-11e6-8e09-e87768fa5cda.png)

**Comment by viniciusandrade** [comment]
Validação alterada para levar em consideração os valores permitidos de acordo com a interface do sistema.

O ponto negativo é que os registros criados em um idioma precisam ser alterados no mesmo idioma de sua criação para não ocorrer o erro de validação do campo.

**Comment by sarahviola** [comment]
@viniciusandrade 

Favor ajustar a mensagem de erro do campo.

Ao invés de escrever somente "Incompatível com LILACS", explicar que título acadêmico precisa estar no idioma da interface.

**Comment by viniciusandrade** [comment]
@sarahviola 

Achei melhor alterar a validação para levar em consideração todos os títulos acadêmicos nos diferentes idiomas. Desta forma só irá apresentar a mensagem se o informado pelo usuário não constar na lista de valores em qualquer idioma. 

Quando possível favor validar no ambiente de testes.

**Comment by sarahviola** [comment]
Ótimo. Testei e está funcionando dessa forma.
