### ISSUE TITLE
Problema na edição de registro Fonte de série periódica migrado da LILACS

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#323]
Ao tentar editar o registro id 651684 aparece a mensagem de erro: "Por favor verifique os erros abaixo", mas não aparece qual o erro. Aparentemente o registro não tem problemas.

![image](https://cloud.githubusercontent.com/assets/18355163/22464971/959f618a-e7a0-11e6-974b-c71ca4e2c621.png)

**Comment by sarahviola** [comment]
Tentei editar um registro LILACS-Express criado no FI-Admin e também aparece o mesmo erro.
Exemplo: id [831505](http://fi-admin.bvsalud.org/bibliographic/edit-source/831505)

**Comment by viniciusandrade** [comment]
@sarahviola,

Acredito que tenha sido decorrente da mudança do campo "indexado em" para obrigatório. Já realizei o ajuste e alterei o comportamento de acordo com o que você havia solicitado em #312, ou seja, somente exigir quando o registro for ser publicado. 

Poderia realizar novo teste para validar que com isso foi resolvido o bug descrito neste issue?

Obrigado

**Comment by sarahviola** [comment]
Certo, agora consegui gravar os dois registros.

Dúvida: no registro fonte id 651684 alterei, a pedido do CC responsável pela indexação, a data de publicação. Para que a data seja atualizada nas analíticas, eu preciso gravar cada uma das analíticas. Certo?

**Comment by viniciusandrade** [comment]
Em realidade não seria necessário uma vez que o sistema ao exportar sempre irá pegar este campo do FONTE, mas para que estes registros sejam novamente coletados pelo @falbrito será necessário entrar nas analíticas e gravar porque ele utiliza a data de última atualização do registro no processamento.

**Comment by sarahviola** [comment]
Certo! 
@suelisuga, precisamos documentar.
