### ISSUE TITLE
Título em inglês não deveria ser obrigatório para registros LILACS-Express

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#324]
Não consegui editar um registro LILACS-Express porque o preenchimento do título em inglês é obrigatório, e ele só tem título em português. 
Não vou incluir este dado porque é de responsabilidade do CC indexador. (registro id [827448](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/827448))

Pelo primeiro comentário da issue #99 , título em inglês não deveria ser obrigatório para registros LILACS-Express. Deve ser obrigatório somente em registros com status Publicado.

**Comment by viniciusandrade** [comment]
Ajuste de validação realizada para não obrigar a informação de título em inglês quando for um registro LILACS-Express. Quando possível favor validar.

**Comment by sarahviola** [comment]
Certo, agora voltou a não ser mais obrigatório.
