### ISSUE TITLE
Erro ao incluir registros com carregamento de PDF

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#325]
Ao incluir registros com upload de arquivos, os editores de revistas LILACS-Express reportaram aparecer "Server Error (500)" na tela.

Os registros eram gravados com status LILACS-Express, mas sem PDF (o que não deveria acontecer).

Além disso, alguns usuários reportaram ter artigos duplicados por causa desse erro.

**Comment by viniciusandrade** [comment]
Para documentação este erro foi ocasionado devido a falta de permissão no servidor para a gravação dos arquivos. Já foi solicitado junto ao suporte e as permissões para a pasta **/uploads/** foram corrigidas.
