### ISSUE TITLE
API está trazendo campo de base de dados duplicado

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#326]
Vinícius verifiquei um registro que foi atualizado no FI-ADMIN e está vindo o campo v4 em duplicidade para o conteúdo REPOSITORIOBVS. ( http://fi-admin.bvsalud.org/api/bibliographic/?format=isis_id&LILACS_original_id__in=242063 )

Procurei no MySQL e para o vínculo na tabela biblioref_reference_indexed_database tem o seguinte:

SELECT * FROM `biblioref_reference_indexed_database` WHERE reference_id = '681172';
    id  reference_id  database_id  
------  ------------  -------------
833682        681172              1  <-LILACS
833683        681172             18  <-REPOSITORIOBVS

Poderia verificar no SELECT da API para ver se existe alguma correção?

Obrigado

**Comment by viniciusandrade** [comment]
@falbrito 

Verifiquei pelo FI-ADMIN que este registro possui no campo base de dados da aba de coleção para a biblioteca BR1.1 os seguintes valores:

NLM
MEDLINE
REPOSITORIOBVS

Neste caso a API esta trazendo primeiro as bases do campo "indexado em" e depois as bases do campo "base de dados" da biblioteca BR1.1.

Caso esteja de acordo com esta explicação favor fechar o issue.

Abraços

**Comment by falbrito** [comment]
Essa aparição se dá na base local pois é necessário para identificar a coleção para o processamento. Porém estamos arrumando o campo "indexado em" e como são conteúdos diferentes em algum momento no futuro precisarão ser separado em campos diferentes na API - pendencia para o futuro.
