### ISSUE TITLE
Falta de mensagem de erro ao preencher incorretamente o campo de data de publicação de registos Fonte de série periódica

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#327]
Ao preencher incorretamente o campo de data de publicação de registos Fonte de série periódica (S), sem o ano de publicação nos últimos 4 caracteres, o sistema não exibe mensagem de erro de preenchimento incorreto do campo, mas também não permite gravar o registro.

![insercao_lilacs](https://cloud.githubusercontent.com/assets/18355163/22931241/1049f7a0-f2ab-11e6-8374-f3536085ab49.jpg)

![server_error](https://cloud.githubusercontent.com/assets/18355163/22931247/11e313da-f2ab-11e6-9578-8efeca65c822.jpg)

O correto seria exibir uma mensagem de erro informando que o campo de Data de publicação não foi preenchido corretamente, com, se houver, mês de publicação seguido do ano.

**Comment by viniciusandrade** [comment]
Ajustes de validação relizados e disponíveis no ambiente de testes para validação.

**Comment by sarahviola** [comment]
Resolvido.
![image](https://cloud.githubusercontent.com/assets/18355163/24768811/77ff614e-1ada-11e7-9a82-e2493c34a96b.png)
