### ISSUE TITLE
Aumentar tamanho de campo Link no DirEve

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#329]
Solicito que o tamanho do campo link seja aumentado, pois houve um link de evento que ficou cortado e o link quebrou no plug-in DirEve.

Exemplo:
http://www.sahealth.sa.gov.au/wps/wcm/connect/public+content/sa+health+internet/health+reform/health+in+all+policies/health+in+all+policies+events/health+in+all+policies+and+the+sustainable+development+goals#Conference%20program

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado. Favor validar.

**Comment by sarahviola** [comment]
Resolvido.

Editei o registro desse mesmo evento no FI-Admin em produção e agora o link correto, inteiro, é gravado.
