### ISSUE TITLE
Aumentar o tamanho do campo Link no LIS (Recursos)

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#330]
Solicito que o tamanho do campo link seja aumentado (atualmente comporta 200 caracteres), pois o link pode ficar cortado e quebrado no plug-in LIS

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
O LIS não possui o problema de limite no campo de link pois utiliza uma caixa de entrada de múltiplas linhas possibilitando a entrada de mais de um link e com tamanhos superiores aos 200 caracteres.
