### ISSUE TITLE
Aumentar tamanho do campo Link no Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#331]
Solicito que o tamanho do campo link seja aumentado (atualmente comporta 200 caracteres), pois o link pode ficar cortado e quebrado no plug-in Multimedia

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado, padronizado para 255 caracteres. Quando possível favor validar.

**Comment by sarahviola** [comment]
Resolvido. FI-Admin está gravando até 255 caracteres no campo de URL.
