### ISSUE TITLE
Aumentar tamanho do campo URL na aba Texto completo no Leyes

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#332]
Solicito que o tamanho do campo URL na aba Texto Completo seja aumentado (atualmente comporta 200 caracteres), pois o link pode ficar cortado e quebrado no plug-in LeisRef

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/d57f97bb9a270667addd19343961649b2c6ff3be
