### ISSUE TITLE
Aumentar tamanho do campo Endereço Eletrônico na aba Texto Completo de Registros Bibliográficos

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#333]
Solicito que o tamanho do campo Endereço Eletrônico na aba Texto Completo de Registros Bibliográficos seja aumentado (atualmente comporta 200 caracteres), pois o link pode ficar cortado e quebrado no iAHx da fonte de informação.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Verificado e ajustado por configuração da aplicação.
