### ISSUE TITLE
Aumentar tamanho do campo URL na aba Recurso Online da fonte Revistas (TITLE)

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#334]
Solicito que o tamanho do campo URL na aba Recurso Online da fonte Revistas (TITLE) seja aumentado (atualmente comporta 200 caracteres), pois o link pode ficar cortado e quebrado no portal de revistas.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@wilsonmoura realizou o ajuste no momento da migração para 255 caracteres para este campo.
