### ISSUE TITLE
Excluir registros com status apagado, recusado ou pendente da exibição no plug-in LIS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#335]
Há registros com status Apagado no LIS que estão sendo exibidos se:
*Acessado via número do ID. Ex: http://bvsalud.org/portal-lis/lis-search/resource/17612#.WKyYJPLLL2Y
*Acessado via Documentos Relacionados, como se vê na imagem.
![composicao-leite-vaca](https://cloud.githubusercontent.com/assets/13105683/23182120/2ad1fd24-f856-11e6-89aa-6e9b30bfeaa1.JPG)

O comportamento esperado é que todos os registros que possuem status Apagado, Recusado ou Pendente, não estejam disponíveis para consulta por parte do usuário final, ou seja, publicado no plug-in da fonte de informação.

Obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
Correção aplicada no plugin do LIS (https://github.com/bireme/lis-wp-plugin/commit/855f9aa3dd2e290b6340f6ae3f12f7373484ef86)
