### ISSUE TITLE
Corrigir navegação de páginas que não funciona

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#336]
Paginação no FI-Admin não funciona no relatório de erros e somente se pode visualizar a primeira página do relatório.
Quando clicamos na segunda aparece no ALT javascript: page ('2') e não ocorre mudança para a próxima página. 
![navegacao_fi-admin](https://cloud.githubusercontent.com/assets/13105683/23182849/bc2e6058-f858-11e6-85ae-26b84ac1ff88.JPG)

Obrigada
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/fi-admin/commit/bb78b672b7ea5093d953809d3a2a59456d8a87f1
