### ISSUE TITLE
Perfil Editor sem botão para gravar registros novos

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#338]
Ao criar registro bibliográfico com o perfil editor, consegui criar o registro fonte, porém somente rascunho de analítica.
O perfil editor precisa conseguir publicar registros.

Obrigada
Sueli
![editor-so-cria-rascunho](https://cloud.githubusercontent.com/assets/13105683/23215801/6633bdf2-f8f2-11e6-91f8-f6a75266853b.JPG)

![editor-so-cria-rascunho2](https://cloud.githubusercontent.com/assets/13105683/23215807/6d280ae6-f8f2-11e6-8417-ab55282c680d.JPG)

**Comment by viniciusandrade** [comment]
@suelisuga 

Ajuste realizado. Favor validar.

Obrigado

**Comment by sarahviola** [comment]
Botão de publicar habilitador para perfil editor nas analíticas e funcionando para publicar os artigos.
