### ISSUE TITLE
Mostrar títulos de acordo com campo de cobertura de indexação

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#339]
Atualmente o filtro esta sendo realizado pelo metadado de código do centro indexador e precisa ser alterado para o centro indexador de acordo com a cobertura de indexação para levar em consideração as demais bases de dados disponíveis no campo "indexado em"

**Comment by viniciusandrade** [comment]
@sarahviola 

Você poderia me ajudar a validar este ticket? Os ajustes estão disponíveis no ambiente de testes mas não sei se a regra esta OK.

Obrigado

**Comment by sarahviola** [comment]
@viniciusandrade 

Retirei da title os dados Código do centro indexador e Código do editor na ana Metadados.
![image](https://cloud.githubusercontent.com/assets/18355163/23275085/e0959e52-f9e3-11e6-9909-d1a4fbbc6333.png)

Em Cobertura de Indexação, apaguei os dados de indexação na LILACS e inclui de indexação na IndexPsi:
![image](https://cloud.githubusercontent.com/assets/18355163/23275147/217f7352-f9e4-11e6-9e16-3e74ff019e35.png)

Depois de salvar os dados, a lista continua aparecendo na lista, então acho que deu certo.

Fiquei em dúvida em na apresentação da lista. Vão aparecer todos os títulos indexados em todas as Fontes de informação da BVS?
Porque o campo abaixo da lista é para preencher "Outro título de revista (para referências não indexadas na LILACS)". Se for assim, então tem que mudar essa frase, já que as revistas das Fontes de informação temáticas da BVS aparecerão na lista
![image](https://cloud.githubusercontent.com/assets/18355163/23275281/ad676366-f9e4-11e6-83c5-193b70749c97.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Obrigado por suas considerações. De acordo com que conversamos com a @suelisuga apliquei algumas melhorias no formato de apresentação da lista para tornar mais simples o processo de seleção da revista. Também alterei o rótulo para o campo de revistas que não são indexadas na BVS.

Quando possível favor verificar.

Obrigado.

**Comment by anakatiacamilo** [comment]
Vini, 
Testei com a Revista Rev. ABENO, 1679-5954
- com o Código do Centro Indexador na Cobertura de Indexação[450] BR1264.1
- somente no Código do Centro Indexador [920]
- e tirando o Código do Centro Indexador - [920/450]
Deu certo em todos os testes

Como esta Revista que NÃO é LILACS, testei colocar no campo "Indexado em " LILACS e não tive problemas, então vou abrir um outro issue para fazer este check.

**Comment by viniciusandrade** [comment]
OK.

Código atualizado em produção.
