### ISSUE TITLE
Utilizar a ASTILL nos descritores.

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin#34]
Consumir dados da ASTILL para o preenchimento dos campos de descritores.

**Comment by suelisuga** [comment]
Endereço da ASTILL: http://catalogo-local.homolog.bireme.org/cgi-bin/wxis.exe/iah/?IsisScript=iah/iah.xis&lang=P&base=astill

**Comment by wilsonmoura** [comment]
Por limitações técnicas, não será possível implementar esse recurso.
