### ISSUE TITLE
Validar arquivos de importação da TITLE para campos de seletiva e de usuário (LILACS Express)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#340]
Analisar arquivo JSON e ISIS utilizados na migração para verificar se os campos de controle de seletiva e usuários foram corretamente migrados.

**Comment by wilsonmoura** [comment]
Campo Usuários: A migração foi realizada corretamente, sendo que a base SeCS usada nesse processo possuia nesse campo apenas dois valores (ccs e OJS).

Campo Seletiva: Analisamos a base de dados e constatamos que a origem correta desse dado era proveniente do campo v920. Sendo assim, esses dados não foram migrados, pois essa informação não estava documentada na issue #211 . Essa issue documenta a solicitação inicial de inclusão de novos campos na cobertura de indexação. Conforme solicitação da @suelisuga , estamos enviando uma lista com o conteúdo do campo v920 para que ela possa revisar. Após essa revisão, vamos tentar aplicar os ajustes necessários na base TITLE.

Segue arquivo: [lista.txt](https://github.com/bireme/fi-admin/files/838500/lista.txt)
