### ISSUE TITLE
Possibilitar restringir a exportação para determinada base do campo "indexado em"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#341]
Criar filtro na API para possibilitar a coleta seletiva que será necessária para o processamento IAHX pós migração de bases para o FI-ADIMIN.

**Comment by viniciusandrade** [comment]
Filtro criado e disponível para testes no ambiente de testes/produção. Favor validar.

Utilizar o parâmetro **indexed_database** e informar o acrónimo da base:

http://fi-admin.bvsalud.org/api/bibliographic/?format=isis_id&indexed_database=LILACS

**Comment by falbrito** [comment]
Realizado testes no navegador. Obrigado.
