### ISSUE TITLE
Configurar a saída no modo ID do campo "indexado em" para a tag de número v904 ao invés de v004

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#343]
Vinícius por gentileza alterar o código para que no modo ID o campo "indexado em" esteja com o número v904 ao invés de v004. Isso proporcionará o filtro exclusivo para a FI. Obrigado.

**Comment by viniciusandrade** [comment]
@falbrito 

API alterada para o campo "indexado em". Quando possível favor validar.

Obrigado

**Comment by falbrito** [comment]
Obrigado Vinícius, perfeito. Pode ser verificado no exemplo abaixo

http://fi-admin.bvsalud.org/api/bibliographic/?format=isis_id&id=243290

!ID 00000
!v008!^gTrue^uhttp://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-59702015000100303^yHTML ESTÁTICO^qhtml^ies 
!v040!es 
!v009!a 
!v092!import 
!v091!2015-04-01T09:00:00 
!v072!3 
!v001!BR2260 
!v113!p 
!v006!as 
!v012!Las medicinas tradicionales en la encrucijada intercultural^ies 
!v012!Traditional medicines at an intercultural crossroads^ien 
!v904!BDS 
!v904!LILACS 
!v002!243290 
!v098!FONTE 
!v010!Loza, Carmen Beatriz^1Instituto Boliviano de Medicina Tradicional Kallawaya 
!v110!s 
!v065!20150300 
!v724!10.1590/S0104-59702015000100018 
!v779!lil-741508 
!v064!Jan-Mar/2015 
!v899!1.9-1 
!v014!^f303^l307 
!v005!S 
!v031!22 
!v038!^bgraf 
!v004!LILACSEXPRESS 
!v004!MEDLINE 
!v030!Hist. ciênc. saúde-Manguinhos 
!v035!0104-5970 
!v093!2017-02-24T10:15:07 
!v032!1 
!v653!LS 1: Bioética e Saúde Pública e Relações Internacionais 
!v776!FI-ADMIN^i243290^bLILACS 
!v778!741508
