### ISSUE TITLE
Criar lista de documentos criados pelo centro do usuário atual e alterados por outro centro cooperante

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#351]
Esta lista deverá conter os registros com status de publicado que possuem alterações realizadas por  usuários de centros cooperantes diferentes do usuário atual e que não foram validados (status da alteração não presente).

A lista deve estar consolidada por documento e apresentar os últimos 10 documentos na página inicial "Painel de controle" do FI-ADMIN.

Relacionado ao #348

**Comment by viniciusandrade** [comment]
Disponível nos ambientes de teste e curso para avaliação.

**Comment by sarahviola** [comment]
Ao clicar nos links dos registros e abrir a tela da validação há pouca informação sobre o documento para decidir sobre validar ou não as alterações.
O ideal seria apresentar pelo menos ao dados básicos, como título e link, ou talvez o registro inteiro.
Para aprovar ou não descritores, por exemplo, é necessário ver todos os outros descritores do registro, já que na indexação coordenamos descritores com outros descritores.
![image](https://cloud.githubusercontent.com/assets/18355163/25240279/cade5372-25c8-11e7-9763-8aa8bc4f6712.png)


Dúvida: depois de validar ou não as pendências, a idéia do fluxo é realmente não avisar o usuário que fez as alterações no documento que as alterações dele foram validadas ou rejeitas?

**Comment by viniciusandrade** [comment]
@sarahviola 

Adicionei na tela de validação os dados básicos (título e revista) do artigo e um link para que o revisor possa ver o registro completo para poder melhor avaliar as alterações.

Sobre sua dúvida, não foi definido durante a etapa de planejamento esta necessidade. 

Quando possível favor validar no ambiente de testes.

[]s
