### ISSUE TITLE
Caracter UTF8  não permite que a API  exporte o registro

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#355]
Tivemos problemas com a coleta do LIS utilizando a API em um registro que tinha esse caractere especificados, apagamos então foi possível fazer a coleta. Seria possível colocar uma check no formulário para não permitir este tipo de caractere?

**Comment by viniciusandrade** [comment]
Issue finalizado por inatividade. Caso seja necessário favor reabrir.
