### ISSUE TITLE
Demora para acessar abas "Registros do meu Centro", "Todos Registros" e "Indexado pelo meu Centro"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#356]
Em sessão virtual realizada sobre FI-Admin na semana passada constatamos demora para acessar abas "Registros do meu Centro", "Todos Registros" e "Indexado pelo meu Centro"

**Comment by viniciusandrade** [comment]
@sueli / @sarahviola 

Foram realizados ajustes no sistema e no banco de dados para melhorar o tempo de resposta ao clicar nas abas.

Os ajustes já foram aplicados em produção. Favor validar. Obrigado.

**Comment by sarahviola** [comment]
ok.

Notei que a aba "Indexado pelo meu Centro" demora um pouco mais do que as outras três para carregar.
