### ISSUE TITLE
Solicito mudança de local do botão "Nova Fonte" para canto superior direito

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#357]
Prezados,

Solicito mudança de local do botão Nova Fonte para o canto superior direito:
![image](https://cloud.githubusercontent.com/assets/13105683/24371479/47992eb2-1301-11e7-920d-61e338a59a4f.png)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado e disponível no ambiente de produção. 

Favor validar. Obrigado.

**Comment by sarahviola** [comment]
Ok para todos os tipos de registros. Mantido o botão ao final da página e adicionado um no início.

![image](https://cloud.githubusercontent.com/assets/18355163/25342610/e36f09b4-28e2-11e7-9c35-5b8151ad8710.png)
