### ISSUE TITLE
Demora para criação de Novo Registro

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#358]
O tempo de transição entre clicar o botão "Novo Registro" e a apresentação do botão "Nova Fonte" é bastante demorada.

**Comment by viniciusandrade** [comment]
Acredito que seja devido a apresentação de listagem de todas as fontes do sistema para o usuário verificar se a fonte já existe no sistema. Qual seria a sugestão nesta tela para não carregar todas as fontes? Talvez somente as últimas, ou somente as fontes de revistas que o centro indexa, etc?

**Comment by viniciusandrade** [comment]
@sarahviola 

Foram realizados ajustes no sistema e no banco de dados para melhorar o tempo de resposta da página.

Já esta disponível em ambiente de produção. Favor validar.

Obrigado

**Comment by sarahviola** [comment]
Testei clicar em novo registro e selecionar algum tipo de registro várias vezes. Na maioria das vezes, o botão "Nova Fonte" aparece rapidamente.
