### ISSUE TITLE
Incluir nos precodificados de idade o período etário que engloba

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#362]
Incluir no precodificados a faixa etária compreendida, assim como aparece em IMS de NLM:
![image](https://cloud.githubusercontent.com/assets/13105683/24770250/a68c9c0c-1adf-11e7-8995-9e6b433a340b.png)

**Comment by suelisuga** [comment]
@viniciusandrade , foi realizado e está aparecendo na produção após comando realizado.

É possível colocar na ordem? Exemplo:
Adulto Jovem antes de Adulto?

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga 

Conforme conversamos a ordenação não é possível devido a não existir um campo para informar a ordem desta lista.
