### ISSUE TITLE
Títulos LILACS que não estão aparecendo no FI-ADMIN

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#368]
A nosso consultora Maria Cristina, esta se queixando que três títulos de revistas LILACS não estão parecendo na lista do FI-ADMIN:
Trab. educ. saúde
Interface comun. saúde educ
Psico (Porto Alegre)

Grata
Katinha

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Acredito ter localizado e corrigido o problema com a lista de títulos disponíveis no FI-ADMIN. Quando possível favor verificar e informar a consultora.

Obrigado
Vinicius
