### ISSUE TITLE
Filtro da aba indexado pelo meu centro não está funcionando corretamente.

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#370]
A revista Cadernos Ibero-Americanos de Direito Sanitario (Impresso) era responsabilidade de indexação do BR2260, mas foi alterada para o BR208.2 indexar.
![image](https://cloud.githubusercontent.com/assets/18355163/25434418/9f25d7e8-2a62-11e7-90d9-2cb438223c0d.png)

Entretanto, os registros dessa revista continuam aparecendo na aba "Indexado pelo meu centro" para usuários registrados sob o código BR2260.
![image](https://cloud.githubusercontent.com/assets/18355163/25434499/e8b528b4-2a62-11e7-8903-edac5d3a3495.png)

Alterei meu usuário para BR208.2, o novo responsável pela indexação da revista, e aparecem títulos que são de responsabilidade de outros centros:
![image](https://cloud.githubusercontent.com/assets/18355163/25434610/58887628-2a63-11e7-819a-938307a5e75d.png)
ABCS health sci > BR1342.1
Rev. Soc. Bras. Clín. Méd > BR33.1
Salusvita >  BR275.1
Arq. ciênc. vet. zool. UNIPAR > BR68.1
Hig. aliment > BR526.1

**Comment by viniciusandrade** [comment]
@sarahviola 

Acredito que o problema aqui foi que o centro BR208.2 não tinha nenhuma revista associada como responsável pela indexação (note que o campo em uso agora é o da aba cobertura de indexação) e o sistema então retornou a lista de todas as revistas. Corrigi para nestes casos não retornar nenhum registro.

O ajuste esta disponível no ambiente de testes.

**Comment by sarahviola** [comment]
@viniciusandrade 

Ok na teste.

É possível atualizar na produção?

**Comment by viniciusandrade** [comment]
@sarahviola 

OK. Correção disponível na produção.
