### ISSUE TITLE
Alguns usuários estão com problemas em salvar registros

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#378]
Dois usuários do FI-Admin (um perfil llxp editor e outro documentalista) informaram que estão com problemas para salvar ou publicar registros, mas não consegui replicar os erros.

* Problema 1
usuário sandrapicchiotti, perfil llxp editor
Informou que não está conseguindo salvar registros. Está usando o Chrome. Tentei replicar o erro, mas consigo salvar normalmente os registros usando perfil llxp edt com o código dela, também usando o Chrome, copiando e colando os dados do PDF que ela enviou. 

Para a usuária, aparece a mensagem de erro abaixo: 

Request Method:	POST
Request URL:	http://fi-admin.bvsalud.org/bibliographic/edit-analytic/833203
Django Version:	1.8.11
Exception Type:	ValueError
Exception Value:	

All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

Exception Location:	/home/apps/bvsalud.org/fi-admin/env/lib/python2.7/site-packages/pysolr.py in _build_doc, line 701
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	

['/home/apps/bvsalud.org/fi-admin/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/apps/bvsalud.org/fi-admin/',
 '/home/apps/bvsalud.org/fi-admin/bireme',
 '/home/apps/bvsalud.org/fi-admin/bireme/fi-admin']

Server time:	Seg, 8 Mai 2017 11:18:55 -0300

Além disso, notei que os últimos registros dela (ids 833203, 833204, 833205) estão com status LILACS-Express, mas sem o PDF - coisa que o sistema não deveria permitir. Notei que todos tem erros em caracteres do resumo e um deles tem erro em caracteres do título ([833204](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/833204)).

* Problema 2
Usuária documentalista conseguir editar o registro id [147126](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/147126) incluindo a descrição, mas ao publicar o registro aparece mensagem de erro e o registro não é publicado.
Eu acessei o registro e consegui publicar normalmente. Voltei ao status LILACS-Express e pedi que tentassem novamente publicar o registro, mas continua aparecendo mensagem de erro:

MultiValueDictKeyError at /bibliographic/edit-analytic/147126
"u'referencelocal_set-1-id'"
Request Method:             POST
Request URL:     http://fi-admin.bvsalud.org/bibliographic/edit-analytic/147126
Django Version: 1.8.11
Exception Type: MultiValueDictKeyError
Exception Value:             

"u'referencelocal_set-1-id'"

Exception Location:        /home/apps/bvsalud.org/fi-admin/env/lib/python2.7/site-packages/django/utils/datastructures.py in __getitem__, line 322
Python Executable:         /usr/bin/python
Python Version: 2.7.6
Python Path:     

['/home/apps/bvsalud.org/fi-admin/env/lib/python2.7/site-packages',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-x86_64-linux-gnu',
'/usr/lib/python2.7/lib-tk',
'/usr/lib/python2.7/lib-old',
'/usr/lib/python2.7/lib-dynload',
'/usr/local/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages',
'/home/apps/bvsalud.org/fi-admin/',
'/home/apps/bvsalud.org/fi-admin/bireme',
'/home/apps/bvsalud.org/fi-admin/bireme/fi-admin']
Server time:        Sex, 5 Mai 2017 08:26:23 -0300

**Comment by anakatiacamilo** [comment]
Vini, a Maria Cristina deve este mesmo problema e percebi que era um caractere com problema no Resumo, devido o problema ela sem querer gravou o registro varias vezes, mas depois que apagamos o  ela não teve mais problemas se tem que apagar os registros duplicados.

RESUMO
Objective: describe the population, evaluate the ecacy of treatment (lung functionality, nutritional 
assessment) and adherence. Methods: Cohort study of patients who began treatment with Tobramycin and/or 
Alpha-Dornase from December 2007 to July 2010. Adherence to Tobramycin was measured by an index that relates the number of cycles received/optimal number of cycles, values > 0.8 were considered optimal. Changes in forced expiratory volume in 1st second (FEV1) and body mass index (BMI) were assessed at one year of treatment. Conclusions:A delay in the diagnostic was observed comparing with international literature (acceptable during the first year of life). Adherence was good, and lung function improved after one year of treatment and BMI remained stable within acceptable parameters.(AU)

**Comment by viniciusandrade** [comment]
Foram realizados ajustes para tentar não gerar erro no sistema quando o título ou resumo possuem caracteres de controle.

@sarahviola no caso (id 833203) eu realizei o teste na produção mas para poder validar eu adicionei a url do texto completo para poder gravar. Você poderia depois validar se esta correto?

Obrigado

**Comment by sarahviola** [comment]
@viniciusandrade , como comigo não estava aparecendo erro nenhum, voltei para status rascunho os registros sem PDF e pedi para ela fazer o upload e publicar, além de incluir novos registros, e nos avisar se continuar com o problema.

**Comment by viniciusandrade** [comment]
@sarahviola OK, caso ela retorne informando que conseguiu completar os documentos favor fechar este issue.

**Comment by viniciusandrade** [comment]
Estou finalizando este issue. Caso ocorra algum outro erro relacionado a caracteres inválidos favor reabrir.
