### ISSUE TITLE
Inclusão de "Fluxo contínuo" no campo Frequência

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#379]
Wilson,

Pf. incluir no campo Frequência a opção:
Português: Fluxo contínuo
Espanhol: Flujo continuado
Inglês: Continuously updated

Help dessa opção: Revistas eletrônicas que publicam continuamente os artigos
sem a necessidade de esperar a composição completa dos fascículos ou de edições seriadas. Não se aplica a revistas que ainda mantém formato impresso.

"A">Anual
"B">Bimestral
"C">Bissemanal
"D">Diário
"E">Quinzenal
"F">Semestral/Bianual
"G">Bienal
"H">Trienal
"I">Três vezes por semana
"J">Três vezes por mês
"K">Irregular
"M">Mensal
"Q">Trimestral
"S">Bimensal
"T">Quadrimestral
**"U">Publicação contínua**
"W">Semanal
"Z">Outras frequências
"?">Frequência desconhecida

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@wilsonmoura 

Favor verificar este ticket com prioridade.

Obrigado.

**Comment by viniciusandrade** [comment]
@suelisuga 

O @wilsonmoura já implementou a opção no campo de frequência e o sistema foi atualizado. 

Qualquer problema favor informar.
