### ISSUE TITLE
Erro de permissão ao tentar acessar PDF carregado no FI-Admin

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#380]
Uma usuária reportou não estar conseguindo acessar o PDF carregado no FI-Admin pelos editores da revista. Aparece a mensagem de erro abaixo:
Forbidden
You don't have permission to access /biblioref/2016/07/685/42845-182087-1-pb.pdf on this server.
Apache/2.4.7 (Ubuntu) Server at docs.bvsalud.org Port 80

Exemplo de artigo com problema: id [685](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/685)

**Comment by viniciusandrade** [comment]
@sarahviola 

As configurações foram ajustadas no servidor e agora os documentos estão acessíveis novamente.

Obrigado
