### ISSUE TITLE
Editar metadados descritivos da página inicial do FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#382]
Login do FI-Admin apresenta informação de LIS. Login.

Solicito exclusão dessa informação e inclusão de: FI-Admin - Administração de Fontes de Informação da BVS.

![image](https://cloud.githubusercontent.com/assets/13105683/25968309/642d926e-3667-11e7-9e42-30927a33db3f.png)

![image](https://cloud.githubusercontent.com/assets/13105683/25968546/4a90235c-3668-11e7-8a86-9aa744ab8e64.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado e também atualizado o logotipo da BIREME no rodapé do sistema.
