### ISSUE TITLE
Habilitar DEselecionar um título abreviado em registros bibliográficos

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#395]
Ao criar um registro de título não mais indexado em LILACS e BBO (ImplantNews - ISSN 1678-6661) preenchi o campo aberto "Outro título de revista (não indexada na Biblioteca Virtual em Saúde)" com o titulo abreviado e ISSN no campo específico, PORÉM, cliquei na caixa de títulos abreviados e isso gerou um problema: Não consegui mais deselecionar o opção e ainda autocompletou o campo ISSN com o número dessa revista que cliquei.

Solicito então que seja implantada a opção deselecionar título, inclusive já notei anteriormente que alguns registros estão vindo com dois títulos abreviados justamente por esse motivo.

![image](https://cloud.githubusercontent.com/assets/13105683/26697022/0e9f2e44-46e7-11e7-8d81-c8857a9ad40c.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Foi criado uma linha em branco no início da lista para permitir ao usuário desmarcar  um item.
