### ISSUE TITLE
Incluir automaticamente o nome da base de dados quando um título de revista for selecionad

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#396]
Considerando que registramos em TITLE os nomes de bases na qual as revistas são indexadas, incluindo fascículo de início de indexação, solicito que ao criar um registro, publicar coleta e ao migrar registros de artigo de revista, checar com o  título abreviado, quais bases de dados esa revista é indexada e já  inserir no campo indexed_database.

Exemplo: Braz. j. oral sci aparece na TITLE:
![image](https://user-images.githubusercontent.com/13105683/27101362-d6ba9cb4-5057-11e7-9d6b-fcfd90ee5b66.png)

E no FI-Admin, o registro tem:
![image](https://user-images.githubusercontent.com/13105683/27101443-27dbeb52-5058-11e7-9694-a907c23e36e7.png)

Se formos criar o registro do zero, não aparece nenhuma base de dados.

A ideia é evitar que o documentalista se esqueça de incluir as bases de dados em um ou outro registro.

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga, para ser possível trabalhar nesta integração seria necessário a padronização do campo "código da fonte de indexação" com o campo "indexado em" pois elas são duas tabelas de valores distintos.

Exemplo na tabela do campo "indexado em" a LILACS esta com o código LILACS e no campo "código da fonte de indexação" esta como LL. 

Em um primeiro momento acredito que seja mais prudente tentar normalizar pelo campo de nome do campo "código da fonte de indexação" pois alterar o código pode causar impactos nos processamentos do portal de revistas e outros.

**Comment by viniciusandrade** [comment]
@sarahviola 

Você poderia me ajudar a validar este ticket? Eu fiz as alterações no código e coloquei no ambiente de testes. Conforme comentário anterior para que funcione corretamente os valores do campo nome da lista de "Códigos de indexação" precisa ser igual ao valor do campo acrônimo da lista de "Bases de dados".

Qualquer dúvida me fale.

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade Testei um título e apareceu corretamente: (BR510.1)
![image](https://user-images.githubusercontent.com/13105683/28343410-98f7e5be-6bf3-11e7-9906-671cb395bc44.png)

Porém outro não funcionou (BR21.1)
![image](https://user-images.githubusercontent.com/13105683/28343485-f11d001c-6bf3-11e7-89f7-c1572dfbb9a4.png)

Já identifiquei que nesse último não aparece o fascículo de indexação na TITLE...

Se @sarahviola quiser verificar outros títulos, é bom tb. A única coisa que fiz foi logar com esses dois códigos e verificar se aparecia as bases corretas para cada revista.

Abraços e obrigada,
Sueli

**Comment by sarahviola** [comment]
@viniciusandrade , pelo que testei, não está funcionando para as bases IndexPsi e BDENF. 
Meus testes foram somente com LILACS, MEDLINE, BBO, IndexPsi e BDENF.

Notei que quando tiramos da Title os dados de início de indexação e CC responsável, mas mantemos a base selecionada, o registro aparece com a base marcada nos registros bibliográficos - o que eu acho que está certo. Então, o problema na revista REME que a Sueli reportou não é por causa disso.

Exemplo:
registro na title:
![image](https://user-images.githubusercontent.com/18355163/28384123-dfd83e42-6c99-11e7-8da6-b8b8b41ea437.png)

essa mesma revista nos registros bibliográficos:
![image](https://user-images.githubusercontent.com/18355163/28384166-10bd1172-6c9a-11e7-8b71-6f275b55f26a.png)

**BDENF** aparece com sigla/código iguais na title e lista de bases de dados de registros bibliográficos:
![image](https://user-images.githubusercontent.com/18355163/28384777-45f60c70-6c9c-11e7-84bc-dff44324d518.png)

**IndexPsi** aparece com diferença nas maiúsculas/minúsculas:
![image](https://user-images.githubusercontent.com/18355163/28384838-74d4f3b2-6c9c-11e7-89b4-5800324992ba.png)

**BBO**, que parece estar funcionando, está com a sigla/código iguais. Assim como BDENF, tem diferença no nome por extenso:
![image](https://user-images.githubusercontent.com/18355163/28384910-af862d78-6c9c-11e7-9b68-2d70ce06eae8.png)


**Exemplos erro**:
Salutem Scientia Spiritus (En línea)
LILACS ok. 
Na title, selecionei "IndexPsi Periódicos", mas não parece automaticamente "Indexado em: IndexPsi - Psicologia" na analítica da revista.

Psicol. Educ. (Online)
LILACS ok. 
Como a revista acima, marquei IndexPsi na title, mas não vem marcado ao criar registro da analítica da revista.

SMAD, Rev. eletrônica saúde mental alcool drog
LILACS, IndexPsi e BDENF; aparece na analítica marcado apenas como LILACS.

**Exemplos ok**:
_Rev. Fed. Argent. Soc. Otorrinolaringol._ 
Criei um fascículo e já veio marcado corretamente com LILACS.
Depois, marquei MEDLINE na title em "Código da fonte de indexação" com dados de início de indexação e CC iguais aos da LILACS. Criei MEDLINE nas bases de dados de Registros Bibliográficos. Ao criar uma analítica da revista, já vem MEDLINE marcado no campo "Indexado em". Mesmo tirando os dados de início de indexação e CC, MEDLINE continua aparecendo em "Indexado em".

Rev. Bras. Odontol. Leg. RBOL
Apenas BBO - ok
(Tem indexação na LILACS preenchida na title, mas com fim de indexação preenchido, por isso não deve aparecer LILACS marcado na analítica).

**Comment by viniciusandrade** [comment]
@sarahviola 

Obrigado pelos testes, acredito que para fazer funcionar nos casos da IndexPsi e BDENF será necessário alterar o campo **Nome** da tabela Title > Códigos de indexação para ficar igual ao campo *Sigla* da tabela Database.

Poderia tentar ajustar e verificar novamente?

Obrigado.

**Comment by sarahviola** [comment]
@viniciusandrade 

Alterando o **Nome** por extenso do código de indexação na title para ficar igual a **Sigla** da Database a marcação das bases funciona corretamente.

Teria como alterar para que o dado do campo Código da title (e não mais do campo Nome) tenha que ser igual ao da Sigla para funcionar? Por que assim não faz sentido ter o campo nome para o código de indexação, já que ele precisa ser necessariamente uma sigla, que já é registrada em código, e não pode ser preenchido com o nome por extenso.

**Comment by viniciusandrade** [comment]
@sarahviola 

Não tenho certeza das implicações ao se alterar o código da Title para outros valores. Por exemplo na Title o código da LILACS é LL e tenho a desconfiança de que este código é usado no Portal de Revistas e em outros processos. Por isso achei mais prudente implementar desta forma.  

Caso esteja de acordo por favor realizar o ajuste para as demais bases no Django Admin.
