### ISSUE TITLE
Inclusão das tabelas de Tipo de registro

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#398]
Só testei o Tipo de Material Visual, mas são essas três que preciso incluir no Django na tabela de "Códigos Auxiliares"

type_of_visual_material
type_of_cartographic_material
specific_designation_of_the_material

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Verifiquei que era necessário re-iniciar o FI-ADMIN para ele carregar os novos valores da tabela auxiliar. Agora estão aparecendo os valores para "type_of_visual_material".

Você poderia inserir ou me passar os valores das outras tabelas auxiliares?

Abraços,
Vinicius

**Comment by viniciusandrade** [comment]
@suelisuga,

Agora as tabelas de "códigos auxiliares" estão aparecendo corretamente no sistema.

Abraços
Vinicius
