### ISSUE TITLE
Checar se os IDs que estão diferentes tem coleção 001 002

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#400]
Olhar o exemplo do ISSN 2237-0439, se não tiver mais nenhum titulo com coleção parear os ID [30] e Numero SeCS [37]. Não parear os registros que não tem Número SeCS [37] 
 Lista:
16443|16442|0738-0151
18422|18462|0023-7213
19811|19812|2448-2455
19812|19813|2447-7567
19813|19814|2409-3459
19814|19815|2446-922X
19815|19816|2236-6407
19816|19817|2359-3466
19817|19818|2310-2594
19818|19819|2525-5711
19819|19820|2446-4740
19820|19821|2525-7374
19821|19822|2318-1419
19822|19823|2358-2871
19823|19824|2359-0777
19824|19825|2175-3644
19825|19826|2409-8663
19826|19827|1982-8829
19827|19828|1390-7581
19828|19829|2357-9641
19829|19830|2447-3405
19830|19831|2358-9868
19831|19832|2175-2834
19832|19833|2175-3520
19833|19834|2176-9745
19834|19835|2358-1883
19835|19836|0124-308X
19836|19837|2409-9759
19837|19838|2236-0867
19838|19839|1984-7742
19839|19840|2446-4732
19840|19841|2411-6289
19841|19842|1980-6108
19842|19843|1518-0557
19843|19844|2255-5021
19844|19845|2173-5115
19845|19846|2254-8874
19846|19847|1885-5857
19847|19848|0123-4226
19848|19849|1900-3803
19849|19850|0121-3261
19850|19851|0121-3709
19851|19852|1794-4449
19852|19853|0258-6444
19853|19854|1659-4142
19854|19855|1659-0775
19855|19856|0253-570X
19856|19857|0188-6266
19857|19858|2007-7521
19858|19859|1688-7026
19859|19860|2393-6797
19860|19861|0376-4362
19861|19862|1646-5830
19862|19863|2183-5985
19863|19864|0004-0592
19864|19865|1138-2635
19865|19866|2174-5145
19866|19867|2225-5214
19867|19868|2410-1702
19868|19869|2312-3893
19869|19870|1679-9941
19870|19871|2447-2115
19871|19872|2451-0629
19872|19873|2007-1833
19873|19874|2520-4386
19874|19875|1995-9494
19875|19876|2317-3076
19876|19877|1579-2021
19877|19878|2530-0164
19878|19879|1808-2998
19879|19880|0083-3908
19880|19881|1677-2997
19881|19882|1413-4799
19882|19883|1806-8650
19883|19884|1519-3691
19884|19885|2237-0439
19885|19886|1679-6381

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
