### ISSUE TITLE
Problema na lista de descritores

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#403]
Por favor, aumentar a quantidade de descritores na lista de descritores DeCS no momento da indexação,
Um usuário esta tentando indexar o com o termo família e devido a quantidade de descritores com esta palavra a lista não passa dos descritores com a letra A assim impedindo que o usuário utilize este descritor.
Grata

**Comment by viniciusandrade** [comment]
Foi alterado a ordem do retorno da lista de descritores para priorizar o termo exato na primeira posição e depois retornar os termos em ordem alfabética.
