### ISSUE TITLE
FI-Admin permite uso de qualificador sem descritor

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#404]
Prezados,

Na indexação o uso dos qualificadores é obrigatoriamente realizado junto com um descritor, porém o sistema permitiu aplicação sem descritor.

![image](https://user-images.githubusercontent.com/13105683/27881991-40909418-61a1-11e7-9665-53708bc12b77.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado no sistema para não permitir selecionar um qualificador isolado de seu descritor na indexação.
