### ISSUE TITLE
qualificador /química não aparece na lista dos descritores

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#405]
Prezados,

Quando pesquiso por qualificadores, normalmente digito "/" e tenho acesso à lista completa de qualificadores e sinonimos de qualificadores.

Hj pesquisei por /química e não encontrei o qualificador e tb não recuperou a lista de qualificadores. Abaixo conteúdo recuperado qdo pesquisa por química:
![image](https://user-images.githubusercontent.com/13105683/27882269-67a68b10-61a2-11e7-8dbe-994df7d3b4c4.png)

O comportamento esperado é que seja apresentado o qualificador junto com a lista de descritores
![image](https://user-images.githubusercontent.com/13105683/27882243-48ecbfe6-61a2-11e7-9c14-dbac732f2912.png)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Ajuste realizado para mostrar nas primeiras posições do resultado o termo exato e qualificador.

Quando possível favor validar.
