### ISSUE TITLE
Incluir código de CC responsável pelo registro

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#411]
Solicito incluir nos registros do FI-Admin, no formulário de entrada/edição de dados, o responsável pelo registro.

Os registros que foram migrados não apresentam histórico e quando precisamos contactar um responsável para correções ou feedback, temos que consultar a interface de usuário.

Incluir em todas as fontes de informação do FI-Admin.

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Foi adicionado no final do formulário a informação do usuário que criou o registro e o código do centro cooperante.

[]s

**Comment by sarahviola** [comment]
Informação está aparecendo. 
![image](https://user-images.githubusercontent.com/18355163/28481857-4a9d12cc-6e3c-11e7-8979-2168a72b78ad.png)

@viniciusandrade , 
Nesse registro ([id 833273](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/833273)) aparece "Última edição realizada em 18 de Julho", mas quando eu acesso o histórico de mudanças não tem nenhuma alteração nessa data. É porque gravaram o registro sem fazer alteração nenhuma?
![image](https://user-images.githubusercontent.com/18355163/28481931-874c74f6-6e3c-11e7-9f0c-a727d948b405.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Isso mesmo, acabei de realizar um teste e mesmo que o usuário não altere nenhum dado no registro e clique no botão de gravar será registrado no campo de último usuário e data de atualização.
