### ISSUE TITLE
Incluir link no qualificador para o registro DeCS de sua definição

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#414]
Incluir link no qualificador para o registro DeCS de sua definição
![image](https://user-images.githubusercontent.com/13105683/28479186-b0fdd3cc-6e31-11e7-9f08-ca8121a4ab68.png)

ao clicar no link apareceria o registro do qualificador
![image](https://user-images.githubusercontent.com/13105683/28479226-ec7b51d6-6e31-11e7-82f0-5d6e3ecbaba7.png)

obrigada
Sueli

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/iahx-opac/commit/5a6a08a35d638550c2f536f022a5a1953b13b380
