### ISSUE TITLE
Permitir que usuário de registros possa apagar seus próprios registros fonte

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#415]
Solicito que usuario de perfil básico possam apagar os registros fonte que eles criaram, desde que as analíticas estejam apagadas.

Ex.
![image](https://user-images.githubusercontent.com/13105683/28577929-8be118e2-712e-11e7-903c-7bb674cb07d8.png)

Atualmente somente perfis avançados conseguem apagar seus fonte:
Ex: Meu perfil
![image](https://user-images.githubusercontent.com/13105683/28578058-f20281c4-712e-11e7-8222-6f38cb2cc4d4.png)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@sarahviola 

Este ajuste foi realizado. Quando possível poderia validar?

Obrigado

**Comment by sarahviola** [comment]
@viniciusandrade 
Consegui deletar um registro Fonte com duas analíticas, uma Rascunho e outra Publicada. Deveria permirtir deletar apenas os registros Fonte sem analíticas. 

Testei na instância de teste, mas vi que o botão de apagar também está aparecendo na produção.

**Comment by sarahviola** [comment]
Duplicado com issue #54 .

Notei também que é possível deletar registros com qualquer status, o que não deveria acontecer.

Pelo que tinha sido discutido e documentado na issue 54, o botão de deletar só ficaria disponível para registros com status Rascunho, para não correr o risco de apagar registros LILACS-Express e Publicados que já estão publicados na base de dados. 

![image](https://user-images.githubusercontent.com/18355163/29180156-4524e518-7dcd-11e7-9943-e61851b818c0.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Foi revisado este problema. Quando possível favor realizar novo teste.

Obrigado

**Comment by sarahviola** [comment]
@viniciusandrade ok. 

Agora só é possível que os usuários deletem seus próprios registros com status **Rascunho** e Registros **Fonte sem analíticas**.

**Comment by sarahviola** [comment]
@viniciusandrade 
Os botões para deletar Rascunhos e Fonte sem analítica não estão aparecendo para o perfil LILACS-Express Editor.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado também para o perfil LLXP. Quando possível favor verificar.

Obrigado
