### ISSUE TITLE
Erro ao criar registro fonte de revista não LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#417]
Verificamos que CC recebeu mensagem de erro ao criar registro fonte de revista não LILACS.

Devido a esse erro, usuária criou vários registros fonte duplicados pensando que o FI-Admin não havia publicado o registro criado anteriormente. Ver abaixo revista ODI - ids 846969, 846965, 846964, 846963 e 846962:
![image](https://user-images.githubusercontent.com/13105683/28586602-bea471b8-714a-11e7-9264-1cb432345bdb.png)

Esse chamado é relacionado ao anterior pois foi necessário apagar esses registros fonte que ficaram duplicados #415 e tb ao chamado sobre impedir duplicação de registro fonte.

Abaixo mensagem de erro apresentada após clicar no botão "Publicar":
![larissadoesnotexist at bibliographic new analytic](https://user-images.githubusercontent.com/13105683/28586539-9714d7aa-714a-11e7-8312-ebcabd7d78f5.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/29993b971db3f173c04f318d33281d473b57b2a4

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajuste realizado, quando possível favor validar.

Obrigado.
