### ISSUE TITLE
Erro ao criar analítica de registro não LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#418]
Chamado relacionado  #417 

Usuário teve problemas ao criar registro fonte de revista não LILACS, porém registro foi criado.
Ao acessar esse fonte e clicar no botão Criar Analítica, recebe mensagem de erro e não consegue criar nenhuma analítica nesse fonte.

Qdo testei a msg recebida foi:
![image](https://user-images.githubusercontent.com/13105683/28640196-570140ea-7221-11e7-8c07-284e40356e08.png)
Obrigada
Sueli

P.S. usuário aguarda retorno.

**Comment by viniciusandrade** [comment]
@suelisuga 

Correção aplicada (https://github.com/bireme/fi-admin/commit/29993b971db3f173c04f318d33281d473b57b2a4). Por favor informar a usuária para validação.

Obrigado
