### ISSUE TITLE
Upload de documentos

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#42]
Implementar o upload de documentos armazenando em file system na estrutura ANO+MES+DIA

**Comment by viniciusandrade** [comment]
Relacionado ao #43. Foi implementado para armazenar os arquivos na estrutura uploads/<nome do app>/<id do documento>. Exemplo:

uploads/biblioref/120/document1.pdf

**Comment by viniciusandrade** [comment]
Conforme sugerido pelo @renatomurasaki foi adicionado a estrutura de diretórios o ano e mês atual para evitar problemas de limites do filesystem. Ficando:

```uploads/<nome do app>/<ano>/<mês>/<id do documento>/```

**Comment by renatomurasaki** [comment]
Mais por performance e balanceamento da estrutura de diretórios e subdiretórios.

Renato
