### ISSUE TITLE
Registros com status "Pendente" e "Recusado" são apresentados nos plug-ins DirEve

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#420]
Solicito correção de implantação dos status  "Pendente" e "Recusado" porque registros com esses status estão sendo apresentados nos plug-ins DirEve

![image](https://user-images.githubusercontent.com/13105683/28829816-6e9ed8c8-76ab-11e7-8f8e-a126429820a4.png)

Obrigada
Sueli

Solicitação de CC:

Fiz também um teste, deixando um evento com “Status” de “Recusado” para a área temática “Homeopatia (Internacional)”, porém, o evento continua na interface pública da BVS Homeopatia. (evento publicado por outras “Áreas Temáticas” apontando para área temática “Homeopatia (Internacional)”)
Exemplo:
- ID – 22245 - Título: V Congreso Latinoamericano de plantas medicinales

**Comment by viniciusandrade** [comment]
@suelisuga 

Poderia informar a url do plugin direve da BVS que realizou esta solicitação? Pois analisando o evento 22245 ele consta como Admitido no FI-ADMIN, portanto OK para publicação. 

O que eu entendi é que a usuária alterou o status para recusado na aba "Áreas Temáticas"  e queria que ele não fosse apresentado no plugin da sua BVS. Preciso analisar a instância em questão para verificar se o filtro do plugin esta OK.

[]s

**Comment by viniciusandrade** [comment]
Finalizado pois não foi possível reproduzir o problema.
