### ISSUE TITLE
Pesquisa por ID não funciona no DirEve

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#421]
Solicito correção de pesquisa por ID na aba "Todos eventos", pois registros não estão sendo recuperados.

Obrigada
Sueli

Solicitação de CC:
(...)
Observação: além do ID estou mencionando o título do evento, pois, fazendo a pesquisa pelo “ID” não aparece o resultado.
(...)

**Comment by viniciusandrade** [comment]
Busca por ID implementado no diretório de eventos. É necessário usar o prefixo id: 

Ex.
id:22382

**Comment by viniciusandrade** [comment]
Busca por ID implementada no diretório de eventos. É necessário utilizar o prefixo **id:**, exemplo id: 22382.
