### ISSUE TITLE
Identificar os elementos Tipo de arquivo e Extensão do arquivo como obrigatórios

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#427]
No campo Endereço eletrônico, identificar os elementos **Tipo de arquivo** e **Extensão do arquivo** como obrigatórios, incluindo o asterisco vermelho.

Atualmente só Endereço eletrônico e Idioma possuem essa indicação.

![image](https://user-images.githubusercontent.com/18355163/29842997-f6305c1c-8ce0-11e7-9235-0ab31660c234.png)

A validação já está correta, exigindo o preenchimento dos campos. Só falta a indicação com o asterisco vermelho.
![image](https://user-images.githubusercontent.com/18355163/29842830-6722f9d0-8ce0-11e7-8682-c22a076920c8.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Pelo que pude verificar estes atributos somente são obrigatórios se o registro for marcado como  metodologia LILACS, correto?

Caso seja este caso infelizmente não conseguirei marcar eles como obrigatórios nesta tela pois dependo da informação da LILACS que somente estará disponível quando o usuário tentar gravar o registro.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

Eu pelo menos não encontrei no manual que são obrigatórios só quando tiverem marcados como Metodologia LILACS.

No manual tem uma tabela em que eles aparecem como obrigatórios, então eu entendi que eles são obrigatórios sempre que for colocado um link (ou seja, sempre que atributo **u** estiver presente), assim como já acontece com o atributo **i** de idioma.
![image](https://user-images.githubusercontent.com/18355163/29889614-2ad0386a-8d9b-11e7-8199-c9ce6cafa4fc.png)

Se quiser dar uma olhadinha no manual de descrição da LILACS: http://metodologia.lilacs.bvsalud.org/download/P/LILACS-2-ManualDescricao-pt.pdf (Dê um localizar em 08 ENDEREÇO ELETRÔNICO)

**Comment by viniciusandrade** [comment]
@sarahviola 

Neste caso sem problemas. Já realizei o ajuste para tornar estes atributos obrigatórios e atualizei os ambientes de teste e produção.

Quando possível favor validar. Obrigado.

**Comment by sarahviola** [comment]
Já está ok na produção.

Obrigada!
