### ISSUE TITLE
Padronizar a formatação dos nomes dos campos nos registros bibliográficos

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#428]
Nas abas **Metadados**, **Indexação** e **Texto completo**, os nomes dos campos estão em preto e sublinhados. O azul é usado somente para as seções dos formulários.
![image](https://user-images.githubusercontent.com/18355163/29940251-047cd630-8e65-11e7-927f-28ae0f1089b0.png)

Nas abas **Biblioteca** e **Evento/Projeto** os nomes dos campos ainda aparecem em azul, como na primeira versão das outras abas. 
![image](https://user-images.githubusercontent.com/18355163/29940075-7542fce2-8e64-11e7-881f-d731d17aa1b5.png)

![image](https://user-images.githubusercontent.com/18355163/29940100-890e1306-8e64-11e7-9f6a-b6e94c7c1d9c.png)

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/fi-admin/commit/79d2ba6f0a2405593338d37c05a4e509a20ff892
