### ISSUE TITLE
Alguns registros não estão apresentando os campos de resumo, palavras-chave e url após a gravação

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#433]
Foi identificado que alguns registros, de uma determinada usuária, não estão apresentando os campos de resumo, palavras-chave do autor e url quando são editados.

Foi verificado que os campos em questão são do tipo JSON e os mesmos estão gravados no banco de dados de forma errada (string com escape)  e por isso não são mostrado ao editar o registro.

**Comment by viniciusandrade** [comment]
Ainda não foi possível identificar a causa do problema. Foi adicionado um ajuste que permite o usuário visualizar o campos em questão e salvar novamente o registro com os campos internamente arrumados.

**Comment by viniciusandrade** [comment]
@sarahviola,

Você poderia me ajudar a tentar encontrar a causa deste problema? Os registros de uma determinada usuária não estão apresentando os campos de resumo, palavras-chave do autor e url do documento depois que eles foram gravados. Nos meus testes locais criando registros do mesmo tipo (a maioria são Não Convencionais) eu não consegui localizar a causa do erro. Ela esta usando o Firefox na criação/edição dos registros.

Obrigado

**Comment by viniciusandrade** [comment]
Não foi possível reproduzir o problema em nossas estações de trabalho usando o mesmo navegador e versão da usuária. Estou finalizando e caso apareça novos casos pode ser reaberto o issue.

**Comment by sarahviola** [comment]
@viniciusandrade 

O registro id [biblio-847631](http://pesquisa.bvsalud.org/repositoriobvs/resource/pt/biblio-847631) está com um erro que acho que é relacionado. 

No iahx ele aparece com uma marcação estranha nos campos de **informação descritiva** e **resumo**. 
![image](https://user-images.githubusercontent.com/18355163/34418868-8eecafcc-ebe7-11e7-9328-718e0fad226e.png)


Deletei os dados e inclui de novo, tentando tirar qualquer formatação, então talvez quando vc for ver já esteja corrigido.

Diferentemente do problema reportado anteriormente, os dados aparecem até aparecem no FI-Admin, mas não direto no formulário de entrada de dados. Eles só aparecem ao clicar no campo, quando abrimos o assistente de preenchimento (nova janela, onde preenchemos os dados de subcampos). Além disso, as palavras-chave e URL estão ok. Não sei se é porque a Sueli já editou esse registro em setembro e já tentou corrigir.
