### ISSUE TITLE
Normalizar dados do campo Base de dados na aba Biblioteca

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#438]
Considerando necessidade de geração de índices a partir de campo Base de dados da aba Biblioteca, solicito criar tabela para controlar os nomes de bases existentes conforme a rede de cooperação.

Ex: BVS SMS
Escola Municipal de Saúde-Acervo
Autarquia Hospitalar Municipal-Acervo
etc

BVS RIC
Produçao Científica
Acervo Geral

Redetsa
Instituto de Evaluación de Tecnologías en Salud e Investigación
Comissão Nacional de Incorporação de Tecnologias no SUS
etc.

Obrigada!
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
Duplicado com #321
