### ISSUE TITLE
Acrescentar os links de Termos e Condições de Uso e Política de Privacidade

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#441]
TERMOS E CONDIÇÕES DE USO DOS SITES E SISTEMAS WEB DA BIREME/OPAS

http://politicas.bireme.org/terminos/pt/
http://politicas.bireme.org/terminos/en/
http://politicas.bireme.org/terminos/es/

POLÍTICA DE PRIVACIDADE DOS SITES E SISTEMAS WEB DA BIREME/OPAS

http://politicas.bireme.org/privacidad/pt/
http://politicas.bireme.org/privacidad/en/
http://politicas.bireme.org/privacidad/es/

**Comment by viniciusandrade** [comment]
Links adicionados no rodapé do sistema.
