### ISSUE TITLE
Analítica de monográfico não coletada para iAHx

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#452]
Registrei uma analítica de monográfico e não encontrei no iAHx da base de dados a referida analítica, somente o registro do fonte.

Caso: Repositório sobre a BVS
Monográfico registrado:
Avaliação de tecnologias de saúde & políticas informadas por evidências / Health technology assessment and evidence-informed decisions
Toma, Tereza Setsuko; Pereira, Tiago da Veiga; Vanni, Tazio; Barreto, Jorge Otávio Maia.
São Paulo; Instituto de Saúde; 2017. 456 p. tab, graf.(Temas em Saúde Pública, 22).
Monografia em Português | Repositório BVS | ID: biblio-868301 
http://pesquisa.bvsalud.org/repositoriobvs/resource/pt/biblio-868301

A analítica corresponde ao id [868302](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/868302) e não foi coletada: 
Abdala, Carmen Verônica Mendes, Figueiró, Mabel Fernandes. Bases de dados de literatura científica e estratégias de busca In: Toma, Tereza Setsuko; Pereira, Tiago da Veiga; Vanni, Tazio; Barreto, Jorge Otávio Maia. Avaliação de tecnologias de saúde & políticas informadas por evidências. São Paulo; Instituto de Saúde; 2017. p. 209-222 tab, graf.(Temas em Saúde Pública, 22).

Para ser sincera, eu gostaria que aparecesse somente a analítica, mas temo que o sistema não permita isso...

Obrigada!
Sueli

**Comment by botturam** [comment]
Sueli, existe alguma pendência a respeito deste chamado?

**Comment by botturam** [comment]
disponível em produção.
