### ISSUE TITLE
Publicar somente analítica de monográfico em iAHx

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#453]
Há situações em que somente a analítica interessa a uma determinada base de dados, porém atualmente não é possível selecionar somente um registro para uma base de dados.

O caso real é um capítulo de monografia que deve ser incluído no Repositório sobre a BVS, porém o fonte não interessa a essa base e nem os outros capítulos desse monográfico.
Exemplo:

Fonte do Monográfico que não deveria ser incluido no Repositório sobre a BVS:
Avaliação de tecnologias de saúde & políticas informadas por evidências / Health technology assessment and evidence-informed decisions
Toma, Tereza Setsuko; Pereira, Tiago da Veiga; Vanni, Tazio; Barreto, Jorge Otávio Maia.
São Paulo; Instituto de Saúde; 2017. 456 p. tab, graf.(Temas em Saúde Pública, 22).
Monografia em Português | Repositório BVS | ID: biblio-868301 

A analítica que deveria ser incluida no Repositório - id [868302](http://fi-admin.bvsalud.org/bibliographic/edit-analytic/868302):
Abdala, Carmen Verônica Mendes, Figueiró, Mabel Fernandes. Bases de dados de literatura científica e estratégias de busca In: Toma, Tereza Setsuko; Pereira, Tiago da Veiga; Vanni, Tazio; Barreto, Jorge Otávio Maia. Avaliação de tecnologias de saúde & políticas informadas por evidências. São Paulo; Instituto de Saúde; 2017. p. 209-222 tab, graf.(Temas em Saúde Pública, 22).

Chamado relacionado com #452 

Obrigada!
Sueli

**Comment by botturam** [comment]
Sueli, há alguma pendência neste chamado de 2017? Verifiquei o registro biblio-868301, e ele consta na IAHx-Regional, assim como na IAHx-RedBVS.

**Comment by botturam** [comment]
disponível em produção.
