### ISSUE TITLE
Campo 8 do formato ID não está vindo o domínio

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#454]
Vinícius por gentileza verificar no formato de exportação "ID" o campo v8^u não está vindo a formatação da URL corretamente

Ex.:
Acessando
http://fi-admin.data.bvsalud.org/api/bibliographic/?status=-3&format=isis_id&limit=100&offset=0&updated_time__gte=2017-11-13&offset=0

!ID 00000
**!v008!^udocument/view/8zpr2^ies^yPDF^qpdf** 
!v083!Introducción: La biopsia hepática permite conocer el tipo y extensión de las alteraciones histopatológicas, para ofrecer un diagnóstico especí co en relación con la clínica y hallazgos paraclínicos correspondientes. Material y métodos: Se revisaron retrospectivamente los diagnósticos de las biopsias hepáticas, realizadas durante el periodo del 1 de enero de 1994 hasta el 31 de diciembre del 2014, en los libros de registro del departamento de patología del Hospital del Niño Doctor José Renán Esquivel y se describe la frecuencia de utilización de la técnica abierta versus la técnica percutánea y las patologías encontradas.
Resultados: Se realizaron en total 486 biopsias de hígado, de las cuales 88.4% correspondían a biopsias percutáneas, y el 11.6% abiertas. Los diagnósticos más frecuentes encontrados fuer
...
...
...

Apenas para ajudar na solução, o formato mostrado na saída abaixo funciona sem problemas
http://fi-admin.bvsalud.org/api/bibliographic/?format=isis_id&id=847992

**Comment by viniciusandrade** [comment]
Problema resolvido na API de coleta do ambiente fi-admin.data.
