### ISSUE TITLE
Duplicados - analisar o que pode ou não existir duplicado.

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#460]

**Comment by arthurtreuherz** [comment]
Fábio, aqui vão alguns exemplos de 

- Duplicações permitidas: 
1. Termos: **em um mesmo registro** o termo preferido (descritor) em um idioma pode duplicar com o termo preferido ou não preferido em outro idioma (e vice-versa).
2. Annotation/nota de indexação (Annotation): de um registro pode duplicar com a nota de indexação (Annotation) de outro registro.
3. Semantic Type/Tipo Semântico, entre registros apenas
4. History Note/Nota histórica, entre registros apenas
5. Online Note/Nota Online, entre registros apenas (confirmar)
6. See also/See Related/TR, entre registros apenas
7. Record Type, entre registros apenas
8. Descriptor Type, entre registros apenas
9. Date of Creation, entre registros apenas
10. Date of Modification, entre registros apenas
11. Month ..., entre registros
12. Year ..., entre registros
13. Day ... entre registros
14. Pharmacological Actions/ Ações Farmacológicas, entre registros apenas
15. Allowed Qualifiers/Qualificadores Permitidos, entre registros apenas

- Duplicações não permitidas nesses campos
1. Scope Note/Nota de escopo/Definição
2. Código hierárquico de descritor
3. Código hierárquico de qualificador
4. Consider also
5. Abreviaturas dos qualificadores
6. MeSH Descriptor ID
7. DeCS Descriptor ID
8. MeSH Concept ID
9. DeCS Concept ID
10. DeCS Term ID
11. MeSH Term ID
12. CAS Type 1 Name
13. Descriptor Abbreviation
14. Historical Termos
