### ISSUE TITLE
"Ação farmacológica" dos medicamentos não é apresentada no serviço do DeCS no FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#462]
Para realizar a indexação de documentos é preciso que o indexador tenha pleno acesso à todas instruções contidas no DeCS.

Verificamos que os descritores de compostos químicos e medicamentos não apresentam uma informação vital para a boa indexação: a "ação farmacológica" que é a forma de ação do medicamento.
Essa é uma coordenação obrigatória e quando não é realizada, a indexação fica incompleta.

Exemplos:
Droga: Aspirina
Açoes farmacológicas existentes:
Anti-Inflamatórios não Esteroides
Antipiréticos
Inibidores de Ciclo-Oxigenase
Fibrinolíticos
Inibidores da Agregação de Plaquetas
![image](https://user-images.githubusercontent.com/13105683/33393026-eeb87a14-d524-11e7-9a27-dd49e980dc1a.png)

Droga: Albuterol
Ações farmacológicas:
Agonistas de Receptores Adrenérgicos beta 2
Broncodilatadores
Tocolíticos
![image](https://user-images.githubusercontent.com/13105683/33393367-1d06c5c8-d526-11e7-962a-d182d033d64d.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga 

Campo de ação farmacológica adicionado na janela que apresenta o termo para indexação.

https://github.com/bireme/iahx-opac/commit/85903e84c456931b1c5a3f3821d75ad536089953

**Comment by acecampos** [comment]
@wilsonmoura reabri esse issue porque:
- a informação não está no site público
- apesar de ter botão de idioma no FI-Admin, creio que a listagem ficaria enorme, a não ser que se fizesse uma seleção de mostrar no site de acordo com o idioma selecionado

**Comment by wilsonmoura** [comment]
@acecampos resolvido em bireme/Gestao-DeCS#49
