### ISSUE TITLE
Área temática na FI Legislação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#470]
@viniciusandrade a @suelisuga e eu revisamos a entrada de dados do leisref e acreditamos que a aba de área temática pode ser eliminada. Inclusive hoje ela é um campo obrigatório.

Você tem alguma informação ou opinião contrária sobre essa decisão?

**Comment by renatomurasaki** [comment]
@suelisuga e eu pensamos melhor e acreditamos que, no curto prazo, é preferível manter o Campo Área Temática para legislação, porém não obrigatório. Exemplo de uso: um ato normativo que pertença ao Repositório de Fatores de Risco em Doenças Crônicas pode também fazer parte da Rede Temática de Câncer e Nutrição, tendo em vista que os atos normativos se categorizam entre tabagismo (câncer) e obesidade (nutrição).

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/aca92a0493e4569d815487e5495453779415b3bf
