### ISSUE TITLE
Criar campo Bases de Dados > "Indexado em" para legislação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#471]
Este campo conterá informação do tipo "Leyes" ou "Fatores de Risco em Doenças não Transmissíveis".

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/9aaea587ea72296ade54f6d7aae973b4f211208b 

A lista de bases de dados deve ser controlada pelo Django Admin.
