### ISSUE TITLE
Campos DeCS que podem e que não podem duplicar

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#485]
Fábio, aqui vão alguns exemplos (depois incluir outros) de 

- Duplicações permitidas: 
1. Termos: **em um mesmo registro** o termo preferido (descritor) em um idioma pode duplicar com o termo preferido ou não preferido em outro idioma (e vice-versa). Também em um mesmo registro, num mesmo idioma o sistema diferencia maiúsculas e minúsculas. Assim, é possível a existência de 2 termos iguais, um iniciado com (ou todo em) maiúsculas, e o outro não.
2. Annotation/nota de indexação (Annotation): de um registro pode duplicar com a nota de indexação (Annotation) de outro registro.
3. Semantic Type/Tipo Semântico, entre registros apenas
4. History Note/Nota histórica, entre registros apenas
5. Online Note/Nota Online, entre registros apenas (confirmar)
6. See also/See Related/TR, entre registros apenas
7. Record Type, entre registros apenas
8. Descriptor Type, entre registros apenas
9. Date of Creation, entre registros apenas
10. Date of Modification, entre registros apenas
11. Month ..., entre registros
12. Year ..., entre registros
13. Day ... entre registros
14. Pharmacological Actions/ Ações Farmacológicas, entre registros apenas
15. Allowed Qualifiers/Qualificadores Permitidos, entre registros apenas

- Duplicações não permitidas nesses campos
1. Scope Note/Nota de escopo/Definição, entre registros não pode. Exemplo: Dois espanhóis podem ter a mesma definição no mesmo registro.
2. Código hierárquico de descritor
3. Código hierárquico de qualificador
4. Consider also (analisar melhor esse caso, pois teoricamente poderiam duplicar. Resta saber se na prática duplicam. Creio que não duplicam.)
5. Abreviaturas dos qualificadores
6. MeSH Descriptor ID
7. DeCS Descriptor ID
8. MeSH Concept ID
9. DeCS Concept ID
10. DeCS Term ID
11. MeSH Term ID
12. CAS Type 1 Name
13. Descriptor Abbreviation
14. Historical Terms

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura esses parâmetros já foram usados para construir o Fi-Admin/thesauro. Podemos encerrar esse issue.
