### ISSUE TITLE
Como administrador ou editor devo poder realizar a criação e edição de registro de Qualificador

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#489]

**Comment by arthurtreuherz** [comment]
Somente Ana, Arthur e Fábio podem criar registro de Qualificador.

**Comment by arthurtreuherz** [comment]
Editores externos à BIREME da Univ. do Chile e da BNCS do ISCIII (a serem identificados/escolhidos para criação de usuários FI-ADMIN) deverão poder editar somente os seguintes campos traduzíveis ao espanhol (descritor, sinônimos e definições). Os primeiros poderão editar apenas os campos na variante da América Latina. Os segundos os campos em espanhol variante da Espanha. 

Por enquanto TCS/AFI/BIREME é responsável pela tradução das notas de indexação em espanhol (chamado de Annotation no MeSH) por conter informação técnica de tradução delicada. Este campo não possui duas variantes e a tradução ao espanhol regional vale também para o DeCS Espanha.
