### ISSUE TITLE
Alterar para publicado todos os registros indexados na base BRISA

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#506]
Alterar no banco de dados do FI-ADMIN o status de todos os registros indexados na base de dados BRISA (código 21) para o valor 1 (publicado).

**Comment by anakatiacamilo** [comment]
Vini, alteração realizada

Documentação:
Scripts em : serverofi5:/bases/fiadmin/tools/select_indexed_database/tpl

Para selecionar os IDs
"SELECT reference_id FROM biblioref_reference_indexed_database WHERE database_id = '21';" >> $ARQ_NAME

Para alterar o Status e a data de atualização para coleta de processamento
update biblioref_reference set  \`status\` = '1', updated_time = '2018-02-05 12:00:00' where id='$id';
