### ISSUE TITLE
Implantar auditoria de registros no Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#511]
Realizar a mesma implantação de auditoria/histórico de mudanças nos registros para a fonte Multimedia.

Outros pedidos em outras fontes:
#256 TITLE
#510 TITLE

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/b4bcbcabf3d825daad94f990d1b40e1e6f388908
