### ISSUE TITLE
Implantar audiotoria / histórico de mudanças no LIS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#512]
Implantar auditoria/histórico de mudanças no LIS conforme já solicitado para outras fontes de informação geridas no FI-Admin
#511 Multimedia
#256  TITLE
#510  TITLE

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/a6414816fd75d9bde934015b00f5253b6e144c9c
