### ISSUE TITLE
Centro cooperante BR1.2 não consegue acessar aba indexado pelo meu centro 

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#513]
BR1.2  entra em Registros bibliográficos e seleciona Indexado pelo meu centro aparece o erro abaixo
![image](https://user-images.githubusercontent.com/37112458/37038338-477e76da-2133-11e8-9963-39a0eaaaf223.png)

**Comment by viniciusandrade** [comment]
@silvalais 

Acredito ter localizado e corrigido o problema. Favor informar a usuária e informar se esta OK.

Obrigado
Vinicius

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/958715fb3975676ebaeff54d9666bcc53fdc0940
