### ISSUE TITLE
Validação de campos obrigatórios e check campos relacionados

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#52]
Implementar a validação de campos obrigatórios e check campos de titulos relacionados na entrada de dados

**Comment by wilsonmoura** [comment]
Resolvido em ac6f2c51a5eb920466a4c4764c79402a86e7e933

**Comment by wilsonmoura** [comment]
Resolvido em 73770e69e49b388868a1d6c9ce8c948197fa8971
