### ISSUE TITLE
Melhorar busca no FI-Admin na aba "Todos registros" para títulos para identificação de registros existentes na base

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#529]
Prezados,

Solicito melhoria do campo de busca na aba "Todos registros" para evitar a criação de registros duplicados nas fontes de informação geridas no FI-Admin.
Por ocasião da criação de recursos educacionais para LIS verificamos que uma buscar realizada resultava em zero registros, no entanto, aprofundando a busca encontramos vários outros registros que poderiam ter sido reaproveitados somente na marcação da área temática.

Exemplos de pesquisa: 

Uso de parênteses: Centro de Vigilância Epidemiológica (CVE) = 0 resultados
![image](https://user-images.githubusercontent.com/13105683/38029043-24721626-326b-11e8-876a-82779263b90d.png)

Uso de hífen - Centro de Vigilância Epidemiológica - CVE = 1 resultado
![image](https://user-images.githubusercontent.com/13105683/38029095-51019856-326b-11e8-9993-9590be6c9025.png)

Sem adoção da sigla - Centro de Vigilância Epidemiológica = 6 resultados
![image](https://user-images.githubusercontent.com/13105683/38029241-b85c2f34-326b-11e8-8151-6980565cae01.png)
Alteramos o segundo registro porque o título não estava condizente, porém haviam outros 3 registros que poderiam ser recuperados.

Obrigada
Sueli

**Comment by rfdeoliveira** [comment]
Vou investigar se a ferramenta [Whoosh](https://whoosh.readthedocs.io/en/latest/quickstart.html) ajudaria neste caso.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula, foram realizadas melhorias na parte de recuperação do FI-ADMIN para as fontes de registros bibliográficos e recursos de internet, por isso quando possível favor avaliar a pesquisa no ambiente de testes e reportar em caso de problemas.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Boa tarde!

Refiz as buscas e obtive os seguintes resultados:

Uso de parênteses: Centro de Vigilância Epidemiológica (CVE) = 5 resultados

![image](https://user-images.githubusercontent.com/47643830/77778970-9643fa80-7030-11ea-8613-1c3a53dc2f82.png)

Uso de hífen - Centro de Vigilância Epidemiológica - CVE = 5 resultados

![image](https://user-images.githubusercontent.com/47643830/77779094-ba9fd700-7030-11ea-9219-fccea14aec73.png)

Sem adoção da sigla - Centro de Vigilância Epidemiológica = 10 resultados

![image](https://user-images.githubusercontent.com/47643830/77779177-d99e6900-7030-11ea-8dd4-15675c0e7b5e.png)

**Comment by viniciusandrade** [comment]
Obrigado, o teste demonstra melhoria na recuperação para recursos de internet.

Para o caso dos registros bibliográficos seria interessante testar as buscas mais comuns dos documentalistas, por exemplo recuperar os registros de uma determinada revista, de um determinado issue da revista e também por palavras do título e títulos completos.

**Comment by AngelicaSAPaula** [comment]
A única busca que não recuperou foi pelo título completo da revista. Os demais, estão ok!

![image](https://user-images.githubusercontent.com/47643830/77783036-f342af00-7036-11ea-9109-9996bc6759d2.png)

![image](https://user-images.githubusercontent.com/47643830/77783083-02c1f800-7037-11ea-9701-73c15a2b4f10.png)

**Comment by viniciusandrade** [comment]
OK, busca por título completo da revista não esta disponível. No meu comentário anterior eu me referia ao título completo do artigo. 
Obrigado

**Comment by viniciusandrade** [comment]
Ajustes aplicados em produção. 
Estes ajustes serão acompanhados durante algumas semanas para identificar possíveis ajustes antes de aplicar a solução para as fontes de eventos, legislação e multimídia. (serão criados issues separados)
