### ISSUE TITLE
Implementar opção de apagar uma referência

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#54]
Necessário levar em consideração se a referência foi criada pelo usuário e também confirmar no caso de ser uma referência do tipo fonte se o usuário confirma a remoção das referências analíticas associadas a fonte.

**Comment by viniciusandrade** [comment]
@suelisuga 

O botão de apagar um registro foi implementado com a seguinte regra:

- O registro do tipo analítica só pode ser apagado com status de "rascunho" e somente pelo usuário que criou o registro
- O registro do tipo fonte só pode ser apagado quando não tiver analíticas associadas e somente pelo usuário que criou o registro

Favor informar se esta regra esta OK ou propor ajuste.

**Comment by sarahviola** [comment]
ok para perfil llxp.

dúvida para perfil documentalista.
Documentalista deve poder recusar registros de usuários perfil llxp.
Exemplo: editorias, cartas, resenhas ou outros registros que podem acabar sendo incluído pelo usuário llxp, mas não são indexados na LILACS.

Teste ainda não realizado com registros criados pelo próprio documentalista.

**Comment by sarahviola** [comment]
perfil **documentalista**:

- ok para apagar **analíticas** em rascunho.
-  não aparece opção de apagar **Fonte** mesmo quando sem analíticas.

**Comment by sarahviola** [comment]
Fazendo outro teste com o perfil **documentalista** vi que ele está sim permitindo **deletar registos Fonte** do próprio usuário quando não há analíticas.

![image](https://cloud.githubusercontent.com/assets/18355163/15745576/df84317a-28a8-11e6-85cf-24cfffa8f8c3.png)

**Comment by sarahviola** [comment]
Usuário perfil llxp cassiachagas não visualiza o botão para deletar seus rascunhos:
![tela fi-admin](https://cloud.githubusercontent.com/assets/18355163/22515900/3a8c116c-e88b-11e6-93d9-d978c59366e6.JPG)

Verifiquei que o registro id 831769 realmente está no histórico de mudanças como criado pelo usuário dela, então ela deveria poder deletar.

Acessei o sistema com perfil documentalista e o botão para deletar analítica criada pelo próprio usuário e com status rascunho está aparecendo.

**Comment by sarahviola** [comment]
@viniciusandrade 
O botão para excluir registros Fonte sem analíticas também não está aparecendo para os usuários com perfil llxp. 
![sci_med](https://cloud.githubusercontent.com/assets/18355163/23022317/4b99a84a-f437-11e6-9036-849ffa5c944d.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Foi revisado esta questão. Quando possível verificar usando perfil llxp.

Obrigado
