### ISSUE TITLE
ComboBox de Tipo do Ato não mostra todos os tipos disponíveis para crear um ato durante o processo de relacionamento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#562]
![image](https://user-images.githubusercontent.com/1226218/39594263-8eba49de-4ee2-11e8-88b2-8d601bc7225f.png)

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/797e1931d2764481f30466bd6de7a5757d2fbb4e
