### ISSUE TITLE
Revisar os relacionamentos que aparecem no plug-in

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#568]
Exemplo http://sites.bvsalud.org/factores-de-riesgo/legislacion/resource/?id=leisref.act.569

Mostra que reforma a Ley 18256. Porém, ao entrar na mesma, não mostra o relacionamento de volta. Ver em http://sites.bvsalud.org/factores-de-riesgo/legislacion/resource/?id=leisref.act.353

**Comment by renatomurasaki** [comment]
@viniciusandrade revisei e atualizei todas os relacionamentos nos três idiomas (pt, es, en), deixando-os independentes de país.

**Comment by renatomurasaki** [comment]
@viniciusandrade  Por favor, atentar-se à forma de escrita no presente e passado para novos relacionamentos.

**Comment by viniciusandrade** [comment]
Revisado em https://github.com/bireme/fi-admin/commit/a067cf51db59883515f4375dec7bf4c0d1291644
