### ISSUE TITLE
Normalizar os campos Tipo de Ato, Coleção, Órgão Emissor e Fonte do Ato

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#569]
Guia para normalização no arquivo anexo.
[listas_controladas.docx](https://github.com/bireme/fi-admin/files/1972226/listas_controladas.docx)

**Comment by viniciusandrade** [comment]
Listas auxiliares revisadas pelo Django Admin e normalizações aplicadas.
