### ISSUE TITLE
Registros com problemas no codigo CC IAHX

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#577]
Vini!
O titulo da revista Clin int j Braz dent 12(2) no FI-admin apresenta a contribuição de forma correta BR186.1

No IAHX aparece indexado com o código do editor
Rergistro criado em 10 de agosto cod. Editor LILACS Express BR1820.9 
Indexer cooperative center code:BR186.1 – cod. do centro indexador
![br186 1](https://user-images.githubusercontent.com/37112458/39996533-2d5d8300-5756-11e8-9b96-52a5af45ffdb.PNG)

**Comment by viniciusandrade** [comment]
Relacionado com o issue #553

**Comment by viniciusandrade** [comment]
Revisado código em https://github.com/bireme/fi-admin/commit/449224d7723b201a97c8c6668a2052c14744f81b para preenchimento do campo indexer_cc_code e também aberto issue #746 para correção nos registros.
