### ISSUE TITLE
Erro na apresentação da aba Sugestões

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#581]
Vinicius, no Fi-Admin na apresentação da tabelas de sugestões, pra Sueli não aparece a aba de palavras chave. veja figura abaixo
![sem-palavra-chave-sugestoes-fiadmin](https://user-images.githubusercontent.com/37112458/40441785-6bbae464-5e98-11e8-8d08-fb5d9707409c.jpg)

Agora, veja copia da minha tela abaixo e temos o mesmo perfil de usuária
![sugestoes](https://user-images.githubusercontent.com/37112458/40441833-8a763426-5e98-11e8-9f61-c9efb6559a5a.PNG)

**Comment by suelisuga** [comment]
Agora esta OK.
