### ISSUE TITLE
Lista de país de afiliação de autor

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#589]
No campo de autor a lista de país de afiliação, quando o formulário esta nos idiomas de inglês e espanhol mantem os nomes dos países em português.

**Comment by viniciusandrade** [comment]
Ajuste realizado. A lista esta sendo apresentada no idioma atual da interface mas esta alteração teve impacto na ordenação da lista que precisou ser desativada pois a mesma só contempla um idioma.
