### ISSUE TITLE
Discussão sobre campo Tipo de Publicação [71]

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#593]
No campo Tipo de publicação quando o usuario não habilita o campo  "Validar usando metodologia LILACS" aparece a lista dos tipos de publicação valida para a Metodologia LILACS.
Estudar de aparecer a lista completa do DeCS.

**Comment by anakatiacamilo** [comment]
Colocar a Informação que na metodologia LILACS não tem o Tipo de Publicação = Artigo de Revista.

**Comment by suelisuga** [comment]
usar categoria CARACTERÍSTICAS DE PUBLICAÇÕES
