### ISSUE TITLE
País de Publicação mudar o check para documentos da OPAS

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#594]
Os Estados Unidos da América não esta na lista de países de publicação da Metodologia LILACS, mas quando o documento for da OPAS incluisive os que forem publicados nos EUA  o Check do sistema deria que deixar gravar.

Segue um exemplo no FI-ADMIN
http://fi-admin.bvsalud.org/bibliographic/edit-source/799203

Grata

**Comment by suelisuga** [comment]
Agora coloquei Estados Unidos na lista de países da América Latina e me deixa salvar, mas da forma como está todos os documentos dos Estados Unios poderão ser registrados na LILACS sem haver controle de consistência se são registros da OPAS.

**Comment by suelisuga** [comment]
@anakatiacamilo acreditoque está ok. Podemos fechar esse issue?

**Comment by anakatiacamilo** [comment]
@suelisuga, se para você esta bom eu vou fechar o issue.
