### ISSUE TITLE
Perfil Editor LILACS-Express deve pesquisar na base do FI-Admin

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#595]
Para evitar duplicação de registros fonte e analíticas, perfil Editor LILACS-Express precisa pesquisar na aba "Todos os registros" do FI-Admin.

Isso ajudará também ao editor a identificar qual o fascículo ele deve criar. Atualmente ele precisa ir na LILACS e pesquisar em separado.

Obrigada!
Sueli

**Comment by AngelicaSAPaula** [comment]
A página inicial para Editor LILACS-Express permanece a mesma, sem possibilidade para pesquisa em todos os registros 

![image](https://user-images.githubusercontent.com/47643830/82921840-3c3bb480-9f4f-11ea-90b6-13ac0f56a077.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula, 

Desculpe agora que percebi pelo seu print que atualizei o ambiente de produção e havia esquecido de atualizar a teste.

Poderia, quando possível, verificar novamente?

Obrigado e desculpe.

**Comment by AngelicaSAPaula** [comment]
Ok, perfil Editor LILACS-Express atualizado e já se pode visualizar todos os registros, como perfil documentalista!

**Comment by viniciusandrade** [comment]
OK, obrigado pela validação este ajuste já se encontra em produção.
