### ISSUE TITLE
Criador e Contribuidor tem formatação de entrada Sobrenome, Nome incompatível com nomes institucionais

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#617]
Ao revisar registro de OER de LIS e DirEve verifiquei que os campos Criador e Contribuidor exigem que a entrada seja feita no modelo de autor pessoal, ou seja, sobrenome, nome.

Há muitos casos, qdo se falam de recursos educacionais, em que a autoria é institucional, como foi o caso aqui.
![image](https://user-images.githubusercontent.com/13105683/42107143-ac9d978e-7bac-11e8-8ff7-290dfbb620d0.png)

Pf. retirar essa regra de consistencia de formato pois erro impede salvar e publicar o registro.

Obrigada!

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/fi-admin/commit/e3719ae9e426f438e97c5f420a13cca71c3a88d2
