### ISSUE TITLE
Mensagem de erro na aba "Objeto de aprendizagem" impede publicação de registro REA

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#618]
Mensagem de erro na aba "Objeto de aprendizagem" impede publicação de registro REA.
Não consegui identificar qual é o problema visto que o vídeo tinha sido carregado pelo Gustavo.

![image](https://user-images.githubusercontent.com/13105683/42107304-3636a224-7bad-11e8-98fc-df1840f2f784.png)

Pf. verificar visto que impede publicação do registro.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Favor realizar novo teste pois foram realizados ajustes referentes a este problema no sistema.

Obrigado.
