### ISSUE TITLE
Tirar registros fonte da aba "Indexados pelo meu centro"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#622]
Pf. retirar da aba "Indexados pelo meu centro" os registros fonte pois eles não são indexados e já aparecem com status "fonte".

![image](https://user-images.githubusercontent.com/13105683/42183313-b26164d0-7e17-11e8-8a52-3daa08c3ec81.png)

Nós revisamos os dados do fascículo, no entanto, uma vez revisados, eles não deveriam continuar nessa aba pois a contagem também fica distorcida, ou seja, na verdade há 37 registros LILACS-Express para indexar no entanto aparecem 60 na somatória.

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Alterei o comportamento para quando o usuário selecionar a aba "Indexados pelo meu centro" o sistema aplicar por padrão os filtros de tipo de registro "Revista - Artigos" e Status "LILACS Express". 

Desta forma ainda será  possível acessar a lista de Fascículos ao alterar o filtro.

Por favor veja se esta de acordo com esta alteração.

Obrigado.
