### ISSUE TITLE
Problema na atualização de registros REA

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#623]
Ao editar o registro id:814 e colocar informação de relacionamento com outro objeto, ao clicar em publicar a interface está mostrando um sinal de advertencia na aba "Objeto de Aprendizaje", como se não tivesse reconhecendo que já há um arquivo que fora carregado. Ao sair da tela e entrar novamente, percebe-se que a informação de relacionamento não foi gravada.

Isso está ocorrendo em todos os registros e em qualquer situação de atualização.

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/fi-admin/commit/99c60ba59395334d10e243d4869bba0a61dc01aa
