### ISSUE TITLE
El filtro regional en los REA está poniendo juntos los recursos de OPS y de BIREME

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#625]
Hay que separar regional - ops y BIREME en separado.

**Comment by viniciusandrade** [comment]
Conforme conversado o filtro no FI-ADMIN é referente ao nó da rede CVSP e por isso os registros OPS e BIREME são apresentados na mesma lista. 

No caso da publicação pelo plugin é feito o filtro pelo código do centro cooperante para a separação dos recursos da BIREME.
