### ISSUE TITLE
Incluir campo de País de Publicação no metadado da API Registros Bibliográficos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/fi-admin#635]
Este campo é necessário para alimentar o cluster País que aparece no plug-in WP.

**Comment by viniciusandrade** [comment]
@renatomurasaki 
Para que eu possa validar os ajustes poderia informar o exemplo de recuperação da base BRISA onde ocorre a diferença no filtro de país de publicação?

Obrigado

**Comment by viniciusandrade** [comment]
O campo de pais de publicação foi adicionado na API para revistas existentes no módulo de revistas do FI-ADMIN.
