### ISSUE TITLE
Um outro problema no FI-ADMIN na indexação do LEGSES.

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#637]
Enviado pela usuária Lilian, do SES.SP

"Um outro problema no FI-ADMIN na indexação do LEGSES. Ao clicar em qualquer ato já indexado (para edição), por exemplo o número 1407, aparece o erro "SERVER ERROR 500", impedindo qualquer alteração no registro."

![image](https://user-images.githubusercontent.com/10047460/44268101-dad9a400-a206-11e8-824c-0b555728359d.png)

**Comment by viniciusandrade** [comment]
@marcoslmori 

Ajustes realizados no sistema para o erro reportado pela usuária. Favor solicitar a validação  e re-abrir o issue em caso de problemas.

Obrigado
