### ISSUE TITLE
Indexação incompleta mostrada iAHx e iAH

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#639]
Registros indexados com descritores primários não são mostrados na interface de usuário:
Exemplo id: biblio-897695
iAHx:
![image](https://user-images.githubusercontent.com/13105683/44526012-1669e780-a6b9-11e8-8bb4-d9fbaeb00e93.png)

iAH:
![image](https://user-images.githubusercontent.com/13105683/44526056-34cfe300-a6b9-11e8-878c-f0f3150995d4.png)

FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/44527198-8a59bf00-a6bc-11e8-9a6a-72b7ae058265.png)
(atualizei a indexação)

Obrigada!

Abraços,

Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 

Lembrando que a atualização dos índices de busca IAHX/IAHX não é automática favor informar quando (mais ou menos) foi realizado a inclusão dos novos descritores?

**Comment by viniciusandrade** [comment]
@falbrito 

Levando em consideração que minha última interação com a Sueli foi a 6 dias e na data de hoje o registro na pesquisa IAHX ainda esta com os descritores desatualizados e pela API aparentemente os descritores estão corretos poder verificar o que passou?

Grato.

**Comment by falbrito** [comment]
Foi realizada a coleta após serem realizadas as correções nos registros com duplicidade nos descritores. Também foi corrigido o tratamento no pós coleta, quando o registro é LILACS-
Express

As bases de insumo foram reprocessadas e disponibilizadas para criação dos XMLs.

Aguardando processamento para validar

**Comment by viniciusandrade** [comment]
Foi realizado ajuste no processamento pois foi identificado para registros LLXP o processamento automáticamente removia os descritores primários.
