### ISSUE TITLE
Revisão dos Metadatos de FI-Admin em español para la FI REA

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-admin#640]
Email enviado por José Jardines
------------------------------------------------------------------------
> On 10 Jul 2018, at 20:26, José B. Jardines Méndez <jardines3@gmail.com> wrote:
> 
> Buenas noches Renato, lo prometido es deuda, esta fue la revisión que te comente para revisar los Metadatos de FI-Admin en español
> 
> Creator ----Creador
> Tipo de curso: 
> Diplomate----Diplomado
> Master Degree----Maestría
> 
> Tipo de Recurso Técnico:
> Collection------Colección
> Interactive Resource-----Recurso Interactivo
> Image------Imagen
> 
> Physical Object------Objeto Físico
> 
> Format 
> Enriched------Enriquecido
> 
> 
> Contexto de aprendizaje
> Professional Formation----- Formación Profesional
> University Posgrade---------Posgrado Universitario
> 
> Free Key Words----Palabras Claves libres
> 
> Interactivity type------Tipo de Interactividad
> Active-----Constructivo
> Medium-----Medio
> Asincrona--------Asíncrona
> 
> Tipo de Relacion
> Requires------Requerido por

**Comment by viniciusandrade** [comment]
Ajustes nas traduções realizados.
