### ISSUE TITLE
Formato isis_id - problema com campo v653 - local_descriptors

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#641]
Vinícius, reparamos que determinado registro não está renderizando o campo v653 no formato de extração isis_id.

Link para análise:
Registro com bug
http://fi-admin.data.bvsalud.org/api/bibliographic/?format=isis_id&id=819883

Exemplo de registro OK:
http://fi-admin.data.bvsalud.org/api/bibliographic/?format=isis_id&id=881733

Verifiquei no MySQL nas tabelas que contêm os campos "local_descriptors"
Não está em biblioref_reference.local_descriptors - O que está certo - ok pois seu uso está "deprecated" certo?

Em biblioref_referencelocal que utiliza oficialmente o campo "local_descriptors" o registro contêm 2 entradas:

select * from biblioref_referencelocal where source_id='819883';
'819883', NULL, 'REPOSITORIOBVS', '', '', 'LS 1: Bioética e Saúde Pública e Relações Internacionais', 'BR2260', '819883'
'832831', NULL, '', '', '', '', 'BR1.1', '819883'

Como existem 2 ocorrências talvez esteja trazendo a 2a. ocorrência que não tem conteúdo no campo e ai acaba não mostrando nada.

O registro de exemplo que está mostrando sem problemas, se formos analisar no MySQL só possui 1 ocorrência.
select * from biblioref_referencelocal where source_id='881733';
'885244', NULL, '', '', '', 'LS 3: Saúde Pública e Relações Internacionais', 'BR2260', '881733'

Por favor queira analisar obrigado.

**Comment by viniciusandrade** [comment]
@falbrito 

Realmente o problema estava ocorrendo na situação descrita onde existe mais de um registro na tabela referencelocal.

Apliquei uma correção que esta disponível no FI-ADMIN DATA para validação e caso esteja OK atualizo os demais ambientes.

Quando possível favor validar. Obrigado.

**Comment by falbrito** [comment]
O problema foi solucionado obrigado.
