### ISSUE TITLE
Erro quando apaga a linha de cobertura de indexação no FI-Admin

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#656]
Segue o link: http://fi-admin.bvsalud.org/title/edit/6757

Amilson

**Comment by viniciusandrade** [comment]
@wilsonmoura 
Quando puder dar uma olhada pois acredito que esta opção não tenha sido testada ainda e verifiquei que esta realmente dando erro ao tentar gravar após apagar uma ou mais linhas na aba de cobertura de indexação.
