### ISSUE TITLE
Falta Tipo de Publicação/Estudo Observacional

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#667]
Favor adicionar no formulário Fi-Admin (aba indexação) o tipo de publicação:
Descritor Inglês:                             Observational Study 
Descritor Espanhol:                       Estudio Observacional 
Descritor Português:                     Estudo Observacional 
Categoria:                          V03.175.500

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga, por gentileza adicionar via Django Admin. Obrigado.

**Comment by suelisuga** [comment]
Foram criados os Tipos de Publicação:
Personal Narratives
Dataset
Pragmatic Clinical Trial
Clinical Study
Expression of Concern
Equivalence Trial
Adaptive Clinical Trial
Observational Study
Encaminharei para @anakatiacamilo e @arthurtreuherz para atualização no DeCS

**Comment by suelisuga** [comment]
@arthurtreuherz reportou por e-mail: 
Treuherz, Arthur (BIR)
Hoje, 15:18
Suga, Sueli Mitiko Yano (BIR);

Todos abaixo agora estão marcados com a letra l (lilacs/lildbiweb).
Para a maioria desses PTs, já havíamos colocado a marcação.
 
Abraços,
Arthur

**Comment by suelisuga** [comment]
Realizado:
![image](https://user-images.githubusercontent.com/13105683/47682612-ba857880-dbab-11e8-9619-3ed92dcedceb.png)
