### ISSUE TITLE
Criação dos elementos 'collection' e 'community' nos documentos recuperados através da api.

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/fi-admin#671]
Quando realizada uma requisição no endereço 'http://fi-admin.bvsalud.org/api/bibliographic', solicito retornar dentro de cada elemento 'object' os elementos  'collection' e 'community'.

**Comment by viniciusandrade** [comment]
Elementos adicionados na API em https://github.com/bireme/fi-admin/commit/30da5ae8076f0ff7de0ac0eb89d5fd738331661d
