### ISSUE TITLE
Excluir qualificador /contraindicações do webservices do DeCS

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#674]
Considerando mudanças no DeCS o qualificador /contraindicações deixou de existir a partir da versão 2018.

Nomenclaturas adotadas: /contraindicações /contra ou /CT
![image](https://user-images.githubusercontent.com/13105683/47107392-99be3a00-d21f-11e8-945a-56dea7241781.png)

Nota técnica da NLM:

Summary of Qualifier Changes For 2018 MeSH Year
The Qualifier – “Contraindications - Q000744” has been deleted from 2018
MeSH and replaced by the MeSH Descriptor: Contraindications.
Two new MeSH descriptors 1) Contraindications, Drug, 2) Contraindications,
Procedure have been added to MeSH.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 
A lista de qualificadores permitidos no caso do webservice já se encontra atualizado com a versão atual do DeCS não sendo necessário ajustes no sistema FI-ADMIN.

Em contato com o Arthur ele identificou alguns poucos (menos de 20) termos que ainda consta este qualificador na lista dos permitidos e será realizado o reparo.

[]s

**Comment by suelisuga** [comment]
Obrigada @viniciusandrade e @arthurtreuherz!

**Comment by suelisuga** [comment]
sistema atualizado:
![image](https://user-images.githubusercontent.com/13105683/47116898-507ae400-d239-11e8-9796-8079904aa5a6.png)
