### ISSUE TITLE
Limpar conteúdo da tabela biblioref_referencelocal 

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#675]
Quando for igual a:
LILACSEXPRESS
ou
LLXPEDT

Ps. Atualizar o campo updated_time com a data da alteração

Vinculado a #639

**Comment by anakatiacamilo** [comment]
No campo "Base de Dados - [04]" da tabela biblioref_referencelocal foram apagados os conteúdos LILACSEXPRESS  e LLXPEDT.

Comandos MySQL:

Listar os IDs dos registros que tem o conteúdo,
Update para apagar o conteudo e mudar a data de atualização para coleta.

"SELECT id FROM biblioref_referencelocal WHERE \`database\` like '%LILACSEXPRESS%';
update biblioref_referencelocal set \`database\`=replace(\`database\`, "LILACSEXPRESS", "") where id='$id';
update biblioref_reference set updated_time = '2018-10-18 08:00:00' where id='$id';

"SELECT id FROM biblioref_referencelocal WHERE \`database\` like '%LLXPEDT%';
update biblioref_referencelocal set \`database\`=replace(\`database\`, "LLXPEDT", "") where id='$id';
update biblioref_reference set updated_time = '2018-10-18 08:00:00' where id='$id';
