### ISSUE TITLE
Adicionar fonte de analíticas (tipo S) no processo de verificação de duplicados

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#687]
- [ ] Criar o schema no DeDup
- [ ] Gerar SQL e arquivo de carga
- [ ] Atualizar índice DeDup com arquivo de carga

**Comment by anakatiacamilo** [comment]
A verificação são para os registros que no campo Tipo de Literatura [5] o primeiro carácter igual a S e não tenha conteúdo no campo Nível de Tratamento [6] 

Os campos para fazer a verificação de duplicados:

Título (Nível Série) [30]
Volume [31]
Número [32]
Ano de publicação [65.4]

Atenciosamente

**Comment by viniciusandrade** [comment]
Relacionado com https://github.com/bireme/DeDup/issues/16

**Comment by heitorbarbieri** [comment]
Feito em commit 4b588f3
