### ISSUE TITLE
Campo de Resumo, com fórmula que corrompe JSON

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#691]
No PK 948595 o Campo de Resumo tem uma fórmula χ^2 que corrompeu o json de modo que o usuario não conseguia nem ver a lista de registros do seu CC, tive que arrumar o Registro no MySQL para que ela pudesse editar novamente. 

Esta pesquisa buscou propor um protocolo para funcionamento de uma ferramenta de auxílio no processo de ensino/aprendizado. Tal protocolo é construído com base nos conceitos de identificação e preenchimento de lacunas de aprendizado, identificadas por intermédio de sucessivos testes rápidos (quiz) que são aplicados durante o desenvolvimento das disciplinas. A fim de verificar o potencial da proposta, e assim motivar a implementação da ferramenta em questão, foi realizado um estudo de caso envolvendo duas turmas de duas disciplinas distintas de graduação da Faculdade Anhanguera de São José dos Campos. A eficácia do processo de ensino investigado foi verificada mediante análises estatísticas, se utilizando dos testes de "Wilcoxon" que visava comparar se houve melhora entre os quizzes do mesmo assunto; "Iteração de uma amostra" que buscou verificar se as melhoras e pioras acontecem de forma aleatória; e "χ^2 para uma amostra" que verificou se a melhora difere com relação ao comportamento mediano esperado. E pôde-se observar resultados favoráveis ao método proposto, o que demonstra eficácia do protocolo, objeto desta pesquisa.

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Conforme verificamos não foi mais possível reproduzir o problema nas instâncias de teste ou produção. Estou fechando e caso seja identificado novo caso podemos reabrir este issue.
