### ISSUE TITLE
Problema com seleção de descritores para indexação de links

### ISSUE THREAD

**Issue by asael-silva** [bireme/fi-admin#7]
Ao solicitar a lista de descritores foram observados os problemas abaixo:
- demora excessiva para retornar a lista de primeiro nível do DeCS;
- navegação hierárquica também demora, às vezes funciona, às vezes trava;
- seleção de item (testado até 3º nível) foi possível;
- busca pela caixa ao topo da janela não mostra os valores encontrados enquanto se digita;
- busca não retorna valor quando se tecla [Enter] ao final do campo.

Testes realizados por Sueli Suga e Asael Silva.

**Comment by viniciusandrade** [comment]
@asael-silva, realizei testes na data de hoje e não consegui reproduzir em nossa rede o problema de lentidão na recuperação de termos do DeCS. Talvez seja um problema de conectividade externo de acesso aos nossos serviços. 

O serviço funciona somente com  auto-complete não sendo possível entrar os termos e teclar [Enter] para retornar uma lista.
