### ISSUE TITLE
Validar usando metodologia LILACS

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#701]
Os registros que no campo "Indexado em" tiver selecionado LILACS, deve ser obrigatório estar marcado o campo "Validar usando metodologia LILACS".

Grata
Katinha

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/cdae550dd85ef2386fd8cc57bd6aad48bf31aa06
