### ISSUE TITLE
Validar o Rascunho quando for gravar

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#702]
Colocar uma validação com mensagem de Erro quando o usuário for gravar o registro mesmo que no Status de Rascunho para que coloque o Título do documento é não deixe gravar um Registro vazio.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/df8197acf1c73d7622013e43383e2b18e01ee13e
