### ISSUE TITLE
Plugin Legislação SES-SP

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#744]
→ Pesquisa não está recuperando adequadamente, conforme exemplo abaixo:
Registro a ser encontrado: Resolução SS nº 171 - 08 de Setembro de 2010
Termos de busca (imagens de cada ao final): 
• Resolução SS nº 171 - 08 de Setembro de 2010
• Resolução SS 171 08 de Setembro de 2010
• Resolução SS 171
• SS 171
• Resolução 171
• Resolucao 171

→ Favor habilitar pesquisa por id
→ Labels ainda estão sem formatação
→ Quando clica em "Início", para refazer a busca, não volta pra página Leisref, mas pra página inicial da SES

![image](https://user-images.githubusercontent.com/47643830/53522990-5b346800-3aba-11e9-8638-e2b669730af2.png)
![image](https://user-images.githubusercontent.com/47643830/53523007-6b4c4780-3aba-11e9-8a68-4ccd03012a29.png)
![image](https://user-images.githubusercontent.com/47643830/53523029-7acb9080-3aba-11e9-922f-1a90111192ab.png)
![image](https://user-images.githubusercontent.com/47643830/53523069-946cd800-3aba-11e9-89a3-ae00841927ab.png)
![image](https://user-images.githubusercontent.com/47643830/53523178-e281db80-3aba-11e9-9e0b-e394637659e3.png)
![image](https://user-images.githubusercontent.com/47643830/53523198-f2012480-3aba-11e9-96a0-79e41e9a75b6.png)

**Comment by viniciusandrade** [comment]
Prezada @AngelicaSAPaula 

Revisamos a pesquisa do plugin e agora é possível localizar a legislação por qualquer termo de busca mencionado no exemplo.

A busca por ID do FI-ADMIN só é possível no próprio FI-ADMIN usando a sintaxe **id:**

Sobre a opção de voltar ao ínicio da página de legislação será necessário a atulização da versão do Wordpress para habilitar esta opção. Desta forma será aberto um chamado em suporte.bvs.br para a atualiação do sistema.

Att
Vinicius

**Comment by marcoslmori** [comment]
Como a nova versão da instancia da ses.sp (WordPress 4.9.6 ) está prevista para ir para a produção em abril 2019.  A correção poderá ser vista na instancia de homologação.
