### ISSUE TITLE
Não permitir o registro de descritores duplicados

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#750]
O FI-Admin não poderia permitir o uso de descritores duplicados, mesmo se como primário e secundário, pois seriam idênticos caso não fosse o problema na acentuação (Doenças Respiratórias e Doencas Respiratorias)

Relacionado ao issue #680

**Comment by viniciusandrade** [comment]
@suelisuga 
Ajuste realizado no sistema pelo Ronaldo. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Sistema alerta para o uso de descritores repetidos.

![image](https://user-images.githubusercontent.com/47643830/65883081-af633b80-e36c-11e9-80f3-57d5eb027573.png)
