### ISSUE TITLE
ISSN online apresentado no campo "Também nos anos" erroneamente

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#754]
Prezados,

O dado de ISSN online é apresentado erroneamente no Portal de Periódicos no campo "Também nos anos" como no exemplo abaixo:

![image](https://user-images.githubusercontent.com/13105683/54557325-9a5b2800-4999-11e9-8988-a8cb958242d7.png)

No FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/54557678-8106ab80-499a-11e9-95d9-69f8706203d3.png)

Esse campo parece ter sido excluido no processo de migração pois hoje não o encontramos mais no FI-Admin Revistas.

Obrigada!
Sueli

**Comment by anakatiacamilo** [comment]
Não mexemos no FI-ADMIN nem no processamento, só alteramos a etiqueta do Portal de Revistas de "Também nos anos" para "ISSN Online"
Atenciosamente

**Comment by wilsonmoura** [comment]
Tarefa em fase de análise.
