### ISSUE TITLE
Busca por tipo de Legislação no Fi-Admin não retorna resultados

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#764]
Busca por tipo de Legislação no Fi-Admin não retorna resultados

![image](https://user-images.githubusercontent.com/47643830/55431584-51919a80-5567-11e9-8570-5cb13deac0df.png)

![image](https://user-images.githubusercontent.com/47643830/55431599-60784d00-5567-11e9-8b4c-fc6af793a07f.png)

![image](https://user-images.githubusercontent.com/47643830/55431623-6b32e200-5567-11e9-8868-ca048c56d5a3.png)

![image](https://user-images.githubusercontent.com/47643830/55431654-74bc4a00-5567-11e9-90e5-fa7e1ed3d251.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Infelizmente o sistema interno de pesquisa do sistema é bastante limitado. 

Para melhorar a recuperação incluí o campo do tipo do ato, que foi o mencionado em seus exemplos  como um filtro na página de pesquisa e também adicionei a informação para o usuário para buscar somente por número na caixa livre.

Favor, quando possível verificar.
