### ISSUE TITLE
Perfil FI-Admin/Histórico de Mudanças

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#768]
Observei que o perfil histórico de mudanças não corresponde ao perfil do momento da publicação. Está carregando o perfil atual do usuário.

Exemplo:

472892 | Influência de posições do joelho no torque e atividade mioelétrica do tríceps sural na flexão plantar isométrica máxima
-- | --
No momento desta publicação o usuário jefferson.mota estava com o perfil BR13.2.

Consultando hoje o registro aparece o histório de mudança com o código atual(BR67.1).

8 de Março de 2019 às 10:54 | **jefferson.mota | BR67.1** | novo Descriptor: → Contração Muscular
-- | -- | -- | --

Aguardo verificação/retorno.
Obrigada!

**Comment by viniciusandrade** [comment]
Em discussão pois o sistema não foi planejado para que um usuário "trabalhe" em diferentes centros cooperantes.

**Comment by viniciusandrade** [comment]
Acredito que este problema já tenha sido tratado no issue #577 com a adição do campo **indexer_cc_code**. 

Olhando a data este campo foi implementado um pouco depois deste exemplo (20/março).

Em resumo o sistema grava o código de centro que o usuário esta no momento da indexação neste novo campo para posteriormente exportar para processamento.

**Comment by anakatiacamilo** [comment]
Fiz o seguinte teste:

Copiei a indexação do MEDLINE de dois artigos da Rev. saúde pública (Online); 52, 2018 
- PK 979023 com o código do Centro Cooperante BR67.2
- PK 979020 com o código do CC BR1.1

E o sistema funcionou como o esperado, no campo indexer _cc_code gravou com o CC correspondente ao CC que o meu usuário estava na hora de indexação, também chequei a api de coleta para a publicação e tudo funcionou corretamente.

Então com a solução do @viniciusandrade de criar o campo indexer_cc_code e gravar nele o CC de quem faz a indexação resolve esta questão.
