### ISSUE TITLE
API para sistemas legados

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#778]
Disponiblizar os dados em formato compatível com os sistemas legados

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/da788dc155a20e513fad17a293ce331761de3178

**Comment by viniciusandrade** [comment]
@anakatiacamilo, favor realizar os testes necessários para validar a exportação dos campos pela API.

**Comment by anakatiacamilo** [comment]
Vini, aparentemente só esta faltando o Nível hierárquico: 612,  613, 614

**Comment by viniciusandrade** [comment]
Implementado nível hierárquico.
