### ISSUE TITLE
Apresentar registro de destino de conceito migrado em "pop-up"

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#781]
Sugestão de apresentar destino da migração de um conceito em janela pop-up, de forma que sempre esteja visível o registro de origem. Justificativa: praticidade quando houver vários termos a serem movidos de um registro para outro distinto. O registro de origem seria atualizado concomitantemente ao aparecimento do pop-up.

**Comment by arthurtreuherz** [comment]
Ana, o Fábio, um tempo atrás, atualizou essa questão, alterando o sistema para que após uma migração o editor continue a visualizar o registro de origem. Antes o editor visualizava o registro destino. Com isso, ficou mais eficiente para quando este editor precisa migrar vários termos. Só não é em formato de pop-up. ok? Com isso, estou fechando o issue.
