### ISSUE TITLE
Não foi possível marcar um termo para ser apagado

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#782]
ID do tesauro DeCS: 32004
Situação:
- selecionado um termo para ser apagado
- aparecimento de mensagem "Este termo já existe!"
- impossibilidade de prosseguir com a eliminação do termo

Referência: mensagem de e-mail de 23-Apr-19; 18h07; de camposan@paho.org para britofa@paho.org com ilustração da situação

**Comment by acecampos** [comment]
Ocorrência igual também com o ID 32062.
Em ambos os casos, seria eliminação por "case sensitivity".

**Comment by arthurtreuherz** [comment]
Ana, agora conseguimos eliminar termos diferentes e quando, por algum motivo foram criados dois termos iguais, na hora de eliminar um deles, a forma que encontramos foi alterá-lo de alguma forma antes e alterar o seu status para Apagado. Por exemplo: "apagado_Termo X". Por isso fechei esse issue.
