### ISSUE TITLE
Eliminar termo DeCS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#783]
Fábio,

Por favor, eliminar o UP deste registro:

Descritor: Tobacco Products
UP português: Tributação de Produtos Derivados de Tabaco

Pois esse termo já está noutro descritor.

**Comment by falbrito** [comment]
Foi pesquisado o termo "Tobacco Products" no banco e só aparece uma vez.

select * from thesaurus_termlistdesc where term_string like "Tobacco Products"
'231464', '1', 'T815285', 'en', 'Tobacco Products', 'Y', 'N', 'NON', 'Y', '', '2012-01-03', NULL, '', '1', '55900'
