### ISSUE TITLE
Sensibilidade a apóstrofo

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#786]
Fábio, ao copiar um descritor com apóstrofo de um doc e colá-lo no Fi-Admin, verifiquei que o sistema não reconhece o copiado, porém, o apóstrofo estava lá no descritor. Será o caso de alguma configuração?

Situação:
Paget’s Disease, Mammary
ID: 31883

**Comment by arthurtreuherz** [comment]
Ana, não consegui reproduzir esse problema, copiando e colando esse termo no FI-ADMIN e também criando num doc e trazendo de lá para um registro do FI-ADMIN e salvando o registro. O apóstrofo continua a existir e a ser visto. Porém, Todos os registros do MeSH e DeCS devem ter o apóstrofo vertical e não o inclinado. Veja no FI-ADMIN e no MeSH os termos com apóstrofo no mesmo registro do seu exemplo: 
https://fi-admin.bvsalud.org/thesaurus/descriptors/view/91181?ths=1
https://meshb.nlm.nih.gov/record/ui?ui=D010144

Por isso, estou fechando o issue.
