### ISSUE TITLE
Visualização incompleta Leisref SES/SP

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#788]
A data de publicação está aparecendo incompleta e os relacionamentos não aparecem identificados no registro publicado.

![image](https://user-images.githubusercontent.com/47643830/56968044-cccf7780-6b38-11e9-9b81-4e909cfb05ad.png)

![image](https://user-images.githubusercontent.com/47643830/56968072-de188400-6b38-11e9-9502-33a3b5cedd95.png)

**Comment by viniciusandrade** [comment]
@marcoslmori 

Favor atualizar o plugin nesta instância para verificarmos se o problema ainda ocorre.

Obrigado

**Comment by AngelicaSAPaula** [comment]
O problema continua

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Ajuste realizado no plugin, quando possível, favor validar.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Os relacionamentos estão aparecendo corretamente, mas a data de publicação não aparece mais nessa nova visualização. No entanto, como ela já aparece no título, creio não haver necessidade dela aparecer, também, na caixa.

![image](https://user-images.githubusercontent.com/47643830/60519589-3c3d2100-9cba-11e9-8595-734f1856043c.png)

**Comment by viniciusandrade** [comment]
O campo da data de publicação só é apresentado na tela de detalhes de uma legislação, acho que é isso, certo?

**Comment by AngelicaSAPaula** [comment]
Isso mesmo!

![image](https://user-images.githubusercontent.com/47643830/60521052-e7e77080-9cbc-11e9-848e-1a87a290bd4d.png)

**Comment by viniciusandrade** [comment]
OK, obrigado pela validação.
