### ISSUE TITLE
No ato da migração, o botão de migrar permite clicar mais de uma vez

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#792]
Na tela destino aparece o conceito duplicado, mas conforme verificado, o conceito não está efetivamente duplicado.

Situação:
pt-br
Domicílios    Publicado

Tipos de Domicílio    Publicado
ID do termo: por0083534
Termo preferido do conceito: N
É permutado: N
LexicalTag: NON
Termo preferido do registro: N
Data de criação: 2 de Agosto de 2018
Anotações de histórico: 2019-05-02, received from F0001249
Tipos de Domicílio    Publicado
ID do termo: por0083534
Termo preferido do conceito: N
É permutado: N
LexicalTag: NON
Termo preferido do registro: N
Data de criação: 2 de Agosto de 2018
Anotações de histórico: 2019-05-02, received from F0001249

**Comment by falbrito** [comment]
Realizado.
