### ISSUE TITLE
Nova geração de DeCS Espanha de processamento - espanhol da Espanha

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#794]
Na geração do DeCS de processamento **da Espanha**, incluir ao final como sinônimos e em ordem alfabética todos os termos em espanhol regional QUE SÃO DIFERENTES daqueles em espanhol da Espanha (desconsiderando se caixa alta ou baixa).

**Comment by falbrito** [comment]
Realizado.
