### ISSUE TITLE
Caso de migração entre registros: termo desaparece

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#796]
Migrei o termo "indicadores ambientales" da Espanha, do descritor  "Environmental Monitoring", conceito M0007512, para o descritor "Environmental Biomarkers", conceito M000625392. Quando procurei o termo "indicadores ambientales" o sistema não achou. Estranho. (observação: na base DeCS não existia esse termo no espanhol regional.) Aí eu criei-o no conceito desejado, M000625392 e o sistema permitiu criar.

**Comment by falbrito** [comment]
Processo simulado em ambiente Beta sem problemas. Fiz uma correção no histórico para manter a relação do termo no momento anterior e o atual.
