### ISSUE TITLE
Caso de migração no mesmo registro: termo é migrado mas também permanece (gera-se uma duplicação)

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#797]
1. No descritor **Environmental Biomarkers**, conceito preferido M000625392, havia o termo da espanha "**indicador biológico**" (tendo anteriormente vindo migrado do descritor **Environmental Monitoring**). Só que "indicador biológico" também é o termo preferido do conceito não preferido desse mesmo descritor, Biological Indicator [ M000625393 ]. Como eu não tinha visto que ela já era o termo preferido do conceito não preferido, migrei-o do primeiro para o segundo e o sistema não impediu nem alertou. Em seguida, nos detalhes do termo aparecia que ele havia sido migrado, mas ao seu lado ainda aparecia "publicado" e não "migrado". Portanto, gera-se uma duplicação.

2. Depois de fazer isso, percebi que, apesar do conceito não preferido ser **Bio**logical **Indicators**, o seu conceito preferido M000625392 deste mesmo descritor **Environmental Biomarkers** possui os termos MeSH "bioindicator", e "bioindicators", e também suas traduções para o espanhol regional, português e francês. Mas vi que no espanhol da Espanha o termo "bioindicador" estava no segundo conceito em vez do primeiro. Então migrei-o de volta para o primeiro conceito. Ao fazer isso o sistema marcou corretamente que ele foi migrado (no segundo conceito) mas repetiu-o várias vezes no primeiro conceito e agora existem oito vezes o termo "bioindicador" no primeiro conceito.

**Comment by falbrito** [comment]
Realizado.
