### ISSUE TITLE
Tipo de evento é desmarcado quando editamos o registro

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#798]
Prezados,

Ao editar registro de evento Mori verificou que o campo "Tipo de Evento" retira a marcação feita anteriormente.
![image](https://user-images.githubusercontent.com/13105683/57253255-9f953480-7024-11e9-9089-a13f1e8d6f9a.png)

Aí o sistema apresenta a mensagem de erro:
![image](https://user-images.githubusercontent.com/13105683/57253291-c18eb700-7024-11e9-8371-a7b133597cb6.png)

Comportamento esperado: uma vez que o registro foi salvo/publicado o valor deve ser mantido mesmo após nova abertura para edição do registro.

Obrigada!
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
Correção aplicada via https://github.com/bireme/fi-admin/commit/c46998f81c099ccc577b7b89d80c1dafdb8c165e
