### ISSUE TITLE
Preenchimento automático de campo do formulário

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#799]
Na criação de termo, caso o usuário preencher/definir/marcar/escolher/determinar que o termo não é o preferido do conceito, o sistema já poderia (ou deveria) preencher "não" no outro campo ao lado direito desse formulário que pergunta se ele é o preferido do registro, para que não ocorram erros desnecessários. 

Uma segunda possibilidade (a ser discutida com a Ana antes de implementada, pois talvez não seja adequado fazer isso) seria, após abrir a janela de criação de termo, assim que o usuário preencher o idioma do termo, caso já exista um termo preferido do conceito (no caso de um PEP), o sistema já poderia preencher com "não", e caso já exista um termo preferido do registro (no caso de se estar no conceito principal), o sistema também poderia preencher este campo automaticamente com "não". A razão de talvez não ser bom automatizar a mudança para "não" é que o editor pode não perceber que o termo foi criado como ET e não como PEP ou MH e o registro ficar errado. Ana, por favor, poderia dar a sua opinião para essa segunda possibilidade?

**Comment by wilsonmoura** [comment]
@acecampos favor confirmar se atualmente o sistema já contempla a primeira possibilidade mencionada pelo Arthur:

> Na criação de termo, caso o usuário preencher/definir/marcar/escolher/determinar que o termo não é o preferido do conceito, o sistema já poderia (ou deveria) preencher "não" no outro campo ao lado direito desse formulário que pergunta se ele é o preferido do registro, para que não ocorram erros desnecessários.

**Comment by acecampos** [comment]
@wilsonmoura Com a possibilidade de criação automática de Termo Preferido do conceito quando fazemos as migrações entre conceitos, creio que o tema já está contemplado. Só que o recurso foi inverso: atribuição de um PEP antes de tudo.
