### ISSUE TITLE
Alterar a ordem de apresentação - Revista-Fasciculo

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#806]
Alterar a ordem de apresentação no FI-Admin, deixar na ordem do mais atual para o mais antigo em ordem de ano, volume e fascículo.
Exemplo: Rev.enferm. UERJ

**Comment by viniciusandrade** [comment]
@silvalais / @AngelicaSAPaula 
Este recurso foi implementado pelo consultor e esta disponível no ambiente de testes.

A ordenação do resultado será aplicado quando for selecionado o filtro **Tipo de registro: Revista - Fascículo**

Favor, quando possível validar.

**Comment by AngelicaSAPaula** [comment]
ok - teste realizado no ambiente de testes!

**Comment by silvalais** [comment]
Teste ok
Obrigada
