### ISSUE TITLE
Problema ao gravar um Fonte de Periódico

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#807]
Ao gravar um Fonte de Periódico quando tem mais de um título abreviado na Title o sistema apresenta o Erro abaixo

MultipleObjectsReturned at /bibliographic/new-analytic
get() returned more than one Title -- it returned 2!

/home/apps/bvsalud.org/fi-admin/bireme/biblioref/forms.py in __init__
                                    title_record = Title.objects.get(shortened_title=title_source)
...
▶ Local vars

**Comment by viniciusandrade** [comment]
O sistema foi implementado levando em consideração que somente exista uma revista por título abreviado.

A @anakatiacamilo,  temporariamente colocou um ponto final no título abreviado no Titulo que não tem o Código do Centro Indexador das revistas abaixo continuar entrando registros bibliográficos delas no FI-ADMIN

Guatemala pediátrica
Revista Científica Odontológica
