### ISSUE TITLE
Indexação não fica gravada

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#817]
Ao publicar o registro #915711, aparece o erro "MultiValueDictKeyError".

![image](https://user-images.githubusercontent.com/47643830/58495646-639a4e80-814e-11e9-819a-13f79e576950.png)

Verifiquei, pelo histórico, que o usuário realizou a indexação, mas não está ficando gravado.

![image](https://user-images.githubusercontent.com/47643830/58495695-7e6cc300-814e-11e9-8eba-f6da4246f2a4.png)

![image](https://user-images.githubusercontent.com/47643830/58495716-888ec180-814e-11e9-927e-ee450ea23432.png)

**Comment by anakatiacamilo** [comment]
O registro estava com problema, porque gravou três vezes as informações local, apagamos as repetições. Por favor, testar.
Grata

**Comment by AngelicaSAPaula** [comment]
A usuária refez os testes e deu certo! Obrigada ☺
