### ISSUE TITLE
Problema com título de monográfico com acento 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#818]
Nos registros Bibliográficos abaixo, foi necessário tirar o acento da primeira palavra acentuada para conseguir gravar o Registro.  

997513
997526
998345

O Bibliotecário fez um teste no ultimo ID tirou a opção "Validar usando metodologia LILACS" e o Título em Inglês e consegui salvar o registro com o Título acentuado.

Em alguns casos os usuário estão relatando este tipo de problema, mas na grande maioria os título acentuados não tem problema para gravar ficando difícil saber como corrigir este problema.

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

Realizei um ajuste no sistema. Poderia, quando possível, validar novamente se é possível gravar os registros.

Obrigado

**Comment by viniciusandrade** [comment]
Testes realizados pelo consultor e gravação OK.
