### ISSUE TITLE
Criar novo campo para armazenar informação do descritor MESH sugerido

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#820]
Criar novo campo para armazenar informação do descritor MESH sugerido.
No decsweb esta informação está no campo v70.

Verificar possibilidade de agregar campo a thesaurus_legacyinformationdesc.

**Comment by arthurtreuherz** [comment]
Decidimos abolir o campo MeSH-gerido. Wilson, por favor verifique quais descritores contém esse campo na última versão da base ISIS do DeCS e liste aqueles cujo descritor MeSH sugerido não existe mais no MeSH, para que possamos atualizar essa informação (retirando-o apenas, ou substituindo por outro descritor MeSH ativo). Em seguida, favor carregar movendo esse campo para o campo "Veja também". serverw/home/decs2020/www/bases/decs.mst / decs.xrf

- na base decs de 2020 acima, gerar uma lista txt de mfn|descritor em ingles (que está no campo 1)|descritor MeSH sugerido (que está no campo 70)

mx decs "pft=if p(v70) then (mfn'|'v1'|'v70/) fi" now -all > descritores-com-mesh-sugerido2020.txt

como é repetitivo, você poderá ter mais de uma linha de um mesmo mfn|descritor em inglês.

- baixar esse arquivo resultante no seu diretório de trabalho e verificar se o descritor em inglês da lista ainda existe no DeCS do FI-ADMIN. Caso não exista mais esse descritor em inglês no decs do FI-ADMIN, lista a linha "mfn|descritor em inglês (da lista)|v70" pra gente fazer o ajuste nessa lista.

- Depois que fizermos o ajuste, solicitamos que o campo v70 dessa lista seja carregado no decs do FI-ADMIN no campo "Veja também".

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura isso não é mais necessário. O campo "Veja também" cobre.
