### ISSUE TITLE
Erro ao criar analítica

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#821]
Boa tarde!

A Elizabeth, do IPEA, descreveu o problema abaixo. Tentei refazer os passos dela, mas eu consigo criar as analíticas, sem erro.

Apaguei o #992043 e ela criou o fonte #998944, que diz que está com o mesmo problema e ela não consegue criar analíticas nele.

À disposição,

Angélica de Souza Alves de Paula
Bibliotecária
FIR - Fontes de Informação Referenciais
BIREME | Departamento de Evidência e Inteligência para Ação em Saúde 
OPAS/OMS | Tel +55 11 5576-9831 VOIP 44863
 

De: Elizabeth Gonçalves Vilarino de Castro Costa <elizabeth.costa@ipea.gov.br> 
Enviada em: quinta-feira, 6 de junho de 2019 16:30
Para: #BIR:Lilacs <bir.lilacs@paho.org>
Assunto: RES: Erro ao gravar registros no FI-Admin

Oi Angélica, boa tarde.

Acredito que não seja isso. Ele não está gravando essas informações...eu estou preenchendo todos os campos e não estou “publicando”, mas somente salvando em “Gravar Rascunho” como fiz com outros 17 que estão nessa situação lá na base (como Rascunho). 

Fui ao registro fonte da Analítica (que é onde entra a editora) preenchi o campo, tentei criar a analítica 3x e continuou com problema fiz muitos na terça-feira e não tive esse problema...nao sei o que fazer  

Elizabeth. 

De: #BIR:Lilacs [mailto:bir.lilacs@paho.org] 
Enviada em: quinta-feira, 6 de junho de 2019 15:31
Para: Elizabeth Gonçalves Vilarino de Castro Costa <elizabeth.costa@ipea.gov.br>
Assunto: RES: Erro ao gravar registros no FI-Admin

Prezado Elizabeth,
Boa tarde!

Não está sendo possível publicar o registro pois faltam as seguintes informações obrigatórias: Autor, título traduzido, editora.

À disposição,

Angélica de Souza Alves de Paula
Bibliotecária
FIR - Fontes de Informação Referenciais
BIREME | Departamento de Evidência e Inteligência para Ação em Saúde 
OPAS/OMS | Tel +55 11 5576-9831 VOIP 44863
 

De: Elizabeth Gonçalves Vilarino de Castro Costa <elizabeth.costa@ipea.gov.br> 
Enviada em: quinta-feira, 6 de junho de 2019 13:45
Para: #BIR:Lilacs <bir.lilacs@paho.org>
Assunto: Erro ao gravar registros no FI-Admin

Angélica, boa tarde.

Hoje não estou conseguindo salvar nenhuma analítica (gravar como rascunho), preencho todos os dados várias vezes e perco tudo porque está dando sempre esse retorno...sabe me dizer o que é?

![image](https://user-images.githubusercontent.com/47643830/59357777-cddff100-8d01-11e9-8af9-e6f5081b3d45.png)

Elizabeth G. V. de Castro Costa
Instituto de Pesquisa Econômica Aplicada – Ipea
Bibliotecária / Bolsista
elizabeth.costa@ipea.gov.br
(61) 2026-5913

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Quando possível favor realizar novo teste para este caso após os ajustes que aplicamos no FI-ADMIN. 

Obrigado
