### ISSUE TITLE
Ao clicar em ID, dá erro (187375)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#822]
Ao clicar no id desse registro, ele aparece o seguinte erro

![image](https://user-images.githubusercontent.com/47643830/59371077-65e9d480-8d1a-11e9-89b1-266b14316e05.png)

Isso acontece com as analíticas da revista Coluna/Columna 15 (1), 2016 (#187364)e 14 (3) 2015 (#187331)

![image](https://user-images.githubusercontent.com/47643830/59371282-fc1dfa80-8d1a-11e9-9176-34ff41bc58fe.png)

![image](https://user-images.githubusercontent.com/47643830/59371301-06d88f80-8d1b-11e9-8307-a0b34ed14f88.png)

**Comment by anakatiacamilo** [comment]
Problema corrigido pontualmente de acento na afiliação. Por favor, testar

Hospital de Traumatología y Ortopedia "Lomas Verdes" of the IMSS (Instituto Mexicano del Seguro Social)

Atenciosamente

**Comment by AngelicaSAPaula** [comment]
Realizei os testes e está tudo certo. Vou entrar em contato com o usuário
