### ISSUE TITLE
Erro ao publicar registro LILACS-Express (#285086)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#823]
•	J. venom. anim. toxins incl. trop. dis; 17 (4), 2011 → Ao tentar gravar, aparece o seguinte erro

![image](https://user-images.githubusercontent.com/47643830/59371698-21f7cf00-8d1c-11e9-987e-d32904134704.png)

**Comment by anakatiacamilo** [comment]
Bom dia Angelica,

Este problema ocorre quando tem dois Títulos Abreviados igual no controle da Title, foi resolvido este título especifico , mas estamos tratando deste assunto no issue #807

Katinha

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo Transformei ele em LILACS-Express para publicar novamente, e deu tudo certinho!
