### ISSUE TITLE
Erro na apresentação do mapa do Google Maps no Plug-in do DirEve

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#824]
Prezados,

Erro na apresentação do Mapa do Google maps para a BVS Homeopatia, porém, para BVS MTCI e BVS Brasil sai normal o google maps de todos os eventos que a usuária inclui para estas BVS.

![image](https://user-images.githubusercontent.com/13105683/59385344-8033aa80-8d3a-11e9-83c5-d5547ebf6d43.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 
Correção realizada pelo Wilson e já aplicada no ambiente do FI-ADMIN.

Favor validar.
Obrigado

**Comment by suelisuga** [comment]
Prezados,

O comportamento está normal no FI-Admin e BVS Regional, porém não foi apresentado o mapa no plug-in de eventos da BVS Homeopatia:

FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/59608931-c9924a00-90ec-11e9-9fd6-c81e6d8f4744.png)


BVS regional:
![image](https://user-images.githubusercontent.com/13105683/59608960-dadb5680-90ec-11e9-810f-d41c054207fd.png)

Visualização na BVS Homeopatia:
![image](https://user-images.githubusercontent.com/13105683/59608875-acf61200-90ec-11e9-831b-0c46bd0d8424.png)

No aguardo.

Obrigada!
Sueli

**Comment by suelisuga** [comment]
Conforme esclarecimento a correção foi realizada no sistema FI-Admin e visualização é possível desde que o plug-in, conforme visto no portal BVS Regional.

Para correção de erro no plug-in do direve da BVS Homeopatia será realizada atualização dele na instancia dessa BVS. Espera-se assim resolver este problema.

Correção encaminhada para suporte técnico da BVS.

Obrigada!
Sueli
