### ISSUE TITLE
Campo indexação não-clicável

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#827]
A usuário gisele.silva (BR1421.1) relatou que quando ela tenta indexar algum registro, como o #958898, o campo para seleção de termos no DeCS fica "não-clicável", com o ícone do mouse vermelho, e aparece a seguinte mensagem no campo: setlmmediate$0.1420304090921971$4 (imagem abaixo)

![image](https://user-images.githubusercontent.com/47643830/59609066-1118d600-90ed-11e9-9549-6dbf4ac458bc.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Caso não seja possível reproduzir o erro em nossos computadores/navegadores se trata provavelmente de um problema local da usuária. 

Favor solicitar que ela tente realizar o teste usuando outro computador e outro navegador para poder nos informar mais detalhes de quando o erro ocorre.

Obrigado
