### ISSUE TITLE
Duplicação de descritores (#958373)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#831]
Quando tento publicar um artigo, apresenta o seguinte erro no sistema. O artigo é da Rev. bras. cineantropom. desempenho hum; 20 (4), 2018. Os descritores duplicam-se.

![image](https://user-images.githubusercontent.com/47643830/59757599-84902400-9262-11e9-89cf-3169f3be887a.png)

**Comment by anakatiacamilo** [comment]
Angelica, arrumamos, por favor, validar.
Grata
Katinha

**Comment by AngelicaSAPaula** [comment]
Transformei em LILACS-Express e publiquei novamente, sem erros e os descritores não estão mais duplicados!

![image](https://user-images.githubusercontent.com/47643830/60463685-0731bf80-9c23-11e9-81eb-df4722d518b6.png)
