### ISSUE TITLE
Termo não selecionável para indexação

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#832]
Um usuário precisa utilizar o termo "Reprodutibilidade dos testes" para indexar um artigo. No entanto, aparece um erro conforme prints anexos. Ao pesquisar, ele retorna com uma tela que não permite selecionar o termo. 

A usuário utilizou o Mozila Firefox e eu utilizei o Chrome, mas em ambos os navegadores o comportamento foi o mesmo.

![image](https://user-images.githubusercontent.com/47643830/60023995-51d49a00-966d-11e9-85d3-9089c1809394.png)

![image](https://user-images.githubusercontent.com/47643830/60024016-5c8f2f00-966d-11e9-977b-23f9692cc27a.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Correção realizada. Poderia, por favor,  realizar novo teste e caso esteja OK informar a usuária?

Obrigado.

**Comment by AngelicaSAPaula** [comment]
Realizei o teste e, no meu perfil, deu certo! Vou comunicar a usuária!

**Comment by viniciusandrade** [comment]
OK, obrigado. Estou fechando o issue mas caso seja necessário pode re-abrir.
