### ISSUE TITLE
Registro com erro ao publicar e, não grava os termos indexadores nem registra as mudanças no histórico (ID 962604)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#835]
Registro com erro ao publicar (ou gravar como LILACS-Express), além de não gravar os termos indexadores nem registrar as mudanças no histórico (ID 962604).

Tentei por 2 navegadores diferentes e deu o mesmo erro que a usuária reportou.

![image](https://user-images.githubusercontent.com/47643830/60440686-b81c6800-9beb-11e9-882d-f2c8831a2259.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Realizei um ajuste no FI-ADMIN. Poderia, por gentileza, realizar novo teste e informar se agora é possível alterar o registro?

Obrigado

**Comment by AngelicaSAPaula** [comment]
@viniciusandrade na hora que cliquei em "Publicar", a mensagem de erro continuou aparecendo (imagem abaixo), mas, ao voltar a página, ele está como publicado:

![image](https://user-images.githubusercontent.com/47643830/60463274-e74dcc00-9c21-11e9-9804-8123da7b0831.png)

![image](https://user-images.githubusercontent.com/47643830/60463352-254af000-9c22-11e9-939b-a1b32a45925d.png)

**Comment by viniciusandrade** [comment]
OK, obrigado pelo teste. Consegui pegar o mesmo erro e fiz um novo ajuste no sistema.

Verifiquei que embora ele tenha publicado perdeu o descritor de assunto devido ao erro apresentado. Eu entrei e coloquei "malaria" somente para testar. 

Você poderia ajustar uma vez mais a indexação e tentar realizar a gravação/publicação novamente?

Obrigado.

**Comment by AngelicaSAPaula** [comment]
A usuária e eu testamos e já  está publicando corretamente!
