### ISSUE TITLE
Erro ao publicar registro (#994624)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#838]
Incluí um termo indexador e publiquei o artigo, sem erro. Depois, apaguei o termo e fui voltar para LILACS-Express e apresentou o mesmo erro reportado pela usuária, conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/47643830/60530574-6c42ef00-9ccf-11e9-97f4-921f9876f7a8.png)

**Comment by AngelicaSAPaula** [comment]
Com o perfil em BR1.1 eu consegui voltar pra LILACS-Express, mas com o BR32.1, deu erro

**Comment by anakatiacamilo** [comment]
Foi excluído o campo duplicado que estava dando problema.Por favor testar.

**Comment by AngelicaSAPaula** [comment]
Usuária já indexou e publicou este registro!
