### ISSUE TITLE
Implementar formulário e validação para tipo "S" nível de tratamento "as"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/fi-admin#84]
Relacionado ao backlog de produto #77

**Comment by sarahviola** [comment]
Falta validações para LILACS nos campos:
- Tipo de registro
- Forma do ítem
- Tipo de periódico

![image](https://cloud.githubusercontent.com/assets/18355163/15122294/d02b312c-15f4-11e6-9fbb-55b35419d0f8.png)

**Comment by viniciusandrade** [comment]
Implementada validação para campos tipo de registro [09] e forma do ítem [110]. 

O campo 113 depende de integração com a TITLE para verificação de separatas. 

Falta implementar javascript responsável em contextualizar os campos do formulário de acordo com o campo tipo de registro [09]

**Comment by viniciusandrade** [comment]
@sarahviola 

Implementado mecanismo (javascript) para contextualizar os campos do formulário de acordo com o tipo de registro [09]. Quando possível favor validar.

**Comment by sarahviola** [comment]
Campos **Forma do Item** [110] e **Tipo de periódico** [113] com **tabelas corretas** de acordo com campo de Tipo de registro [09].

@viniciusandrade 
**Falta** validação para documentos **indexados em LILACS**:
- Tipo de registro: material textual (a)
- Forma do item: Eletrônico (s) ou vazio*
- Tipo de periódico: Revistas (p) ou Separatas (u). 

* Dúvida: campo forma do item pode ser Eletrônico ou vazio, mas como definimos na issue #159 , agora terá que ser necessariamente "Eletrônico"? E não conseguiremos editar registros antigos se necessário?

**Comment by sarahviola** [comment]
@viniciusandrade 

Corrigir a palavra **item**, em "Forma do ítem", retirando o acento.
Apesar de estar com acento no LILDBI-Web e nos manuais da LILACS, a palavra item não é acentuada.

**Comment by viniciusandrade** [comment]
@sarahviola 

Ajustes realizados. Quando possível realizar nova verificação no ambiente de testes.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade 

O sistema está dando erro no campo **Tipo de periódico** quando preenchido corretamente com Revistas ou com Separatas, tanto para salvar como LILACS-Express como Publicado..

![image](https://cloud.githubusercontent.com/assets/18355163/15791098/c82a033e-29ab-11e6-93e3-dd6ee281b771.png)

**Comment by viniciusandrade** [comment]
@sarahviola 

Realmente a verificação estava errada. Por favor quando possível verifique novamente.

[]s

**Comment by sarahviola** [comment]
@viniciusandrade, 

Agora consigo publicar registros Sas sem Tipo de periódico, mas para revistas LILACS o sistema deveria exigir Revistas ou Separatas (antes exigia e não deixava salvar mesmo selecionando um dos dois).

**Comment by viniciusandrade** [comment]
@sarahviola 

OK, ajuste realizado. Quando possível realizar novo teste.

[]s

**Comment by sarahviola** [comment]
Agora está ok!

Falta ajustar na mensagem de erro que tem que ser Revistas ou Separatas somente quando marcado "Indexado em LILACS". (Testei desmarcar "Indexado em LILACS" e o sistema está permitindo gravar os outros tipos de periódico, que é o comportamento correto).

Então, a mensagem de erro deveria ser algo tipo "Para artigos **indexados na LILACS** o tipo de periódico deve ser Revistas ou Separatas"

Mensagem atual do LILDBI-Web também não é muito clara:
![image](https://cloud.githubusercontent.com/assets/18355163/15832939/ddd82598-2bfa-11e6-98db-6a8874527be8.png)

**Comment by viniciusandrade** [comment]
@sarahviola,

Mensagem de erro ajustada. Favor verificar e fechar se estiver OK.

[]s

**Comment by sarahviola** [comment]
certo!
