### ISSUE TITLE
Múltiplos registros iguais no campo de sinônimo (pt-br)

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#840]
Fábio,
Ao inserir um termo de entrada no ID 126 do tesauro DeCS, este termo foi multiplicado por 8.
![image](https://user-images.githubusercontent.com/35345406/60542322-04e66880-9cea-11e9-8b4c-7d4402e3ee95.png).
Ao tentar apagar a primeira repetição do termo, o sistema bloqueou a alteração para "Apagado", conforme abaixo:
![image](https://user-images.githubusercontent.com/35345406/60542437-58f14d00-9cea-11e9-9026-f730bfca0950.png)
Ao dar "Cancelar" para voltar, verifiquei que o termo só aparece duplicado (e não 8 vezes) na página inicial do registro:
![image](https://user-images.githubusercontent.com/35345406/60542575-a2da3300-9cea-11e9-8e02-b3fae90417e1.png)

**Comment by falbrito** [comment]
Duplicação corrigida.
