### ISSUE TITLE
Fi-admin - não deleta id na Title

### ISSUE THREAD

**Issue by amilsonsantos** [bireme/fi-admin#842]
Fi-admin não deleta titulo duplicado na Title, aparece mensagem de erro,
ex. de titulo para deletar: id-9834 e id-4168

![ERRO_DELETE_TITLE](https://user-images.githubusercontent.com/53013793/61400460-afdc5200-a8a6-11e9-8537-26633f28d6b6.PNG)

**Comment by rfdeoliveira** [comment]
@viniciusandrade, entendi o problema. O que acontece é que, quando o campo `created_by`, que armazena o usuário que cadastrou o `Title` está vazio, [essa condição](https://github.com/bireme/fi-admin/blob/master/bireme/title/views.py#L295) se torna verdadeira e retorna um objeto `HttpResponse`, ou seja, entramos no fluxo em que o usuário logado é diferente do que criou o `Title`, portanto, não teria permissão para deletar o registro. O comportamento esperado do método `get_object`, caso não seja possível retornar o objeto que será deletado, seria levantar uma exceção, avisando ao usuário que o mesmo não pode executar essa ação, pelo que entendi. Você acha que faria sentido permitir a exclusão do registro quando o mesmo não possuir dono, ou deveríamos apenas ajustar o fluxo para que a mensagem da exceção deixe mais claro o que houve?

**Comment by viniciusandrade** [comment]
@rfdeoliveira, verifiquei com o pessoal aqui e como este modelo atualmente é administrado pela equipe interna por favor altere a verificação para permitir esta ação somente para usuários do centro **BR1.1**, esta info pode ser obtida como abaixo:
```
user_cc = self.request.user.profile.get_attribute('cc')
```

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula, correção disponível no ambiente de testes. 
Quando possível, favor validar.
Obrigado

**Comment by AngelicaSAPaula** [comment]
Teste ok!

**Comment by viniciusandrade** [comment]
:+1:
