### ISSUE TITLE
Alterar código hierárquico do ID de transporte UI16f6bbaf para HP4.000.000.026 e avisar-me

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#862]
Fábio, movi o único conceito de um registro (ID de transporte = UI16f6bbaf) para outro registro e me esqueci de primeiro alterar o seu código hierárquico para um valor fictício crescente/sequencial. O próximo valor disponível é HP4.000.000.026. Você pode fazer isso para mim, por favor? Por favor me avise quando você o fizer para eu poder então incluir esse código hierárquico nesse outro descritor.

Desde já agradeço.

**Comment by falbrito** [comment]
Realizado.
