### ISSUE TITLE
Erro ao visualizar PDF no iAHx

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#866]
Alguns registros da SES, realizados pela usuária tania.andrade, quando pesquisamos no iAHx, ao clicar em "texto completo" dá erro. Testei por vários navegadores e o comportamento é o mesmo.

Entrei no registro de cada um no fi-admin e verifiquei os arquivos PDF e eles estão ok.

Alguns exemplos de registros: 1005977, 1005969, 1006009, 1006500

![image](https://user-images.githubusercontent.com/47643830/62545123-778dbb00-b837-11e9-8064-68311ee019ae.png)

**Comment by anakatiacamilo** [comment]
Bom dia, 
Alguns registros estão com problema na URL (falta o domínio do FI-ADMIN)

^uhttp://fi-admin.bvsalud.org/document/view/56csn

Fizemos uma nova coleta especifica de todos os registros com problema, por favor, testar para ver se deu certo no iaHx a partir do dia 12/08

Exemplos:
000001|945|^udocument/view/wyms7^ipt^yPDF^qpdf
000331|998172|^udocument/view/54gtn^ipt^yPDF^qpdf
000333|998284|^udocument/view/j86c8^ipt^yPDF^qpdf
000464|1007994|^udocument/view/wmfmd^ipt^yPDF^qpdf
000468|1006470|^udocument/view/yzmg7^ies^yPDF^qpdf
000471|1006481|^udocument/view/z6tfa^ies^yPDF^qpdf
000499|1007762|^udocument/view/5r26d^ipt^yPDF^qpdf
000507|1007904|^udocument/view/wsatv^ipt^yPDF^qpdf
000512|1008003|^udocument/view/bhbh7^ipt^yPDF^qpdf
000513|1008013|^udocument/view/zg5yt^ipt^yPDF^qpdf
000519|1008201|^udocument/view/6re5q^ies^yPDF^qpdf
000525|1008259|^udocument/view/547nc^ipt^yPDF^qpdf
000526|1008265|^udocument/view/jay7x^ipt^yPDF^qpdf
000533|1008300|^udocument/view/mcyx7^ipt^yPDF^qpdf
000534|1008301|^udocument/view/gttpq^ipt^yPDF^qpdf
000536|1008311|^udocument/view/6gx6s^ipt^yPDF^qpdf
000537|1008317|^udocument/view/n87fh^ipt^yPDF^qpdf

Atenciosamente
Katinha

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo Todos os ids mencionados anteriormente continuam com o mesmo erro

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, arrumamos no Processamento então conforme orientado acima olhar no portal de pesquisa (iaHx) somente na semana que vem quando ele será publicado. Por isto não encerrei o issue.

**Comment by anakatiacamilo** [comment]
@viniciusandrade, por favor, verificar o ambiente da API do FI-ADMIN Data onde fazemos a coleta a questão da URL dos arquivos que são carregados no FI-ADMIN que não estão aparecendo com o domínio na API de coleta. Temporariamente fizemos uma coleta na Produção para poder publicar os dados corretamente. Grata

**Comment by viniciusandrade** [comment]
@anakatiacamilo 

O ambiente foi revisado e identificamos que o arquivo de configuração havia sido alterado em 28/06 pelo suporte e portanto dados desta data em diante não estão com o campo de URL completo.

Ajustei a configuração e agora esta novamente OK.

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula fizemos os testes e os links agora estão Ok
