### ISSUE TITLE
Reprocessar analíticas de fontes que foram alterados

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#879]
Ao fazer modificação do título abreviado de um periódico, verificamos que os dados das analíticas não são recuperáveis na busca do FI-Admin.

Na visualização as analíticas mostram o dado do fonte atualizado, mas não aparece como resultado de pesquisa.

![image](https://user-images.githubusercontent.com/13105683/63115620-f6889f00-bf6d-11e9-96a3-0600e160ba02.png)

Lembrar de fazer o processamento de coleta para a publicação no iaHx destas analíticas que foram alteradas com a mudança do fonte, mas não foi alterado a data de modificação.

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga 
Foi implementado que ao gravar um registro do tipo fonte o sistema realiza a atualização do título da revista em todas as analíticas.

A @anakatiacamilo vai repassar os casos para que sejam realizados os testes no sistema.

**Comment by suelisuga** [comment]
@viniciusandrade verificamos que é necessário publicar novamente o fonte para que a analítica apareça... Pensando que todos os fontes terão que ser revisados, penso que tudo bem.

Na lista atual temos 200 e tantos para LILACS e iremos priorizá-los.

Criaremos uma lista com todas as bases para ver o tamanho da ação necessária e atribuir a revisão interna.

Obrigada!
Sueli

**Comment by suelisuga** [comment]
ok. obrigada
