### ISSUE TITLE
Incluir status "Migrado" e "Submissão" no filtro de busca Status

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#881]
Prezados,

Incluir status "Migrado" e "Submissão" no filtro de busca Status
![image](https://user-images.githubusercontent.com/13105683/63287113-ea635100-c28f-11e9-8d70-08af387e23c8.png)

Pf. confirmar com @anakatiacamilo se status "Submissão" será mantido, se não, nao incluir e trocar status dos que já estão na base.
 
Obrigada!
Sueli

**Comment by anakatiacamilo** [comment]
@suelisuga não é necessário incluir o status de Submissão no filtro de busca do Status, atualmente não tem registros com este Status e a tendencia é não ter mais.

**Comment by suelisuga** [comment]
@anakatiacamilo ok.

Então pf. incluir o status "Migrado"

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Ajuste disponibilizado no ambiente de testes, aguardando validação para publicação.

**Comment by AngelicaSAPaula** [comment]
Filtro "migrado" já aparece e faz a recuperação corretamente no ambiente de testes
