### ISSUE TITLE
Entrada duplicada - idioma es Conceito M000606085

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#890]
Fábio, por favor, elimine o idioma duplicado **es** preferido do Conceito **M000606085** em destaque.

![image](https://user-images.githubusercontent.com/35345406/63884713-16c44f00-c9ad-11e9-9b8a-e4236e0a5cf1.png)

Agradeço!

**Comment by acecampos** [comment]
Da mesma forma, favor eliminar o idioma es duplicado, conforme aconteceu com o **M0577154**
![image](https://user-images.githubusercontent.com/35345406/64129007-c45da680-cd8f-11e9-88bc-fa092a6802d4.png)
Obrigada!

**Comment by falbrito** [comment]
Realizado.
