### ISSUE TITLE
Mudança de título/fonte não aparece dados nos campos com assistente

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/fi-admin#892]
Katinha, 

Conforme conversamos segue alguns exemplos:

https://fi-admin.bvsalud.org/bibliographic/edit-source/833207 mudança fonte de Interface comun. saúde educ para Interface (Botucatu, Online)

https://fi-admin.bvsalud.org/bibliographic/edit-analytic/833208 analítica não aparece os campos:
palavras-chave do autor
Resumo
Texto completo

https://fi-admin.bvsalud.org/bibliographic/edit-source/883846 mudança fonte de Gerais para Gerais (Univ. Fed. Juiz Fora)

https://fi-admin.bvsalud.org/bibliographic/edit-analytic/883853 analítica não aparece os campos:
palavras-chave do autor
Resumo
Texto completo

Obrigada!

**Comment by anakatiacamilo** [comment]
@alvesmarilda foi ajustado os problemas, por favor, verificar se nas próximas não vão mais ocorrer.
Quanto os que já foram alterados estamos fazendo um script para alterar.
Katinha

**Comment by anakatiacamilo** [comment]
@alvesmarilda é do mudar o id

https://fi-admin.data.bvsalud.org/api/bibliographic/?format=isis_id&id=999999

**Comment by suelisuga** [comment]
@anakatiacamilo está ok?

**Comment by anakatiacamilo** [comment]
Ok
