### ISSUE TITLE
Incluir busca por ID no Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#893]
Prezados,

Ao realizar buscas por ID no Multimedia não recuperamos o ID do registro na base.
Solicito implantação.

![image](https://user-images.githubusercontent.com/13105683/64292125-04638b80-cf40-11e9-862b-ce70c15ea2af.png)

Obrigada!

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Ajuste disponibilizado no ambiente de testes, aguardando validação para publicação.

**Comment by AngelicaSAPaula** [comment]
Ok, busca por ID está ok no ambiente de teste!
