### ISSUE TITLE
Incluir pesquisa por ID no LIS (recursos)

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#894]
Solicito inclusão de IDs na busca dentro de Recursos de Internet no FI-Admin
 ![image](https://user-images.githubusercontent.com/13105683/64292461-d92d6c00-cf40-11e9-82fe-34e61733a31c.png)

Obrigada
Sueli

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Ajuste disponibilizado no ambiente de testes, aguardando validação para publicação.

**Comment by AngelicaSAPaula** [comment]
Busca por ID ok no ambiente de teste
