### ISSUE TITLE
Erro na Gravação Status LILACS-Express- no sistema FI-Admin

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-admin#904]
Id:955483 - no momento de gravar como LILACS-Express apresenta o erro abaixo:
![UERG-](https://user-images.githubusercontent.com/37112458/64621852-c55c8c80-d3bc-11e9-8fb4-1ba6632d1c2e.PNG)

**Comment by anakatiacamilo** [comment]
Lala, é aquele problema de gravar duas vezes os dados locais, ja apaguei um agora deve estar funcionando.

**Comment by silvalais** [comment]
Você tem que apagar por baixo? Porque eu apaguei mas não funcionou

Obrigada
Laís

De: anakatiacamilo <notifications@github.com>
Enviada em: terça-feira, 10 de setembro de 2019 11:44
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Silva, Lais Aparecida da (BIR) <silvala@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Erro na Gravação Status LILACS-Express- no sistema FI-Admin (#904)


Lala, é aquele problema de gravar duas vezes os dados locais, ja apaguei um agora deve estar funcionando.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F904%3Femail_source%3Dnotifications%26email_token%3DAI3EVCWMFDIK57B6IFYV6RLQI6XB7A5CNFSM4IVILB22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6LLANQ%23issuecomment-529969206&data=02%7C01%7Csilvala%40paho.org%7C95b713b1d7f34f9a40c908d735fd47f9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637037234311685032&sdata=%2F4gT2d8grEoJtLwIAQ0tBrCGgWJY0uhFqFoQ7fWgsRE%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI3EVCUASCNL6LIAH3KYBSDQI6XB7ANCNFSM4IVILB2Q&data=02%7C01%7Csilvala%40paho.org%7C95b713b1d7f34f9a40c908d735fd47f9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637037234311685032&sdata=w46W4AXwhBpUQqmsycGcCNNl81N2HBGoVR%2F5snmxt4E%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by anakatiacamilo** [comment]
@silvalais sim eu tenho que apagar por baixo

**Comment by anakatiacamilo** [comment]
@silvalais este problema foi resolvido vou fechar esta issue
