### ISSUE TITLE
Ao selecionar um termo para indexação, aparece outro.

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#905]
Ao selecionar o termo "**Testes**", aparece a definição do termo "**Testículos**".

![image](https://user-images.githubusercontent.com/47643830/64626671-94805580-d3c4-11e9-8d26-95cfa864f9da.png)

![image](https://user-images.githubusercontent.com/47643830/64626710-a3670800-d3c4-11e9-881a-a7a67211ee7d.png)

**Comment by falbrito** [comment]
O Descritor "Testis" em inglês, tem como sinônimo em inglês também "Testes".
Então como é um sinônimo vem como resultado da busca.

![image](https://user-images.githubusercontent.com/6940371/64864463-88d39f80-d60d-11e9-9259-e462d263d976.png)

**Comment by viniciusandrade** [comment]
Estou fechando uma vez que como explicado pelo @falbrito se trata de sinônimo de descritor do MeSH.
