### ISSUE TITLE
Problema de duplicar as informações Locais.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#907]
Problema de duplicar as informações Locais da Aba Biblioteca, se possível desabilitar o botão de gravar o Registro depois da primeira vez que ele foi clicado (Se aparecer mais de um botão como "Gravar como ...." + "Publicar" desabilitar os dois) talvez com isso pare de duplicar algumas informações.  

Referente ao chamado #867

Grata

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
O Ronaldo implementou esta issue que tem como objetivo prevenir a ocorrência do erro "MultiValueDictKeyError" que acontece esporadicamente e necessita da intervenção da Katinha para ajuste na base de dados.
O que ele fez, e que foi uma sugerência do Renato, foi desabilitar os botões quando o usuário envia o formulário, evitando o envio múltiplo.
Este ajuste esta disponível no ambiente de testes, por favor, quando possível da uma olhada se esta OK para ir para produção.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Ok, farei o monitoramento!

**Comment by viniciusandrade** [comment]
OK, ajuste aplicado em produção.
