### ISSUE TITLE
Links errôneos no DeCS online

### ISSUE THREAD

**Issue by acecampos** [bireme/fi-admin#911]
Boa tarde, Fábio!

A Anália identificou links errados nas notas de escopo dos registros dos descritores:
"Condicionamento Físico Humano" e "Condicionamento Físico Animal"

Na nota de escopo em espanhol: "Modificación de la dieta y *ejercício físico* para mejorar la capacidad...", onde aparecem dois links (um para _ejercício_ e outro para _físico), deveria haver um único link para "ejercício físico".

![image](https://user-images.githubusercontent.com/35345406/64970139-97bf8980-d87b-11e9-8fbc-72acd0a823bb.png)

Muito agradecida!

**Comment by falbrito** [comment]
Ana, para o DeCS 2019 existem na base os termos "exercicio" e "físico" como preferidos, dessa forma o invertido trouxe um link para cada um.

**Comment by acecampos** [comment]
Obrigada, Fábio!


Ana Cristina Espindola Campos
Analista de Informação
BIREME/OPAS/OMS<http://www.paho.org/bireme> | Tel +55 11 5576-9817 VOIP 44824
[cid:image001.png@01D571E8.D2CD5100]

De: Fabio Brito <notifications@github.com>
Enviada em: Monday, September 23, 2019 08:20
Para: bireme/fi-admin <fi-admin@noreply.github.com>
Cc: Campos, Ana Cristina Espindola (BIR) <camposan@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/fi-admin] Links errôneos no DeCS online (#911)


Ana, para o DeCS 2019 existem na base os termos "exercicio" e "físico" como preferidos, dessa forma o invertido trouxe um link para cada um.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Ffi-admin%2Fissues%2F911%3Femail_source%3Dnotifications%26email_token%3DAINVH7UU7J2XSMCPHT3VOJDQLCQ45A5CNFSM4IXDWOE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7KRA4Q%23issuecomment-534057074&data=02%7C01%7Ccamposan%40paho.org%7C5e161b030707470547fd08d74017ef2f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637048343857961592&sdata=rC5cbW7J%2F6Q%2BL3dxO%2FqR9LVdHHzgp5nbmDOPxSYUu90%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINVH7QC7GDOL3NMLJ2Y2JTQLCQ45ANCNFSM4IXDWOEQ&data=02%7C01%7Ccamposan%40paho.org%7C5e161b030707470547fd08d74017ef2f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637048343857961592&sdata=nzZsUgD%2B0o8XFDLeJuQvdkV205UkhvHdoLUc2ir7Gvc%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
