### ISSUE TITLE
Registros 'excluídos' da base

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#912]
Existem 43 registros de multimídia (pôsteres do CRICS10), realizados pela usuária "_anaaraujo_" entre fevereiro e março deste ano, que não estão mais na base. Seria possível verificar?

Alguns ID's: 2490, 2491, 2492, 2493, 2494, 2496, 2498, 2500, 2501

Estes são os títulos:

- e-BlueInfo: Information Platform for Health Practice
- BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) 
- Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)
- Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud
- Processo de avaliação e seleção de periódicos LILACS Brasil (2008-2017)
- Producción científica de miembros de Sociedades Científicas de Estudiantes de Medicina de America Latina 2008-2018: análisis y perspectivas
- Gestão da informação e organização documental o Centro de Memória CETESB"
- DSAt ESF/PAVS: Diagnóstico socioambiental territorial para equipes estratégia saúde da família
- Gestão de dados de produção do Programa Ambientes Verdes e Saudáveis com ferramentas online gratuitas
- Coleta, indexação, organização e validação da produção científica de uma instituição: relato de caso
- Repositório Institucional da Organização Pan-Americana da Saúde como ferramenta estratégica de armazenamento, organização, disseminação, acesso gratuito ao conhecimento científico e preservação memória técnica
- Arquitetura da informação da Biblioteca Virtual em Saúde do Instituto Evandro Chagas à luz da plataforma de gestão WordPress
- Dois anos do Telessaúde Redes do Município de São Paulo: qualiicando a regulação da assistência e fortalecendo a atenção básica
- Metodologia para expansão temática do vocabulário controlado DeCS
- Terminologias em Saúde: ensino e aprendizagem
- Búsqueda de literatura científica para proyecto de tuberculosis, en período de 2008-2017, en Cuba
- Adaptação de filtro de busca para estudos de avaliação da qualidade de vida no Portal Regional da Biblioteca Virtual em Saúde (BVS)
- O Diretório de defesa de teses e dissertações da Biblioteca Virtual de Saúde Pública como fonte de informação e comunicação científica
- Panorama da Fonoaudiologia no Brasil a partir das publicações dos programas de pós-graduação (Quadriênio CAPES 2013-2016)
- Programa de pesquisa em saúde e saneamento da FUNASA
- Projeto de Resposta Rápida à Sífilis nas Redes de Atenção: Uma análise de causa e efeito sobre o processo de implementação do eixo estratégico de Educomunicação nos municípios prioritários, Brasil, 2018
- Implantação do Sistema de Gestão de Acervo SOPHIA na Biblioteca do Instituto Evandro Chagas, Ananindeua, Pará
- Gerenciamento dos indicadores de produção científica institucional: identificando potencialidades e impulsionando desenvolvimento científico
- Criação da Rede de Bibliotecas dos Hospitais e Institutos do Ministério da Saúde
- Filas de Espera por Cirurgias no SUS: O impacto das filas na vida do paciente
- A experiência da realização do inventário do acervo do Hospital do Câncer I do Instituto Nacional de Câncer José Alencar Gomes da Silva
- A atualização da Biblioteca Virtual Bioética e Diplomacia em Saúde: uma fonte de informação de qualidade para promoção da saúde humana
- Tecnologias de Informação em Saúde e a Teoria U: inovando no ensino-aprendizagem para gerar mais inovações em saúde
- BVS Enfermería Internacional: perspectivas de integración en América Latina y el Caribe
- El trabajo colaborativo como pilar del modelo BVS: la experiencia de cooperación en Colombia
- Viver Mais e Melhor, por meio das Práticas Integrativas e Complementares em Saúde oferecidas na Atenção Básica do SUS, em Santo Amaro e Cidade Ademar – Município de São Paulo - SP
- Experiência colaborativa para implantação de novos serviços e produtos: novas demandas dos usuários visando Modernização das Bibliotecas da Fiocruz 
- Rede Sudeste de Repositórios: relato de experiência
- Indexação de periódicos científicos na área de saúde: um estudo sobre a representação temática do domínio psicanálise nos Descritores em Ciências da Saúdes (DeCS)
- Redução na geração de resíduos radiológicos em unidade básica de saúde
- O geoprocessamento como ferramenta de gestão nos casos de tuberculose no território da Supervisão Técnica de Saúde da Penha
- BVS SMS São Paulo uma ferramenta estratégica para a gestão da informação
- Qualificação do processamento e faturamento da produção apresentada pelas unidades de saúde gerenciadas pela organização social de saúde SPDM/PAIS
- Roteiro de exercício de pesquisa bibliográfica em saúde
- Modelo de mapeamento de avaliação e monitoramento de políticas e estratégias editoriais para desenvolvimento de periódicos científicos indexados na LILACS
- Utilização da Internet e das redes sociais e sua relação com a formação/desenvolvimento e transformações da estrutura cerebral
- A importância dos Sistemas de Informação para Avaliação de Indicadores de pre-natal junto a gestantes imigrantes bolivianas da região Brás, Pari e Belenzinho
- Análise do desempenho e o impacto financeiro das equipes ESF/ESB no Programa de Melhoria de Acesso e Qualidade - PMAQ e nas unidades gerenciadas pela Organização Social OSS-SPDM

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula,

Eu e o @viniciusandrade verificamos este issue.

Pelo sistema FI-ADMIN, somente a pessoa que criou o registro pode apaga-lo.  
Segue a imagem do registro com um X na coluna da Ações.

![screenshot-fi-admin teste bvsalud org-2019 09 18-12_28_01](https://user-images.githubusercontent.com/19270675/65162920-7512a980-da10-11e9-90c4-94c439d2a4a9.png)

Recuperamos os logs de alguns desses registros apagados. O que esta registrado no logs desses registros é que eles foram APAGADOS pelo usuário 573 "anaaraujo", tem a data e a hora das modificações.

998564,"2019-06-04 15:41:05",**573**,34,2490,"e-BlueInfo: Information Platform for Health Practice",3,"[{"new_value": "", "previous_value": "e-BlueInfo: Information Platform for Health Practice", **"field_name": "Mídia", "label": "deleted"**}]"

Exemplos dos Logs

ID 2490
id,action_time,user_id,content_type_id,object_id,object_repr,action_flag,change_message
844489,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",1,"[{"new_value": "e-BlueInfo: Information Platform for Health Practice", "previous_value": "", "field_name": "Mídia", "label": "new"}]"
844490,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Tecnologia da Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844491,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Conhecimentos, Atitudes e Prática em Saúde", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844492,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Atenção Primária à Saúde", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844493,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Portal da Rede BVS", "previous_value": "", "field_name": "Áreas Temáticas", "label": "new"}]"
844494,"2019-02-21 15:09:43",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": ["Inglês"], "previous_value": [], "field_name": "language"}]"
844631,"2019-02-21 16:08:57",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Aplicativos Móveis", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
846949,"2019-02-22 22:10:05",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "Pôster apresentado no CRICS10, eixo temático Inovação e Saúde.", "previous_value": "Poster. Inovação e Saúde Digital. CRICS10", "field_name": "content_notes"}]"
998554,"2019-06-04 15:41:04",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",2,"[{"new_value": "", "previous_value": "Portal da Rede BVS", "field_name": "Áreas Temáticas", "label": "deleted"}]"
998564,"2019-06-04 15:41:05",573,34,2490,"e-BlueInfo: Information Platform for Health Practice",3,"[{"new_value": "", "previous_value": "e-BlueInfo: Information Platform for Health Practice", "field_name": "Mídia", "label": "deleted"}]"

ID 2491
id,action_time,user_id,content_type_id,object_id,object_repr,action_flag,change_message
844624,"2019-02-21 16:08:14",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",1,"[{"new_value": "BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ", "previous_value": "", "field_name": "Mídia", "label": "new"}]"
844625,"2019-02-21 16:08:14",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "Tecnologia da Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844626,"2019-02-21 16:08:14",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "Acesso à Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844627,"2019-02-21 16:08:14",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "Registros Eletrônicos de Saúde", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844628,"2019-02-21 16:08:15",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "Portal da Rede BVS", "previous_value": "", "field_name": "Áreas Temáticas", "label": "new"}]"
844629,"2019-02-21 16:08:15",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": ["Inglês"], "previous_value": [], "field_name": "language"}]"
846951,"2019-02-22 22:10:33",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "Pôster apresentado no CRICS10, eixo temático Inovação e Saúde ", "previous_value": "Poster. Inovação e Saúde Digital. CRICS10", "field_name": "content_notes"}]"
998555,"2019-06-04 15:41:05",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",2,"[{"new_value": "", "previous_value": "Portal da Rede BVS", "field_name": "Áreas Temáticas", "label": "deleted"}]"
998565,"2019-06-04 15:41:05",573,34,2491,"BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ",3,"[{"new_value": "", "previous_value": "BVS-InfoButton: The recovery of technical and scientific information available in the Virtual Health Library according to the context of Clinical Information Systems (CIS) ", "field_name": "Mídia", "label": "deleted"}]"

ID 2492
id,action_time,user_id,content_type_id,object_id,object_repr,action_flag,change_message
844665,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",1,"[{"new_value": "Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)", "previous_value": "", "field_name": "Mídia", "label": "new"}]"
844666,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Armazenamento e Recuperação da Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844667,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Redes de Informação de Ciência e Tecnologia", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844668,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Acesso à Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844669,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Gestão da Informação em Saúde", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
844670,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Portal da Rede BVS", "previous_value": "", "field_name": "Áreas Temáticas", "label": "new"}]"
844671,"2019-02-21 16:30:46",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": ["Português"], "previous_value": [], "field_name": "language"}]"
846952,"2019-02-22 22:11:22",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "Poster apresentado no CRICS10, eixo temático Gestão da Informação.  ", "previous_value": "Poster. Gestão da Informação. CRIC10 ", "field_name": "content_notes"}]"
998574,"2019-06-04 15:41:18",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",2,"[{"new_value": "", "previous_value": "Portal da Rede BVS", "field_name": "Áreas Temáticas", "label": "deleted"}]"
998599,"2019-06-04 15:41:18",573,34,2492,"Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)",3,"[{"new_value": "", "previous_value": "Rede de Referencistas da Biblioteca Virtual em Saúde (BVS)", "field_name": "Mídia", "label": "deleted"}]"

ID 2493
id,action_time,user_id,content_type_id,object_id,object_repr,action_flag,change_message
846056,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",1,"[{"new_value": "Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud", "previous_value": "", "field_name": "Mídia", "label": "new"}]"
846057,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "Bibliotecas Digitais", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
846058,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "Acesso à Informação", "previous_value": "", "field_name": "Descriptor", "label": "new"}]"
846059,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "bibliotecas virtuais", "previous_value": "", "field_name": "Keyword", "label": "new"}]"
846060,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "Portal da Rede BVS", "previous_value": "", "field_name": "Áreas Temáticas", "label": "new"}]"
846061,"2019-02-22 14:31:06",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": ["Espanhol"], "previous_value": [], "field_name": "language"}]"
846953,"2019-02-22 22:12:23",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "Poster apresentado no CRICS10, eixo temático Gestão da Informação.  ", "previous_value": "Poster. Gestão da Informação. CRIC10 ", "field_name": "content_notes"}]"
998575,"2019-06-04 15:41:18",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",2,"[{"new_value": "", "previous_value": "Portal da Rede BVS", "field_name": "Áreas Temáticas", "label": "deleted"}]"
998600,"2019-06-04 15:41:18",573,34,2493,"Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud",3,"[{"new_value": "", "previous_value": "Biblioteca Virtual en Salud de Honduras (www.bvs.hn): 18 años proporcionando recursos de información en salud", "field_name": "Mídia", "label": "deleted"}]"

Atenciosamente
Katinha
