### ISSUE TITLE
Tirar os Fontes com Status de APAGADO da lista de Resultados

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#914]
Por favor, tirar os fontes que estão com o Status de apagado(3) da lista de Resultados
Segue o exemplo que esta no FIADMIN de Teste.

969707 | Rev. Asoc. Med. Bahía Blanca; 18 (2), 2008

Grata

**Comment by viniciusandrade** [comment]
@anakatiacamilo 
Ajuste realizado na lista de resultados. Favor proceder com a alteração de status para as fontes duplicadas.
