### ISSUE TITLE
Problema navegação termos de indexação

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#917]
Usuário reclamou, realizei o teste e aconteceu a mesma coisa: na aba 'indexação', ao digitar um termo para indexar, quando vou usar a barra de rolagem para ver os termos que estão mais para baixo, a lista some. Já tentei em vários navegadores e o problema persiste.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Eu fiz um pequeno ajuste nesta tela apresentando menos termos e criando uma barra de rolagem interna para que a lista continue visivel na tela.

Quando possível favor verificar (talvez seja necessário pressionar F5 para atualizar a tela de popup devido a este ajuste).

Obrigado

**Comment by AngelicaSAPaula** [comment]
Consegui navegar pelos termos, sem que a lista sumisse ao clicar na barra de rolagem!
