### ISSUE TITLE
Erro ao publicar artigo #994531

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#925]
Ao tentar publicar o registro 994531, com perfil documentalista e sob o código BR32.1, apresenta o seguinte erro:

![image](https://user-images.githubusercontent.com/47643830/65713297-45e2e480-e06f-11e9-8bc4-3b85d32a612e.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula Apaguei o registro com problema esse erro não deve mais acontecer neste registro.  #907

**Comment by AngelicaSAPaula** [comment]
A analítica #994521, do mesmo registro fonte, acontece o mesmo erro.

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, não consigo identificar o problema deste registro.

**Comment by AngelicaSAPaula** [comment]
Usuária já conseguiu indexar e publicar os registros.
