### ISSUE TITLE
Prevenir a entrada de dados duplicados

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#928]
Apresentar lista de fontes ou analíticas possivelmente duplicados no sistema logo após o  usuário adicionar o título da analítica ou os dados do fonte.

**Comment by rfdeoliveira** [comment]
@viniciusandrade poderia, por gentileza substituir o protocolo da URL do serviço que checa duplicidade nos títulos? Tentei realizar um teste e, aparentemente, o serviço está funcionando com HTTPS:

<img width="711" alt="Screen Shot 2019-10-21 at 13 12 34" src="https://user-images.githubusercontent.com/7614112/67222975-cc87a900-f404-11e9-975b-270d90bbac7b.png">

**Comment by viniciusandrade** [comment]
@rfdeoliveira foi alterado a configuração no ambiente de testes porém o serviço DEDUP ainda não esta funcionando corretamente com HTTPS, @heitorbarbieri que é o desenvolvedor esta trabalhando no ajuste.
Assim que estiver OK te aviso.

**Comment by rfdeoliveira** [comment]
Perfeito, @viniciusandrade. Muito obrigado!

**Comment by viniciusandrade** [comment]
@suelisuga 
A lista de possíveis duplicados agora é apresentado abaixo do campo de título.

Este ajuste esta disponível no ambiente de testes, para testar você pode iniciar uma nova analítica de um fonte já existente e tentar adicionar novamente um título que já foi ingressado no sistema.

Esta alteração no momento,  esta disponível somente para artigos de revista.

Favor validar para podermos aplicar o ajuste em produção.

Obrigado.

**Comment by AngelicaSAPaula** [comment]
Realizei um teste, com perfil LILACS-Express, tentando suplicar uma analítica dentro da mesma fonte e apareceu o recado

![image](https://user-images.githubusercontent.com/47643830/82922104-8de43f00-9f4f-11ea-9ddd-7edeca6215b4.png)

Com perfil Editor, consegui duplicar fonte.

A analítica só é mostrada como possível duplicação quando é realizada no mesmo periódico. Para periódicos diferentes, é possível duplicar a analítica.

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula,

Obrigado pelo teste. 

Fiz a seguinte alteração: quando o usuário tentar entrar uma mesma fonte, ou seja, se o serviço de duplicados retornar que existe a mesma revista, volume e número, será desabilitado os botões de gravar e publicar. 

Não irá funcionar para todos os casos uma vez que existem fontes que só possuem a informação de volume mas deve ajudar bastante a evitar duplicações. 

Só funcionará para fonte pois os artigos podem ter títulos muito semelhantes que podem ser registros diferentes então o melhor é alertar ao usuário para que ele revise os possíveis duplicados.

Agradeço se puder avaliar no ambiente de testes.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Realizei um novo teste e funcionou perfeitamente: além de avisar da duplicidade, inabilitou os botões

![image](https://user-images.githubusercontent.com/47643830/83179223-17cf0c00-a0f8-11ea-8271-b2b777a185a8.png)

**Comment by viniciusandrade** [comment]
Obrigado, ajuste foi adicionado ao sistema em produção.
