### ISSUE TITLE
Erro ao publicar artigos

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#930]
Os registros #997976 e #998262 dão erro no momento de Gravar como LILACS-Express ou Publicar, quando estou no código BR1264.1

![image](https://user-images.githubusercontent.com/47643830/66226351-f163e880-e6b0-11e9-851b-666904468fa7.png)

![image](https://user-images.githubusercontent.com/47643830/66226330-e741ea00-e6b0-11e9-94f7-ecab8bbb405e.png)

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, registros corrigidos, por favor, testar.

**Comment by AngelicaSAPaula** [comment]
Estão ok! Já consegui publicá-los!
