### ISSUE TITLE
Incluir parceiros para o site

### ISSUE THREAD

**Issue by falbrito** [bireme/fi-admin#933]
Incluir os seguintes parceiros para o site

NIH
https://www.nih.gov/

INSERM
https://www.inserm.fr/

University of ROUEN
http://www.univ-rouen.fr/

Instituto de Salud Carlos III
https://www.isciii.es

Facultad de Medicina - Universidad de Chile
http://www.medicina.uchile.cl/

**Comment by marcioalvessilva** [comment]
Parceiros Inseridos
