### ISSUE TITLE
Apagar registro fonte sem analíticas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#944]
Seria possível permitir a exclusão de registros fontes que não tem analíticas, principalmente no caso de serem duplicados? Ex.: id:1019924

**Comment by anakatiacamilo** [comment]
@viniciusandrade teve um efeito colateral, não esta aparecendo as analíticas das revistas com o Status apagado

Regra da Fonte de Serie (revista)
bibliographic record = S 
treatment_level = Vazio

**Comment by viniciusandrade** [comment]
Ajuste aplicado para excluir somente registros do tipo FONTE do resultado. Favor, quando possível verificar.

**Comment by anakatiacamilo** [comment]
@viniciusandrade testei apagando o fonte e a analítica e o resultado foi esperado, só uma observação que é possível mudar o status a analítica quanto o fonte esta com o status de apagado.

**Comment by viniciusandrade** [comment]
OK, obrigado pela validação.
