### ISSUE TITLE
Identificar termos de um idioma (principalmente o espanhol da Espanha) que são iguais (não considerando a caixa, i.e., não considerando se maiúsculo ou minúsculo) ao de outro idioma (principalmente o espanhol do Chile) mas estão em conceitos diferentes do mesmo registro (i.e., no mesmo DescriptorUI ou QualifierUI).

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#948]
Esse caso trata de duplicação **no mesmo registro**. Este procedimento permitirá que distribuamos os termos para os seus devidos conceitos, atividade que vem sendo feito à medida que encontramos esses casos, mas que se automatizada seria muito mais eficiente, permitindo maximizar a validade do termos encontrados nos conceitos. 

Já uma duplicação **entre registros** e entre espanhol do Chile e da Espanha (como também entre outros idiomas) tampouco deveria ser permitida, pois causaria erro na recuperação da informação bibliográfica. 

Como antecedentes: muitos termos da Espanha ficaram no conceito preferido, pois vieram do sistema de edição antigo (decsweb) que não dividia os termos por conceito. Por isso, foram todos carregados no primeiro conceito de cada registro. Os outros idiomas foram carregados da versão do DeCS em XML, logo depois que esses arquivos foram produzidos pela NLM. Algumas informações foram perdidas, mas, de poucos dias de trabalho. Outro dado que se perdeu foram os termos em inglês exclusivos do DeCS que acrescentamos a registros do MeSH. Para esse último problema, resolvemos descartá-los. 

Ver também o issue #1144 que trata de mover o termo da Espanha que está no primeiro conceito e que deveria estar noutro conceito do mesmo registro, onde a tradução do Chile é igual a ele. É um outro modo de ver o mesmo problema.

**Comment by arthurtreuherz** [comment]
Ao se produzir a lista resultante, perceberemos que em quase todos os casos o termo da Espanha estará no primeiro conceito (preferido) e o do Chile estará no conceito correto (não preferido), ou seja, essa lista servirá para encontrar os termos da Espanha que deveremos mover para o conceito não preferido. Por conseguinte, o procedimento deve procurar somente em registros que possuam mais de um conceito.

**Comment by acecampos** [comment]
@wilsonmoura essa demanda ainda persiste

**Comment by lucianaPRB** [comment]
Encerrar, solução semelhante ao #1144.
