### ISSUE TITLE
Fonte de Seriado sem fascículo 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#953]
Por favor, quando o registro não tiver a informação do fascículo não colocar o () vazio nem na apresentação do fonte no Sistema, nem no reference_title.

1012656	MedicalExpress (São Paulo, Online); 6 (), 2019
894374	MedicalExpress (São Paulo, Online); 5 (), 2018
968435  Rev. saúde pública (Online); 53 (), 2019

Grata

**Comment by viniciusandrade** [comment]
@anakatiacamilo ajuste realizado. Como o campo reference_title só é gerado na criação/atualização dos registros esta mudança só é válida daqui em diante. 
Caso encontre algum problema favor reabrir este issue. Obrigado.
