### ISSUE TITLE
Campo de definição em inglês com subcampo n mas sem conteúdo

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#954]
Hoje, no decs em ISIS de 2019 da homologação, achei estranho que o número de definições em inglês deu igual ao número de descritores em inglês, pois eu lembrava que pelo menos até recentemente havia descritores que não tinham definição. Então fui checar se havia conteúdo nos subcampos n e percebi que há mais de 1200 descritores com subcampo n vazio. Pode verificar se esse erro foi, de alguma forma, convertido para o novo sistema? Você poderia nos informar quantas notas de escopo com conteúdo aparecem no DeCS do FI-ADMIN? 

Grato, Arthur

Comandos usados na homologação:

**Definição em português OK**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v7) and v7^n='' then mfn/ fi" now | wc
      **0**       0       0

**Definição em espanhol do Chilel OK**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v6) and v6^n='' then mfn/ fi" now | wc
      **0**       0       0

**Definição em espanhol da Espanha OK**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v8) and v8^n='' then mfn/ fi" now | wc
      **0**       0       0

**Definição em inglês com subcampo vazio:**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v5) and v5^n='' then mfn/ fi" now | wc
   **1298**    1298    9086

**Número de descritores em inglês**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v1) then mfn/ fi" now | wc
  **33966**   33966  237762

**Número de definições em inglês com conteúdo (veja que é menor do que o número total de descritores em inglês:**
G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if p(v5) and v5^n<>'' then mfn/ fi" now | wc
  **32668**   32668  228676

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura essa demanda não existe mais.
