### ISSUE TITLE
Alteração de nome de variante do idioma espanhol no formulário de entrada

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/fi-admin#961]
Fábio, 

Favor alterar os nomes dos idiomas espanhóis que existem no formulário do sistema de gestão do DeCS:
 
Interface em português:
 
De: Espanhol América Latina
 
Para: Espanhol da América Latina
 
Interface em espanhol:
 
De: Español latino america
 
Para: Español latinoamericano
 
------
De: lengua española utilizada en españa
 
Para: Español utilizado en España
 
 
Grato,
Arthur

**Comment by falbrito** [comment]
Realizado
