### ISSUE TITLE
Erro ao gravar registro (#1021403)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/fi-admin#962]
O registro apresenta erro ao gravar / publicar e quando voltamos nele, os descritores estão duplicados

![image](https://user-images.githubusercontent.com/47643830/67509432-5f288200-f669-11e9-9fa8-cdb087818919.png)

**Comment by anakatiacamilo** [comment]
Apaguei os dados do Complemento que estavam duplicados e agora esta funcionando corretamente.
