### ISSUE TITLE
Busca nos registros bibliográficos com o prefixo LILACS_original_id 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/fi-admin#963]
Por favor, trazer somente o registro exato quando utilizar o prefixo LILACS_original_id nas buscas dos registros bibliográficos. 
Grata

**Comment by rfdeoliveira** [comment]
Apresentar o LILACS original id nos dados administrativos do registro quando usuário for **BR1.1**

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula / @suelisuga 

Esta alteração foi implementada e esta disponível no ambiente de testes. Favor validar para passarmos para produção.

Além de pesquisar exatamente pelo ID original da LILACS na edição de um registro no quadro de informações administrativas da parte inferior é apresentado este ID para verificação.

Obrigado

**Comment by viniciusandrade** [comment]
Disponível em produção.
