### ISSUE TITLE
"Referências bibliográficas" do perfil llxp - exibir página de "Nova Fonte"

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#97]
Ao clicar em "Referências bibliográficas" utilizando o perfil llxp, exibir a página "Nova fonte".

A página "Nova Fonte" é visualmente mais limpa, mostrando apenas os fascículos e com link para acessar as analíticas de cada fascículo. A página "Referências bibliográficas" exibe uma lista com todos os registros, fonte e analítica, de todos os fascículos.

----

Nova fonte
![image](https://cloud.githubusercontent.com/assets/18355163/14506247/32f181d8-0193-11e6-86cd-6b3e37941543.png)

Referências bibliográficas
![image](https://cloud.githubusercontent.com/assets/18355163/14506271/4b2e79ea-0193-11e6-8f06-a0ab674dd971.png)

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/fi-admin/commit/9ce146151ed68670c47d1d08b0c8447c11a4c3bd
