### ISSUE TITLE
Mudar forma de apresentação do campo "Pré-codificados" para select box

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#972]
Prezados,

Solicito que descritores pré-codificados sejam apresentados em forma de select box.
Atualmente para selecionar mais de um descritor é necessário clicar o botão "Control" e isso gera confusão e erros na contribuição.

![image](https://user-images.githubusercontent.com/13105683/67982220-058ffc80-fc01-11e9-971a-cbd4cdb04881.png)

Sugiro apresentá-lo como o programa da NLM:
![image](https://user-images.githubusercontent.com/13105683/67982297-2c4e3300-fc01-11e9-9751-6cc7201c830a.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga e @AngelicaSAPaula,

Ajuste realizado pelo @rfdeoliveira e disponível no ambiente de testes para validação.

Obrigado

**Comment by AngelicaSAPaula** [comment]
Não aparece como select box

![image](https://user-images.githubusercontent.com/47643830/70629660-1755be00-1c09-11ea-800e-74b831133add.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Desculpe, é que entraram outras atualizações e esta que estava pendente de validação foi desabilitada. 

Por favor, quando possível pode verificar novamente. É importante validar se este ajuste não causa impacto nos registros já marcados anteriormente e também na criação de novos registros. Obrigado.

**Comment by AngelicaSAPaula** [comment]
Ao criar uma nova analítica, aparece o select box, mas ao gravar como rascunho, aparece o seguinte erro:

![image](https://user-images.githubusercontent.com/47643830/70635519-d5317a00-1c12-11ea-9678-df21dcf818a2.png)

Nos demais status, está ok!

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Fiz uma correção para este caso. Poderia, quando possível, testar novamente?

Obrigado

**Comment by AngelicaSAPaula** [comment]
Fiz um novo teste, mas quando seleciono "-------", ele não desmarcou os outros termos.

![image](https://user-images.githubusercontent.com/47643830/70751022-4f92f480-1d0e-11ea-8b05-62d9428823e1.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Respondido em https://github.com/bireme/fi-admin/issues/973#issuecomment-565438667

**Comment by viniciusandrade** [comment]
Testes OK, aplicado em produção.
