### ISSUE TITLE
Sugiro mudar a forma de apresentação do campo "Tipo de Publicação" para select box

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#973]
Prezados,

Sugiro mudar a forma de apresentação do campo "Tipo de Publicação" para select box:
DE:
![image](https://user-images.githubusercontent.com/13105683/67982458-7e8f5400-fc01-11e9-9f17-2424cd114b54.png)

PARA:
![image](https://user-images.githubusercontent.com/13105683/67982409-67e8fd00-fc01-11e9-9d47-0044d13275b7.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@sueli / @AngelicaSAPaula 

Favor verificarem implementação proposta pelo @rfdeoliveira para este issue no ambiente de testes do FI-ADMIN.

Obrigado

**Comment by suelisuga** [comment]
Prezados,

O select box funcionou na aba "Todos Registros" com registros com status LILACS-Express, Rascunho e não funcionou Migrado e Publicado.
![image](https://user-images.githubusercontent.com/13105683/68608666-376f5180-0492-11ea-8390-4088d5600e7d.png)

![image](https://user-images.githubusercontent.com/13105683/68608724-579f1080-0492-11ea-85aa-a4266c9c9911.png)

Na aba "Meus registros" quando abro um registro novo e um registro com status publicado e rascunho não é apresentado as opções em select box.

Obrigada!
Sueli e Angélica

**Comment by viniciusandrade** [comment]
@suelisuga e @AngelicaSAPaula,

Obrigado pelos testes. O Ronaldo ajustou para apresentar o select para os demais casos. 
Quando possível favor verificarem novamente no ambiente de testes.

**Comment by suelisuga** [comment]
@viniciusandrade e @rfdeoliveira funcionou com lilacs-express, rascunho, migrado, publicado, recusado e apagado.

Agora notei que há uma opção [Select all] que é desnecessária visto que não se aplica ao campo, ou seja, em nenhum caso será necessário selecionar todos os tipos de publicação.

Outra dúvida é a opção ------------ é usada em que momento? Se eu abrir o campo "Tipo de Publicação" devo necessariamente selecionar essa opção caso não queira escolher nenhum tipo de publicação?

Solicito excluir a opção [Select all].

Quanto a --------------, aguardo retorno sobre como deveria ser o funcionamento dele.

Obrigada!
Sueli

**Comment by rfdeoliveira** [comment]
Olá, @suelisuga!

A opção "[Select all]" é padrão do componente utilizado nesta melhoria, verei se é possível suprimí-la.
Já a opção "-------" não sei te dizer para que serve (talvez o @viniciusandrade possa nos ajudar), mas, conforme a imagem abaixo, esta opção já estava existia na antiga forma de apresentação:

![Screen Shot 2019-11-21 at 09 22 43](https://user-images.githubusercontent.com/7614112/69337914-cc1b4180-0c40-11ea-9716-d2a759d0075e.png)

**Comment by viniciusandrade** [comment]
Na apresentação padrão da lista com múltipla seleção a opção "-------"  serve para desmarcar todas as opções previamente selecionadas, com a nova apresentação do componente acredito que essa opção possa ser suprimida.

**Comment by rfdeoliveira** [comment]
@viniciusandrade, verifiquei que o que cria esta opção é o valor da chave `choices` do dicionário `defaults` do field `MultipleAuxiliaryChoiceField`, utilizado no modelo para popular as opções do select. Removendo o `BLANK_CHOICE_DASH`, eliminamos a opção "-------". Minha dúvida é se alteração pode ser aplicada diretamente neste field, ou se pode haver outro uso para este campo que necessite da opção "-------".

https://github.com/bireme/fi-admin/blob/f0d9a7b5e165877079eccde7b223791040f76dc1/bireme/utils/fields.py#L94
MultipleAuxiliaryChoiceField

**Comment by viniciusandrade** [comment]
@rfdeoliveira vamos manter desta forma pois pode ter impacto nos demais campos que não utilizam o compomente alternativo de seleção.

**Comment by rfdeoliveira** [comment]
Perfeito, @viniciusandrade,  enviei ontem o patch com a remoção da opção `selectAll`.

**Comment by viniciusandrade** [comment]
@suelisuga 
A opção "[Select all]"  foi retirado mas a opção "-------" precisa ficar pois o mesmo componente é utilizado em outros formulários do sistema.

Favor informar se os testes foram realizados para passarmos para produção.

**Comment by AngelicaSAPaula** [comment]
Entrei no ambiente de testes, mas não está mais como select box...

![image](https://user-images.githubusercontent.com/47643830/70629432-c0e87f80-1c08-11ea-98c1-3f6152504b6a.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

Desculpe, é que entraram outras atualizações e esta que estava pendente de validação foi desabilitada. 

Por favor, quando possível pode verificar novamente. É importante validar se este ajuste não causa impacto nos registros já marcados anteriormente e também na criação de novos registros. Obrigado.

**Comment by AngelicaSAPaula** [comment]
Ao criar uma nova analítica, aparece o select box, mas ao gravar como rascunho, aparece o seguinte erro:

![image](https://user-images.githubusercontent.com/47643830/70635519-d5317a00-1c12-11ea-9678-df21dcf818a2.png)

Nos demais status, está ok!

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 
Fiz uma correção para este caso. Poderia, quando possível, testar novamente?

Obrigado

**Comment by AngelicaSAPaula** [comment]
Fiz um novo teste, mas quando seleciono "-------", ele não desmarcou os outros termos.

![image](https://user-images.githubusercontent.com/47643830/70751022-4f92f480-1d0e-11ea-8b05-62d9428823e1.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula 

O que acontece é que este tipo de lista controlada é apresentada para outros campos do formulário (ex. idioma do texto) onde a opção "-------" sim serve para desmarcar os itens previamente selecionados.
Para os campos Tipo de publicação e Descritores precodificados foi alterado a forma de apresentação do componente e por isso a opção "-------" perdeu sua função mas não é possivel remove-la devido ao uso do mesmo tipo de lista para outros campos.

**Comment by AngelicaSAPaula** [comment]
Obrigada pela explicação! Testes ok! ( #972 também)

**Comment by viniciusandrade** [comment]
Testes OK, aplicado em produção.
