### ISSUE TITLE
Implantar campo DOI (Digital Object Identifier) nos tipos de literatura Monográficos e Documentos não convencionais

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#974]
Chamado relacionado #406 

Incluir o campo DOI nos tipos de literatura M - monográficos e N - documento não convencional no registro fonte e nas analíticas.
![image](https://user-images.githubusercontent.com/13105683/67982977-7c79c500-fc02-11e9-87f7-cef380b298b2.png)

Obrigada.
Sueli

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula,

Campo adicionado no formulário de entrada de Monográficos e Não convencionais. 

Quando possível favor validar esta implementação no ambiente de testes. Também foi adicionado validação para solicitar que o campo seja preenchido no formato 10.1000/xyz123.

Obrigado

**Comment by suelisuga** [comment]
@viniciusandrade verifiquei que foi implantado.

Dúvida: a inclusão do help é feita na instancia de teste?

Vou abrir outros chamados para outros tipos de documentos.

Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga ajuste publicado em produção.

Textos de ajuda devem ser adicionados diretamente em produção.

Abraços
