### ISSUE TITLE
Mudança do nome da fonte de "Recursos" para "Recursos de internet"

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#977]
Prezados,

Como há usuários que confundem a cooperação com o LIS e o DirEve, solicito que o label Fontes de Informação > Recursos torne-se "Recursos de Internet".

![image](https://user-images.githubusercontent.com/13105683/67983466-7f28ea00-fc03-11e9-88d7-5ed4658081e7.png)

Obrigada!
Sueli

**Comment by suelisuga** [comment]
@viniciusandrade e @rfdeoliveira agora vi o resultado. UFA! Que bom! Obrigada!

**Comment by viniciusandrade** [comment]
:+1:
