### ISSUE TITLE
Busca por LILACS_original_id não recuperou registro correto

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#980]
Prezados,

Pesquisando o ID lil-73566 não consegui localizar o registro que eu buscava. ==>LILACS_original_id:73566

![image](https://user-images.githubusercontent.com/13105683/68426268-82355480-0186-11ea-8544-3b4e08142b00.png)

Resultado da busca foi:
![image](https://user-images.githubusercontent.com/13105683/68426328-ad1fa880-0186-11ea-9eec-7574520043e5.png)
![image](https://user-images.githubusercontent.com/13105683/68426420-d8a29300-0186-11ea-9068-16edf67ebeed.png)

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Resolvido com a implementação do issue #963.
