### ISSUE TITLE
Permitir navegação na lista de registros do FI-Admin por meio de pesquisa

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-admin#981]
Prezados,

Para o controle de qualidade dos registros do FI-Admin é necessário navegar em listas de registros. Solicito implantar uma pesquisa na barra de navegação para que o usuário possa pular da página 1 para a 20 sem precisar passar por várias outras páginas antes, como é o que ocorre hoje.

![image](https://user-images.githubusercontent.com/13105683/68478141-fb2bbf00-020d-11ea-9a34-f8ce0e3326a3.png)

Obrigada!
Sueli

**Comment by suelisuga** [comment]
@viniciusandrade e @rfdeoliveira não encontrei onde foi implantada a melhoria.
![image](https://user-images.githubusercontent.com/13105683/69145723-0f44ab80-0aad-11ea-90c1-8af3f23f2512.png)
Podem me mostrar como funciona?

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Foi implementado na parte superior a direita, mas concordo que ficou difícil de localizar.

@rfdeoliveira seria possível mover para a mesma linha da navegação de páginas?

**Comment by rfdeoliveira** [comment]
@viniciusandrade e @suelisuga, vou tentar mover para baixo, perto das setas de paginação.

**Comment by rfdeoliveira** [comment]
Feito, @viniciusandrade: 

![Screen Shot 2019-11-21 at 12 16 37](https://user-images.githubusercontent.com/7614112/69350739-da755780-0c58-11ea-80c9-e77b0d495b8c.png)

**Comment by viniciusandrade** [comment]
Obrigado @rfdeoliveira.

@suelisuga / @AngelicaSAPaula  quando possível favor verificar no ambiente de testes.

**Comment by suelisuga** [comment]
ok. testado.
pf. colocar na produção.

Obrigada!
Sueli

**Comment by viniciusandrade** [comment]
Disponível em produção.
