### ISSUE TITLE
Campos obrigatórios – analíticas de série periódica

### ISSUE THREAD

**Issue by sarahviola** [bireme/fi-admin#99]
Devem ser obrigatórios para analíticas de série periódica com **status LILACS-Express**:
- [08] Endereço eletrônico (informar URL ou carregar PDF)
- [40] Idioma do texto

Devem ser obrigatórios para analíticas de série periódica com **status Publicado**:
- [10, subcampo 1] Afiliação.
Quando não tem o dado, obrigatório preencher "s.af", que indica sem afiliação.

- [10, subcampo p] País da afiliação.
Obrigatório quando subcampo 1 preenchido com algum dado que não "s.af".

- [12 ou 13] Título em inglês.
Obrigatório Título [12] com subcampo i preenchido com inglês **ou** preencher campo Título Traduzido para o Inglês [13] .

- [14] Páginas ou [110 e 08] meio eletrônico
Obrigatório informar paginação **ou** identificar Forma do Ítem como "Eletrônico" e preencher campo de Endereço Eletrônico.

Atualmente são obrigatórios apenas os campos de autor e título. Manter dessa forma para registros com **status rascunho**.

----

Para referência, campos obrigatórios para analíticas de série periódica no LILDBI:
![image](https://cloud.githubusercontent.com/assets/18355163/14531164/a366dca2-0232-11e6-8838-906860b31a37.png)

**Comment by marcoslmori** [comment]
Consistência do campo 12 e 13 [título e título em inglês] está aplicado ao status lilacs-express e deveria ser somente no publicado.

**Comment by sarahviola** [comment]
Status **LILACS-Express**: idioma do texto não está como obrigatório.

Na Metodologia LILACS, atualmente registramos o Idioma em dois lugares: 
- Subcampo idioma do campo de Endereço Eletrônico (preenchido por default com "inglês")
- Campo Idioma do texto - deveria ser obrigatório

**Comment by sarahviola** [comment]
Status **Publicado** está como obrigatório somente:
- Autor (pessoal ou institucional)
- Título e título em inglês
- Idioma do texto
- Descritor 
- Área temática

Faltam ainda:
- Afiliação
- País da afiliação quando afiliação presente
- Paginação ou informar que é eletrônico

**Comment by sarahviola** [comment]
Status **LILACS-Express** com obrigatoriedade dos campos correta.

**Comment by viniciusandrade** [comment]
@sarahviola 

Validações implementadas para:
- Afiliação
- País da afiliação quando afiliação presente
- Paginação ou informar que é eletrônico

Atualizado no ambiente de testes. Quando possível favor verificar para que eu possa atualizar a produção.

[]s

**Comment by sarahviola** [comment]
* Afiliação - ok

* Para registros com status **LILACS-Express**, preencher campo 08 (enviando PDF ou preenchendo URL) deve ser sempre obrigatório. mesmo quando paginação informada.

* Deve ser obrigatório para status **Publicado** pelo menos um descritor primário. Atualmente está como obrigatório um descritor, não exigindo primário.

**Comment by viniciusandrade** [comment]
@sueli,

Conforme verificamos a metodologia indica que caso seja informado paginação o campo de meio eletrônico passa a ser opcional. 

A proposta é alterar esta validação para sempre que for um documento do tipo "Sas" exigir a informação de meio eletrônico ou upload de documentos e também remover a validação.

Favor informar se podemos realizar esta alteração.

Relacionado ao #62.

**Comment by viniciusandrade** [comment]
@sarahviola,

- Implementando validação do campo de **endereço eletrônico** para registros do tipo **Sas** conforme definido em #159.

- Implementado validação para status **Publicado** de pelo menos um descritor primário.

Favor, quando possível, validar no ambiente de testes.

Obrigado.

**Comment by sarahviola** [comment]
Validações ok.
